### PR TITLE
Distributed estimation

### PR DESCRIPTION
**Pull request by lbybee**
See #3055 and #3395 for reference.

### CODE REVIEW

**Comment by lbybee** [comment]
@kshedden this should be ready to merge now.  @josef-pkt thanks for the advise on the rebasing, worked well.

**Comment by josef-pkt** [comment]
The squashing looks good, but you didn't rebase on master. master is merged in the last commit into this branch.
According to the network graph, this branch still starts at some point in the past, behind master.

I think you could rebase this branch on master without needing any additional interactive squashing or history adjustments.

**Comment by lbybee** [comment]
Ok, now there is an issue with the reverted PHreg changes being reintroduced.  I'm aware of it and working on it.

**Comment by lbybee** [comment]
I believe that this should now be correctly rebased.

**Comment by josef-pkt** [comment]
network graph looks good, it's now rebased on master.

PHReg is still in there. It can stay in there, if it's used during development and doesn't hurt much the PHReg history, from my perspective. Or I can do some surgery. But it would mean editing quite a bit of the commits.

https://github.com/lbybee/statsmodels/commits/44240e786b7a06d3dfe2c9986323608a94a3f5a5/statsmodels/duration/hazard_regression.py

**Comment by josef-pkt** [comment]
About the unit tests: they look ok, but for my taste it has too many `shape` tests.

a relatively easy way to convert to regression test and to add regression numbers would be to use 
`nosetests --pdb-failures <path_to>/statsmodels/base/tests/test_distributed_estimation.py `

add the asserts and copy the values from the test failure into the unit test, e.g.
```
assert_equal(dmat.shape, X.shape)
assert_allclose(dmat, np.ones(X.shape), rtol=1e-6)
```

**Comment by josef-pkt** [comment]
@lbybee Thanks, looks good
If you can amend the last commit, then you could add a code comment to the test functions, that those unit tests are `regression tests`. i.e. reference numbers are results from functions. 
That's usually very helpful when we have to look at and possibly change those tests later.

**Comment by lbybee** [comment]
Ok, I believe this should all be correct now.  @kshedden should be ready to merge whenever you want at this point.

**Comment by kshedden** [comment]
@josef-pkt This looks good to me.  If we merge it in we can experiment some more and do a follow-up PR if needed.

**Comment by josef-pkt** [comment]
Looks good based on brief skimming.
It's a bit behind master given the recent activity, but should be fine to merge

**Pull request merged**
