### PR TITLE
BUG: Remove change of global pickle method

### LINKED ISSUE #4772: statsmodels.graphics.functional pickle issue
I have code that needs to pickle functions (i.e. for joblib) that are defined in modules where statsmodels.api is imported. The pickle attempt leads to an `AttributeError` from the `statsmodels.graphics.functional` module:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\[...]\lib\site-packages\statsmodels\graphics\functional.py", line 32, in _pickle_method
    if m.im_self is None:
AttributeError: 'function' object has no attribute 'im_self'
```
This can be simply reproduced by creating a short module with the following code:
```
import statsmodels.api as sm
class Dummy(object):
    def __init__(self):
        pass
    def get_add_constant(self):
        return sm.add_constant
```
If this code is saved in a file, `test_mod.py`, then I can trigger the exception by opening a python session and entering:
```
>>> from test_mod import Dummy
>>> dum = Dummy()
>>> pickle.dumps(dum.get_add_constant)
```

I have worked around the issue by narrowing my import to just the classes needed in my code, but this seems like a bug in graphics.functional that should be addressed. 

Note: I observed this issue using statsmodels 0.9.0 in Windows.

### PR DESCRIPTION
**Pull request by bashtage**
Refactor PCA and Kernel methods to avoid instance methods
Remove buggy pickling method change in functional graphics

closes #4772

### CODE REVIEW

**Comment by jbrockmendel** [comment]
+1

**Comment by josef-pkt** [comment]
LGTM, 
copyreg was added in #4049, based on a quick look I don't see what it was needed for, i.e. if some pickling doesn't work anymore and we don't have unit tests for it.

merging

@bashtage Thank you

**Comment by bashtage** [comment]
It was added to allow pickling of instances from what I can tell.  Instances that use dicts to hold functions can't be trivially pickled and so these should be avoided.  It would be a good idea to test pickling everything model in the api and every result to avoid these issues in the future.

**Comment by josef-pkt** [comment]
We have pickling and `remove_data` tests in base for the core models outside of tsa. But this might not have kept up with recent models, and does not cover non-model objects that don't inherit base models e.g. `load` and `save` are LikelihoodModelResults methods.

**Comment by jbrockmendel** [comment]
> Instances that use dicts to hold functions can't be trivially pickled and so these should be avoided

The only remaining special cases that come to mind are `NegativeBinomial` and `DiscreteResults`.  De-special-izing those would not be too difficult.

> `remove_data`, `load` and `save` are LikelihoodModelResults methods

`load` and `save` are also duplicated in `wrapper.ResultsWrapper`.  I'm not clear on why they are needed in both places, but not gonna make a big deal out of it.  Is there a compelling reason why these are in LikelihoodModelResults instead of just Results?

> We have pickling and `remove_data` tests in base for the core models outside of tsa

The current implementation of `remove_data` makes it really easy for things to fall through the cracks, see #4421.

**Comment by josef-pkt** [comment]
I don't remember why the wrapper also has load save, I guess it is because we also need to pickle the wrapper class and not just the underlying results class.
There is no explanation for this in #188 and some related issues that I briefly checked

The advantage of the current implementation is that it is "boring", i.e. it's conceptually very simple and we mainly need to check that everything is in the white lists.

I didn't check: I think ZeroInflated and similar models will most likely not work correctly with `remove_data`, because the model contains submodels that need to be handled separately.

**Pull request merged**
