### PR TITLE
MAINT: remove pandas compat shims; assorted cleanups

### PR DESCRIPTION
**Pull request by jbrockmendel**
Follow-up to #5000

### CODE REVIEW

**Comment by josef-pkt** [comment]
Did you edit `examples/python/robust_models_1.py` by hand?

I think I didn't pay enough attention to some recent changes.
AFAIR, the `examples/python` were supposed to be synchronized, exported versions of `examples/notebooks`

https://github.com/statsmodels/statsmodels/pull/2652#issuecomment-168396096

can you check this?
i.e. export the notebook version of `robust_models_1` to python and see whether the "necessary" changes are there (not pep-8, style and formatting changes).

keeping those python example modules as exported version of the notebooks has two advantages
- we only have one version to maintain
- if we were (as I intend for some cases) to export the notebook to py files after each change set in the notebook, then we would have standard change sets for python code that is easier to read in the git history.

**Comment by jbrockmendel** [comment]
> Did you edit examples/python/robust_models_1.py by hand?

Yes.

> AFAIR, the examples/python were supposed to be synchronized, exported versions of examples/notebooks [...] can you check this?

The synchronized thing is a nice idea, but it looks like these have fallen out of sync.  I found the edited files by searching for `compat.pandas`' `sort_values`, which the robust_models_1.py has, but robust_models_1.ipynb does not have.

Enforcing the synchronization sounds like a good goal/Issue (maybe only generate the .py files for releases?)

**Comment by jbrockmendel** [comment]
@josef-pkt thoughts on how to handle out-of-sync example files?  I’ll be happy to help handle those in a systematic way after we get the current crop over with.

**Comment by jbrockmendel** [comment]
@josef-pkt reverted _most_ of the edits to robust_models_1.py example file; leaving the central ones (getting rid of sort_values shim) in place.  As it turns out the corresponding ipynb file had already removed those shims.

**Comment by jbrockmendel** [comment]
@josef-pkt concerns have been addressed

**Comment by jbrockmendel** [comment]
Rebased again.

**Comment by jbrockmendel** [comment]
Rebased again.

**Comment by josef-pkt** [comment]
You just managed to add more than 18 hours to the appveyor queue.

**Comment by jbrockmendel** [comment]
How would you suggest keeping PRs merge-ready?  "Hey let's finish this before merge conflicts pop up" doesn't seem to be working.

**Comment by josef-pkt** [comment]
I'm trying to look at and work on other things.

I will start to enforce a limit on the number of appveyor jobs by the same author to 4 or 5 unless the queue is short.
I cannot do a review and merge round in the morning because PRs (mine and others that were close to merging) are still waiting in the appveyor queue.

**Comment by josef-pkt** [comment]
AFAICS, a `sortvalues` "compatibility" PR would be fine if that is compatible with our minimum pandas.

The rest is style changes all over the place, and I try not to think about those in details (for now)

**Comment by jbrockmendel** [comment]
OK.  See also #5157.

**Comment by jbrockmendel** [comment]
Closed in favor of #5217.

**Pull request closed without merging**
