### PR TITLE
MAINT: remove functions duplicated from scipy

### PR DESCRIPTION
**Pull request by jbrockmendel**
The scipy versions can be counted on to be better tested, optimized, documented, etc.  Besides which statsmodels' only testing of the existing functions is that they match scipy's implementations.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt CI fail is spurious, easy win here

**Comment by bashtage** [comment]
@josef-pkt Simple PR removing compat code.  Should be merged.

**Comment by jbrockmendel** [comment]
@josef-pkt no-brainer here

**Comment by jbrockmendel** [comment]
@josef-pkt let’s keep the hot-streak going

**Comment by josef-pkt** [comment]
deleting this is fine
our adjusted copy of numpy pinv that we use is `statsmodels.tools.tools.pinv_extended`
scipy pinv has now an option to return matrix rank, but we use numpy's pinv

merging

**Pull request merged**
