### PR TITLE
ENH: Improved date handling in tsa

### PR DESCRIPTION
**Pull request by ChadFulton**
See #3124.

### CODE REVIEW

**Comment by ChadFulton** [comment]
This is a first attempt at a general refactoring of date handling in `tsa`.

- I was surprised that it was *relatively* easy to refactor the date handling without touching "too much" code.
- Tests pass on local machine, but likely will fail on some versions.
- This PR will probably progress slowly, since there are lots of corner cases waiting to bite.

**Comment by ChadFulton** [comment]
This is now green (except for the usual unrelated failures). The next step for me will be to see how it works for the corner cases that people have reported with the current date handling.

**Comment by ChadFulton** [comment]
This PR is surprisingly done. It pretty much replicates the current existing behavior. Here are the details:

**Indexes / wrapping**

All `tsa` models now have *some* associated internal index (stored in the `self._index` attribute). If a date index *with an associated frequency* is given (either as the index to the `endog` or `exog` datasets, or through the `dates` argument), then that is used as the internal index. In all other cases (if there is no index, or if the given index is not a date index with an associated frequency) the underlying internal index is an Int64Index with values 0, 1, ..., nobs-1.

Model / results output is still only wrapped with a Pandas index if the original data was Pandas or if the `dates` argument was used.

**Prediction / Forecasting**

This is as it was before. `start`, `end`, and `steps` arguments can be specified as integers or as a date-coercible object (mostly strings and datetime objects).

However, it now allows negative indexes to `predict` and `forecast` (e.g. `res.predict(start=-2)` will return predictions of the last two observations).

**Improvements**

The primary improvement is that it strips out almost all of our custom date handling code and relies on Pandas instead. This is now entirely possible since most of the date-handling code in Statsmodels had been written to deal with Pandas as early as 0.8. So we have less code to support in Statsmodels and fewer corner cases (I think), and anything that works with the users' version of Pandas should work with the users' version of Statsmodels.

The two other main improvements are clear exception messages / explicit warnings, and a broader range of index types in unit tests (`test_tsa_indexes.py`).

**Backwards incompatible changes**

Right now it raises `KeyError` when an invalid key is passed as a key to `predict` or `forecast`, rather than a `ValueError`. This is not essential (I could return it to a `ValueError`), but I think it makes more sense, because ultimately the `start` and `end` arguments to predict are meant to be index keys (and under the hood we're using a `get_loc()` call on a Pandas index, and that's what raises the `KeyError`.

Also, there are likely to be some weird corner cases where the behavior has changed. I don't think there's anything that was *supposed* to work before that now fails, but there are probably cases which happened to work that will raise an exception or issue a warning now.

**Comment by ChadFulton** [comment]
The last few commits added support for custom indexes, so that now in some models (only `statespace` right now because there are a lot of moving parts that I don't fully understand to add this to the older models).

Below I'll give some examples of various input `endog`, `dates`, and `freq` combinations and warnings / exceptions that result.

**Comment by ChadFulton** [comment]
**Example 1**: `endog` as numpy array.

```python
np.random.seed(1234)
endog = np.random.normal(size=5)
mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0))
res = mod.fit()
print(res.predict())
# [ 0.         -0.26985572  0.68173024 -0.82010042  0.17896608]
print(res.forecast(2))
# [ 0.41247452 -0.23610587]
print(res.forecast(2, index=['f', 'g']))
# ValueWarning: Because the model data (`endog`, `exog`) were not
#               given as Pandas objects, the prediction output will
#               be Numpy arrays, and the given `index` argument will
#               only be used internally.
# [ 0.41247452 -0.23610587]
```

**Comment by ChadFulton** [comment]
**Example 2**: `endog` as Pandas Series, no dates / index specified

```python
np.random.seed(1234)
endog = pd.Series(np.random.normal(size=5))
mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0))
res = mod.fit()
print(res.predict())
# 0    0.000000
# 1   -0.269856
# 2    0.681730
# 3   -0.820100
# 4    0.178966
# dtype: float64
print(res.forecast(2))
# 5    0.412475
# 6   -0.236106
# dtype: float64
print(res.forecast(2, index=['f', 'g']))
# f    0.412475
# g   -0.236106
# dtype: float64
```

**Comment by ChadFulton** [comment]
**Example 3**: `endog` as Pandas Series, string dates with inferrable freq. given

```python
np.random.seed(1234)
endog = pd.Series(np.random.normal(size=5))
dates = ['1950', '1951', '1952', '1953', '1954']
mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0), dates=dates)
# ValueWarning: No frequency information was provided,
#               so inferred frequency AS-JAN will be used.
res = mod.fit()
print(res.predict())
# 1950-01-01    0.000000
# 1951-01-01   -0.269856
# 1952-01-01    0.681730
# 1953-01-01   -0.820100
# 1954-01-01    0.178966
# Freq: AS-JAN, dtype: float64
print(res.forecast(2))
# 1955-01-01    0.412475
# 1956-01-01   -0.236106
# Freq: AS-JAN, dtype: float64
print(res.forecast(2, index=['f', 'g']))
# f    0.412475
# g   -0.236106
# dtype: float64
```

**Comment by ChadFulton** [comment]
**Example 4**: `endog` as Pandas Series, with "unsupported" index

```python
np.random.seed(1234)
endog = pd.Series(np.random.normal(size=5),
                  index=['a', 'b', 'c', 'd', 'e'])
mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0))
# ValueWarning: An unsupported index was provided and will be
#               ignored when e.g. forecasting.
res = mod.fit()
print(res.predict())
# a    0.000000
# b   -0.269856
# c    0.681730
# d   -0.820100
# e    0.178966
# dtype: float64
print(res.predict(start='c', end='e'))
# c    0.681730
# d   -0.820100
# e    0.178966
# dtype: float64
print(res.forecast(2))
# ValueWarning: No supported index is available. Prediction results will
#               be given with an integer index beginning at `start`.
# 5    0.412475
# 6   -0.236106
# dtype: float64
print(res.forecast(2, index=['f', 'g']))
# f    0.412475
# g   -0.236106
# dtype: float64
```

**Comment by ChadFulton** [comment]
**Example 5**: `endog` as Pandas Series, string dates **without** inferrable freq

```python
np.random.seed(1234)
dates = ['1950', '1951', '1952', '1953', '1956']
endog = pd.Series(np.random.normal(size=5), index=dates)
mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0))
# ValueWarning: A date index has been provided, but it has no
#               associated frequency information and so will be
#               ignored when e.g. forecasting.
res = mod.fit()
print(res.predict())
# 1950    0.000000
# 1951   -0.269856
# 1952    0.681730
# 1953   -0.820100
# 1956    0.178966
# dtype: float64
print(res.predict(start='1953', end='1956'))
# 1953   -0.820100
# 1956    0.178966
# dtype: float64
print(res.forecast(2))
# ValueWarning: No supported index is available. Prediction results will
#               be given with an integer index beginning at `start`.
# 5    0.412475
# 6   -0.236106
# dtype: float64
print(res.forecast(2, index=['f', 'g']))
# f    0.412475
# g   -0.236106
# dtype: float64
```

**Comment by ChadFulton** [comment]
Since no one is interested, I guess I'll keep moving ahead on this. My only question is about the `ValueError` vs `KeyError` backwards compatibility issue (everything else *should* be backwards compatible, but I suppose there will be some corner cases that are not; also I add new features here).

@josef-pkt : do we worry about backwards compatibility on type of exception thrown? Should I leave it as `ValueError` for now and add a `DeprecationWarning`? Or is it okay to change it to `KeyError`?

**Comment by TomAugspurger** [comment]
I gave this a quick skim a couple days ago and +1 to the overall direction. I won't be able to give this a closer look for a while unfortunately. 
Tom






On Thu, Nov 24, 2016 at 11:14 PM -0700, "ChadFulton" <notifications@github.com> wrote:












Since no one is interested, I guess I'll keep moving ahead on this. My only question is about the ValueError vs KeyError backwards compatibility issue (everything else should be backwards compatible, but I suppose there will be some corner cases that are not; also I add new features here).


@josef-pkt : do we worry about backwards compatibility on type of exception thrown? Should I leave it as ValueError for now and add a DeprecationWarning? Or is it okay to change it to KeyError?

**Comment by josef-pkt** [comment]
The examples look good to me, I didn't look at the actual changes.

AFAIR, we never had a discussion about backwards compatibility for the type of exceptions.
In general, I think we should be careful in cases where it is likely that users use exception handling, e.g. we use it in the lag search when optimization fails for some reason, or perfect separation exception in binary models.
I don't think invalid input exceptions are something that will usually be try ... except protected.
So, I think you can keep the change to KeyError and see if anyone complains while it is in master.

**Comment by josef-pkt** [comment]
@ChadFulton one maintainer task is to add labels to issues and PRs :)

**Comment by ChadFulton** [comment]
> @ChadFulton one maintainer task is to add labels to issues and PRs :)

👍

**Comment by ChadFulton** [comment]
@TomAugspurger Thanks for taking even a brief look - that's very helpful. There's no rush on this, so if you think you might be able to take any kind of deeper look (just however close you think is worth your time, doesn't have to be exhaustive) I have no problem just putting it on the back burner until then.

On the other hand, there's no reason to drag it out if you will be too busy in the near-term, and we can simply merge sooner and refine as we go.

One of the non-technical advantages of merging this PR is that I will be more able to take ownership of any date-related issues that come up. This is I think preferable to the current situation where no one has any stake in the current date-handling code.

**Comment by ChadFulton** [comment]
I guess my plan is to to merge this PR tomorrow night. I have no strong preference for this, so if anyone thinks this should wait longer, or needs more review, or needs more tests, or ..., just let me know.

**Comment by TomAugspurger** [comment]
+1 for merge and iterate. Though just to make sure, this won't be back ported to the 0.8 release when that is cut?

**Comment by josef-pkt** [comment]
This cannot be backported. IMO, it will need at least a few months in master so we can see if any corner cases or changes in behavior cause problems for existing user code.

+1 for merge ASAP

**Comment by ChadFulton** [comment]
Great, thanks for your comments. I agree that we'll need some time to make sure this is stable.

**Pull request merged**
