### PR TITLE
Skip slow MixedLM test on some setups

### LINKED ISSUE #2907: TST:  test_lme.TestMixedLM.test_regularized slow or stalls with scipy 0.12
The older python 2.7 version on TravisCI is slow and takes much longer than the newer versions.

Sometimes test_lme.TestMixedLM.test_regularized finishes slowly (based on watching the TravisCI progress), and a few times it stalled. e.g. https://travis-ci.org/statsmodels/statsmodels/jobs/125724307
It stalled first in a PR that doesn't change any non-doc code (#2905)

Because there are no problems on travis with recent versions of dependencies (numpy, scipy, ...), it doesn't look like anything serious, but worth investigating. Is there anything fragile in the tests? 

And, it's a reason to start dropping old numpy and scipy versions.

### PR DESCRIPTION
**Pull request by kshedden**
Closes #2907

### CODE REVIEW

**Comment by bashtage** [comment]
Is .15 a problem? And should it be `@skipif(COND)`?

**Comment by josef-pkt** [comment]
`@skipif(COND)`  would be better, because it's easier to search code for skipped tests, and those tests are reported as skipped tests.

I don't know about the scipy version

**Comment by josef-pkt** [comment]
looks ready to merge, is it? @kshedden

**Comment by kshedden** [comment]
Yes ready.

**Comment by josef-pkt** [comment]
Thanks @kshedden  merged

**Pull request merged**
