### PR TITLE
MAINT: Remove outdated pandas compat shims

### PR DESCRIPTION
**Pull request by jbrockmendel**
Replaces #5036.

### CODE REVIEW

**Comment by josef-pkt** [comment]
LGTM

**Comment by jbrockmendel** [comment]
@josef-pkt ping, defacto green.

**Comment by josef-pkt** [comment]
in it is

@jbrockmendel thank you

(I think this was the last on my shortlist)

**Comment by jbrockmendel** [comment]
Great.  If you’re looking for a new shortlist, 5147 was written for precisely that purpose.

**Pull request merged**
