### PR TITLE
REF: fix non-idiomatic names, closes #5019

### LINKED ISSUE #5019: _diagnostic_count functions starting with "test_" should renamed

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #5019

### CODE REVIEW

**Comment by josef-pkt** [comment]
not now, if ever

I don't like the names, they are not general enough like e.g. `wald_test_xxx`
in OLS diagnostic I tried to prefix with what they are testing, e.g. acorr_xxx, het_xxx

The api is still open, e.g. whether and how to attach them. 
For plots we decided on a post-fix `plot` in functions and prefix `plot` in methods.

**Comment by jbrockmendel** [comment]
Please leave open for discussion of alternatives.

cc @bashtage

**Comment by josef-pkt** [comment]
You can open an issue for discussion, or, better, look for an issue where I worked on this and added my developer notes.

Suggestions for a good api for diagnostics tests are welcome.. My related comments should be in several issues and PRs for this.

At the moment those are private functions that are essentially only used in my notebooks. One of the reasons is that the API is unclear/undecided.

**Comment by josef-pkt** [comment]
https://github.com/statsmodels/statsmodels/labels/topic-diagnostic

There is a lot of room for discussion there

**Comment by josef-pkt** [comment]
> For plots we decided on a post-fix plot in functions and prefix plot in methods.

but that's not currently the case. we have both prefix and postfix plot functions
specifically regression plots are `plot_xxx`

In this module, the idea was to distinguish `test_xxx` functions from `plot_xxx` functions, i.e. visual inspection versus formal hypothesis tests.

**Pull request closed without merging**
