### PR TITLE
DOC: api.py, docstring improvements

### PR DESCRIPTION
**Pull request by josef-pkt**
more docstrings #7564
and api cleanup in stats #7013
The two issues are not finished by this PR, still some problems left

this includes now some additions to api.rst, and some reordering init by topic

### CODE REVIEW

**Comment by josef-pkt** [comment]
Cleanup of module namespaces didn't work (I thought I had done this in the (distant) past)
`del` names at end of module, deletes them from the runtime environment, and breaks functions
e.g. https://stackoverflow.com/questions/30040658/delete-modules-to-clean-namespace

In my notebook I only imported the modules to check available names. I didn't run any functions. That works without problems.

(initially posted to wrong issue)

**Comment by josef-pkt** [comment]
checking module name finds imports, e.g.

`m = [i for i in m if not getattr(getattr(module, i), "__module__", None) == module.__name__]`

but has false positives, if a function is written in another module, but the current module is the "official" public module for it.

**Comment by josef-pkt** [comment]
I removed all the `del` at end of modules again, amended and force pushed to clean commit

I still have a few functions missing in api.py for which I'm not sure about whether or how to add them, e.g. knockoff_effects

**Comment by josef-pkt** [comment]
related aside: `formula.api` has `del` at the end of the module to clean namespace. But it doesn't have functions defined in the module, so there are no problems.

**Comment by bashtage** [comment]
You need to link to the actual location that is used in the docs, not the API version.

**Comment by bashtage** [comment]
Also see
```
/home/runner/work/statsmodels/statsmodels/docs/source/examples/index.rst:394: WARNING: toctree contains reference to nonexisting document 'examples/notebooks/generated/copula'
```

Is notebook working correctly?

**Comment by josef-pkt** [comment]
something strange
notebook and using copula.api in docs works in main
`dev` html docs look correct

**Comment by josef-pkt** [comment]
Import error, I made a mistake and didn't run the `distribution` tests locally.
(I was only paying attention to `stats`)

**Comment by bashtage** [comment]
Can you add an `__all__` to get rid of the unused import messages?

**Comment by josef-pkt** [comment]
problem/type with singular or plural names, I might have to rename a module
`depfuncs_ev` versus `depfunc_ev`
for `transforms` I used plural

**Comment by josef-pkt** [comment]
@bashtage 

why does LGTM ignore pylint and flake options in module?
```
# pylint: disable=W0611
# flake8: noqa
```
which satisfies the azure style check in copulas.api

**Comment by bashtage** [comment]
Why not just add to `__all__` which is the correct approach?

**Comment by josef-pkt** [comment]
> Why not just add to __all__ which is the correct approach?

because it's a pain to maintain and it is never used.

**Comment by bashtage** [comment]
It is used by ipython.

**Comment by josef-pkt** [comment]
another false alarm in docs:

the links to the two other notebooks work correctly in the `dev` html docs

```
/home/runner/work/statsmodels/statsmodels/docs/source/examples/notebooks/generated/formulas.ipynb:201: WARNING: File not found: 'examples/notebooks/generated/regression_diagnostics.html'
/home/runner/work/statsmodels/statsmodels/docs/source/examples/notebooks/generated/formulas.ipynb:498: WARNING: File not found: 'examples/notebooks/generated/contrasts.html'
```

I have one mistake in api.rst, wrong path to model
and one more missing function in `stats.api.__all__`

**Pull request merged**
