### PR TITLE
BUG: MPL boxplot handles lists and arrays differently

### PR DESCRIPTION
**Pull request by jseabold**
See #1090.

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt @jseabold Boxplot should probably be removed in favor of seaborn, which is much more developed and maintained.

**Comment by josef-pkt** [comment]
I put milestone to 0.9 so we have time to decide whether and what we deprecate in graphics.

**Comment by bashtage** [comment]
https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.violinplot.html

**Comment by bashtage** [comment]
This is fixed in master.

**Pull request closed without merging**
