### PR TITLE
TST: Fix incorrect test closes #4325

### LINKED ISSUE #4325: test_arima testing the wrong thing
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/tests/test_arima.py#L1815

```
def test_bad_start_params():
    [...]
    mod = ARMA(endog, (15, 0))
    assert_raises(ValueError, mod.fit)

    inv = load_macrodata().data['realinv']
    arima_mod = ARIMA(np.log(inv), (1,1,2))
    assert_raises(ValueError, mod.fit)
```

I'm pretty sure that last line is supposed to have `arima_mod.fit` instead of re-testing `mod.fit`.

Can we _please_ have a concerted code-quality/cleanup Topic Week?

### PR DESCRIPTION
**Pull request by jbrockmendel**
`assert_raises(ValueError, mod.fit)` is redundant since it has already been called.  Changed to test `arima_mod`.

### CODE REVIEW

**Comment by bashtage** [comment]
LGTM

**Comment by jbrockmendel** [comment]
@ChadFulton this is close enough to your domain, already OKed by bashtage

**Comment by jbrockmendel** [comment]
@josef-pkt fix incorrect test, green, no merge conflict

**Comment by jbrockmendel** [comment]
@ChadFulton I'm gonna try to spend some time away.  Mind merging this obvious test-fix before I go?

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel, enjoy your time.

**Pull request merged**
