### PR TITLE
MAINT: remove cythonize.py made unnecessary by #4871

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@ChadFulton remove cythonize.py made unnecessary by#4871

**Comment by jbrockmendel** [comment]
@josef-pkt if your trouble multitasking has abated enough to look at armacovf, then you can probably handle this (and other) much more obvious things.

Carthage must be destroyed.

**Comment by josef-pkt** [comment]
@bashtage and @ChadFulton  are the cython experts.

(I only looked at arima_process to answer a mailing list question, and at acovf because it was my ancient code.)

**Comment by jbrockmendel** [comment]
You make a good point; bashtage should be able to handle this know me of thing.

**Comment by bashtage** [comment]
It is no longer used.

**Comment by ChadFulton** [comment]
Great to get rid of this file!

**Pull request merged**
