### PR TITLE
DOC: Doc fixes backport to 0.8.x

### PR DESCRIPTION
**Pull request by bashtage**
Fixes for notebooks
Fixes for conf that allow module index to build
Small fixes to docs

### CODE REVIEW

**Comment by bashtage** [comment]
@TomAugspurger @josef-pkt Some fixes that will allow a better set of docs to be built from the 0.8.x branch

**Comment by josef-pkt** [comment]
I'm not sure yet whether we should plan for a 0.8.1 release. We don't know yet if it will be necessary.
If it looks like, then maybe we start with a backport0.8.1 label.

**Comment by bashtage** [comment]
I though these could be merged in just for a doc rebuild.  There are lots of errors in the /stable/ site .

**Comment by josef-pkt** [comment]
Good idea, I didn't think about that

merging, and we have a new label backport-0.8.1  to distinguish it from what's in the release

**Comment by TomAugspurger** [comment]
Just pushed a new build of the docs. Thanks @bashtage!

**Pull request merged**
