### PR TITLE
CLN: Fix and lint for potential double-negatives E713,E714

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
I doubt I will agree to this.
It's not a double negative and I had used this consistently in the past.
(not worth adding noise to history)

**Comment by jbrockmendel** [comment]
Note the word "potential".  It is very easy for readers to miss this, assuming that the author would use the pythonic idiom.

The git history complaint is a bad reason to avoid making things better.

**Comment by bashtage** [comment]
Vote for consistent use of `not in`  and `is not`.

More flake rules that are generally enforced will improve sm over the long term and help its health.

**Comment by josef-pkt** [comment]
@bashtage I agree for current and future code, I switched to `is not` and `not in` a few years ago.

But I don't like the changes in the sandbox which has an older consistent pattern.
I think the sandbox can be excluded from any linting to reduce the history noise there.

**Comment by jbrockmendel** [comment]
Refusing to allow incremental improvements only ensures that things are not incrementally improved.  Tautology for the win.

Between a clean git history and a clean git present, present wins every time.

**Comment by josef-pkt** [comment]
> Between a clean git history and a clean git present, present wins every time.

As a developer I care a lot more about git history than about some ..... pep-8 whitespace rules or `is not` versus `not ... is` in miscellaneous code.
(Furthermore I find binomial proportions again a lot less stressful that pep-8 PRs)

**Comment by bashtage** [comment]
It might be helpful to consider the pov of someone new rather than someone who wrote code in their own preferred style.  A clean, uniform code base with strong rules makes it much easier for new contributors to integrate into the workflow.  Existing code is easier to read since it looks like any other Python code base that uses reasonable rules.  Contributions will also naturally conform to the common style.

Pandas has been a good example of a code base that went from anything that works goes to one that has strict but clear rules.   This has improved DRY and allows contributors who are not developing core features to get involved.  This has allowed some contributors to move form typo/clean/simple refactoring contributors to making larger contributions and/or reviewing other typo/cleaning/refactoring PRs.  I would describe welcoming contribution that make virtually any improvement -- docs, typos, cleaning, modernizing -- as a strong positive feature of an OSS development process.

**Comment by bashtage** [comment]
Rebase and this is in.

**Pull request merged**
