### PR TITLE
MAINT: fix and lint for W292 newline at end of file

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt easy win to top off a productive day

**Comment by jbrockmendel** [comment]
@josef-pkt Travis fail is unrelated from the copulas mess a little while back.  While this _is_ a CLN PR, by construction it won't affect the history you're concerned about.  Let's get it out of the way.

**Comment by bashtage** [comment]
Needs a rebase.

**Comment by bashtage** [comment]
Linting failure.

**Comment by bashtage** [comment]
Longer lint thyself

**Pull request merged**
