### PR TITLE
CLN: strict linting for results files in sandbox/regression/tests/

### PR DESCRIPTION
**Pull request by jbrockmendel**
Among other things, removes 4 duplicated-within-one-file versions of `Bunch`

### CODE REVIEW

**Comment by bashtage** [comment]
Looks like a random fail.

**Comment by bashtage** [comment]
Files for machines.

**Comment by josef-pkt** [comment]
Why do you reformat autogenerated files?

Those are files created by machines, and I don't want any reformating from my machine generated files.
It's not possible to get a diff with the results of a new run of the same Stata file.

**Comment by jbrockmendel** [comment]
> of the same Stata file.

which stata file?  I'll make sure it produces the same lint-compliant format.

Besides which, a medium-term goal I've got in mind is ensuring (in the CI or possibly a less-often-run analogue) that the results files are reproducable.

**Comment by josef-pkt** [comment]
I'm producing, reproducing and reading the Stata results files and I write the unit tests.
And as long as I'm the only one doing that, I get my preferred format and not some pep8 version.
(You can reformat when I completely retire.)

**Comment by bashtage** [comment]
Why not just throw a single call to autopep8 in the function that creates the files, in which case there is no challenge in creating clean files programmatically.  Something like

```
import autopep8

with open('dumped-results.py') as res:
    clean = autopep8.fix_code('x.has_key(y)\n', options={'aggressive': 1})
with open('dumped-results.py', 'w') as res:
    res.write(clean)
```

I use the same method when converting notebooks to python files example (only using yapf).

**Comment by bashtage** [comment]
The reason to clean files for machines is that it might allow additional rules to be enforced to the entire codebase which will produce code that it more readable in the long-run.  That is always the goal behind enforcing style in code. It is the same reason NumPy, SciPy and pandas enforce style.

**Comment by josef-pkt** [comment]
at least flake8 has an option to mark a module as exempt
http://flake8.pycqa.org/en/latest/user/violations.html#ignoring-entire-files
Maybe also the other pep-8, linters have an option like this

**Comment by bashtage** [comment]
I agree that in exceptional circumstances, say a very dirty file that is blocking a directory being put under lint (e.g., var_model or similar), then it is reasonable to except a file tightening the rules around new additions.  I requested that we add Pep8 speaks, don't know if you saw that.

**Comment by josef-pkt** [comment]
I saw the pep8 speaks request, but when I checked it was already installed. It says now installed 2 days ago.

Do I need to do anything to get it to work? It looks like it already has the required permissions on github.

**Comment by bashtage** [comment]
It should start posting -- lets what and see.

**Pull request merged**
