### PR TITLE
BUG: Ensure internal tester exits with error if needed

### PR DESCRIPTION
**Pull request by bashtage**
Ensure that the internal tester errors when an internal error was encountered

### CODE REVIEW

**Comment by josef-pkt** [comment]
this exits the interpreter after a call to statsmodels.test(), doesn't it?

This is not intended behavior, i.e. we want to be able to use repeated calls in the same python session.
```
statsmodels.regression.test()
statsmodels.genmode.test()
...
```

**Comment by bashtage** [comment]
It appears to be needed to get a correct status when running on a CI

python -c "import statsmodels;statsmodels.test()"

I'll just make it optional with a kwarg exit=False by default.

**Comment by josef-pkt** [comment]
kwarg sounds good

In an old version I had
`sudo $PYTHON -c "import statsmodels as sm; a=sm.test(); import sys; sys.exit((len(a.failures)+len(a.errors))>0)"`

e.g. https://github.com/statsmodels/statsmodels/pull/1082/files#diff-354f30a63fb0907d4ad57269548329e3L49

but adding an exit kwarg is simpler

**Comment by josef-pkt** [comment]
looks good to me as far as I can tell

green enough, merging

@bashtage Thank you

**Pull request merged**
