### PR TITLE
BUG: Fix return of ValueError instead of Raise

### LINKED ISSUE #4997: web._generate_url returns ValueError--> intentional?
```
            return ValueError('Input not understood')
```
seems like it should be `raise` instead of `return`.  Am I missing something?

### PR DESCRIPTION
**Pull request by jbrockmendel**
closes #4997 

Cleanups in the vicinity, add a bunch of files to the strict-lint list.

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@josef-pkt definitely a bugfix here.

**Comment by jbrockmendel** [comment]
@josef-pkt green, OKed by bashtage, no merge conflicts... best 3 minutes you'll spend all day.

**Comment by josef-pkt** [comment]
1 line BUG, 3 or 4 lines REF out of 80 lines in 11 modules

You are also deleting commented out asserts that might be working now (pandas in predict)

That's more than 3 minutes, and more later if I have to find a few relevant lines in the git history of this PR.

**Comment by jbrockmendel** [comment]
You make a fair point about the commented-out asserts, someone should fix those.  The fact remains that a bunch of very easy PRs have been sitting idly for weeks.

**Comment by jbrockmendel** [comment]
I’ll update to in-delete bad asserts

**Comment by jbrockmendel** [comment]
Deletion of commented-out assertions reverted.

**Comment by jbrockmendel** [comment]
BTW #5136 re-enables those assertions

**Pull request closed without merging**
