### PR TITLE
DOC: Update release instructions [skip ci]

### PR DESCRIPTION
**Pull request by bashtage**
Update release instructions for versioneer

### CODE REVIEW

**Comment by bashtage** [comment]
I did a dry run on my repo and they worked fine.  Obviously couldn't test the twine step, but I know that one works.

**Comment by bashtage** [comment]
@thequackdaddy I think this is the correct release strategy for a tag-is-build-number release.

**Comment by bashtage** [comment]
You can see the effects here: 

https://github.com/bashtage/statsmodels/releases

and here:

https://github.com/bashtage/statsmodels/branches

**Comment by bashtage** [comment]
I'm going to purge those eventually but will leave them up for a while.

**Comment by josef-pkt** [comment]
LGTM

To get the full steps you could add a section for how to release from the maintenance branch, e.g. to make the final release after the rc1.

**Comment by bashtage** [comment]
I should look in @matthew-brett since I'm not sure when the wheels should be built. Ideally, these would be built after the release is final, but tags are pretty light weight and can be deleted. One option would be the 

 - tag
 - push tag
 - build wheels off tag, make sure every thign passes*
 - upload sdist and wheels

* If wheel building fails, delete the release tag, fix the issue, and retag the release. 

I think this doesn't destroy git history, although it is a bit complicated.

**Comment by josef-pkt** [comment]
release tags are not "cheap". 
They are automatically picked up by one of the reference (ISBN like) registration service.
It happened to me once when I released an unfinished version in the middle of the release process.

**Comment by bashtage** [comment]
But what happens if you delete it and then republish the same tag?

**Comment by josef-pkt** [comment]
I don't remember much. I'm trying to find some information.
We have a github webhook for `Zenodo` to pick up `release` tags.
It might be similar to pypi that you cannot change a distribution file or binary once it is release.

https://github.com/statsmodels/statsmodels/issues/2403#issuecomment-120645676

I never looked at how Zenodo works except for the one time with the premature release tag.
I cannot figure out from the tags what I did.
It must have been for the 0.6 release which was my first release after Skipper became unavailalble

**Comment by josef-pkt** [comment]
zenodo show a 0.7rc1 https://zenodo.org/record/30622#.W6UBdM5KjIU
which doesn't exist anymore as tag or release on github
so I guess I just deleted the tag release that was incorrect, and gave up figuring out releasing 0.7

**Comment by bashtage** [comment]
Should probably do a `pre` like `v0.10.0.pre0` using a lightweight tag (non-annotated) and then make sure that builds correctly.  If it does, then release.  If not, fix and tag `v0.10.0.pre1` and try again.   Once passing, final tag on branch.  I think the lightweight tags can be freely cleaned up.

**Comment by josef-pkt** [comment]
AFAIU, non-release tags are for free. 
Converting a non-release tag to a release tag can be done by just pushing a "Publish Release" button on github's "edit tag" page.

**Pull request merged**
