### PR TITLE
BLD: Add platform-specific skips

### PR DESCRIPTION
**Pull request by bashtage**
Add the ability to manually skip each platform using the syntax below anywhere in the commit message

[skip appveyor]
[appveyor skip]
[skip travis]
[travis skip]

### CODE REVIEW

**Comment by bashtage** [comment]
Can reduce pressure on CI when only working on docbuild issues or appveyor debugging.

**Comment by bashtage** [comment]
Could add [skip circle] or [circle skip] for #5238

**Comment by bashtage** [comment]
If you look at the builds, they are all skipped shortly after starting. Not as nice as [skip ci] which is still preferred, but appveyor has gotten strange about skip ci/skip appveyor (needs to be in commit subject now) and sometimes you want to skip one but not the other.

**Comment by jbrockmendel** [comment]
Seems like an easy win.  Needs rebase

**Pull request merged**
