### PR TITLE
EqClass covariance structure for GEE

### PR DESCRIPTION
**Pull request by kshedden**
This PR adds a new covariance structure to GEE that allows the covariances among pairs of observations to be specified through a collection of equivalence classes.  All pairs of observations within an equivalence class have the same covariance.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Another test case would be AR with equ class being time distance.

I didn't try to understand the details well enough, but looks fine overall. Eventually, I guess we need to speed up the loops.

**Comment by kshedden** [comment]
Right now our AR is only AR(1), so the correlation between two observations made d time units apart is r^d.  Thus except for the trivial case where the distances are constant, I don't think it is equivalent to an EqClass covariance.  I need to add a more flexible AR at some point.

**Comment by josef-pkt** [comment]
The PR looks fine, 
the name started to bother me a bit `eq`  usually stands for equal or equation
I think the name should be extended to at least `Equiv`, or `EquivalenceClass` or just `Equivalence`

`class` has a different meaning from the programming `class`, which I would prefer to avoid, but we don't have to avoid it.

**Comment by josef-pkt** [comment]
@kshedden  thanks, merging

**Pull request merged**
