### PR TITLE
WIP-GLM nonlinearity test-issue#1479

### PR DESCRIPTION
**Pull request by mina1987**
This is an initial WIP PR for issue#1479 for the fulfillment of the GSoC2019 PR requirement.

### CODE REVIEW

**Comment by josef-pkt** [comment]
wrong location

The word "tests" means two different things in statsmodels
- unit tests; those are in the folders called `tests` which are located in each subpackage
- hypothesis tests: those are located with the models or in central locations like modules in `statsmodels.stats` for example statsmodels.stats.diagnostics.

I think we will add a genmod.diagnostic.py module to collect GLM specific unit tests.
(I'm not sure yet whether we want to add more diagnostic and specification tests to statsmodels.stats or to new modules in the model specific folders.)

**Comment by mina1987** [comment]
> wrong location
> 
> The word "tests" means two different things in statsmodels
> 
> * unit tests; those are in the folders called `tests` which are located in each subpackage
> * hypothesis tests: those are located with the models or in central locations like modules in `statsmodels.stats` for example statsmodels.stats.diagnostics.
> 
> I think we will add a genmod.diagnostic.py module to collect GLM specific unit tests.
> (I'm not sure yet whether we want to add more diagnostic and specification tests to statsmodels.stats or to new modules in the model specific folders.)

Sorry about that. I think having a genmode.diagnostic.py is a good idea. For now I will add a reset_ramsey_GLM to outliers_influence.py. It can be relocated in the future.

**Comment by josef-pkt** [comment]
Don't copy the previous comment into the reply, unless it is just a short segment when replying to a specific item.
On the github issue page we see the full sequence comments

I just found #4697 again, i.e. I'm not sure yet how the module structure and location for diagnostic tests should look like, once we get the for several models and at different generality.

**Comment by josef-pkt** [comment]
@mina1987 any news on your PR, reset test for glm?

**Comment by mina1987** [comment]
I plan to have an initial commit for Poisson reset test in
diagnostics.genmod next week. I am busy this week with some deliverables
for PhD program.

**Comment by josef-pkt** [comment]
The problem is that we need to tell the PSF and Google how many student slots we would like to have. So far, we haven't seen enough of your work to tell whether you will be able to have a successful GSOC with this topic.

**Comment by josef-pkt** [comment]
closing, no code

**Pull request closed without merging**
