### PR TITLE
CLN: remove empty __main__ sections

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Sure would be nice if there was a way to make coveralls not "fail" on this kind of thing.

**Comment by ChadFulton** [comment]
LGTM. Will merge this tomorrow unless there are concerns. Please feel free to ping if I forget.

**Comment by jbrockmendel** [comment]
@ChadFulton I think the following are all in the no-brainer category (at worst there may be a merge conflict because many of these touch setup.cfg, but GH will tell us if that's the case):

#4883 (this)
#4895 
#4888 
#4897 
#4900 
#4874 
#4846 
#4849

**Comment by jbrockmendel** [comment]
ping

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel

**Pull request merged**
