### PR TITLE
WIP: Relax precision for ppc64el

### PR DESCRIPTION
**Pull request by ginggs**
- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by ginggs** [comment]
Building statsmodels 0.9.0 fails on the ppc64el architecture (IBM POWER) in Ubuntu.

```
____________________ TestDiagnosticG.test_compare_nonnested ____________________

self = <statsmodels.stats.tests.test_diagnostic.TestDiagnosticG object at 0x3fff74cb6790>

    def test_compare_nonnested(self):
        res = self.res
        res2 = self.res2
        #jt = jtest(fm, lm(ginv ~ ggdp + tbilrate))
        #Estimate         Std. Error  t value Pr(>|t|)
        jtest = [('M1 + fitted(M2)', 1.591505670785873, 0.7384552861695823,
                  2.155182176352370, 0.032354572525314450, '*'),
                 ('M2 + fitted(M1)', 1.305687653016899, 0.4808385176653064,
                  2.715438978051544, 0.007203854534057954, '**')]
    
        jt1 = smsdia.compare_j(res2, res)
        assert_almost_equal(jt1, jtest[0][3:5], decimal=13)
    
        jt2 = smsdia.compare_j(res, res2)
>       assert_almost_equal(jt2, jtest[1][3:5], decimal=14)
E       AssertionError: 
E       Arrays are not almost equal to 14 decimals
E       
E       Mismatch: 50%
E       Max absolute difference: 1.99840144e-14
E       Max relative difference: 5.73115664e-14
E        x: array([2.71543897805152, 0.00720385453406])
E        y: array([2.71543897805154, 0.00720385453406])

statsmodels/stats/tests/test_diagnostic.py:480: AssertionError
```
```
____________________ TestDiagnosticG.test_compare_nonnested ____________________

self = <statsmodels.stats.tests.test_diagnostic.TestDiagnosticG object at 0x3fff6f62f3a0>

    def test_compare_nonnested(self):
        res = self.res
        res2 = self.res2
        #jt = jtest(fm, lm(ginv ~ ggdp + tbilrate))
        #Estimate         Std. Error  t value Pr(>|t|)
        jtest = [('M1 + fitted(M2)', 1.591505670785873, 0.7384552861695823,
                  2.155182176352370, 0.032354572525314450, '*'),
                 ('M2 + fitted(M1)', 1.305687653016899, 0.4808385176653064,
                  2.715438978051544, 0.007203854534057954, '**')]
    
        jt1 = smsdia.compare_j(res2, res)
        assert_almost_equal(jt1, jtest[0][3:5], decimal=13)
    
        jt2 = smsdia.compare_j(res, res2)
        assert_almost_equal(jt2, jtest[1][3:5], decimal=13)
    
        #Estimate        Std. Error  z value   Pr(>|z|)
        coxtest = [('fitted(M1) ~ M2', -0.782030488930356, 0.599696502782265,
                    -1.304043770977755, 1.922186587840554e-01, ' '),
                   ('fitted(M2) ~ M1', -2.248817107408537, 0.392656854330139,
                    -5.727181590258883, 1.021128495098556e-08, '***')]
    
        ct1 = smsdia.compare_cox(res, res2)
>       assert_almost_equal(ct1, coxtest[0][3:5], decimal=13)
E       AssertionError: 
E       Arrays are not almost equal to 13 decimals
E       
E       Mismatch: 50%
E       Max absolute difference: 2.44915199e-13
E       Max relative difference: 4.35353472e-13
E        x: array([-1.304043770978,  0.192218658784])
E        y: array([-1.3040437709778,  0.1922186587841])

statsmodels/stats/tests/test_diagnostic.py:489: AssertionError
```

**Comment by ginggs** [comment]
Is relaxing the precision to allow these tests to pass pcc64el acceptable?

If so, I will retry building against current head and updating the patch if more changes are needed.

**Comment by bashtage** [comment]
Can you add a Travis build for ppc?

**Comment by josef-pkt** [comment]
you could change the assert to using `assert_all_close`
This is old code before`assert_all_close` existed in numpy

relaxing precision is fine, those are tight. AFAIR we had linalg differences across machines where we needed to relax to 1e-12

**Comment by bashtage** [comment]
Travis PPC looks like

https://github.com/bashtage/randomgen/blob/master/.travis.yml#L30

Would need to use pip

**Comment by ginggs** [comment]
Thanks, I will rebuild against current head and look at switching to `assert_all_close`.

**Pull request merged**
