### PR TITLE
ENH: Add optional parameters for summary_col to indicate FEs (rebased)

### PR DESCRIPTION
**Pull request by josef-pkt**
rebased version of #9191
changes startswith to `in`, adds unit tests

closes #9191

### CODE REVIEW

**Comment by josef-pkt** [comment]
Warning: We cannot remove all trailing whitespaces in test_summary2.
The desired reference strings that we compare to need trailing whitespace.
summary_col, summary2 as_text has trailing whitespace to make it rectangular.

**Comment by adrianmross** [comment]
Thanks for picking this up, this looks great!

**Comment by adrianmross** [comment]
@donbowen it's in.

**Comment by donbowen** [comment]
🔥 good job @adrianmross ! Very very cool to see a student add a feature to a package. I’m going to have to update some code because of you now :)

**Comment by josef-pkt** [comment]
related stackoverflow question that I just found in a different PR

https://stackoverflow.com/questions/49471014/python-do-not-show-dummies-in-statsmodels-summary

**Pull request merged**
