### PR TITLE
MAINT: Travis fixes

### PR DESCRIPTION
**Pull request by thequackdaddy**
A little WIP here... some of this will fail. There's also some PEP8 issues I haven't thought fully through yet.

### CODE REVIEW

**Comment by josef-pkt** [comment]
I left the pep-8 in gam intentionally, and fixed line lenght and similar.
The indent changes in your PR are fine, I'm just not convinced I want to end a line with an open parenthesis.
But don't "fix" the unused variable/name pep-8 complaints. Those need substantive review and enhancements or refactoring and are left as reminder, (at least most of them, I didn't check every unused name again.)

Thanks for tackling pandas compatibility.

**Comment by thequackdaddy** [comment]
Yes, I wasn't clear. I have no intention of removing the unused variables from the test files as they appear to be smoketests. What I meant by fixing them was really silencing the rest. 

I did remove a couple unused lines from the actual non-test modules. I can revert if you like, but they are clearly irrelevant.

**Comment by thequackdaddy** [comment]
Oh and there is still a strange Pandas error that I haven't cracked yet.

**Comment by thequackdaddy** [comment]
I think I'm happy with this. Let me know if you want something changed.

**Comment by josef-pkt** [comment]
great, travis is all green again, appveyor has one #5457

I only skimmed the changes and didn't try to understand the pandas changes, but LGTM AFAICS

Thanks a lot, merging

**Comment by thequackdaddy** [comment]
My pleasure. statsmodels is a great.

Meant to ask a local—I’ll be in Quebec City for a couple days in a few weeks. Any must-see attractions?

**Pull request merged**
