### PR TITLE
TST: use same corr_fact as elsewhere instead of hand-defining it

### PR DESCRIPTION
**Pull request by jbrockmendel**
Just a guess as to what this is supposed to be.

Places where results had to be manually tinkered with should have big TODO notes to systematically get an extra pair of eyeballs every so often

### CODE REVIEW

**Comment by josef-pkt** [comment]
This change removes all the information about weights. `nobs` is not directly relevant here.
It also replaces a comment specific to this case with a generic one which looses information.

do NOT merge

**Comment by josef-pkt** [comment]
If this passes with `corr_fact = np.sqrt((nobs - 1.) / nobs)` which seems to be the case with green test results, then this needs an issue and review.
I think it shouldn't pass with nobs, or Stata does something "strange" and we need substantive review of the df correction decision, i.e. we don't hide this in a test cleanup PR.

**Comment by jbrockmendel** [comment]
Definitely agreed this is a Discussion Starter and nothing else.  The discussion at hand: is it a coincidence that this gives us the same `corr_fact`?  Is there a comment that could be added that would retain the relevant information and let us use the non-bespoke impleemntation?

**Comment by josef-pkt** [comment]
You could leave the comment as is and comment out the old corr_fact, and then add your nobs based corr fact with a comment that unit tests pass with it.
And open an issue that this needs investigation.

weights is a difficult topic, and Stata's usage is good but I don't agree with all their decisions and definitions. So, investigating this is quite a bit of work, especially given that I didn't get this part. 
(Stata always normalizes wsum = nobs except for freq_weights, ....)
I don't remember the details.

**Pull request closed without merging**
