### PR TITLE
implement copy_doc decorator, use it in discrete

### PR DESCRIPTION
**Pull request by jbrockmendel**
This is purely aesthetic.  If there's concensus, I'll incrementally apply it elsewhere.

Note it comes with tests.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Given that it's just replacing one "obvious" line with something where it's difficult to guess how it works, my first impression is negative. (obfuscation?)

I this purely import time or does it also have a runtime penalty?

**Comment by josef-pkt** [comment]
The other usual question was how does it affect tab completion and the visibility of the signature?

(I haven't looked at decorators in years, when I had a strong aversion to them.)

**Comment by jbrockmendel** [comment]
> I this purely import time or does it also have a runtime penalty?

purely import-time

> The other usual question was how does it affect tab completion and the visibility of the signature?

Unaffected.

To the extent that it's just a matter of aesthetic preferences, a) I'll defer to you and b) might be worth asking if others have opinions.

**Comment by josef-pkt** [comment]
This pull request fixes 1 alert - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-c597fe4c1c1434eed5db52b916d0f9c49f8bb5e5)

**fixed alerts:**

* 1 for Mismatch between signature and use of an overridden method

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
Actually there is a not-purely-aesthetic difference: pep8/flake8 prefers this version.

**Comment by jbrockmendel** [comment]
False-positive errors are a higher priority.  Closing.

**Pull request closed without merging**
