### PR TITLE
WIP: Exponential smoothing

### PR DESCRIPTION
**Pull request by jseabold**
This includes #1484 and will need to be rebased on master when that is put into master. This is not close to merging. The only thing that's tested is the `ses` model. I don't even know how to replicate some of these models yet in R, so this is going to be a longer term project than I'd hoped.

### CODE REVIEW

**Comment by ispmarin** [comment]
Any news on this front? Can I help somehow? I can't clone the rep right now.

**Comment by jseabold** [comment]
What this needs is for someone to sit down and code the optimization heuristics to help convergence that Hyndman talks about in his book. It's not a ton of work, but it's very much not sexy/fun.

**Comment by jseabold** [comment]
Actually might be worth putting in the new state space framework we have. A decent amount of the code may be able to be re-used but maybe not.

**Comment by ispmarin** [comment]
Could you please put some pointers in the existing state space framework code?

**Comment by jseabold** [comment]
https://github.com/statsmodels/statsmodels/tree/master/statsmodels/tsa/statespace

There are notebooks in the example folder.

**Comment by jseabold** [comment]
The tests and dataset can be re-used certainly. I think they may already be in master. This needs a rebase. I'll see about it soon-ish.

**Comment by ispmarin** [comment]
Great. I'll try to take a look at it after work.

**Comment by josef-pkt** [comment]
statespace model is so far only linear (and, less relevant, Gaussian)

Can all of the exponential smoothed methods be represented as linear statespace model?

**Comment by jseabold** [comment]
Yes, as far as I recall. The multiplicative error models might need a transformation, but I haven't looked at this in a long time.

**Comment by datnamer** [comment]
Is this dead?

**Comment by Leoyzen** [comment]
I've working on a simple case of exponential smoothing based on new SSM, as the same as tbats model of R forecast package.I have no clue how to transform multiplicative version to linear.

**Comment by conorbmurphy** [comment]
What's the latest on this?  I was looking to develop a similar tool before I stumbled across this thread.  Will this be incorporated into statsmodels?

**Comment by zachmayer** [comment]
@Leoyzen Can't you log transform to convert a multiplicative model to linear?

**Comment by zachmayer** [comment]
>What this needs is for someone to sit down and code the optimization heuristics to help convergence that Hyndman talks about in his book. It's not a ton of work, but it's very much not sexy/fun.

@jseabold Where in the book does he talk about optimization heuristics?

**Comment by bashtage** [comment]
@josef-pkt This has been superseded by released code.

**Comment by josef-pkt** [comment]
Holt Winters was merged in #4176,  released in 0.9.0, 
refactored in #4845 for 0.10

**Pull request closed without merging**
