### PR TITLE
DOC: Linear regression diagnosis

### PR DESCRIPTION
**Pull request by pkaf**
Example notebook to create diagnostic plots to identify potential problems in linear regression.

### CODE REVIEW

**Comment by pkaf** [comment]
Starting clean again, @bashtage

**Comment by bashtage** [comment]
LGTM, but need to check out the failure.

**Comment by bashtage** [comment]
Seems random, thanks.

**Comment by pkaf** [comment]
Thank you.

I have updated the landing.yml, do I have to do any thing additional to get the example in here https://www.statsmodels.org/stable/examples/index.html ? @bashtage

**Pull request merged**
