### PR TITLE
TST: Re-enable webuse test

### PR DESCRIPTION
**Pull request by bashtage**
Re-enable test with direct check for file availability.

closes #2278

### CODE REVIEW

**Comment by josef-pkt** [comment]
most likely I don't merge this for 0.8
The only automatic testing for this is pythonxy Ubuntu nightly, which won't run right away. I also don't remember why we had to go back and forth on this several times.

**Comment by josef-pkt** [comment]
looks fine to me, put in merge queue

**Comment by bashtage** [comment]
@josef-pkt This is harmless so can be merged IMO.

**Comment by josef-pkt** [comment]
merged, thanks @bashtage 

I don't think we have currently any test runners that don't allow internet access. We will need to see if Debian and Ubuntu are fine with this.

**Pull request merged**
