### PR TITLE
BUG: Prevent indent running on None

### LINKED ISSUE #7460: is class DocString modifying c-extension `tp_doc` attributes after PyTypeReady?
https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/tools/docstring.py#L534

It seems the DocString class is modifying `tp_doc` strings after `PyTypeReady` has been called, which does not work on PyPy. It works only by chance on CPython. Is it possible to modify this code to do that manipulation in a precompile step, write the docstrings out to a header file, and read them in before instantiating the type?

xref [PyPy issue 3471](https://foss.heptapod.net/pypy/pypy/-/issues/3471). Another option would be to (like NumPy) be aware that the `__doc__` attribute may be empty for optimized python (when using `python -OO`) or for PyPy.

### PR DESCRIPTION
**Pull request by bashtage**
Use non-protected indent to prevent indent on None

- [X] closes #7460 
- [X] code/documentation is well formatted.  
- [X] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by josef-pkt** [comment]
Why did you delete all the gee simulation files?

**Comment by bashtage** [comment]
Accident -- they are all broken and when I was trying to recursively import all modules, these were raising.  I meant to move them to a sub-folder where they were no longer part of a module, but I think it doesn't really matter now.

**Comment by stonebig** [comment]
Will there be a statsmodels-0.12.3 patch release in June ?

**Comment by bashtage** [comment]
No. Next release is 0.13 which will likely be late summer.

**Pull request merged**
