### PR TITLE
TST: Use assert_allclose instead of assert_approx_equal etc

### PR DESCRIPTION
**Pull request by jbrockmendel**
This isn't even close to all of them, but it makes a real dent.

### CODE REVIEW

**Comment by bashtage** [comment]
It is hard to switch these.  For example, 0.000000001 and 0.000000009 are approx equal with decimal=8 but are not assert_allclose with any reasonable rtol (but with an atol=1e-8).  I suppose rtol=0 and atol=1e-DECIMAL should be very similar.

**Comment by jbrockmendel** [comment]
hopefully more tedious than difficult.  The binding constraint will be maintainer willingness to allow change.

**Comment by josef-pkt** [comment]
(I didn't have github access for some time this morning)

I think to improve the unit tests in a move to assert_allclose, we need to go through all the unit tests and check whether rtol makes more sense and what a good rtol is.
(I converted a few asserts when I was in a neighborhood of some of those tests.)

second: changing assert is a big, potentially dangerous refactoring (unless it's equivalent which I don't like) and should not be mixed with style cleanups in one PR.

**Comment by josef-pkt** [comment]
(github access was broken again after send, and I still have incomplete access)

clarifying (because I also got briefly confused)

0.000000001 and 0.000000009 are *almost* equal with decimal=8
0.000000001 and 0.000000009 are *approx* equal with significant=0   (they don't agree on any significant digit)

almost_equal uses only a rounded atol
approx_equal uses only a rounded rtol
allclose can handle either or both

However, I think if we change this, then we should "tune" again our precision requirement in assert_allclose. There will be cases where using both can have tighter tolerance requirements, e.g. when the values are pretty different in magnitude and some are close to zero.

In the past I only did a few conversions when I was in the neighborhood and knew roughly the context of the test, and had already access to the test numbers.

**Comment by jbrockmendel** [comment]
I'll give this another shot, leaving almost_equal alone for now.

**Comment by jbrockmendel** [comment]
@josef-pkt many things would be easier if more progress can be made on #5147.  Let me/us know if that can be made easier somehow.

**Pull request closed without merging**
