### PR TITLE
WIP: PCA class

### PR DESCRIPTION
**Pull request by jseabold**
Fair warning, I haven't looked at this code in 2 years. Rescued and rebased from upstream. Deleted the branch in upstream to keep things tidy.

Would be nice to replicate the notebook of @kshedden with the class to get an idea of what needs to be fixed, added, generalized, etc. Comments (or PRs) very welcome.

http://nbviewer.ipython.org/urls/umich.box.com/shared/static/6m7f4lw9bdog241kqcmb.ipynb

### TODO

- [ ] add tests (correlation only eyeball tests so far)
- [x] move out of sandbox
- [x] replicate notebook / add notebook to examples
- [x] add fertility data to datasets
- [ ] code review
- [ ] add to release notes
- [x] add to main docs
- [x] scree plot
- [ ] projections method in results
- [ ] MLE (or information criteria) for selecting keepdim
- [ ] factor rotations
- [ ] add pandas wrapping
- [ ] where should this code live?
- [ ] symmetric eigen decompositions

### CODE REVIEW

**Comment by josef-pkt** [comment]
PR #2004  has been merged.   
This PR can be closed unless there is still something in here that we need to use and include

**Comment by springcoil** [comment]
+1 for this to be merged.

**Comment by bashtage** [comment]
If there is a chance this will be merged, I'm happy to rebase

**Comment by josef-pkt** [comment]
@bashtage   Your PCA version has been merged a year ago.
This is Skipper's older version, but I haven't checked whether there are still extras or examples left in here that's not in master yet.

**Comment by bashtage** [comment]
Ok. Perils is github email responses. I think I strictly nested, including
notebooks.

**Comment by josef-pkt** [comment]
Thanks, closing then

**Pull request closed without merging**
