### PR TITLE
BUG: clustered cov fails when groups are 2d vector. Closes #2168

### LINKED ISSUE #2168: BUG: get_robustcov_results('cluster') fails if `groups` is 2D vector
```python
import pandas as pd
import numpy as np
from numpy.random import randn, randint

import statsmodels.api as sm

N = 1000000
Ng = 100000
df = pd.DataFrame({'y': randn(N), 'a': randn(N), 'b': randn(N),
                   'group': randint(Ng, size=N)})
reg = sm.OLS.from_formula('y ~ a + b', df).fit()
if 1 == 1:
    # Variation 1: An (N, 1) array
    clust = reg.get_robustcov_results('cluster', groups=df[['group']].values)
else:
    # Variation 2: An (N, 1) DataFrame
    clust = reg.get_robustcov_results('cluster', groups=df[['group']])
```
As far as I can tell from the documentation, passing these kind of arrays should be supported. It also seems like it should be very easy to fix both. I would have just gone straight to a pull request, but I haven't been using statsmodels very long and I'm still getting a feel for the code, philosophy, etc etc. Wanted to check first before spending the time.

Versions: win7, python 2.7.7 (Anaconda), pandas 0.15.2, numpy 1.9.1, statsmodels 0.7.0 (pulled about 10 minutes ago)

### PR DESCRIPTION
**Pull request by dmsul**
fixes #2168,  
cov_type cluster fails if groups has extra dimension, missing squeeze

### CODE REVIEW

**Comment by dmsul** [comment]
Wasn't sure how this kind of input test should be handled. Happy to hear any suggestions to change it up.

**Comment by josef-pkt** [comment]
I made comment in commit instead of PR by accident.

thanks @dmsul 
I'll need to look at this, my guess would be that it should not be in the `elif` part, but I don't remember enough without going through the code again.

**Comment by josef-pkt** [comment]
I didn't know that a pandas DataFrame `squeeze`s to a Series.

**Comment by dmsul** [comment]
I just pushed a new commit to this branch. Moved the `squeeze` to its own if statement, changed the test to use a DataFrame if pandas is installed.

While I getting this to work, I noticed that using a DataFrame to pass groups for 2way clustering failed because they slice differently than arrays. I added two lines to fix that and some tests to cover it. As soon as I pushed the commit I realized that this is probably its own issue. I'll be happy to move them to their own branch etc. if that's the case.

**Comment by dmsul** [comment]
Took out the try-except parts around pandas.

**Comment by josef-pkt** [comment]
I think this looks good, 

The same change needs to be applied to statsmodels.base.covtype   since this code duplication hasn't been removed yet (it's almost completely a copy)

**Comment by josef-pkt** [comment]
I think it's better to squash these 3 commits

**Comment by dmsul** [comment]
Changes copied, commits squashed.

**Comment by josef-pkt** [comment]
looks good, all green, merged

Thanks @dmsul

**Pull request merged**
