### PR TITLE
MAINT: remove exact duplicate file datamlw.py

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt ping; I'd really rather not clog up the CI with rebasings of super-easy PRs.

**Comment by josef-pkt** [comment]
@jbrockmendel not specific to this PR
It's no use rebasing or pushing 15 or so PRs at once.
We have a 24 hour queue on our CI, which means higher priority PRs won't get merged either.

**Comment by jbrockmendel** [comment]
> We have a 24 hour queue on our CI, which means higher priority PRs won't get merged either.

My point is that the relevant constraint is not the CI but your ability/willingness to review/merge PRs. Since I don't expect you to change your habits, the solution here to to empower Kevin to handle topics where he has a significant comparative advantage.

**Comment by jbrockmendel** [comment]
@josef-pkt ping; green again.

**Comment by jbrockmendel** [comment]
@josef-pkt ping

**Comment by jbrockmendel** [comment]
@josef-pkt still trivially easy

**Comment by jbrockmendel** [comment]
@josef-pkt super-easy, going on 4 weeks old

**Comment by jbrockmendel** [comment]
@josef-pkt I'm holding off on pushing rebased versions of a handful of things.  In the meantime, a few that are especially easy and ready: 4941 (this), 5211, 4325, 5070, 4977, 5003, 5005, and less-easy but close 5121, 5127

**Comment by jbrockmendel** [comment]
@josef-pkt removes a file which is an exact duplicate of another file

**Comment by jbrockmendel** [comment]
@ChadFulton empty appvryor queue, good time to be a hero

**Comment by jbrockmendel** [comment]
@josef-pkt duplicate file ->  bigger distribution size -> more bandwidth used -> electricity usage -> carbon emissions -> TEOTWAWKI

**Comment by jbrockmendel** [comment]
@josef-pkt exact duplicate file

**Comment by jbrockmendel** [comment]
@josef-pkt reviewing this amounts to confirming that the file is, as I claim, an exact duplicate.  Carthage could be destroyed by a trained monkey here.

**Comment by jbrockmendel** [comment]
@josef-pkt this got your OK two weeks ago.  Merge?

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel!

**Pull request merged**
