### PR TITLE
ensure MultinomialResults has J, K.  Get rid of unnecessary lmap usage

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request **fixes 1 alert** when merging 54ab7401fcbf8fa36a627545a254ef5b1bbf3ced into 1ca7113cea3e652b627a07dee00bad34b97567e4 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-fc5fe93eea7a273d31d857222f242dee19f56acf)

**fixed alerts:**

* 1 for First argument to super\(\) is not enclosing class

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
Appveyor is still segfaulting in test_simulate.  Unrelated to this pr

**Comment by jbrockmendel** [comment]
ping

**Comment by jbrockmendel** [comment]
@josef-pkt

**Comment by jbrockmendel** [comment]
@josef 6 months old and super easy

**Comment by bashtage** [comment]
rebase and it is in

**Comment by bashtage** [comment]
Some sort of nontrivial bug in the PR now.

**Comment by jbrockmendel** [comment]
@bashtage the linting jobs seem to think this PR is introcuding the removed file dump2module.  Any idea what thats all about?

**Comment by bashtage** [comment]
Rebase.

**Comment by jbrockmendel** [comment]
already up-to-date

**Comment by jbrockmendel** [comment]
(could do dummy commit to force CI?)

**Pull request merged**
