### PR TITLE
ENH: Replacement for AR

### PR DESCRIPTION
**Pull request by bashtage**
A replacement for the error-prone AR class that only uses OLS
and refers users to SARIMAX for MLE.

- [ ] closes #xxxx
- [ ] tests added / passed. 
- [X] code/documentation is well formatted.  
- [X] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by bashtage** [comment]
@ChadFulton my part in revamping tsa to get rid of problematic things.  I think there is still room for a pure AR that only uses OLS since it avoids initial values. This model is also an ARDL when using exog rather than an OLS with AR errors.

**Comment by ChadFulton** [comment]
> I think there is still room for a pure AR that only uses OLS since it avoids initial values. This model is also an ARDL when using exog rather than an OLS with AR errors.

Very nice! Definitely people will like the ARDL and seasonal-via-OLS option.

I'll take another look tomorrow or Saturday - with my other `tsa`-related stuff, one of the main goals was to get more consistency in `tsa`, and for me what was easiest was just subclassing everything from SARIMAX. I think that's not an option here because of how `exog` is entering as intercept while in SARIMAX it's the mean, but we can make sure that what we're all doing keeps the consistency anyway.

Are you planning to do a deprecation cycle and eventually make this the `AR` model?

**Comment by bashtage** [comment]
> Are you planning to do a deprecation cycle and eventually make this the `AR` model?

Yes, a loud, hard to silence warning (no flag, so users have to use `warnings.simplefilter` explicitly). 

I will use the same pattern as your `tsa2`.  If We rename, then I'll use `AutoReg`. If we use a new submod, then this will become `tsa.NEWLOC.AR`. The latter is starting to seem better. We can leave `tsa.NEWLOC.AR` for a very long time (possibly forever, even if we also have this function at `tsa.AR` eventually.

**Comment by ChadFulton** [comment]
(Sorry for delay)

Obviously this is a big improvement over the current `AR` model and it adds features that people will want to use, so I think it's better to get it in sooner than later.

Basically, the thing that I've been thinking about is that I would like to eventually have some or all of the functionality of this class available in the framework consistent with #5827. The main two reasons for me are: (1) easier to ensure consistency across models for support and documentation / discoverability purposes, and (2) model selection based on #5151 will be easier to implement since everything is defined the same.

But I guess that trying to do that in this PR would probably make it take a long time to get merged, which doesn't sound like a good idea. And maybe that's undesirable for other reasons too (e.g. the complexity of the state space framework can make it hard for contributors other than me to reason about bugs, etc.).

So I think my only question is just: is it problematic that I might eventually duplicate some of this functionality elsewhere? To me it is not a problem.

**Comment by bashtage** [comment]
I think duplication is OK as long as it is intentional.  I'm not sure there will be another OLS-based AR/ARDL though.  I've thought about extending this to a propper ARDL which would also need to understand the lag structure of the X variables.

**Comment by bashtage** [comment]
This model could be adapted to the framework once in as well, although it supports options that are not common (seasonal dummies).

**Comment by josef-pkt** [comment]
I haven't looked at this and just saw it.

One good reason to keep MLE instead of OLS is that it can be extended to non-Gaussian distributions and it's easier to impose restrictions or penalization. This is easier with non-linear optimization than with linear algebra estimation methods.
(e.g. miscmodels has a TArma model for ARMA with t distributed errors, but just has the usual results and no time series specific results. )

**Pull request merged**
