### PR TITLE
BUG: Fix name-related error in random_effects

### PR DESCRIPTION
**Pull request by kshedden**
This came up in discussion of #2961.

What I have here fixes the issue and adds a test, but I want to change the names to be more consistent (sometimes they are Z1, Z2, etc. which is not very meaningful).

### CODE REVIEW

**Comment by kshedden** [comment]
I changed the default names from Z1 RE, etc. to V1 RE.  (V for "variable").  I guess this is better.

**Comment by josef-pkt** [comment]
`"V"` sounds more like "variance" to me. 

"x_re1"  ?
"x_re1 RE"   ? What is `exog_re_names_full` used for? 

(I don't remember what various parts mean here, or never tried to figure it out.)

**Comment by kshedden** [comment]
@josef-pkt I went with your suggestion here.  If no other issues I think it is ready to merge.

**Comment by josef-pkt** [comment]
good, merged

(aside: I'm busy until Friday with a forecasting presentation, and will continue with another round of review and merging on Friday)

**Pull request merged**
