### PR TITLE
FIX Bootstrapping GenericLikelihoodModel with no exog

### PR DESCRIPTION
**Pull request by mtzl**
See #944 

EDIT: I think I should add some tests...

### CODE REVIEW

**Comment by josef-pkt** [comment]
A unit test would be helpful because we don't have any no-exog cases.
related: #2633 GMM has the same problem and there is a gamma distribution parameter example.

What are your extra `__init__` arguments that you mention in the issue?

The changes looks good based on reading through it.
However, it might be good to take this opportunity to check and update some things.

e.g. 
- we use now `_init_kwds` instead of cloneattr. 
- if extra init kwds are nobs arrays, e.g. weights or offset, then we would also have to use the bootstrap selection, and not the original arrays.

**Comment by josef-pkt** [comment]
a general comment:

My workaround if there are no real exog was always to use an array of ones, i.e. just a constant that could mean any of the parameters, or even not be used at all in the loglike and derivatives.

**Comment by josef-pkt** [comment]
I restarted one of the travis jobs that stopped even before getting to statsmodels.

**Comment by josef-pkt** [comment]
It will take me a day to understand the implementation again, and to see where we want to improve this additionally to changes in this PR.

In your notebook, the use of bootstrap is misleading because it doesn't do any inplace modifications, AFAICS. The results in summary are based on hessian, asymptotic standard errors.
I thought I had a version with parameter covariance from bootstrap instead of just standard errors `bse`

**Comment by josef-pkt** [comment]
another example for distribution fitting, but doesn't use bootstrap in #2527 MLE for Gamma, should be comparable to the GMM version in #2633

I think I'm changing my mind about adding more refactoring here. My last round was in 2013 and GenericLikelihoodModel and results need a face lift and updating. Many things have changed in 5 years, and some of my early experiments with GenericLikelihoodModel are no part of the general structure, e.g. we can use cov_type to set the cov_params_default in `Results.__init__` which could take the bootstrap cov, and we could get rid of the old ResultMixin parts like covjac.
But that's several days or a week of refactoring.

**Comment by mtzl** [comment]
I'm currently trying to add the `_init_kwds` support; the only issue currently is to make it compatible with `ModelData.handle_missing` -- I don't want to change that one since it would require far more bits in the code.

> In your notebook, the use of bootstrap is misleading because it doesn't do any inplace modifications, AFAICS. The results in summary are based on hessian, asymptotic standard errors.
I thought I had a version with parameter covariance from bootstrap instead of just standard errors bse

Ah, okay. I really only looked at the histogrammed output of `result.bootstrap` -- I don't need it to be written into the summary, the issue was just that is wanted to look at `summary` independently of the bootstrap. I should clarify this in the notebook, I assume -- it's just there to demonstrate that this unrelated method does not raise an exception.

**Comment by josef-pkt** [comment]
> How is this be addressed? Just keep using the cloneattr for now and refactor this elsewhere?

Yes, fixing directly the problem within the current setting will have minimal side effects.

I opened #4679 for more general refactoring. But refactoring in `base` is not easy, and usually it takes me a while just to figure out where all the pieces connect and where possible side effects might occur.
And then it's still necessary to take backwards compatibility and our deprecation policy into account.
I didn't want to get far into #4679 because currently I'm refactoring or enhancing other parts which also require keeping track of many moving parts. 
(The advantages and disadvantages of writing and maintaining generic code.)

**Comment by josef-pkt** [comment]
This pull request **introduces 1 alert** and **fixes 3** when merging 0f94dc0e579cb918c6ea1dfd79839cc97381c8af into 6611e878fb625e20b587a34c208f69e1b9d2495b - [view on LGTM.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-a58999710c609fcfb0c45a36b928ddc5cd4b93b7)

**new alerts:**

* 1 for Unreachable code

**fixed alerts:**

* 2 for Variable defined multiple times
* 1 for Unreachable code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
It looks like this needs some heavier git surgery to extract the commits of this PR.
I'm trying to do an interactive rebase

**Comment by josef-pkt** [comment]
I opened PR #5143 with an interactively rebased version.
I didn't check yet whether everything is fine with it.

**Comment by bashtage** [comment]
closed by #5143

**Pull request closed without merging**
