### PR TITLE
small steps of algebra simplification

### PR DESCRIPTION
**Pull request by jbrockmendel**
The NegBin and GeneralizedPoisson likelihood/score/hessians are big hotspots for profiling.  They are _also_ complicated spots of algebra that are difficult to read/inspect.

This cleans them up a little bit and does a _few_ substitutions to reduce redundant calculations.  There are several more steps worth of algebraic simplification available, but this is a place where its easy to make mistakes, so let's do this in bite-size pieces.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Any objections to this?  Doing this as a first-step will make subsequent algebraic steps much easier.

**Comment by jbrockmendel** [comment]
This is mostly just changing where line-breaks are to break on addition and subtraction and avoid breaking on multiplication and division.

**Comment by jbrockmendel** [comment]
green button

**Comment by jbrockmendel** [comment]
@ChadFulton little help?  Because this is an algebra-simplification thing, it needs to be broken into many individually-trivial steps.  That plan only works if there's a quick-ish turnaround.

**Comment by ChadFulton** [comment]
I reviewed the changes and they look fine to me (I didn't see any substitutions that you mentioned in the OP?) although I don't have an opinion on whether they represent an improvement over the status quo.

I will plan to merge tomorrow night unless there are concerns.

**Comment by jbrockmendel** [comment]
You're right; the main thing this does is change e.g.

```
(foo*bar + baz *
zap - baz * bar *
foo / baz)
```

to 

```
(foo * bar +
baz * zap -
baz * bar * foo / baz)
```

The idea being that this makes subsequent steps much more obvious.

**Comment by jbrockmendel** [comment]
ping

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel

**Pull request merged**
