### PR TITLE
BUG fix pickling for discrete fit_regularized

### LINKED ISSUE #2685: Discrete models fit_regularized save pickle fails
saving a `fit_regularized` causes pickle to fail:

``` python
class TestRemoveDataPicklePoissonRegularized(RemoveDataPickle):

    def setup(self):
        #fit for each test, because results will be changed by test
        x = self.exog
        np.random.seed(987689)
        y_count = np.random.poisson(np.exp(x.sum(1) - x.mean()))
        model = sm.Poisson(y_count, x)  #, exposure=np.ones(nobs), offset=np.zeros(nobs)) #bug with default
        self.results = model.fit_regularized(method='l1', disp=0, alpha=10)


        #TODO: temporary, fixed in master
        self.predict_kwds = dict(exposure=1, offset=0)
```

gives:

```
Traceback (most recent call last):
  File "statsmodels/base/tests/test_shrink_pickle.py", line 290, in <module>
    tt.test_remove_data_pickle()
  File "statsmodels/base/tests/test_shrink_pickle.py", line 68, in test_remove_data_pickle
    res, l = check_pickle(results._results)
  File "statsmodels/base/tests/test_shrink_pickle.py", line 27, in check_pickle
    cPickle.dump(obj, fh, protocol=cPickle.HIGHEST_PROTOCOL)
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

### PR DESCRIPTION
**Pull request by josef-pkt**
#3678 interactively rebased with edit of changes

#2685 original bug report
#2686 unit test PR

`closes #2685, closes #2686, closes #3678`

### CODE REVIEW

**Comment by josef-pkt** [comment]
strange thing: 
I cannot run the statsmodels/base/tests/test_shrink_pickle.py with nosetests. If I kill it with Ctrl+C, then it shows problems with loading multiarray.c around/in kalman

test_shrink_pickle.py runs without errors with pytest, and tsa tests run and pass in the interpreter (`statsmodels.tsa.test() which uses pytest)

also, I don't have problems running the discrete tests with nosetests

**Comment by josef-pkt** [comment]
ready to merge if green

**Comment by josef-pkt** [comment]
Thanks @kashif @jbrockmendel

**Comment by kashif** [comment]
thank you!

**Pull request merged**
