### PR TITLE
CI: Add Python 3.11 jobs

### PR DESCRIPTION
**Pull request by EwoutH**
Add Python 3.11 jobs to the Azure pipelines CI.

- [x] part of #8287
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message).

### CODE REVIEW

**Comment by bashtage** [comment]
I think you missed a flag allowing experimental pythons so 3.11rc2 was not found.

**Comment by bashtage** [comment]
These errors on Windows are disturbing:
```
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\03ff0982-4e99-4cc0-a1d9-ea80a607e06f.cmd""
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
ERROR: while parsing the following warning configuration:

```

We are supposed to be used latest supported numpy which is supposed to automatically handle this.

**Comment by EwoutH** [comment]
I fixed the Python versions syntax. It looks like the Windows errors are unrelated, right?

I would recommend reviewing and merging this PR https://github.com/statsmodels/statsmodels/pull/8430, which add a weekly scheduled run to the Azure pipelines. That way we can detect errors caused by upstream dependencies or changes in the build environment earlier.

**Comment by bashtage** [comment]
This is happending because pandas moved the locations of certain errors.  You can delete the line `error:Estimation of VARMA:statsmodels.tools.sm_exceptions.EstimationWarning` from the pyproject file in your PR.

**Comment by josef-pkt** [comment]
> You can delete the line error:Estimation of VARMA:statsmodels.tools.sm_exceptions.EstimationWarning from the pyproject file in your PR.

I don't really know what that means, pyproject.toml doesn't have anything like this. Is the a different pyproject file?

It looks like there is a separate issue building the documentation #8432

**Comment by EwoutH** [comment]
The last run that passed used SciPy 1.9.1. The first run that failed [1.9.2](https://github.com/scipy/scipy/releases/tag/v1.9.2). It could be that there is an issue caused by or related to that change.

**Comment by EwoutH** [comment]
Scikit-learn also has issues with the latest SciPy release: https://github.com/scikit-learn/scikit-learn/issues/24612#issuecomment-1273818865

We probably should create a separate issue for this.

**Comment by bashtage** [comment]
Could just pin Scipy !=1.9.2

**Comment by EwoutH** [comment]
There is now also a discussion on the SciPy repo, we could see how that plays out: https://github.com/scipy/scipy/issues/17191

**Comment by bashtage** [comment]
@EwoutH if you rebase on main and force push it might pass now.

**Comment by EwoutH** [comment]
The current issue is that [lxml](https://github.com/lxml/lxml) doesn't have Python 3.11 wheels available on [PyPI](https://pypi.org/project/lxml/4.9.1/#files), and it fails to build the wheels itself. There is a tracking issue for this: https://bugs.launchpad.net/lxml/+bug/1977998

The Python 3.10 error on Windows is the NumPy error again, and unrelated: `RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe`.

I can highly recommend merging #8430 to catch those errors on the main branch early.

**Comment by bashtage** [comment]
If you rebase on main you should get past the windows error. It is a scipy build issue.

**Comment by EwoutH** [comment]
How heavy is the dependency on [lxml](https://github.com/lxml/lxml)? I feel the repository is not that actively maintained, and their build infrastructure looks outdated and fragile. It could be a source of more build issues in the future.

**Comment by bashtage** [comment]
It isn't that important. I suspect it is needed by the doc build.  Do you know what is requesting it?

**Comment by EwoutH** [comment]
Difficult to say, I used [pipdeptree](https://pypi.org/project/pipdeptree/) and it doesn't look like a dependency of statsmodels itself.

```
statsmodels==0.13.2
  - numpy [required: >=1.17, installed: 1.23.4]
  - packaging [required: >=21.3, installed: 21.3]
    - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
  - pandas [required: >=0.25, installed: 1.5.1]
    - numpy [required: >=1.21.0, installed: 1.23.4]
    - python-dateutil [required: >=2.8.1, installed: 2.8.2]
      - six [required: >=1.5, installed: 1.16.0]
    - pytz [required: >=2020.1, installed: 2022.5]
  - patsy [required: >=0.5.2, installed: 0.5.3]
    - numpy [required: >=1.4, installed: 1.23.4]
    - six [required: Any, installed: 1.16.0]
  - scipy [required: >=1.3, installed: 1.9.3]
    - numpy [required: >=1.18.4]
```
dependencies

**Comment by bashtage** [comment]
I looked and it is being pulled in by the sphinx-theme AFAICT.  You could see hat happens if you comment out all of the docbuild stuff from requirements-dev.

**Comment by EwoutH** [comment]
Testing it out at https://github.com/statsmodels/statsmodels/pull/8428, see this [pipeline run](https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=4700&view=results)

**Comment by bashtage** [comment]
I think one more rebase if you incorporate the changes in the requirements should get it done.

**Comment by bashtage** [comment]
Same for your other PRs.

**Comment by bashtage** [comment]
Progress, but now something to do with Cython.

**Comment by EwoutH** [comment]
Great news, everything [is passing](https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=4716&view=results) on my [test PR](https://github.com/statsmodels/statsmodels/pull/8428)!

I ported the changes from that PR to this one, cleaned up and rebased. This PR is ready for review and merging!

@bashtage Thanks for all the help!

**Comment by bashtage** [comment]
Close and reopen to retrigger CI

**Comment by EwoutH** [comment]
Fixed the issue, the macOS images are lacking a bit behind.

See https://github.com/actions/runner-images/issues/6459#issuecomment-1290645470.

**Comment by EwoutH** [comment]
@bashtage all checks pass, so I say let's go!

**Comment by bashtage** [comment]
One comment.  Could you move the OSX back to 3.10.  The latest marker is for lastest dependencies, not Python.  We don't have a lot of capacity to debug OSX so something more stable than 3.11 makes sense for us.

**Comment by bashtage** [comment]
Thanks.

**Comment by EwoutH** [comment]
Sorry, just saw you last comment, thanks for merging!

Ironically Python 3.11.0 was just added to macOS runners (https://github.com/actions/setup-python/issues/531#issuecomment-1291855440), so we don't need the pre-release anymore. I've created #8466 in which this is reverted.

**Pull request merged**
