### PR TITLE
MAINT: strict linting for test_varmax

### PR DESCRIPTION
**Pull request by jbrockmendel**
@ChadFulton 

also updated usages of `assert_raises` to more readable `with pytest.raises`

### CODE REVIEW

**Comment by ChadFulton** [comment]
Why is `assert_equal` bad?

**Comment by jbrockmendel** [comment]
> Why is assert_equal bad?

Take a look at how it is used at the moment: `assert_equal(re.search('Results for equation %s' % name, table) is None, False)`.  This is obviously a relic being forced to avoid `assert ` statements;  a reader will find that _much_ less intuitive than the pythonic replacement `assert re.search('Results for equation %s' % name, table)`

**Comment by ChadFulton** [comment]
> a reader will find that much less intuitive than the pythonic replacement assert re.search('Results for equation %s' % name, table)

This seems like a dubious empirical claim :)

**Comment by jbrockmendel** [comment]
> This seems like a dubious empirical claim :)

Are you serious?  Because I expect I compose a large portion of the non-you/josef readership of these files and I as such I am an expert on the empirics of this claim.

**Comment by jbrockmendel** [comment]
Can we get this over with.  The regexp part in particular should be obvious after a good night's sleep.

**Comment by jbrockmendel** [comment]
>> a reader will find that much less intuitive than the pythonic replacement` assert re.search('Results for equation %s' % name, table)`

> This seems like a dubious empirical claim :)

Consider a thought experiment about internal consistency. `tsa.x13` has the code:

```
    if re.search("Mean is not significant", results.results):
        include_mean = False
    elif re.search("Constant", results.results):
        include_mean = True
    else:
        include_mean = False
```

I contend that this is much more readable than the alternative:

```
    if np.equal(re.search("Mean is not significant", results.results) is None, False):
        include_mean = False
    elif np.equal(re.search("Constant", results.results) is None, False):
        include_mean = True
    else:
        include_mean = False
```

The notion that `assert_equal(re.search(...) is None, False)` is clearer than `assert re.search(...)` is analogous to the notion that the latter `if np.equal(...)` version above is clearer than the existing code in `tsa.x13`.

**Pull request closed without merging**
