### PR TITLE
Initial commit to fix issue 2178

### LINKED ISSUE #2178: ENH hazard regression prediction with formula
When hazard_regression was fit with a formula, the predict method doesn't accept a new exog data frame to be processed through the formula.  Needs refactoring.

### PR DESCRIPTION
**Pull request by kshedden**
This should close #2178.

### CODE REVIEW

**Comment by jseabold** [comment]
lgtm

**Comment by jseabold** [comment]
FWIW, in the future, if you add `Closes #2178` to the commit message then it will automatically close the issue, those Josef also wants you to still list the PR # in the description.

**Comment by kshedden** [comment]
Will do.  Thanks for the review.

**Comment by josef-pkt** [comment]
looks good to me also
However, I don't like the inconsistent returns of predict across models, still TODO but this PR doesn't  affect or change it.

around 6 unrelated commits behind master, so still ok.

**Pull request merged**
