### PR TITLE
Use scientific-python-nightly-wheels

### PR DESCRIPTION
**Pull request by jarrodmillman**
Update to use new location for nightly builds:
- https://anaconda.org/scientific-python-nightly-wheels/

More details are available here:
- https://scientific-python.org/specs/spec-0004/

This depends on https://github.com/pandas-dev/pandas/pull/53341

How do you build and upload wheels to https://anaconda.org/scipy-wheels-nightly/ currently? There is a GH action that you may want to use (see https://scientific-python.org/specs/spec-0004/#build-nightly-wheels).

### CODE REVIEW

**Comment by bashtage** [comment]
This is just the testing fix.  AFAICT, there is no pandas there yet, so for now, you would need to have two pip installs, one for numpy and scipy and one for pandas at the old location.

The upload script live at https://github.com/MacPython/statsmodels-wheels/

**Comment by jarrodmillman** [comment]
NumPy, SciPy, and Pandas wheels are all being uploaded to the new location now:
- https://anaconda.org/scientific-python-nightly-wheels/numpy/files
- https://anaconda.org/scientific-python-nightly-wheels/scipy/files
- https://anaconda.org/scientific-python-nightly-wheels/pandas/files

You may want to take a quick look to make sure all the wheels you expect are there. Let me know if there are any issues.

**Comment by jarrodmillman** [comment]
See fae5488b99ed248befd11e430aaa12d95fd6df21

**Comment by mattip** [comment]
Hi. I see many files still at https://anaconda.org/channels/scipy-wheels-nightly/packages/statsmodels/files which this PR moved away from. Can I delete them?

**Pull request closed without merging**
