### PR TITLE
MAINT: remove code explicitly marked as "not used anymore"

### PR DESCRIPTION
**Pull request by jbrockmendel**
Part of the effort to salvage usable (and used!) code from sandbox.stats.multicomp

### CODE REVIEW

**Comment by jbrockmendel** [comment]
> I will have to go through multicomp as a refactoring/enhancment project.

Yep, that's what I'm trying to get a move on, in pieces small enough to be trivially reviewed.  This module is used from outside sandbox, so the current level of QA is unacceptable.

**Comment by josef-pkt** [comment]
The parts that are used outside are unit tested.
Refactoring doesn't mean deleting code, it means writing more unit tests and getting more options to work correctly, or verifying that they already do so.

**Comment by jbrockmendel** [comment]
> The parts that are used outside are unit tested.

This should be made obvious to the not-so-casual reader (e.g. yours truly) by creating a clear delineation between useful and non-useful code.

> Refactoring doesn't mean deleting code

In the case of things marked e.g. "to be deleted" I'm sure there are more appropriate terms than "refactoring", but deleting is usually the appropriate course of action.

**Comment by jbrockmendel** [comment]
PS a bunch of super-easy PRs got tagged by bashtage yesterday, any chance we can see movement on them today?

**Comment by jbrockmendel** [comment]
Closing temporarily to clear the queue.

**Pull request closed without merging**
