### PR TITLE
BLD: Ensure master is available when linting

### PR DESCRIPTION
**Pull request by bashtage**
Travis only clones a single branch by default. Manually clone master

### CODE REVIEW

**Comment by jbrockmendel** [comment]
The coveralls false positive is annoying.  Is the config in the repo?  Or in josef’s account?

**Comment by bashtage** [comment]
This doesn't produce a fp.  Instead the modifications I put in place to strictly lint new files aren't being run since master isn't available on travis.   This will allow new files to be strictly linted.  At least that is that I think is happening.

**Comment by bashtage** [comment]
The coveralls is either due to a bug in the way they aggregate coverage
from multiple runs or a noisy test that sometime covers a branch and other
time doesn't.

**Comment by jbrockmendel** [comment]
> The coveralls is either due to a bug in the way they aggregate coverage

Yah, I think it may be in mixed_linear_model (#5082).  I was thinking of the config because rgommers mentioned a few threads back that scipy sets the failure cutoff at 1% to avoid this issue.

**Comment by bashtage** [comment]
This may not be needed.

**Comment by josef-pkt** [comment]
coveralls: I had mixed up percent and fraction, the threshold was at 0.011 percent, now I changed it to 0.11 percent which should cover the -0.03 percent.

**Comment by bashtage** [comment]
This is needed to get the new file lint to work correctly and should be correct now.

**Comment by bashtage** [comment]
@josef-pkt small build issue about linting

**Comment by josef-pkt** [comment]
merging, (I assume it's fine, I don't know enough to tell whether a partial, depth limited would be enough. looks fast enough) 

@bashtage thank you

**Pull request merged**
