### PR TITLE
BUG: Statespace: get_prediction/get_forecast with exog

### LINKED ISSUE #3108: No Confidence Intervals for SARIMAX Forecast
Hey,

I am using the function SARIMAX from statsmodels 0.8.0 with an exogenous variable. It seems that the methods get_prediction() and subsequently conf_int() do not work out-of-the box when used with an exogenous variable, is that correct?

I get the following error message: "ValueError: Forecasting for models with time-varying obs_intercept matrix requires an updated time-varying matrix for the period to be forecasted."

### PR DESCRIPTION
**Pull request by ChadFulton**
Closes #3108.

@josef-pkt I change the order of keyword arguments in this PR to make the SARIMAX methods match with the generic mlemodel method order. Is that considered a backwards incompatible change that I should avoid?

### CODE REVIEW

**Comment by josef-pkt** [comment]
There is no backwards compatibility problem here also because it hasn't been released yet.
We don't guarantee the sequence of keywords as general policy, although we should be careful.

unit tests for the exog shapes are missing.

**Comment by josef-pkt** [comment]
are there still `predict` and `forecast` methods after renaming of the methods to the `get_xxx` methods?

**Comment by ChadFulton** [comment]
> unit tests for the exog shapes are missing.

I'll add these. I also need to add similar tests for the UC models.

> are there still predict and forecast methods after renaming of the methods to the get_xxx methods?

Yes, they can be safely inherited from the parent, because they're just wrappers over the get_xxx methods that only return the `predicted_mean` attribute.

**Comment by ChadFulton** [comment]
Closes #3111

**Comment by ChadFulton** [comment]
This is now green and good to merge, also should be good to backport.

**Pull request merged**
