### PR TITLE
TST: de-duplicate a ton of test code for IRLS

### PR DESCRIPTION
**Pull request by jbrockmendel**
This can be simplified way further if my guess about #4935 is right.

### CODE REVIEW

**Comment by josef-pkt** [comment]
I only briefly skimmed this

I'm not sure this is the right approach or split of functions #4612
i.e. needs careful review and some thoughts about the structure for reusable components for additional test cases in future.

**Comment by jbrockmendel** [comment]
What approach do you have in mind?  I’m open to suggestions.

**Comment by josef-pkt** [comment]
I'm not sure, I haven't thought much about the details
some thoughts
a new module should only have helper function or classes but not unit tests directly. I don't like the splitting out of test functions into test_irls because `irls` is just an method option in the regular classes and conceptually it doesn't belong in a separate module.

helper function or class or other object should include a list of all combinations and generate datasets, similar to what's in the current loops. My guess is that this needs an option to provide exog, e.g. I have been working recently often with the two sample case (constant + 1 dummy variable).
The final target would be something that can easily be reused for additional functionality in future, e.g. something that statsmodels base generic tests are also useful for.

**Comment by jbrockmendel** [comment]
Fair enough.  While I start in on another pass at this, any thoughts on #4935?

**Comment by jbrockmendel** [comment]
Re-written so as to not create a new file.  Written with an eye towards parametrizing in the medium-run.  Ideally these big loops would be separate tests and we would xfail non-convergent cases instead of skipping them.  That way we know when they get fixed.

The only actual change in logic here is in the value `lin_pred` takes in `test_glm_weights` in the cases with `(family_class, link) == (fam.NegativeBinomial, lnk.identity)`.  In master this clips at `1e-3`, while the two tests in `test_glm` clip at `1e-4`.  This makes them all clip at `1e-4`.

One difference in behavior that it would be nice to standardize:  `lin_pred` in the case with `(family_class, link) == (fam.Poisson, lnk.sqrt)` is `lin_pred = 2 + exog.sum(1)` for the two tests in `test_glm`, but `lin_pred=-2 + exog.sum(1)` for the test in `test_glm_weights`.  If there isn't a compelling reason for the difference, it would be nice to not need the special case.

**Comment by jbrockmendel** [comment]
Travis failure in grouputils unrelated.  @josef-pkt something else relevant changed recently?

**Comment by josef-pkt** [comment]
about travis test failure: I didn't find any changes in the environment at the time when the failure started to show up, The dependencies that I checked, numpy, scipy, pandas, cython and some spot checking for others all seem to be the same versions as before.

**Comment by jbrockmendel** [comment]
Ok.  I can’t help with the appveyor one, but will look into the new Travis failure.

Identifying real errors would be much easier if the queue of easy PRs got trimmed.

**Comment by jbrockmendel** [comment]
@josef-pkt green

**Comment by jbrockmendel** [comment]
@josef-pkt this isn’t just de-deuplication, it’s preparatory to identifying and then trying to fix cases with convergence problems.

**Comment by jbrockmendel** [comment]
@josef-pkt tracking down the cases with convergence problems is something you care about right?  This is a step towards that goal.

**Comment by jbrockmendel** [comment]
@josef-pkt green and no merge conflict.  I'd really like to get this through so I can move on to troubleshooting the non-convergent cases.

**Comment by jbrockmendel** [comment]
@bashtage any thoughts here?  Besides the virtues of de-duplication, this will go a long way towards making tests parametrizable so we can get more systematic coverage.

**Pull request closed without merging**
