### PR TITLE
Fail more gracefully on bad exog for ARMAX

### PR DESCRIPTION
**Pull request by rishabmarkand**
fixes https://github.com/statsmodels/statsmodels/issues/2129

Let me know if any changes are to be made, especially with the error message.

### CODE REVIEW

**Comment by bashtage** [comment]
When does this occur?  Can you write a more direct test rather than producing all do the values that fit makes?

**Comment by bashtage** [comment]
You should also add a test that will trigger this error that checks that this error was raised.

**Comment by rishabmarkand** [comment]
It appears to occur when the exog matrix has one or more constant columns and trend='c'

**Comment by bashtage** [comment]
I think you can just check for a constant in exog and if trend == 'c'.  You can check for a constant using something like

```
nobs = x.shape[0]
rank = matrix_rank(np.hstack((ones((nobs, 1)), x)))
has_constant = rank == x.shape[1]
if has_constant and trend == 'c':
    raise ValueError()
```

rather than a full call to GLS.

**Comment by bashtage** [comment]
At a minimum this needs a test that will raise the error to ensure it is correct.  

The PR would be better it if directly tested the rank rather than relying on a full fit of GLS which could be slow if the dataset is large.

**Comment by rishabmarkand** [comment]
```python
def safe_is_const(s):
                try:
                    return 0.0 in np.ptp(s,axis=0) and np.any(s != 0.0)
                except:
                    return False
            if safe_is_const(exog) and trend == 'c':
                raise ValueError("Shape mismatch between exog and endog"
                                " matrices. Check that the exog matrix"
                                " is not comprised of constant columns.")
```
After checking for constant column in the exog in the above manner, numerous other (previously written) test cases produce errors. However, after the running the GLS fit, if I check the equality of k (the no. of exogenous vars including constant) and the number of ols parameters, the test cases are passing.

```python
if k != len(ols_params):
    raise ValueError("Shape mismatch between exog and endog"
                                " matrices. Check that the exog matrix"
                                " is not comprised of constant columns.")
```
This snippet seems to fix the issue. Let me know what you think!

**Comment by bashtage** [comment]
This specific issue appears to be fixed in master.

**Pull request closed without merging**
