### PR TITLE
DOC: add recent stats addition to docs

### PR DESCRIPTION
**Pull request by josef-pkt**
add functions from my recently merged `stats` PRs

I don't build docs locally, so I don't know which mistakes there are

### CODE REVIEW

**Comment by bashtage** [comment]
I don't understand the point of putting in half-baked functions into master.

Quite a few of the docstrings of these recently introduced functions are not good, and are below the quality of what should be merged:

```
statsmodels.stats.meta_analysis.combine_effects: Double line break found; please use only one blank line to separate sections or paragraphs, and do not leave blank lines at the end of docstrings
statsmodels.stats.meta_analysis.combine_effects: Parameter "alpha" description should start with a capital letter
statsmodels.stats.meta_analysis.combine_effects: Parameter "effect" description should start with a capital letter
statsmodels.stats.meta_analysis.combine_effects: Parameter "method_re" description should start with a capital letter
statsmodels.stats.meta_analysis.combine_effects: Parameter "row_names" description should start with a capital letter
statsmodels.stats.meta_analysis.combine_effects: Parameter "row_names" type should use "str" instead of "string"
statsmodels.stats.meta_analysis.combine_effects: Parameter "variance" description should start with a capital letter
statsmodels.stats.meta_analysis.combine_effects: Parameters {use_t, **kwds} not documented
statsmodels.stats.meta_analysis.combine_effects: The first line of the Returns section should contain only the type, unless multiple values are being returned
statsmodels.stats.meta_analysis.effectsize_2proportions: Parameter "count1, nobs1, count2, nobs2" description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_2proportions: Parameter "statistic" description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_2proportions: Parameter "zero_kwds" description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_2proportions: Parameters {nobs1, count1, nobs2, count2} not documented
statsmodels.stats.meta_analysis.effectsize_2proportions: Return value description should finish with "."
statsmodels.stats.meta_analysis.effectsize_2proportions: Return value description should finish with "."
statsmodels.stats.meta_analysis.effectsize_2proportions: Return value description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_2proportions: Return value description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_2proportions: Sections are in the wrong order. Correct order is: Parameters, Returns, See Also, Notes
statsmodels.stats.meta_analysis.effectsize_2proportions: Summary must start with infinitive verb, not third person (e.g. use "Generate" instead of "Generates")
statsmodels.stats.meta_analysis.effectsize_2proportions: Unknown parameters {count1, nobs1, count2, nobs2}
statsmodels.stats.meta_analysis.effectsize_smd: Double line break found; please use only one blank line to separate sections or paragraphs, and do not leave blank lines at the end of docstrings
statsmodels.stats.meta_analysis.effectsize_smd: Parameter "mean1" description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_smd: Parameter "mean2, sd2, nobs2" description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_smd: Parameter "nobs1" description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_smd: Parameter "sd1" description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_smd: Parameters {sd2, mean2, nobs2} not documented
statsmodels.stats.meta_analysis.effectsize_smd: Return value description should finish with "."
statsmodels.stats.meta_analysis.effectsize_smd: Return value description should finish with "."
statsmodels.stats.meta_analysis.effectsize_smd: Return value description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_smd: Return value description should start with a capital letter
statsmodels.stats.meta_analysis.effectsize_smd: Unknown parameters {mean2, sd2, nobs2}
```

```
statsmodels.stats.rates.etest_poisson_2indep: Double line break found; please use only one blank line to separate sections or paragraphs, and do not leave blank lines at the end of docstrings
statsmodels.stats.rates.etest_poisson_2indep: Parameter "alternative" type should use "str" instead of "string"
statsmodels.stats.rates.etest_poisson_2indep: Parameter "count1" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.etest_poisson_2indep: Parameter "count2" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.etest_poisson_2indep: Parameter "exposure1" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.etest_poisson_2indep: Parameter "exposure2" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.etest_poisson_2indep: Parameter "method" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.etest_poisson_2indep: Parameter "ratio" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.etest_poisson_2indep: Parameter "ratio: float" description should start with a capital letter
statsmodels.stats.rates.etest_poisson_2indep: Parameters {count1, ratio_null, exposure1, count2, exposure2, method} not documented
statsmodels.stats.rates.etest_poisson_2indep: Return value description should finish with "."
statsmodels.stats.rates.etest_poisson_2indep: Return value description should start with a capital letter
statsmodels.stats.rates.etest_poisson_2indep: Return value has no description
statsmodels.stats.rates.etest_poisson_2indep: Unknown parameters {exposure2: float, count1: int, ratio: float, count2: int, exposure1: float, method: {"score", "wald"}}
statsmodels.stats.rates.test_poisson_2indep: Double line break found; please use only one blank line to separate sections or paragraphs, and do not leave blank lines at the end of docstrings
statsmodels.stats.rates.test_poisson_2indep: Parameter "alternative" type should use "str" instead of "string"
statsmodels.stats.rates.test_poisson_2indep: Parameter "count1" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.test_poisson_2indep: Parameter "count2" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.test_poisson_2indep: Parameter "exposure1" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.test_poisson_2indep: Parameter "exposure2" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.test_poisson_2indep: Parameter "method" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.test_poisson_2indep: Parameter "ratio" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.test_poisson_2indep: Parameter "ratio: float" description should start with a capital letter
statsmodels.stats.rates.test_poisson_2indep: Parameters {etest_kwds, count1, ratio_null, exposure1, count2, exposure2, method} not documented
statsmodels.stats.rates.test_poisson_2indep: The first line of the Returns section should contain only the type, unless multiple values are being returned
statsmodels.stats.rates.test_poisson_2indep: Unknown parameters {exposure2: float, count1: int, ratio: float, count2: int, exposure1: float, method: string}
statsmodels.stats.rates.tost_poisson_2indep: Double line break found; please use only one blank line to separate sections or paragraphs, and do not leave blank lines at the end of docstrings
statsmodels.stats.rates.tost_poisson_2indep: Parameter "count1" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.tost_poisson_2indep: Parameter "count2" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.tost_poisson_2indep: Parameter "exposure1" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.tost_poisson_2indep: Parameter "exposure2" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.tost_poisson_2indep: Parameter "low, upp " requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.tost_poisson_2indep: Parameter "low, upp :" description should start with a capital letter
statsmodels.stats.rates.tost_poisson_2indep: Parameter "method" requires a space before the colon separating the parameter name and type
statsmodels.stats.rates.tost_poisson_2indep: Parameters {count1, low, upp, exposure1, count2, exposure2, method} not documented
statsmodels.stats.rates.tost_poisson_2indep: Return value description should finish with "."
statsmodels.stats.rates.tost_poisson_2indep: Return value description should finish with "."
statsmodels.stats.rates.tost_poisson_2indep: Return value description should finish with "."
statsmodels.stats.rates.tost_poisson_2indep: Return value description should start with a capital letter
statsmodels.stats.rates.tost_poisson_2indep: Return value description should start with a capital letter
statsmodels.stats.rates.tost_poisson_2indep: Return value description should start with a capital letter
statsmodels.stats.rates.tost_poisson_2indep: Unknown parameters {exposure2: float, count1: int, count2: int, exposure1: float, method: string, low, upp :}
```

Note the spelling of the section. Most of these have effectively no docstring.

image

**Comment by josef-pkt** [comment]
The functions are not half baked, the docstrings are.
Also, I haven't added a notebook yet for how to use it.

I'm not building docs locally, so I don't see the results, e.g. missing line breaks in several docstring for list of items.

**Comment by bashtage** [comment]
These docstrings

https://www.statsmodels.org/devel/generated/statsmodels.stats.oneway.anova_generic.html#statsmodels.stats.oneway.anova_generic

https://www.statsmodels.org/devel/generated/statsmodels.stats.oneway.power_equivalence_oneway.html#statsmodels.stats.oneway.power_equivalence_oneway

https://www.statsmodels.org/devel/generated/statsmodels.stats.oneway.power_equivalence_oneway0.html#statsmodels.stats.oneway.power_equivalence_oneway0

do not give that impression.  Why should anything *draft* be merged into master?

**Comment by bashtage** [comment]
You don't have to build locally to see docstring errors.  Just scroll to the bottom of configuration 2 of any build:

https://travis-ci.org/github/statsmodels/statsmodels/jobs/705970109

**Comment by josef-pkt** [comment]
leaving power_equivalence_oneway0 was most likely an oversight.

I merged anova when I had over 90% test coverage and was mostly happy with the code. I even did the silly pep-8 formatting

**Pull request merged**
