### PR TITLE
BUG: Add check to ensure array in arma order selection

### LINKED ISSUE #4727: arma_order_select_ic function throw "IndexError: index 0 is out of bounds for axis 0 with size 0"
Hi, I got a problem when I run the code `sm.tsa.arma_order_select_ic(ts,max_ar=6,max_ma=4,ic='aic')['aic_min_order']  # AIC` with my dataset. 

The problem showed below: 
```
~/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/stattools.py in arma_order_select_ic(y, max_ar, max_ma, ic, trend, model_kw, fit_kw)
   1149     for i, result in iteritems(res):
   1150         mins = np.where(result.min().min() == result)
-> 1151         min_res.update({i + '_min_order' : (mins[0][0], mins[1][0])})
   1152     res.update(min_res)
   1153 

IndexError: index 0 is out of bounds for axis 0 with size 0
```

However, I just cannot figure what is going on. And When I run the sample code, there is no problem. So what caused this problem? Is there something wrong with my dataset?

### PR DESCRIPTION
**Pull request by bashtage**
Add call to asarray to ensure data is a numpy array

closes #4727

### CODE REVIEW

**Comment by josef-pkt** [comment]
I don't see how this fixes #4727. There is no conversion of y or y_arr to numpy array.
Am I missing something in reading this?

**Comment by bashtage** [comment]
Somehow I forgot to add the asarray.  Although this doesn’t appear to be buggy, so it isn’t clear what caused the issue in the first place.

**Comment by josef-pkt** [comment]
this has now merge conflicts that need to be resolved
otherwise LGTM and ready for merge

(issue looks now more like REF than BUG)

**Comment by josef-pkt** [comment]
all green, merged

@bashtage thank you

**Pull request merged**
