### PR TITLE
CLN: Fix some invalid escapes

### PR DESCRIPTION
**Pull request by jbrockmendel**
Small subset of #5361

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@ChadFulton gentle a handful of invalid escapes.  Travis fail is unrelated timeout

**Comment by ChadFulton** [comment]
This LGTM.

**Comment by jbrockmendel** [comment]
Good to go?  Following merge I can rebase related PRs and see if any of them get into striking distance.

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel!

**Pull request merged**
