### PR TITLE
Share code between CountModel subclasses

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request **fixes 1 alert** when merging 575b27392f51594bf1157b75da9d24cc2841ad48 into 8adde71743a616fc5680d8cd6979538c789f6702 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-f3f46c8d13182d86b04b4038ce23fb3ca172a894)

**fixed alerts:**

* 1 for Unnecessary pass

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
There is too much distribution/model specific code in the "shared" code.
It also will not extend to other count models like zero-inflated and the new ones that are still in PR.

**Comment by jbrockmendel** [comment]
> There is too much distribution/model specific code in the "shared" code.

Like with the "FIXME: this is incorrect" thing, your reflexive disagreement is getting the better of you.  Look at the existing code for NegativeBinomial/NegativeBinomialP/GeneralizedPoisson.  Their finding-start_params code is effectively identical.  The only special casing here is for Poisson.

> It also will not extend to other count models

Right, which is why its in a separate mixin instead of directly in CountModel.  Also see #4517.

> and the new ones that are still in PR.

If you're looking for new ways to effectively discourage contributions this is a good one, but you've already got a bunch of those...

**Comment by josef-pkt** [comment]
My discouraging contributions is selective.
e.g. this refactoring will make it more difficult to add improvements to individual models, e.g. #3925 #3918
e.g. in #3928 I needed to work through individual models until I could separate out some common helper methods.

I mentioned before that I prefer partial code duplication when it makes it much easier to understand and improve the code (at least until the part of the code is settled, i.e. no major problems are expected anymore.)

**Comment by jbrockmendel** [comment]
>  when it makes it much easier to understand

a) it is non-trivial to figure out that the three identical chunks of code are in fact functionally identical (seriously, even if you refuse to share them, at least refactor them into a well-scoped helper method)
b) It is not obvious in its current form that the defining of `alpha_p` is only necessary for finding `start_params`.
c) 3x as much to read ~= 3x as hard to understand.

> at least until the part of the code is settled

Counter-example: get_robustcov_results.  It will stay this way indefinitely unless made a priority.

> and improve the code

I take that back; it will inexorably _get worse_ unless made a priority.  Small differences will inevitably accumulate (again get_robustcov_results and dozens more\*) and it will be a PITA to figure out that someone edited one without realizing they should have edited all of them.  People will incorrectly assume "well it must be this way for a good reason, right?"  Whoever made the edit will be long gone or will have forgotten (e.g. glm_weight_results).

\* Yesterday I found a place in arima_model where geterrors_css and loglike_css had near-duplicate code, but one had a `.astype(params.dtype)` that the other was missing.  Turned out to make a difference.

You don't want to prioritize this stuff; I do.  This is a Labor Specialization win.

**Comment by josef-pkt** [comment]
> You don't want to prioritize this stuff; I do. This is a Labor Specialization win.

This doesn't help me if I still have to fight with optimization and convergence problems. It is difficult to understand and change code that is spread out over several classes, or many functions.
Any cleanup in this part has to wait for the next "round", when I have time to think about it and have a better idea what the pattern for transform_params and other issues should be.

(e.g. discrete margins was written by Skipper when he thought using many helper functions is a good idea. I still haven't managed to get an overview and just need to trace individual pieces, functional code paths, when there are problems. Currently, I don't even know which helper functions provide a useful structure and which are too much outsourcing. The margins code is fine as it is, but I have a hard time figuring out how to write extensions to it.)

**Comment by jbrockmendel** [comment]
> e.g. discrete margins was written by Skipper when he thought using many helper functions is a good idea. I still haven't managed to get an overview and just need to trace individual pieces

Sounds like the kind of thing that would be made easier if some kind handsome soul would come along to separate the parts that [need](https://github.com/statsmodels/statsmodels/issues/4451) [your](https://github.com/statsmodels/statsmodels/issues/4454) [attention](https://github.com/statsmodels/statsmodels/issues/4474) from [those](https://github.com/statsmodels/statsmodels/pull/4477) [that](https://github.com/statsmodels/statsmodels/pull/4467) [don't](https://github.com/statsmodels/statsmodels/pull/4443).

Or say, noting that `discrete_margins.Margins` is a throwaway class that can+should be deleted makes the problem marginally more manageable.

> It is difficult to understand and change code that is spread out over several classes

It is easy to copy/paste code in a parent class and edit it in a specific class _in a local scratch-paper branch_.  It is difficult to go the other direction.

**Comment by jbrockmendel** [comment]
> [...] which does not include maintenance issues

Right, which is why I'm offering to take some of this off your plate.  Thine preference hath revealed itself.

> As I said, discrete Margins is fine and useful and working for the usecase it was written for, and is now also used in GLM and GEE.

Well, no.  If you look at the definition of `DiscreteMargins` you'll see:

```
#class DiscreteMargins(Margins):
class DiscreteMargins(object):
```

`Margins` may have at one point been used for something, but it is not now.  Right now its very existence is causing confusion.

**Comment by josef-pkt** [comment]
I never looked at that `Margins` class, or not more than a few seconds and forgot about it again.
"Mostly a do nothing class."  doesn't sound confusing to me.
I thought you were talking about DiscreteMargins.

Interesting, cov_margins is missing in DiscreteMargins so we cannot test linear restrictions across several margins (#3721)

**Comment by josef-pkt** [comment]
> And reflexively disagreed instead of considering what I'm saying.

I thought you meant to say: "And reflexively found a potential use for it."
:)

**Comment by jbrockmendel** [comment]
You've already forgotten Margins exists once.  You'll forget again long before Margins becomes useful, just like with a hundred other pieces of leftover-detritus code scattered about.

Just like inevitably it will be forgotten that the finding-start_params code is identical between the classes touched by this PR.  Small fixes will be made to one and no one will know to apply them to the others, and they will turn into get_robustcov_results.

The pile of Things That Can't Be Resolved Without Josefpkt will grow, and on the day that you're unavailable, the community will be screwed.

And it will all be my fault, for having been annoying enough to get you to reflexively refuse the very concept of "making code less bad"

**Comment by josef-pkt** [comment]
`margins` is not my code. I'm a "new" developer to this like anybody else, although I fixed bugs and added enhancements in there. 
see #2154 for what I thought as a ex-post code reviewer

rewrites and enhancements by new developers are still possible, e.g. Chad refactored the datetime handling in tsa without access to Skipper as the original author.

The main advantage I have is for relatively quick bug-fixes because I'm approximately familiar with most of the code (excluding mixed and statespace models) and with the statistics and econometrics background, and that in most cases I have a reasonably good idea, or can quickly figure out, whether a new application requires a lot of work and changes.

Robust cov_types and margins are great pieces of functionality that we provide, and that's independent of whether the code is pretty. But I don't want to change working code without a clear idea where the code should go, i.e. what I would think would be a good long term target for rewrites and refactorings.

(The next round of cov_type work will get rid of the duplicate code in linear_model, but I will need to figure out how to generically support cov_types that are only available in some models. e.g. Quasi-MLE in GLM with excess dispersion but without HC, non-existing HC and similar in RLM. Anyone who wants to figure out to add more GLM and RLM cov_types, doesn't have to worry much about the duplicate code in linear models.)

> refuse the very concept of "making code less bad"

What code is good or bad is not clear, or I have in many cases a different view than you do.
To come back to this PR: 
DRYing code is not really better code if it makes it more difficult to understand and change it. It might in some cases be prettier, but it adds additional conceptual work for maintenance and for additional development.

**Comment by jbrockmendel** [comment]
> The main advantage I have is for relatively quick bug-fixes because I'm approximately familiar with most of the code

And that's fantastic, really.  But as you mention every so often, your time is the constraining factor.  If the code was made readable, no-working garbage was removed, and commented-out junk removed-or-documented, then the statsmodels Bus Factor wouldn't be so daunting.

> and that's independent of whether the code is pretty.

Pretty would be nice, I'm asking for readable.  Code that screams "carelessness!" is not something to be proud of.

> Anyone who wants to figure out to add more GLM and RLM cov_types, doesn't have to worry much about the duplicate code in linear models

I specifically want _fewer_ half-finished features.

> DRYing code is not really better code if it makes it more difficult to understand and change it. It might in some cases be prettier, but it adds additional conceptual work for maintenance and for additional development.

As the most recent person to figure out what this particular code does, I claim that making an informatively-named well-scoped helper method that happens to be DRY makes it much easier to understand and even change.

**Pull request closed without merging**
