### PR TITLE
ENH: Zivot Andrews test

### LINKED ISSUE #4746: ENH: Zivot-Andrews structural-break unit-root test
We have a nice c++ implementation which I quickly ported to python for experimentation. Repo is JimVaranelli/ZAUnitRoot. Not all params/features are implemented yet but it should give a good idea of execution. I tried to optimize the design matrix assembly process but please suggest improvements. The c++ implementation follows the ZA paper as written (T-trim autolag regressions). It's an expensive test, so for the python I used Baum's (2004/2015) approximation which runs a single autolag regression on the base model and uses that lag value for all of the T-trim break-period regressions. The Baum method tends to be more pessimistic than the original but I haven't quantified the size/power tradeoff. I haven't added it to the repo code yet, but I also have MC-derived CVs (nobs=2000, repl=1MM) for each of the three models in order to generate pvals. Take a look and let me know if there is any interest in adding it to SM in which case I will finalize the implementation in the repo and submit a PR. I also included 4 test cases, three of which were used in the original ZA paper.

### PR DESCRIPTION
**Pull request by bashtage**
- [X] closes #5455 
- [X] tests added / passed. 
- [X] code/documentation is well formatted.  
- [X] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by bashtage** [comment]
@JimVaranelli thanks for this.

**Comment by JimVaranelli** [comment]
@bashtage @josef-pkt @ChadFulton Glad to help! Let me know if you need some help on other projects and I will assist where possible. On another note, I've added Leybourne-McCabe stationarity test to my github repo (https://github.com/JimVaranelli) and plan to add Phillips-Perron and DFGLS unit-root tests in the near future to support a manuscript currently under development for peer-review. Let me know if any of these is of general interest to the SM community and I will PR it. The most important one is probably PP since it is by far the most well-behaved test in very small samples. The LM is interesting since it has very low tool implementation coverage (only Matlab as far as I can tell). The DFGLS is the least interesting but is a low-effort add-on to ADF if that is a concern.

**Comment by bashtage** [comment]
Leybourne-McCabe isn't available in Python, AFAICT, so that would expand the capabilities.  My `arch` package has the other two, although these are welcome here as well. Ideally, any of these would follow the same pattern as the ZivotAndrews test to KISS for users.

**Comment by bashtage** [comment]
Will try and get your White's Spec test in too.

**Pull request merged**
