### PR TITLE
MAINT: Use more recent miniconda for travis, numpy 1.14 has broken genfromtext

### PR DESCRIPTION
**Pull request by thequackdaddy**
Hello,

I'm noting that travis fails on the docbuild. 

I think running `conda update conda` fixes it. It looks like there are some new dependencies that `conda` that is shipped with miniconda can't seem to handle.

### CODE REVIEW

**Comment by josef-pkt** [comment]
It fixed the problem with the doc build
But we got two extra failures. travis is now using numpy 1.14.0

@thequackdaddy  Thanks, I will merge this tonight after I have time to look at this.

**Comment by thequackdaddy** [comment]
@josef-pkt Don't merge. I'm trying to figure out what the problem is, but it looks like more `rec.array` fun.

**Comment by thequackdaddy** [comment]
Well I think this is actually something that is above my paygrade. There is another unrelated problem I don't understand. Obviously, it has something to do with #2127 and #3980. Time series/arima is something I know nothing about... so I'd appreciate any clues/help. 

Alternatively, I can squash this and you can merge as-is, and someone else can take a shot?

**Comment by josef-pkt** [comment]
I will merge this as is, 2 commits for the two parts are good.

about lutkepohl data: one of the files has a german character but the file is not utf, but it's in ignored test (I don't remember where I looked at it)
The pandas fix is fine here.

about the ARIMA test failure: I will look again later, but it's strange because this is with old versions of scipy and numpy where the test passed before.  I have no idea what might be wrong this time with it.

**Comment by thequackdaddy** [comment]
Accidentally deleted branch when I was trying to test something. I realized the distributed estimation example notebook was broken. The generated endog data was normally distributed, but we were trying to fit a binomial model on it... that won't work when you generate negative numbers.

**Comment by thequackdaddy** [comment]
Ok I think I may have fixed this in a dumb way. I guess we had disabled `conda update conda` for reasons I don't know. When I re-enable it, it seems to work now. 

Weird thing is, I an't actually see any additional packages get installed. But this definitely feels like it fixes it. Perhaps `conda update conda` has some hidden under-the-hood configuration changes?

**Comment by josef-pkt** [comment]
merged
Thanks @thequackdaddy

**Comment by thequackdaddy** [comment]
Well the same error occurred. I’m totally baffled by this. Hope someone else can fix...

**Pull request merged**
