### PR TITLE
surv object being overwritten bug

### PR DESCRIPTION
**Pull request by joestox**
the PHSurvivalTime.surv object was getting overwritten when the number of strata is greater than 1. This commit fixes the bug. I did not include a test. I'm not that comfortable writing them yet.

### CODE REVIEW

**Comment by josef-pkt** [comment]
@joestox Thanks

fix looks correct to me.
@kshedden 

(We have currently a problem with one machine on TravisCI which are unrelated to this.)

**Comment by kshedden** [comment]
It looks reasonable.  Apparently I had a test for this that is commented
out in master, I can't remember why, or maybe it was inadvertent.  Can you
try uncommenting line 83 in test_phreg.py and see if the tests pass after
making your change?

**Comment by joestox** [comment]
The test case runs successfully after uncommenting. Had to change baseline_hazard on line 83 to baseline_cumulative_hazard

**Comment by kshedden** [comment]
This looks good to me.  Thanks @joestox !

**Comment by josef-pkt** [comment]
good, then I recommend copying the line also to the last case in these sequence which uses strata, i.e. after line 104. And add a code comment `# smoke test` before the line to indicate that we are not comparing numbers yet.
(could also be done with amend last commit and force push.)

**Comment by joestox** [comment]
ok, done. checked it out and it runs fine.

**Comment by josef-pkt** [comment]
@joestox Thank you, I'll merge when TravisCI reports no related failures.

**Comment by josef-pkt** [comment]
merged, (sorry for the delay, I got distracted)

**Comment by joestox** [comment]
Awesome! Thanks

**Pull request merged**
