### PR TITLE
CI: Update used actions, cache pip deps, Python 3.10

### PR DESCRIPTION
**Pull request by EwoutH**
A bit of CI maintenance:
- Update to actions/checkout@v3, actions/setup-python@v3, r-lib/actions/setup-pandoc@v2 and ts-graphviz/setup-graphviz@v2
- Cache packages installed by pip
- Remove the `python -m` part, `pip` is directly callable

Checklist
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message).

### CODE REVIEW

**Comment by EwoutH** [comment]
I rebased this PR, @bashtage would you be able to enable the workflow and take a look at it?

**Comment by bashtage** [comment]
On this one, can we leave the `python -m pip`, which is currently considered the best practice way to use `pip`.  We try and use `python -m {pip, build}` consistently rather than directly calling `pip` or using other ways to build/install.

**Comment by EwoutH** [comment]
Done

**Comment by bashtage** [comment]
Thanks!

**Pull request merged**
