### PR TITLE
MAINT: switch back to old TraviCI infrastructure - don't merge

### PR DESCRIPTION
**Pull request by josef-pkt**
This is just to check the timing of old versus new, container based TravisCI infrastructure

### CODE REVIEW

**Comment by bashtage** [comment]
It can be really hard to get consistent timings since these are EC2 instances and the other loads matter for performance.

**Comment by josef-pkt** [comment]
We wait a bit to get more numbers. But right now it looks to me that the time for python 3.4. has doubled. https://travis-ci.org/statsmodels/statsmodels/builds/90246598  
from 17 to 38 minutes which cannot be mostly new tests.

I didn't quite understand the parallel/ multicore feature in the new setup. If it uses multiple cores it could actually slow things down.

**Comment by jseabold** [comment]
I haven't tried the travis containers infrastructure yet. We moved to CircleCI since Travis was taking a while to allow private docker containers (if they do now). One of the nice things about having containers is that you can now replicate the test environment, so things like this weird hang we're getting now can be debugged locally.

Does anyone have any idea about this? I'd like to get master back to passing and put in some maintenance work over the coming weeks.

**Comment by josef-pkt** [comment]
The most recent is #2738 where @ChadFulton  proposes to add KnownFailure to them.
Chad's PR and issue are the first indication about what might be causing it.

**Comment by jseabold** [comment]
What image does Travis use by default? Do we know? I don't see anything in a cursory search of their documentation. If not, we should probably explicitly use an image, so we can replicate things locally.

**Comment by josef-pkt** [comment]
I never tried to figure out the details, so I don't know how this works.

**Comment by jseabold** [comment]
According to my most recent attempt, our stuff is running on "Legacy Precise"

https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

**Comment by jseabold** [comment]
Ah, it's in the build info. in the logs. Some nice stuff, but I still prefer using a container we can easily deploy locally.

```
Build system information
Build language: python
Build group: stable
Build dist: precise
Build image provisioning date and time
Sun Dec 13 03:14:21 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-63-generic
Cookbooks Version
fad6c97 https://github.com/travis-ci/travis-cookbooks/tree/fad6c97
Git version
git version 1.8.5.6
bash version
GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.2
mysql --version
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.2
Pre-installed PostgreSQL versions
9.1.19
9.2.14
9.3.10
9.4.5
Redis version
redis-server 3.0.5
riak version
2.1.3
MongoDB version
MongoDB 2.4.14
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 38.4.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-63-generic", arch: "amd64", family: "unix"
```

**Comment by josef-pkt** [comment]
#2739  merged Skipper's change to running containers.

This PR is obsolete now, closing

**Pull request closed without merging**
