### PR TITLE
WIP/Demonstration for MNLogit

### PR DESCRIPTION
**Pull request by jbrockmendel**
Two things here.

1) Implement a catch-all for special cases in wrapping.

2) Implement some tests that currently fail.  Among other things, I'm now thinking that `MNLogitResutlsWrapper.params` is not wrapped correctly.

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request introduces 1 alert and fixes 1 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-92a3cfa0ace47a6788673b84ff6ac4710942191d)

**new alerts:**

* 1 for Potentially uninitialized local variable

**fixed alerts:**

* 1 for First argument to super() is not enclosing class

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
Another option for wrapping, especially for special cases, would be to have data.wrap pass through already-pandas objects.  For things that never need the non-wrapped version this could be easier (and certainly simpler) than creating special wrap functions that are rarely used.

**Comment by josef-pkt** [comment]
This pull request introduces 1 alert and fixes 1 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-0361924f68eaaf60c83c866349b4057113c3cde4)

**new alerts:**

* 1 for Potentially uninitialized local variable

**fixed alerts:**

* 1 for First argument to super() is not enclosing class

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request introduces 1 alert and fixes 1 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-fb52a11d55e620e868edb66c356bdc655a6a557a)

**new alerts:**

* 1 for Potentially uninitialized local variable

**fixed alerts:**

* 1 for First argument to super() is not enclosing class

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Pull request closed without merging**
