### PR TITLE
PERF: Import speed

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #3082 (does not close)

### CODE REVIEW

**Comment by bashtage** [comment]
cmd on Windows needs " around the command, as in `python -c "import statsmodels"`

**Comment by jbrockmendel** [comment]
Ended up just skipping on windows, since no variant of the command worked.

I think this will also make the test in #5235 pass.

**Comment by jbrockmendel** [comment]
de-facto green

**Comment by bashtage** [comment]
Will wait until after release.

**Comment by bashtage** [comment]
I'll use this tag to remember PRs that are approved but deferred.

**Comment by bashtage** [comment]
Any idea how much difference this makes?

**Comment by jbrockmendel** [comment]
Running `python3 -X importtime -c "import statsmodels.api as sm"` on master takes 954861 microseconds, on this branch 853969.  So a little more than 10%.

**Comment by bashtage** [comment]
Probably worth getting in before the next release then. 

Have you looked into how pandas is getting into the main namespace?  I think it happens though compat (which grabs a bunch of stuff)

**Comment by jbrockmendel** [comment]
> Have you looked into how pandas is getting into the main namespace?

For `import statsmodels.api.as sm` my assumption is that it is imported in too many places to make lazifying it reasonable.  For `import statsmodels`, I think it came in through `tools._testing`, where IIRC it is just for assert_foo_equal and could totally be removed.

**Comment by jbrockmendel** [comment]
Trying this out, lazifying pandas imports in a few places gets the import time for "import statsmodels" from 447082 microseconds down to 196531.  Down to 154490 if we get `tools.tools` imports out of `tools.__init__`, but that seems unlikely.

**Comment by bashtage** [comment]
That seems like a worthy refactor.  One could consider moving tools._testing (or PyTestRunner in particular) to somewhere that prevents many imports. The privacy of this module allows for immediate refactoring w/o any issues.

**Comment by jbrockmendel** [comment]
> One could consider moving tools._testing

I looked at something like this and it doesn't help because we also import from `statsmodels.tools.sm_exceptions` into `statsmodels.__init__`

**Comment by bashtage** [comment]
Yes, that filtering is unfortunate.  Is it even needed?  Aren't warnings always shown when given, except things like deprecation?

**Comment by bashtage** [comment]
No apparently.  I wonder if we could move that to base.__init__.  It seems like base.__init__ would always be imported before any model could be estimated that would produce those errors.

**Comment by bashtage** [comment]
Actually, just move it to 

statsmodels.tools.sm_exceptions after the exceptions.

This file is always imported before any of these exceptions are given (obviously).  Also a natural place to have it.

**Comment by jbrockmendel** [comment]
OK, will update.

In pandas there's a discussion about implementing asv for import times.  When that gets figured out I'll port whatever is implemented here.  (Will start putting together an asv suite here before that hopefully)

**Comment by jbrockmendel** [comment]
Just pushed, for "import statsmodels" im seeing 84628 microseocnds vs 395499 on master.

**Comment by bashtage** [comment]
I'm going to merge this for the next release since it has been a pain point.

**Comment by bashtage** [comment]
Once all green.

**Comment by bashtage** [comment]
You need to pass args and kwargs through to tst

**Comment by jbrockmendel** [comment]
> You need to pass args and kwargs through to tst

Updated.

Any ballpark on how long the RC period will be?

**Comment by bashtage** [comment]
One more week. PytestTester is having problems detecting the path.  Should modify it to take an argument `package_path=None` (which triggers teh current check), so that __file__ can be passed in from `statsmodels/__init__.py`

**Comment by bashtage** [comment]
Thanks. Improving import perf is very useful.

**Pull request merged**
