### PR TITLE
BUG: Fix exposure/offset handling in GEEResults

### LINKED ISSUE #5253: BUG: GEEResults fittedvalues ignores offset and exposure
GEEResults.fittedvalues uses explicit computation instead of going through predict

```
    @cache_readonly
    def fittedvalues(self):
        """
        Returns the fitted values from the model.
        """
        return self.model.family.link.inverse(np.dot(self.model.exog,
                                                     self.params))
```

all the resids are defined in terms of fittedvalues and will have the same behavior as consequence

this is incorrect in case of offset and inconsistent definition for exposure
GLM uses the correctly defined mu=predict() including user provided offset and exposure.

found when I tried to get an overview about how fittedvalues are defined
https://github.com/statsmodels/statsmodels/issues/37#issuecomment-424019626

### PR DESCRIPTION
**Pull request by kshedden**
- [x] closes #5253
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

WIP to address this bug.  Subclass GEE and GEEResults from GLM and GLMResults.

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by rebecca-palmer** [comment]
How does this fix #5253?? The bad definition of fittedvalues was in GEEResults itself, not inherited, and I don't see a change to it here.

(A test for #5253 would also be a good idea, though I admit my patch didn't have one either.)

**Comment by kshedden** [comment]
It's still WIP.  We needed to fix predict as well, it suffered from similar issues.  Most post-estimation for GEE should be able to inherit from GLM, which we weren't doing before.  Marginal effects should also be inherited.  This will all help to reduce the size of the GEE file, which is good.

**Comment by rebecca-palmer** [comment]
> We needed to fix predict as well, it suffered from similar issues

What issues?  GEE predict() already does include exposure (see below, from 0.10, and feel free to base a test on this), the bug I know about is that fittedvalues doesn't use it.

As Debian maintainer, I am considering applying my one-line fix (in #5253) to our 0.10 package, but that won't work if predict() is broken as well.

> This will all help to reduce the size of the GEE file, which is good.

I agree that sharing code where possible is a good idea, but it won't fix this bug if fittedvalues isn't one of the inherited items.

```
>>> import pandas as pd
i>>> import statsmodels.api as sm 
>>> import numpy as np;x=pd.DataFrame([np.arange(10),30-np.arange(10)]).T
>>> y=x[0]*x[1]
>>> y
0      0
1     29
2     56
3     81
4    104
5    125
6    144
7    161
8    176
9    189
dtype: int64
>>> x
   0   1
0  0  30
1  1  29
2  2  28
3  3  27
4  4  26
5  5  25
6  6  24
7  7  23
8  8  22
9  9  21
>>> f0=sm.GLM(exog=x,endog=y,family=sm.families.Poisson(),exposure=x[1])
>>> f1=f0.fit()
>>> f1.summary()
<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                   10
Model:                            GLM   Df Residuals:                        8
Model Family:                 Poisson   Df Model:                            1
Link Function:                    log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -79.481
Date:                Wed, 29 Jan 2020   Deviance:                       100.68
Time:                        07:25:54   Pearson chi2:                     67.4
No. Iterations:                     4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
0              0.2563      0.010     26.915      0.000       0.238       0.275
1              0.0041      0.003      1.541      0.123      -0.001       0.009
==============================================================================
"""
>>> f1.predict()
0     33.886645
1     42.153788
2     52.375469
3     64.992755
4     80.538924
5     99.656073
6    123.113674
7    151.828806
8    186.887524
9    229.566341
Name: 1, dtype: float64
>>> f1.predict(x)
0     1.129555
1     1.453579
2     1.870552
3     2.407139
4     3.097651
5     3.986243
6     5.129736
7     6.601252
8     8.494887
9    10.931731
dtype: float64
>>> f1.predict(x,exposure=x[1])
0     33.886645
1     42.153788
2     52.375469
3     64.992755
4     80.538924
5     99.656073
6    123.113674
7    151.828806
8    186.887524
9    229.566341
Name: 1, dtype: float64
>>> f0=sm.GEE(exog=x,endog=y,cov_struct=sm.cov_struct.Exchangeable(),family=sm.families.Poisson(),exposure=x[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'groups'
>>> groups=np.arange(10)%2
>>> groups
array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
>>> f0=sm.GEE(exog=x,endog=y,cov_struct=sm.cov_struct.Exchangeable(),family=sm.families.Poisson(),exposure=x[1],groups=groups)
>>> f1=f0.fit()
>>> f1.predict()
0     31.632287
1     39.779771
2     49.966306
3     62.681289
4     78.524004
5     98.225452
6    122.673344
7    152.940229
8    190.314343
9    236.332294
Name: 1, dtype: float64
>>> f1.predict(x)
0     1.054410
1     1.371716
2     1.784511
3     2.321529
4     3.020154
5     3.929018
6     5.111389
7     6.649575
8     8.650652
9    11.253919
dtype: float64
>>> f1.predict(x,exposure=x[1])
0     31.632287
1     39.779771
2     49.966306
3     62.681289
4     78.524004
5     98.225452
6    122.673344
7    152.940229
8    190.314343
9    236.332294
Name: 1, dtype: float64
>>> f1.fittedvalues()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Series' object is not callable
>>> f1.fittedvalues  
0     1.054410
1     1.371716
2     1.784511
3     2.321529
4     3.020154
5     3.929018
6     5.111389
7     6.649575
8     8.650652
9    11.253919
dtype: float64
>>> f1.summary()
<class 'statsmodels.iolib.summary.Summary'>
"""
                               GEE Regression Results                              
===================================================================================
Dep. Variable:                           y   No. Observations:                   10
Model:                                 GEE   No. clusters:                        2
Method:                        Generalized   Min. cluster size:                   5
                      Estimating Equations   Max. cluster size:                   5
Family:                            Poisson   Mean cluster size:                 5.0
Dependence structure:         Exchangeable   Num. iterations:                    13
Date:                     Wed, 29 Jan 2020   Scale:                           1.000
Covariance type:                    robust   Time:                         07:29:54
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
0              0.2648      0.017     15.917      0.000       0.232       0.297
1              0.0018      0.004      0.421      0.674      -0.006       0.010
==============================================================================
Skew:                         -0.3679   Kurtosis:                      -1.1279
Centered skew:                -0.3266   Centered kurtosis:             -1.2179
==============================================================================
"""
>>> 
```

**Comment by kshedden** [comment]
@rebecca-palmer @josef-pkt if you agree that everything is fixed now, I will merge

**Comment by rebecca-palmer** [comment]
The last commit does look like a fix (though I haven't tested it).

(As noted in #5253, there's also a misleading docstring on **GLM**Results.fittedvalues, should we fix that as well?)

**Comment by rebecca-palmer** [comment]
The above fixes the misleading docstring.

The red CI is test_nondiagonal_obs_cov slightly out of tolerance - given that no actual code changed, I suspect random rounding error.

**Comment by bashtage** [comment]
That is a known random fail.

**Comment by kshedden** [comment]
I will merge later today if no objections.

**Pull request merged**
