### PR TITLE
ENH: more work on copula (deriv, classes)

### PR DESCRIPTION
**Pull request by josef-pkt**
resurrecting copulas see #4046

the first commit is from 2011 and was never included in the statsmodels.sandbox version

### CODE REVIEW

**Comment by josef-pkt** [comment]
example that was in the `__main__` of my version of `copula.py`

```
# -*- coding: utf-8 -*-
"""

Author: Josef Perktold
"""



import numpy as np
from statsmodels.sandbox.distributions.copula import (copulanamesbv,
                                                      CopulaArchimedean,
                                                      TransfClayton,
                                                      TransfFrank,
                                                      TransfGumbel,
                                                      )

copula_examples = [
                   ('indep', ()),
                   ('min', ()),
                   ('max', ()),
                   ('clayton', (0.5,)),
                   ('clayton', (1.1,)),
                   ('clayton', (2.,)),
                   ('frank', (0.5,)),
                   ('frank', (2.,)),
                   ('frank', (10.,)),
                   ('gumbel', (2.,))
                   ]

doplot = 1
if doplot:
    eps = 0.1 #1e-4
    import matplotlib.pyplot as plt
    u = np.linspace(0+eps,1-eps,51)[:,None]
    for c, a in copula_examples[-2:]:
        cdfvalues = copulanamesbv[c](u, u.T, *a)
        plt.figure()
        plt.contour(cdfvalues)
        plt.title(c + repr(a))

    uvec = np.column_stack(map(np.ravel, np.broadcast_arrays(u, u.T)))
    clayton = CopulaArchimedean(TransfClayton())
    cdfv = clayton.cdf(uvec, args=(0.9,), axis=1)
    plt.figure()
    #plt.contour(uvec[:,0], uvec[:,1], cdfv)
    plt.contour(cdfv.reshape(51, 51))
    plt.title('clayton 0.5 class cdf')
    pdfv = clayton.pdf(uvec, args=(0.99,), axis=1)
    plt.figure()
    #plt.contour(uvec[:,0], uvec[:,1], cdfv)
    plt.contour(pdfv.reshape(51, 51))
    plt.title('clayton 0.99 class pdf')

    frank = CopulaArchimedean(TransfFrank())
    pdfv = frank.pdf(uvec, args=(0.5,), axis=1)
    plt.figure()
    #plt.contour(uvec[:,0], uvec[:,1], cdfv)
    plt.contour(pdfv.reshape(51, 51))
    plt.title('frank 0.99 class pdf')

    gumbel = CopulaArchimedean(TransfGumbel())
    pdfv = gumbel.pdf(uvec, args=(2.,), axis=1)
    cdfv = gumbel.cdf(uvec, args=(2,), axis=1)
    print(pdfv.shape, cdfv.shape)
    plt.figure()
    #plt.contour(uvec[:,0], uvec[:,1], cdfv)
    plt.contour(cdfv.reshape(51, 51))
    plt.title('gumbel 2 class cdf')

    plt.show()
```

**Comment by josef-pkt** [comment]
Right now I only added the commit, I don't really know what the status is. 
Looks like working towards multivariate version with dimension larger than bivariate and a class for it.

**Comment by josef-pkt** [comment]
2 travis fail because of an unrelated XPASS

the derivative or the archimedean transforms are used to compute the pdf in 

extreme value copulas don't have a full class with pdf yet.
It looks like the cdf can be computed for the EV

```
>>> import statsmodels.sandbox.distributions.copula as cop
>>> cd = cop.copula_bv_ev(u, u.T, cop.transform_tawn, args=(0.5,0.5,0.5))
>>> cd.shape
(51, 51)
>>> plt.contour(cd)
```
same pattern as using the archimedean in example script: `cdfvalues = copulanamesbv[c](u, u.T, *a)`

trying out a few cases for tawn:
with these args the shape of the cdf looks strange
`cd = cop.copula_bv_ev(u, u.T, cop.transform_tawn, args=(0.9,0.9,0.001))`
maybe not enough points for good contour interpolation

this one looks closer to `min` (Leontief in economics)
`cd = cop.copula_bv_ev(u, u.T, cop.transform_tawn, args=(0.9,0.9,0.01))`

The EV copula transforms are functions without derivatives, while the Archimedean transforms are classes with methods to compute inverse transform and derivatives.
Code for either explicit or generic pdf for EV copulas is missing. Maybe something similar to `CopulaArchimedean.pdf` can be used for EV copulas.

**Comment by josef-pkt** [comment]
multivariate > 2
I don't see an example for the case with more than 2 marginals, e.g. for copula_mv_archimedean, copula_power_mv_archimedean
CopulaArchimedean looks like it's designed for arbitrary multivariate dimension (uses sum and product)
example/test case ?

**Comment by josef-pkt** [comment]
3 times the same functionality:
cdf for Archimedean copulas can currently be computed in 3 ways:
- explicit formulas: copula_bv_indep, ... used in `copulanamesbv`
- copula_bv_archimedean or copula_mv_archimedean with using transform
- CopulaArchimedean class with using transform

It looks like those define only the copula, using given (uniform) marginal values

CopulaDistributionBivariate, CopulaDistribution combine the Copula class with the marginal distributions to get the distribution for the observed variables.
Marginal distribution is provided currently by cdf functions, and we don't have other method besides cdf yet.

**Comment by josef-pkt** [comment]
generic idea (I don't know about the details, and didn't read up on fit methods)
The classes for copula and distribution are designed in a similar way to scipy distributions, i.e. `args` are provided like `params` to each method and are not attributes of the instance (i.e. are not frozen distributions).
This means that one fit method could be to use Generic MLE, i.e. we could wrap the distribution in a estimation class, possibly using link functions to impose the limits on the parameters (e.g. (0,1) or [0, inf), or (-inf, 0))

**Comment by josef-pkt** [comment]
some quick browsing/search:

the copula density is `C12 (F1(·),F2(·))f1(·)f2(·)`
page 54 equ 4.1 in
Pravin K. Trivedi and David M. Zimmer (2007), "Copula Modeling: An Introduction for Practitioners", Foundations and Trends® in Econometrics: Vol. 1: No. 1, pp 1-111. http://dx.doi.org/10.1561/0800000005

C12 is the second cross derivative of the copula 
`C12((F1|x1;β1), (F2|x2;β2);θ) = ∂C((F1|x1;β1), (F2|x2;β2);θ)/∂F1∂F2`

f1, f2 are pdf of marginal distributions, so the CopulaDistribution classes need a marginal distribution instances that have both cdf and pdf methods.

(edf is not a continuous distribution, so that will not work for getting a copula distribution density)

**Comment by josef-pkt** [comment]
a notebook based on the old script with addition of plots of extreme value copulas:
https://gist.github.com/josef-pkt/ac83ac2a414424cc384b3a94570a9f8a

(time to stop and go back to the scheduled program)

**Comment by josef-pkt** [comment]
This is essentially backwards compatible with the current master version.
It's still in the sandbox, so I don't see a problem with merging this.

**Comment by josef-pkt** [comment]
a reference in one of my old folders, survey for quickly checking some parts, with finance application
http://www.thierry-roncalli.com/download/copula-survey.pdf working paper from 2000
e.g. has section on MLE, including two-step (first marginal, then copula parameters) and using EDF marginals.

**Comment by josef-pkt** [comment]
If someone volunteers to work on code, then I help.
I care a lot more about getting new functionality in than about being pretty.

**Comment by jbrockmendel** [comment]
This obviously doesn’t belong outside of the sandbox.  Stats.diagnostic and multicomp code that is used outside sandbox belongs outside.

We all know you don’t care about “prettiness” (AKA “bug prevention”) but you could avoid actively hampering the process and just empower Kevin to handle stuff you don’t care about.

**Comment by josef-pkt** [comment]
prettiness is only marginally related to bug prevention, unit tests are the main tool for that.

(I would have given Kevin commit rights a long time ago because he is one of the main maintainers of statsmodels, but I worry that in combination with you after one month I will not recognize nor find my way around the code base anymore.)

**Comment by jbrockmendel** [comment]
> unit tests are the main tool for that.

And I look forward to the day when the test suite is reliable (#4966).  Even then, the best tool is the Mark I Eyeball, and for that readability counts.

> I would have given Kevin commit rights a long time ago

I'll consider it a win that this suggestion finally got a response.

> but I worry that in combination with you after one month I will not recognize 

Consider agreeing to reasonable limits on what a new committer is allowed to handle solo.  e.g. CI, or Build, or docstrings, or tests, or "non-namespace-changing readability improvements that I don't want to bother with", or only modules with names containing the letter "r", or ...

> nor find my way around the code base anymore

If done correctly, the code layout would be self-explanatory (#4992).  Regardless, the vast majority of recent PRs wouldn't change layout, and those that do are for the very good reason of isolating sandbox from non-sandbox (#4887).

**Pull request merged**
