### PR TITLE
REF: Remove compatibility mode for state space

### PR DESCRIPTION
**Pull request by ChadFulton**
Not much more to say.

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request **fixes 1 alert** when merging e2b4f26ab3ff93f8a4eca4db41052aa34ece407f into c6a76ede3588ec75ee68411b3a11e685e7c5d230 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-1eb3620b10bb351ed73b8a19752800976be10a1c)

**fixed alerts:**

* 1 for Unreachable code

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request **fixes 1 alert** when merging 6b16e035dcf9df5cf3a3c38d3c3a1c5c61fcdcc9 into c6a76ede3588ec75ee68411b3a11e685e7c5d230 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-710667b3fc3bf9513d8fce51ec4af77e8ae92ef3)

**fixed alerts:**

* 1 for Unreachable code

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request **fixes 1 alert** when merging f62d38d19f25a2833380d3d3b5bc70bb9095a008 into c6a76ede3588ec75ee68411b3a11e685e7c5d230 - [view on LGTM.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-2ecfd0002b867d62eafda5e5d7ec61bbdd27a0ab)

**fixed alerts:**

* 1 for Unreachable code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
I guess this can be merged, so I will do that tonight unless there are concerns.

**Pull request merged**
