### PR TITLE
[MAINT/CLN] remove numdiff  __main__ section explicitly marked as scratch work

### PR DESCRIPTION
**Pull request by jbrockmendel**
`# below is Josef's scratch work`

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@josef-pkt please consider allowing someone junior to handle some of these.

**Comment by jbrockmendel** [comment]
@josef-pkt is there something worth salvaging here? Bashtage and I think not,  it if there is I’ll glady paste it in the sandbox so we can get through this

**Comment by josef-pkt** [comment]
The issue header and description are not searchable, i.e. they don't mention the module and don't mention what "content" gets removed.

My guess is that all the main parts ended up in unit tests, the only potentially interesting piece of information is the comparison with numdifftools.
E.g. from another issue, if you want to compare our hessian with and adaptive stepsize hessian, then examples like this would be helpful.

Otherwise I don't think it's important enough to keep it present in the repo, e.g. as example.

**Pull request merged**
