### PR TITLE
TST: circle ci

### PR DESCRIPTION
**Pull request by thequackdaddy**
Here's an attempt to use circle ci. 

xref #5144
xref #5154

### CODE REVIEW

**Comment by bashtage** [comment]
Should add [skip appveyor] to any commit that only requires travis (osx, docs, etc) or circle ci.  I should also do the same.

**Comment by jbrockmendel** [comment]
+1

**Comment by thequackdaddy** [comment]
Yes, its a little slow. 

I was thinking if feasible though to offload some of the test cases from travis here. Maybe we only use 2-3 jobs? 

That might free up time so #5237 is not as annoying.

**Comment by bashtage** [comment]
Going to close.  I think azure dominates since this isn't setup.

**Pull request closed without merging**
