### PR TITLE
COMPAT: update calls to pandas objects/methods

### PR DESCRIPTION
**Pull request by toobaz**
No idea what's the plan, if any, with this code/functionality... but updating it to work with recent pandas shouldn't do any harm ;-)

### CODE REVIEW

**Comment by toobaz** [comment]
(disclaimer: by "work" I only mean "running the script without any error")

**Comment by josef-pkt** [comment]
@toobaz   Thanks, It's good to get working code in the sandbox. I know almost nothing about how the pandas Panel classes work, and I'm usually lost in how to update old code.

the main PR that supersedes this code is #1133. I thought that there is a more recently rebased version but don't find any branch or PR for it.
AFAIK, Vincent and Skipper switched to mainly using pandas multi-index for the (econometrics) panel data models.

**Comment by josef-pkt** [comment]
merged

**Comment by toobaz** [comment]
@josef-pkt : just to be sure I'm not missing anything: is there currently any (sandboxed or not) way in statsmodels to run for instance the equivalent of ``plm(formula, data=data, index = (id, year), effect = "twoways")`` (regardless of the structure of the data, which is to me less relevant)?

(the ``DeprecationWarning`` for ``PanelOLS`` in pandas currently points to [MixedLM](http://statsmodels.sourceforge.net/stable/mixed_linear.html)...)

**Comment by josef-pkt** [comment]
@toobaz   Is that `plm` call using fixed or random effects?

MixedLM variance components implements random effects (intercept) for crossed or arbitrary groupings. The estimator is MLE or REML.
Fixed effects are currently only implemented through dense dummies that can be created through patsy. I have PR's open for sparse regression and for absorbing fixed effects that work even if there are a large number of fixed effects.

The panel PR implements standard econometrics one-way or two-way random and fixed effects/intercepts. random effects are estimated by standard two-step estimation (moment conditions for variance)

**Comment by toobaz** [comment]
That ``plm`` call should be using fixed effects.

I think I have the picture a bit clearer now, thanks!

**Comment by josef-pkt** [comment]
How many fixed effects levels/individuals/timeperiods do you have?  
I wrote the sparse regression when a user had a large number of them.
`Absorb` currently doesn't provide all result statistics for the absorbed effects, so it's mainly useful when we don't need to know details or tests about the fixed effects (nuisance parameters).

**Comment by toobaz** [comment]
I have ~ 10 time periods, but several thousands of individuals.

And I don't care much about fixed effects estimates themselves.

So you're suggesting that I look at https://github.com/statsmodels/statsmodels/issues/2568 ?

**Comment by josef-pkt** [comment]
Do you have one-way fixed effects?
Those would be easy to remove by demeaning all variables by groups/individuals. (*)
Part of the PR, or a PR is to add `ddof` degrees of freedom correction to OLS, which would be all that is needed for the `within` fixed effects estimator.
Most likely I'm merging at least that part next week (ddof option for OLS)


(*) To get the standard estimate for the constant Stata and I add the grand mean back in, after subtracting the group means.

**Comment by josef-pkt** [comment]
> ddof option for OLS

I don't find any branch with this code on github.

**Comment by josef-pkt** [comment]
I will continue notes on ddof for OLS in issue #2799 https://github.com/statsmodels/statsmodels/issues/2799#issuecomment-225451994

**Pull request merged**
