### PR TITLE
ENH/DOC: Added linting instruction in CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by bksahu**
- It addresses issue #5447 
- Added instruction for both Linux and MacOS

### CODE REVIEW

**Comment by ChadFulton** [comment]
Thanks! This LGTM, but I'll wait until tomorrow to merge, in case there are other comments.

**Comment by bksahu** [comment]
Sure. Although I have no idea why build is failing. Any ideas ?

**Comment by ChadFulton** [comment]
Thanks @bksahu!

**Comment by bksahu** [comment]
It is my pleasure @ChadFulton. Could you please tell me why that one build is failing? It is failing in my other PR too.

**Pull request merged**
