### PR TITLE
TST: Add mac testing

### PR DESCRIPTION
**Pull request by thequackdaddy**
Here's an attempt to get travis to run on Mac. 2 more scenarios, so even slower than before. 

There are 2 runs. The first will use pyenv to download/install python 3.6.6 and I basically just use our pip install with a few modifications. 

The second run uses python 3.7 and uses pretty much our conda install. 

xref #2069 
xref #5154

### CODE REVIEW

**Comment by bashtage** [comment]
LGTM.  Putting them as expected fail, for now, is a good idea. The only downside is the increased pressure on CI. Both Travis and Appveyor will take about 1 hour to complete now.

**Comment by josef-pkt** [comment]
I think it's worth the extra testing time.

@thequackdaddy  can you rebase, there are merge conflicts now
Then I will merge.

**Comment by thequackdaddy** [comment]
@josef-pkt Sorry for delay. Rebased.

**Comment by josef-pkt** [comment]
(19 hours is not a delay, especially given that it took me months to look at it.)

one mac https://travis-ci.org/statsmodels/statsmodels/jobs/461015476
has precision problem in `test_arima_exog_predict`
otherwise all green.

I think we will be able to switch to not allowing failures after some short trial period.

merging, 
@thequackdaddy @bashtage  Thank you

**Pull request merged**
