### PR TITLE
BLD: Include License in Wheel

### PR DESCRIPTION
**Pull request by bashtage**
[skip ci] [skip appveyor]

Include License for installation through wheel

### CODE REVIEW

**Comment by rgommers** [comment]
cool, learned something new:)

**Comment by bashtage** [comment]
Any a question for you: how does SciPY get the .txt files (LICENSE, HACKING.rst.txt, etc) into the wheel?  I have had a very hard time getting files in the root into the Wheel install -- they go in the wheel into a data folder but then do not get installed anywhere.

**Comment by rgommers** [comment]
It's a bit complicated, took me a little while to track down - I think this is all of it:

- Adding license as data file, so it gets installed: https://github.com/scipy/scipy/blob/master/setup.py#L402
- Adding other licenses as data files: https://github.com/scipy/scipy/commit/811a69a6dff5cd2d5a7df73268edabe78b28a4eb
- Per platform checking (we bundle different libs): https://github.com/MacPython/scipy-wheels/blob/master/patch_code.sh
- Amending Windows license: https://github.com/MacPython/scipy-wheels/blob/919b9906adb56b2155f03abaa8d5e406272291bb/appveyor.yml#L180
- Checking for license presence: https://github.com/MacPython/scipy-wheels/blob/master/check_license.py

**Comment by jbrockmendel** [comment]
+1

**Comment by jbrockmendel** [comment]
+1 on removing the extra license file.  Want to update the date on the remaining one while at it?  Then I can close #4973.

**Comment by bashtage** [comment]
I updated to 2018.

**Comment by bashtage** [comment]
In case anyone wants to know, I am packaging setup.cfg so pytest can find its configuration information when run from an installed wheel.  The test will run without this but may produce a lot of warning noise.

**Comment by josef-pkt** [comment]
merging, assuming it works, without checking

@bashtage Thanks

**Pull request merged**
