### PR TITLE
un-mangle tests

### PR DESCRIPTION
**Pull request by jbrockmendel**
_please_ let me go through and fix these in a systematic way.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt please let us fix obviously-bad stuff like this.
@bashtage thoughts?

**Comment by ChadFulton** [comment]
Although I have no knowledge about these models, this PR looks reasonable to me.

Except, what's going on with `test_jac`? It looks like maybe the `no_info` was a way to do a skip test, with the reason being that there is "no information" (I don't know what "no information" means, unfortunately). So by removing those lines, are you now allowing a parent `test_jac` to run when it shouldn't?

**Comment by josef-pkt** [comment]
Also, this PR fails on 
"E   NameError: name 'pytest' is not defined" 
and doesn't run the tests, AFAICS from spot checking

**Comment by jbrockmendel** [comment]
> "E NameError: name 'pytest' is not defined"

Totally reasonable, fixed (and rebased to keep the git history pretty, just for you buddy!)

> and doesn't run the tests, AFAICS from spot checking

Not sure I follow; what's the concern?

**Comment by jbrockmendel** [comment]
> So by removing those lines, are you now allowing a parent test_jac to run when it shouldn't?

If you look at the status quo, `test_jac` is defined twice in each of the three affected classes.

**Comment by josef-pkt** [comment]
> and doesn't run the tests, AFAICS from spot checking
Not sure I follow; what's the concern?

AFAICS, the travis test run stopped before running the unit tests (pytest stops immediately on syntax and similar errors)
So, we don't know yet if any of the changes breaks other tests, like deleting the test_jac override or enabling `test_pvalues` (which I assume should be fine as typo fix)

**Comment by josef-pkt** [comment]
Also, there are some duplicate definitions of test_jac

```
    def test_jac(self):
        pass
```
and
`test_jac = no_info`

in the same test class.

I remember I just fixed some test_jac, so those should work or made to work for (almost) all cases.
Checking, that's in my current WIP PR #4716
I was looking at my PR checkout.

**Comment by jbrockmendel** [comment]
> Also, there are some duplicate definitions of test_jac

I'm pretty sure I caught all of those, though another set of eyeballs couldn't hurt.

> Checking, that's in my current WIP PR #4716

I've got a tab open for that, will review before long.

**Comment by josef-pkt** [comment]
It looks like all test_jac overrides are in NegativeBinomial.
I didn't look at it recently because I skipped it for score_factor addition. NB is too messy with the 3-in-1 model.

**Comment by jbrockmendel** [comment]
ping

**Comment by jbrockmendel** [comment]
@josef-pkt ping

**Comment by jbrockmendel** [comment]
@josef-pkt Go Go Gadget Teamwork!

**Comment by jbrockmendel** [comment]
Well done sir!  Thanks for handling a couple of the more pesky ones over the last few days.  I think this is the last Truly Painful ones at the moment.

Are either of you by chance attending scipy in Austin?

**Comment by jbrockmendel** [comment]
Ping

**Comment by jbrockmendel** [comment]
@josef-pkt lets make the tests suite more reliable, yah?

**Comment by jbrockmendel** [comment]
Closing in favor of #4983, #4980, #4978.

**Pull request closed without merging**
