### PR TITLE
 BUG/ENH: VARMAX Fix trend / exog. timing. Add polynomial trends.

### PR DESCRIPTION
**Pull request by ChadFulton**
VARMAX models with trend or exog used a misleading timing convention that I think qualifies as type-bug-wrong. The timing convention it used was as according to the general state space transition equation:

`\alpha_{t+1} = d_t + T_t \alpha_t + \eta_t`

But for a VAR, `\alpha_t = y_t`, and so trend / exog for time t would be associated with the endog for t+1.

This fixes this problem and also adds a more extensive set of trends (allows a polynomial trend like in SARIMAX rather than just `trend='c'`).

Also adds a bunch of unit tests for VARX models with and without trends against the R package "vars".

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 75013561b69cabd519f6ecb97318a2ab18c84770 into 450f30dbe999923e1ef565ed241d0ba4eae19778 - [view on LGTM.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-eb2ce6efc4da74e04aad4cd0ae14298671ef6c18)

**new alerts:**

* 1 for Unused local variable

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging e16ef787666f19015d9144ee184e0a18f3ccafc4 into 450f30dbe999923e1ef565ed241d0ba4eae19778 - [view on LGTM.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-18abb0695be98725717b094f5c62abbc996c6cc2)

**new alerts:**

* 1 for Unused local variable

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
This PR also switches from raising an error on non-stationary or non-invertible starting params to giving a warning. This is the same as what #4739 did for SARIMAX.

**Comment by ChadFulton** [comment]
This is coming up green. Since it's a bigger PR, I'll wait a bit (tomorrow or on the weekend) before merging (or longer if there are concerns), but it would be good to get the fix in.

**Comment by josef-pkt** [comment]
This pull request **fixes 1 alert** when merging d6d1b3db4537dacdcc6749e6ff61aa1a5fbf2d28 into 450f30dbe999923e1ef565ed241d0ba4eae19778 - [view on LGTM.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-c7486ed719399f64567940caa0166533ad3d774d)

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
