### PR TITLE
DOC: remove orphaned docs files

### PR DESCRIPTION
**Pull request by jbrockmendel**
These ones are unused and have not been touched in 7 years.

There are a few other .rst.TXT files in docs/source/ that are likely orphaned, but have some complicating factor so merit double-checking:
- [ ] glm_techn1.rst.TXT and rlm_techn2.rst.TXT both just say "just a placeholder", but they are referenced in glm.rst (maybe remove those references?)
- [ ] gmm_techn.rst.TXT has some actual content in it (should it be referenced in gmm.rst?)
- [ ] extending.rst.TXT is empty, but is referenced in gmm_techn.rst.TXT
- [ ] regression_techn1.rst.TXT just says "just a placeholder", not referenced elsewhere
- [ ] tsastats.rst.TXT has an example of `sm.tsa.add_lag`, and then a TODO referencing scikits.timeseries

cc @thequackdaddy since I've seen you working in the docs recently

### CODE REVIEW

**Comment by jbrockmendel** [comment]
cc @bashtage since we're on a docs-focused mode

**Comment by bashtage** [comment]
@josef-pkt has a much stronger connection to these, so this needs his approval.

**Comment by jbrockmendel** [comment]
@josef-pkt thoughts? xred #5442

**Comment by josef-pkt** [comment]
I don't see a reason why we would throw away the lyx/pdf files
Those are the only beginning of a GLM doc that we have.

lyx files can be exported to standard LATEX, AFAIK.


As for the rest: The question should be how can we improve our documentation, deleting never used stub files is secondary.
Obviously Skipper and I never took much time for it, and nobody else volunteered to write any technical background to the models.
Most likely the future is in notebook documentation.

**Comment by jbrockmendel** [comment]
> I don't see a reason why we would throw away the lyx/pdf files

Because non-you readers shouldn't have to figure out which files are and are not pointful.  The same way they shouldn't have to figure out which commented-out code is likely to get re-enabled.

**Comment by josef-pkt** [comment]
This has nothing to do with me.

The GLM lyx file was written by Skipper, I guess, and would be useful to anyone working on GLM or improving it's documentation.

It's much easier to understand in the context of a model or subpart of statsmodels than jumping and browsing randomly through the source.

scipy.stats.distribution had a lyx file with all/most of the distribution formulas. Some volunteer converted it to rst doc pages and they are now part of the regular scipy docs (that happened many years ago.)

**Comment by bashtage** [comment]
If they are salvagable then it seems that they should be converged to rst as well.  In `linearmodels` I use a two step process where I export lyx to LaTeX and then LaTeX to rst.  For example, this [document](https://bashtage.github.io/linearmodels/doc/panel/mathematical-formula.html) starts its life as a LyX file.

**Comment by bashtage** [comment]
One way forward on these types of PRs would be to create an archive folder that at the root called `archive`.  files could be `git mv` to this folder if they are likely ready for deletion.  They can sit there for a good while with their complete history and not distract from the main codebase.  The archive folder should have a README.md with an explainer this is archived code/docs that has been retained for reference but is not longer part of the core, and that it is unmaintained.

**Comment by jbrockmendel** [comment]
good idea.  implemented

**Comment by jbrockmendel** [comment]
implemented the archive/ idea

**Pull request merged**
