### PR TITLE
ENH: Multiple imputation via Gaussian model

### PR DESCRIPTION
**Pull request by kshedden**
This PR provides a way to impute missing values in a dataset using a multivariate Gaussian model.  The imputations are obtained via Gibbs sampling from the joint posterior of the mean vector, covariance matrix, and missing values.  Thus, uncertainty in the mean vector and covariance matrix are accounted for.  A new MI class is provided that can be used with other imputation schemes that may be implemented in the future.

This provides an alternative to MICE that should be much faster as it bypasses Patsy formula processing, and does not fit a model at every step.   However it is less general as each missing value is modeled through a Gaussian regression on the remaining components.

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request **introduces 3 alerts** when merging 913cddc54f7ca83b75afa9ea9b5550639ab09d9a into d9eacb09682909106b66a543485a2d024b316263 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-5048a769d4cc84b8b27d7c50f3209d968b52e67d)

**new alerts:**

* 3 for Module\-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request **introduces 3 alerts** when merging e7bf9314b96c24826b12491815462f71e046537f into d9eacb09682909106b66a543485a2d024b316263 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-f0e8d8ebec8b7fb733298b634314d52edb79c9c9)

**new alerts:**

* 3 for Module\-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
Can this be merged for 0.9, or should it wait for 0.10?
I haven't looked at any details.

**Comment by kshedden** [comment]
I think it can go in.  I was going to rebase and merge but go ahead if you
want to do it.

**Comment by josef-pkt** [comment]
you can rebase and merge.
I'm mainly trying to do a final check what should still go into 0.9

**Comment by josef-pkt** [comment]
This pull request **introduces 3 alerts** when merging dbdc8d6fd07bfea698e12e907499c7be9b566fc4 into 9f2ed83a2e38347c4eb85b48082a9e952d04fba2 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-281894b17fb6cd561f8ff0d5331e4e598e3738e9)

**new alerts:**

* 3 for Module\-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by kshedden** [comment]
@josef-pkt I'm struggling to resolve the lgtm warning about cyclic imports... any hints?

**Comment by josef-pkt** [comment]
AFAIK, the cyclic import warnings are false alarms. I have seen them in several places related to the api imports. But AFAIK we still have the api.py separate from the regular modules. 
I've never seen a problem coming from circular import in our code and PRs.

**Comment by josef-pkt** [comment]
@kshedden  ( and @ChadFulton )  Please add labels and milestone so we know for which release PRs were merged and what kind of PRs they are.

**Pull request merged**
