### PR TITLE
Triumph of Hope Over Experience: Remove Trailing Whitespace

### PR DESCRIPTION
**Pull request by jbrockmendel**
Exactly what it says on the label.  Fixes something like 15k flake8 warnings.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Do you have any hints on how I might feasibly review this PR? :)

**Comment by jbrockmendel** [comment]
> Do you have any hints on how I might feasibly review this PR? :)

Assuming the diff is rendered in your browser the same as it is in mine, it should be pretty trivial -- albeit admittedly tedious -- to verify that the diff is as described.

For the big files you could look at a sample of lines instead of scrolling through all of them.  At some sample size you should conclude that regular expression replacement works as expected.

And if all else fails, I'll be happy to split this into smaller pieces.

**Comment by josef-pkt** [comment]
I doubt it's worth the huge wholesale change. Most modules have only a few cases, but changes in VECM test files look large.
I guess, this means that my current git doesn't have automatic trailing whitespace cleanup on rebase anymore, I used it before to clean up PRs that I rebased before merging.

**Comment by josef-pkt** [comment]
as reference, automatic trailing whitespace fix for changes in a git commit:

`>git config --edit --global`

add if missing
```
[core]
	whitespace = trailing-space
[apply]
	whitespace = fix
```

This should only clean up current changes, i.e. no retro-active file cleaning. I must have lost it when I changed computers or during some updates.

**Pull request closed without merging**
