### PR TITLE
TST: parametrize tests in test_lme

### PR DESCRIPTION
**Pull request by jbrockmendel**
@kshedden your domain

Relevant to #4396 since failing cases will all be displayed in test output.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@kshedden ping

**Comment by kshedden** [comment]
Looks good to me.

**Comment by jbrockmendel** [comment]
@kshedden I'm gonna try to spend some time away.  Mind merging before I take off?

**Comment by jbrockmendel** [comment]
@kshedden ping

**Comment by kshedden** [comment]
@jbrockmendel thank you, merging

**Pull request merged**
