### PR TITLE
BLD: Add pinned numpy on appveyor

### PR DESCRIPTION
**Pull request by bashtage**
Pin numpy against old SciPy

### CODE REVIEW

**Comment by josef-pkt** [comment]
didn't help, same error even with numpy 1.11.3
something else wrong than my guess in #4939

```
statsmodels\compat\scipy.py:259: in <module>
    from scipy.special import gammaln
c:\py\lib\site-packages\scipy\special\__init__.py:636: in <module>
    from ._ufuncs import *
E   ImportError: DLL load failed: The specified module could not be found.
```

**Comment by josef-pkt** [comment]
I don't know much about conda
e.g. it looks like old numpy version got reuploaded/rebuilt 2 days ago, our appveyor also started to fail 2 days ago
https://anaconda.org/anaconda/numpy/files?version=1.11.3

I have no idea what that implies or where to get more info

**Comment by bashtage** [comment]
I suspect that icc_rt is required.  It disappeared across the successful and the failed builds.  I've added this as a requirement so we'll see if that fixes the issue.

**Comment by josef-pkt** [comment]
just as background info: what is icc_rt?

Thanks for figuring this out.
Merging, so we have one ci green again

**Comment by bashtage** [comment]
Intel c compiler runtime

**Pull request merged**
