### PR TITLE
Fix OpenBLAS `pow_dd` unresolved symbol error, update Emscripten CI testing

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
- [ ] closes #xxxx
- [x] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

### Description

This PR follows up on changes made in #9270. Here's a small, point-wise summary noting the changes:
- It updates the Emscripten/Pyodide CI job added in #9270 and removes the workaround JavaScript test suite file, since we fixed the `pow_dd` OpenBLAS unresolved symbol coming from SciPy upstream, having updated SciPy in-tree.
- The [Pyodide xbuildenv](https://github.com/pyodide/pyodide/releases/tag/0.27.0a2) can now be used to set up a virtual environment to run the tests in the same way as they were running before.
- The [`pyodide-build` tool](https://github.com/pyodide/pyodide-build) has been unvendored from the Pyodide repository and now infers the Pyodide version from the releases.
- At the time of writing, Pyodide 0.27alpha2 is used in the CI job; once 0.27 stable comes out and `cibuildwheel` updates to it, we can update `cibuildwheel` in https://github.com/MacPython/statsmodels-wheels/pull/161 and run the test suite there (if it makes sense to do so – since the test suite is on the slower side without parallelization).
- The tests for the "Tukey's HSD" statistical test that were previously marked as xfailing due to issues with SciPy (more specifically, `scipy.optimize`) have been restored. 

### Additional context

- Pyodide CI support was first discussed in #9166
- https://github.com/pyodide/pyodide/pull/4871#issuecomment-2325393399

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
`test_tukeyhsd` is displayed as failing, but it's a strict xpass – I'm not sure why the behaviour differs in the xbuildenv venv versus the Node.js runner. Restored it in 62ceeba6fcc7c2cf55e5ff41e825be4be25c33ba.

**Comment by agriyakhetarpal** [comment]
On that note, maybe the rest of the Tukey HSD tests in `test_pairwise.py` now work, too. I'll undo those skips/xfails and check.

**Comment by agriyakhetarpal** [comment]
Addressed in 316ca4d1c4e8550fe77fcd4327792e9a7fdbd700, the only failing tests under WASM in the entirety of the `statsmodels` test suite should now be those where threading/multiprocessing isn't available and the Matplotlib tests (which use a different backend). This is now ready for review, @bashtage, thank you!

**Comment by agriyakhetarpal** [comment]
Azure macOS test errors seem unrelated.

**Comment by bashtage** [comment]
Agree.  It is a random failure.

**Comment by agriyakhetarpal** [comment]
Thanks for the speedy review and merge! :)

**Pull request merged**
