### PR TITLE
ENH: White spec test (clean commit for PR 4721)

### PR DESCRIPTION
**Pull request by JimVaranelli**
Clean commit history for PR 4721

### CODE REVIEW

**Comment by JimVaranelli** [comment]
@josef-pkt I don't understand the appveyor/merge conflict here. The same error appears on the original PR as well?

**Comment by josef-pkt** [comment]
You did not rebase on or branch off current master.
There is a merge conflict in the imports in the stats.diagnostic module (deprecated functions have been removed from the import list)

Needs rebase and manual conflict resolution

**Comment by JimVaranelli** [comment]
> You did not rebase on or branch off current master.
> There is a merge conflict in the imports in the stats.diagnostic module (deprecated functions have been removed from the import list)
> 
> Needs rebase and manual conflict resolution

Do you know why the original PR 4721 is showing the same conflict error? Nothing was changed in that branch?

**Comment by josef-pkt** [comment]
The CI testing merges the branch into current master. If there are other changes already in master, as in this case, then trying a new test run will show a merge conflict. 
Actually, github already checks for the merge conflict, that's why github will show the merge conflict after an updated check. AFAIU, any new comment or changes in the PR will trigger the github merge conflict check.

**Comment by JimVaranelli** [comment]
OK the merge issue should now be fixed. It was related to the deprecated breushpagan (mis-spelling) call. Do I need to do the same for 4721?

**Comment by josef-pkt** [comment]
not for 4721, we leave that as is

(I will look later today at the PR when I am back on the computer)

**Comment by JimVaranelli** [comment]
Looks like a few unrelated (?) tests failed in Travis-CI.

**Pull request closed without merging**
