### PR TITLE
MAINT: bump SciPy to versions supporting python 3.7

### PR DESCRIPTION
**Pull request by tupui**
Minimal SciPy version supporting Python 3.7 is SciPy 1.6.

### CODE REVIEW

**Comment by bashtage** [comment]
This doesn't seem right.  There are wheels for SciPy 1.5.4 on PyPI for Python 3.7.

**Comment by bashtage** [comment]
SciPy 1.2 seems to have support for Python 3.7.

**Comment by bashtage** [comment]
Since SciPy is a build-time dep, maybe we need python-specific dependencies here:

https://github.com/statsmodels/statsmodels/blob/4e2cf0587fde72a3e54170cca8f9a0b333ee8447/pyproject.toml#L6

**Comment by tupuinui** [comment]
Oh sorry I got confused with the minimal Python version. Feel free to close this.

**Comment by tupui** [comment]
Oh sorry I got confused with the minimal Python version. Feel free to close this.

**Comment by bashtage** [comment]
Thanks for the clarification.

**Comment by tupui** [comment]
Still maybe bumping to 1.15 would make sense as to respect NEP29?

**Comment by bashtage** [comment]
I'm happy with 1.4 but @josef-pkt is usually more conservative. IIRC we have 1.3 as the lowest since we have a CI run against it, which is the main determinant.

**Comment by josef-pkt** [comment]
I need to check when I’m back on my computer.
I like to be conservative with updating requirements if supporting older versions doesn’t cost as anything, or not much

**Pull request closed without merging**
