### PR TITLE
ignore_temp gam rebased

### PR DESCRIPTION
**Pull request by josef-pkt**
this is a temporary PR to check whether TravisCI is triggered, and try out rebasing.

This PR is not to be merged.

see PR #2435 for Luca's branch and PR

### CODE REVIEW

**Comment by josef-pkt** [comment]
travisci still doesn't work

rebasing is messy, I get many merge conflicts.
Also during merge conflict I have now a conflict with uncommitted local file `.idea` which is not supposed to be in the repo. I need to start over in a empty folder and not in my working folder (eclipse/pydev)

also a lot of trailing whitespace that is removed during rebase but not always during merge conflict resolution.

git hint:
`E:\...\statsmodels>git checkout --theirs statsmodels/sandbox/gam_gsoc2015/smooth_basis.py`
to accept the next version
see http://stackoverflow.com/questions/8146289/how-to-get-their-changes-in-the-middle-of-conflicting-git-rebase

**Comment by josef-pkt** [comment]
rebased with many conflicts, most likely not clean, skipping two commits where I couldn't fix the merge conflict

**Comment by josef-pkt** [comment]
the rebase enabled travis-ci for this branch

**Comment by josef-pkt** [comment]
It looks like this PR didn't increase the number of unit tests

This PR `Ran 3996 tests in 638.114s, OK (SKIP=158)`     (last commit add fit pirls method)
master   `Ran 3996 tests in 638.316s, OK (SKIP=158)`    (after merge GLSAR)

**Comment by josef-pkt** [comment]
there are no `__init__.py` in the folders for gam, added

**Comment by jbrockmendel** [comment]
@josef-pkt @bashtage now there is a “real” gam, is this closeable?

**Comment by josef-pkt** [comment]
last GAM PR #5481 was merged

**Pull request closed without merging**
