### PR TITLE
BUG: raise instead of return ValueError

### LINKED ISSUE #4997: web._generate_url returns ValueError--> intentional?
```
            return ValueError('Input not understood')
```
seems like it should be `raise` instead of `return`.  Am I missing something?

### PR DESCRIPTION
**Pull request by jbrockmendel**
Closes #4997.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt broken off from #5028.

**Comment by jbrockmendel** [comment]
Green

**Comment by jbrockmendel** [comment]
@josef-pkt ping, concerns from previous iteration addressed.

**Comment by josef-pkt** [comment]
LGTM (I edited title and changed it to BUG)

@jbrockmendel thank you

**Pull request merged**
