### PR TITLE
Correlation

### PR DESCRIPTION
**Pull request by Sarmentor**

### CODE REVIEW

**Comment by Sarmentor** [comment]
@josef-pkt  Just to inform I've done this new PR with correlation.py and respective tests regarding KMO and Bartlett Sphericity tests. Cheers

**Comment by Sarmentor** [comment]
@josef-pkt  Please advise where to put the tests.csv file. The automated checks are failing due to errors like file not found. Cheers

**Comment by josef-pkt** [comment]
@Sarmentor I'm not sure what the problem with the csv file is, there are several possibilities.

The easiest is to follow our standard pattern, put the file in tests/results and use the full file path

e.g. another test in stats
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/tests/test_mediation.py#L56

```
    cur_dir = os.path.dirname(os.path.abspath(__file__))
    data = pd.read_csv(os.path.join(cur_dir, 'results', "framing.csv"))
```

**Comment by Sarmentor** [comment]
@josef-pkt @bashtage  Hi! I believe the tests are all ok. I'll be out for the weekend. I'll be back next monday, if you need more feedback from me please leave a message and I'll work on that next week.
Cheers

**Comment by Sarmentor** [comment]
@josef-pkt Hi! Can you please confirm if this merge will be associated with release 0.9?

**Comment by josef-pkt** [comment]
@Sarmentor   Yes, it will be in 0.9 for sure.
The main thing missing is an API review. (I'm still not sure what the return type should be, we don't use named tuples because they are not forward compatible.)

**Comment by Sarmentor** [comment]
@josef-pkt Hi! Should I close the other two PRs that are now obsolete?

**Comment by josef-pkt** [comment]
@Sarmentor  Do you have a reference that the bartlett_sphericity can be used with spearman correlation? i.e that it has the same distribution of the test statistic.

One confusing thing about it is that it is a test that the covariance matrix is diagonal, so the covariance does not need to be spherical. Stata has the same test statistic and pvalues for the diagonal covariance test.

**Comment by Sarmentor** [comment]
@josef-pkt Depending on the variable type, different methods to obtain the correlation matrix should be used. In the case of quantitative variables, Pearson correlations have satisfactory results. However, in the case of nominal and ordinal variables, some authors (for example, Marôco, 2011) advocate the use of Spearman correlation. Please note that in the function provided I give the option to choose between Spearman or Pearson correlations. Default option is currently Spearman, however the user can change this.

**Comment by josef-pkt** [comment]
Is Marôco, 2011 reference the SPSS book in Portuguese?

I don't like adding things where I don't see a theoretical justification or at least has been confirmed by some Monte Carlo studies. The correlation test is for Pearson correlation with a normal distributed sample and might be robust to some distributional deviation from normality. My guess would be that using spearman does not have the correct scaling.

To avoid the issue and to have more flexibility, for example with using outlier robust estimators, I'm thinking of just using the correlation matrix as argument, e.g.
`corr_test_spherical(corr, nobs)`

I went over the Stata manual and the chapter in Rencher Christensen that they refer to and I'm thinking of adding
cov_test_xxx(cov, ..., nobs, ...) for one sample, spherical, diagonal (which is the same as corr_test_spherical, k-sample equality and a few more.
https://github.com/statsmodels/statsmodels/issues/2765#issuecomment-342697378

e.g. the call would then be with a dataframe

`cov_test_diagonal(df1.cov(), df1.shape[0])`

I would like some extra functions that take the data and call the underlying corr_test or cov_test, but I don't know yet what the design for that should be. I think that's not urgent given that computing various cov/corr is easy with pandas.

**Comment by josef-pkt** [comment]
Paritally related: for multivariate outlier detection and robust covariance or correlation estimation, I wrote a function that converts some of the other correlation types to be consistent at normality https://github.com/statsmodels/statsmodels/pull/3230/files#diff-0999b4a53db162f8a6150dbeecb638d7R35

The corr_test would have lower requirements because under the null the correlations are zero, so only the neighborhood of zero is relevant.

**Comment by josef-pkt** [comment]
just a piece of information:
for the fisher transform and testing a single correlation coefficient the variance differs between pearson and spearman, and kendall tau. According to the wikipedia page the variance for spearman z_s is 1.060 / (n - 3)
The Fieller, E. C.; Hartley, H. O.; Pearson, E. S. (1957).  reference in Wikipedia also has it for kendall 
var(z_K) = 0.437 / (n - 4)
z = tanh^{-1}(r) = artanh(r)
https://academic.oup.com/biomet/article-lookup/doi/10.1093/biomet/44.3-4.470

**Comment by josef-pkt** [comment]
Hauke, Kossowski is just a comparison of single correlation coefficients. They don't specify which significance test they use, but by default there should be two different versions for the two types of correlations.

In any case, if we use correlation matrix as argument to the function, then it is up to the user to decide what to use. (Right now my guess is that the test overrejects when spearman is used, but I have no guess how strong the distortion might be.)

**Comment by josef-pkt** [comment]
looks like my guess about overrejection is wrong, at least in the normal case spearman is similar to pearson correlation in maintaining size

```
>>> cov_test_ = cov_test_diagonal
>>> k_vars = 5
>>> res_mc = [cov_test_(stats.spearmanr(np.random.randn(nobs, k_vars))[0], nobs) 
...           for _ in range(10000)]   
>>> res_mc = np.array(res_mc)
>>> (res_mc[:,1:] <= alphas).mean(0)
array([ 0.0114,  0.0506,  0.0981,  0.1998])

>>> res_mc = [cov_test_(stats.spearmanr(np.random.randn(nobs, k_vars))[0], nobs) 
...           for _ in range(30000)]   
>>> res_mc = np.array(res_mc)
>>> (res_mc[:,1:] <= alphas).mean(0)
array([ 0.00953333,  0.04823333,  0.09943333,  0.1999    ])
>>> alphas
[0.01, 0.05, 0.1, 0.2]

>>> nobs, k_vars
(500, 5)


>>> nobs=100
>>> res_mc = [cov_test_(stats.spearmanr(np.random.randn(nobs, k_vars))[0], nobs) 
...           for _ in range(30000)]   
>>> res_mc = np.array(res_mc)
>>> (res_mc[:,1:] <= alphas).mean(0)
array([ 0.01016667,  0.0498    ,  0.09846667,  0.1961    ])
```

**Comment by josef-pkt** [comment]
Another MC run, it looks pretty good even with nobs, k_vars = 50, 10

```
# using spearman rho
cov_test_ = cov_test_diagonal
nobs, k_vars = 50, 10
# normal
t0 = time.time()
res_mc = [cov_test_(stats.spearmanr(np.random.randn(nobs, k_vars))[0], nobs) 
          for _ in range(30000)]    
t1 = time.time()
print()
print('time', t1 - t0)
res_mc = np.array(res_mc)
alphas = [0.001, 0.005, 0.01, 0.05, 0.1, 0.2]
prop_reject = (res_mc[:,1:] <= alphas).mean(0)

print(alphas)
print(prop_reject)
```

``
time 38.5162250995636
[0.001, 0.005, 0.01, 0.05, 0.1, 0.2]
[ 0.00126667  0.00543333  0.01046667  0.05036667  0.10133333  0.20196667]
```

```
>>> import statsmodels.stats.proportion as smprop
>>> smprop.proportion_confint(0.0054333 * 30000, 30000)
(0.0046014667741415861, 0.0062651332258584127)
>>> smprop.proportion_confint(0.0054333 * 30000, 30000, method='wilson')
(0.0046624338048734592, 0.0063308071530681466)
```

**Comment by Sarmentor** [comment]
@josef-pkt What do you think? Robust?

**Comment by josef-pkt** [comment]
Yes, based on the limited MC examples using spearman looks good. Maybe the difference in scaling is not large around zero correlation. I found another article that compares single correlation confidence intervals that compares pearson, spearman and a few others where spearman with the Bartlett version (1.06) does very well. (I only looked at abstract and some graphs)

However, for 0.9 I would prefer to stick to the basic versions that use either corr or cov as argument, and postpone both more API decision and more quality checks to 0.10.

What I'm still not sure about is what the functions should return. My trend is to think of returning some results instance by default. I don't like named tuples because they need to create the instance and class and don't allow adding additional returns in future (not future proof).
(statsmodels has still no consistent pattern for returns in hypothesis tests.)

**Comment by josef-pkt** [comment]
postponed to 0.10 after all
needs decision on how to include this and related functions

**Comment by Sarmentor** [comment]
@josef-pkt 
Hi, is this somewhat forgotten or better options were taken to provide such tests in the package?

Best

**Comment by josef-pkt** [comment]
I added sphericity and similar tests for covariance patterns in a simple way in #6693

KMO is still missing, and I haven't looked at the details again. I guess it will go in statsmodels.multivariate to support the statistical methods there, e.g. FA, and not in statsmodels.stats as standalone.

I'm still working my way around stats in several rounds.

**Pull request closed without merging**
