### PR TITLE
DOC: add to release notes, smaller doc fixes, references

### PR DESCRIPTION
**Pull request by josef-pkt**
another round for 0.13

### CODE REVIEW

**Comment by bashtage** [comment]
In the copula code did you mean to super over the parent class in a couple of places?  There are some calls like  

```
super(ArchimedeanCopula).func()
```
which is the same as

```
Copula.func(self)
```

since `Copula` is the parent of ArchimedeanCopula

in specific copulas, rather than `super(GumbelCopula).func()` or simply `super().func()`. This might be right, but it is uncommon to go over the parent's version of the function.

https://github.com/statsmodels/statsmodels/blob/7a95aff38d99172d4f4943c6cbe1029a91c9fcd8/statsmodels/distributions/copula/archimedean.py#L171

**Comment by josef-pkt** [comment]
It's intentional. The intermediate class does not do the appropriate thing in those cases.
There is a conflict whether pdf or logpdf should be the primary implementation. Currently we have both cases.

(We have similar cases of skipping intermediate classes in discrete_model.)

**Comment by bashtage** [comment]
It might be better to leave a note since this is uncommon, or to explicitly call `Copula(self, ...)` which is more explicit.

**Comment by josef-pkt** [comment]
I will add some code comments.
I prefer the super call because it explicitly tells me that I'm skipping one level in the hierarchy.

This would go away here if or when we have logpdf as main implementation. ( logpdf might not always be numerically more stable than pdf, but it will be the primary method used for estimation.)

**Pull request merged**
