### PR TITLE
DOC: Restore import

### PR DESCRIPTION
**Pull request by bashtage**
Restore import for notebook

- [X] code/documentation is well formatted.  
- [X] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message).

### CODE REVIEW

**Comment by bashtage** [comment]
xref #5005

**Comment by thequackdaddy** [comment]
Do you want to try the "set -e" setting again? 

Seeing as some of the notebooks also attempt to download stuff and those downloads fail randomly, is there a way to auto-retry building a notebook 2 or 3 times before failing?

**Comment by thequackdaddy** [comment]
Wait I'm not remembering the whole story right. We do have "set -e", but it only runs before `make html`. 

https://github.com/statsmodels/statsmodels/blob/ef65a1757a9740c71df71a154174a923963bb264/tools/ci/docbuild.sh#L9

**Comment by bashtage** [comment]
If it was above pytest then this would have failed.

**Pull request merged**
