### PR TITLE
MAINT: clean up x13.py, delete main

### PR DESCRIPTION
**Pull request by jbrockmendel**
@ChadFulton for when ...

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by ChadFulton** [comment]
LGTM, although not sure what our framework for thinking about the goodness / badness of the contents of `if __name__ == '__main__'` sections is.

**Comment by jbrockmendel** [comment]
> about the goodness / badness of the contents of if __name__ == '__main__' sections is.

As I recall one of the first things I was told when I started contributing here was that these had all/mostly been removed, and the rest were on there way out.

**Comment by jbrockmendel** [comment]
@ChadFulton de facto green

**Comment by jbrockmendel** [comment]
@ChadFulton since your email said you're having trouble keeping track of things you've given LGTM, I'll collect a bunch here instead of flooding your email:

(BTW midway through a draft of response to your mailing list email in which I acknowledge the flood of PRs is my doing and will cut it down/out)

#5040 (this)
#5079 
#5020 (waiting on Appveyor as of 2018-09-01 16:52 UTC, Travis fail is spurious)

Things josef gave an LGTM to and then [?]
#5065 
#5026 (just rebased 2018-09-01 16:51 UTC, will be a few hours before ready)
#5014 
#4981 

Things that are causing the CI to fail on everything right now:
#5080 

Things you haven't given an LGTM to, but almost almost surely will (two sets of measure zero just to be on the safe side)
#5075 
#5068 
#4922 

Things outside of your domain but super-trivial
#5071 
#5070 

Things outside of your domain but super-trivial but I expect josef to need some convincing on (and not from me)
#5047
#5048 
#5050 
#5053 
#5041 (just rebased 2018-09-01 16:47 UTC, waiting on CI)

Other things to which @bashtage gave a "should be merged" a few days ago:
#5028
#5027 
#5020 
#5011 
#5007 
#5005 
#5003 
#5002 
#4990 
#4979 
#4977 
#4973

**Comment by jbrockmendel** [comment]
Looks like I listed #5020 above incorrectly, will try to track down that typo.

**Comment by jbrockmendel** [comment]
@ChadFulton this got your “LGTM” last week.  Ideally we can clear out already-approved ones before another round of rebasing.

**Comment by josef-pkt** [comment]
merging

example from main (I don't know whether we have enough examples)

```
if __name__ == "__main__":
    import numpy as np
    from statsmodels.tsa.arima_process import ArmaProcess
    np.random.seed(123)
    ar = [1, .35, .8]
    ma = [1, .8]
    arma = ArmaProcess(ar, ma, nobs=100)
    assert arma.isstationary()
    assert arma.isinvertible()
    y = arma.generate_sample()
    dates = pd.date_range("1/1/1990", periods=len(y), freq='M')
    ts = pd.Series(y, index=dates)

    xpath = "/home/skipper/src/x12arima/x12a"

    try:
        results = x13_arima_analysis(xpath, ts)
    except:
        print("Caught exception")

    results = x13_arima_analysis(xpath, ts, log=False)

    # import pandas as pd
    # seas_y = pd.read_csv("usmelec.csv")
    # seas_y = pd.Series(seas_y["usmelec"].values,
    #                        index=pd.DatetimeIndex(seas_y["date"], freq="MS"))
    # results = x13_arima_analysis(xpath, seas_y)
```

**Pull request merged**
