### PR TITLE
Implement full flake8 checking for a subset of files in good condition

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by ChadFulton** [comment]
I think this sounds like a good idea, and we can hopefully progressively increase the list.

**Comment by jbrockmendel** [comment]
Yep, and #4835 does that “progressive” thing from the opposite direction.

**Comment by jbrockmendel** [comment]
@ChadFulton once the button is pushed here we can make a push to get all of statespace over the fully-passing line.

**Comment by ChadFulton** [comment]
Will merge this tomorrow, unless there are concerns.

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel

**Pull request merged**
