### PR TITLE
FIX: State space: Cholesky factorization with complex step derivatives

### PR DESCRIPTION
**Pull request by ChadFulton**
Fixes the issue described #2514 by forcing filtering to use univariate or LU factorization (rather than Cholesky) whenever complex-step derivatives are calculated.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Also removes an obsolete inversion method.

**Comment by josef-pkt** [comment]
merging, (I don't understand the details.)

**Comment by ChadFulton** [comment]
Just for future reference - there are 5 methods available in the Cython code to invert the forecast error covariance matrix:

1. Simple division, in the univariate case (INVERT_UNIVARIATE)
2. Cholesky factorization with inversion (INVERT_CHOLESKY)
3. Cholesky factorization with linear solver (SOLVE_CHOLESKY)
3. Cholesky factorization with linear solver (SOLVE_CHOLESKY)

**Comment by ChadFulton** [comment]
Just for future reference - there are 5 methods available in the Cython code to invert the forecast error covariance matrix:

1. Simple division, in the univariate case (`INVERT_UNIVARIATE`)
2. Cholesky factorization with inversion (`INVERT_CHOLESKY`)
3. Cholesky factorization with linear solver (`SOLVE_CHOLESKY`)
4. LU factorization with inversion (`INVERT_LU`)
5. LU factorization with linear solver (`SOLVE_LU`)

Numbers 2 and 3 would cause the gradient to be calculated as zero for variance terms when using complex-step methods. The PR forces the specific filter calls where complex-step methods are used to use 1 or 5 (`INVERT_UNIVARIATE | SOLVE_LU`)

**Pull request merged**
