### PR TITLE
ENH: Fix lilliefors results for single-column DataFrames

### PR DESCRIPTION
**Pull request by Rijgersberg**
- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

The `lilliefors` function is broken on (single-column) DataFrames. The input gets coerced by `np.as_array()` into an array of shape `(N, 1)`, where it should be `(N,)`. This causes problems in the further calculations in the function, leading to incorrect results.

This PR adds a test that reproduces the problem, and fixes it by calling `np.squeeze()` on the array. It also adds raising a `ValueError` when the array cannot be squeezed to a 1d array.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks for reporting and PR.

What's the current (without this PR) behavior with a 2-column array or DataFrame?

**Comment by Rijgersberg** [comment]
> Thanks for reporting and PR.
> 
> What's the current (without this PR) behavior with a 2-column array or DataFrame?

ValueError:
```python3
>>> from statsmodels.stats.diagnostic import lilliefors
>>> import numpy as np
>>> import pandas as pd
>>> from scipy import stats
>>> np.random.seed(3975)
>>> x_n = stats.norm.rvs(size=500)
>>> multi_column_dataframe = pd.DataFrame(data=[x_n, x_n])
>>> lilliefors(multi_column_dataframe, dist='norm', pvalmethod='approx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rijgersberg/.local/lib/python3.8/site-packages/statsmodels/stats/_lilliefors.py", line 286, in kstest_fit
    raise ValueError('Test for distribution {0} requires at least {1} '
ValueError: Test for distribution norm requires at least 4 observations
>>> 

```

**Comment by bashtage** [comment]
An enhancement since it only claims to work for 1d data.

https://github.com/statsmodels/statsmodels/pull/7698/files#diff-d8ff13b59922f145c398db95ce8a6012076a92bce434c14dee50edce95aa06a0R230

**Comment by josef-pkt** [comment]
using DataFrame with observations in columns

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-60d630f3860f> in <module>
      2 x_n = stats.norm.rvs(size=500)
      3 multi_column_dataframe = pd.DataFrame(data=[x_n, x_n]).T
----> 4 lilliefors(multi_column_dataframe, dist='norm', pvalmethod='approx')

m:\josef_new\eclipse_ws\statsmodels\statsmodels_py37_main\statsmodels\statsmodels\stats\_lilliefors.py in kstest_fit(x, dist, pvalmethod)
    287                          'observations'.format(dist, min_nobs))
    288 
--> 289     d_ks = ksstat(z, test_d, alternative='two_sided')
    290 
    291     if pvalmethod == 'approx':

m:\josef_new\eclipse_ws\statsmodels\statsmodels_py37_main\statsmodels\statsmodels\stats\_lilliefors.py in ksstat(x, cdf, alternative, args)
    124     cdfvals = cdf(x, *args)
    125 
--> 126     d_plus = (np.arange(1.0, nobs + 1) / nobs - cdfvals).max()
    127     d_min = (cdfvals - np.arange(0.0, nobs) / nobs).max()
    128     if alternative == 'greater':

ValueError: operands could not be broadcast together with shapes (500,) (500,2) 
```

**Comment by josef-pkt** [comment]
I would like to have these type of functions properly vectorized by column.

The squeeze is to general, and likely not future compatible with a proper 2-d behavior.
I think a 2-d row should raise.

AFAICS, in the examples, the current behavior for 1 column array is to return incorrect results instead of raising an exception at some point. That's a more serious problem (even if the docstring says 1-d).

**Comment by josef-pkt** [comment]
for example, we could explicitly handle the 1-column case with

```
if x.ndim == 2 and x.shape[1] == 1:
    x = x[:, 0]
elif x.ndim != 1:
    raise ValueError(...)
```

I think, the only difference to a fully column vectorized version would be that 1-column returns scalar in this case, vectorized solution would return 1-element array.

**Comment by josef-pkt** [comment]
vectorizing this now for 0.13 is too much work. So we need the ValueError for cases that are not correctly supported.

@Rijgersberg Can you change the squeeze to the condition that we only support 1-column arrays and Dataframes, and raise in all other cases.

azure failure is unrelated style check

**Comment by josef-pkt** [comment]
aside: `as_norm` anderson-darling is vectorized and has one 2-d unit test in test_statstools.py

**Comment by Rijgersberg** [comment]
> @Rijgersberg Can you change the squeeze to the condition that we only support 1-column arrays and Dataframes, and raise in all other cases.

Sure!

**Comment by Rijgersberg** [comment]
I've also added tests for the 1d array enforcing, but they might be a tad repetitive.

**Comment by Rijgersberg** [comment]
> I've also added tests for the 1d array enforcing, but they might be a tad repetitive.

As an alternative I've reworked the tests into a single test in the latest commit. Let me know which style you prefer.

**Comment by bashtage** [comment]
LGTM.  Failure is unrelated.  Thanks.

**Pull request merged**
