### PR TITLE
DOC: Small doc fixes

### PR DESCRIPTION
**Pull request by bashtage**
Fix layout problem whihc excluded css
Fix broken URL
Remove missing todo document

[skip ci]

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt A few small doc problems that led to 404 errors

**Comment by bashtage** [comment]
@josef-pkt @TomAugspurger 

There are no doc build errors after this patch on Windows except:

  * x12/13 needs to be installed
  * graphics are output in the wrong place, easy to manually fix
  
All of the WARNINGs are to do with missing toctree which can be ignored.

**Comment by bashtage** [comment]
Doesn't fix notebooks in #3345 so that patch is needed too

**Comment by TomAugspurger** [comment]
Looks good to me, @josef-pkt ?

> graphics are output in the wrong place, easy to manually fix

Are these the graphics produced by code blocks, or just some static assets? What would fixing that entail?

**Comment by bashtage** [comment]
They come from code blocks using @savefig.  But it dumps them in docs/source and then the log shows a complaining about them not being somewhere else.

**Pull request merged**
