### PR TITLE
Just use pandas StataReader/StataWriter

### PR DESCRIPTION
**Pull request by jbrockmendel**
It's actually tested etc.

### CODE REVIEW

**Comment by bashtage** [comment]
+1 on this.  The pandas Stata code is very up to date and well tested.   I think the sm Writer will accept record arrays but this is likely an unused feature.

**Comment by jbrockmendel** [comment]
rebased

**Comment by ChadFulton** [comment]
Also +1 from me, I think it’s great when we can shift this stuff to Pandas

**Comment by josef-pkt** [comment]
@jbrockmendel general recommendation: test a PR locally at least for the directly affected unit tests before pushing that lowers the load on our CI.

**Comment by bashtage** [comment]
You can also setup your own travis against your fork and test branches before opening PRs.

**Comment by josef-pkt** [comment]
we had the discussion about how easy it is to  run
`pytest --pdb path-to-module-or-directory`

or even
```
import statsmodels.iolib as smio
smio.test()
```

:)

**Comment by bashtage** [comment]
IDD but sometimes you want to do easy cross-version testing and personal travis/appveyor can reduce the load on statsmodels. One can also cancel/restart/etc personal travis.

**Comment by jbrockmendel** [comment]
Closing to clear the queue until recarrays are removed

**Pull request closed without merging**
