### PR TITLE
fix indentation by four typos

### PR DESCRIPTION
**Pull request by jbrockmendel**
@josef-pkt fix it once, add it to CI, never worry about it again.

@cclauss if/when this is merged, can you add E111 and E114 to #4768 (or config-based version thereof) to keep it fixed until the end of time?

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@ChadFulton ping

**Comment by jbrockmendel** [comment]
@josef-pkt ping

**Comment by jbrockmendel** [comment]
@ChadFulton @josef-pkt so... are we just giving up?

**Comment by josef-pkt** [comment]
looks ok, I spot checked and don't expect merge tedious merge conflict with other PRs.

(Although I don't see the value for some of the whitespace cleanups, especially in sandbox `https://github.com/scipy/scipy/pull/8920` )

(I'm back from the beach, but will be two more days in France.)

**Comment by cclauss** [comment]
> I don't see the value for some of the whitespace cleanups

Python 3 treats them as Syntax Errors and halts the program.

**Comment by josef-pkt** [comment]
@cclauss  I don't think we have any tabs in our code, unless something slipped in. We never had problems with it and usually those are discovered during PR review.

I was thinking mainly of adding spaces to comments or commented out code in "irrelevant" files.  (But there are not a huge number of those cases, so I'm fine with it.)

**Comment by jbrockmendel** [comment]
> I was thinking mainly of adding spaces to comments or commented out code in "irrelevant" files. (But there are not a huge number of those cases, so I'm fine with it.)

There are a huge number of such cases, irrelevant files shouldn't be present, please avoid derailing, and I hope you have/had a nice vacation.

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel, @cclauss, and @josef-pkt!

**Comment by jbrockmendel** [comment]
Good teamwork folks.

@cclauss can you please add this to the lint checks so we can add this to the Never Worry About It Again pile?

**Pull request merged**
