### PR TITLE
Add CodeQL workflow

### PR DESCRIPTION
**Pull request by p-**
Hi `statsmodels/statsmodels`!

This is not an automatic, 🤖-generated PR, as you can check in my [GitHub profile](https://github.com/p-), I work for GitHub and I am part of the [GitHub Security Lab](https://securitylab.github.com/) which is helping out with the migration of LGTM configurations to Code Scanning.
You might have heard that we've integrated LGTM's underlying CodeQL analysis engine natively into GitHub. The result is [__GitHub code scanning__](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning)!

With LGTM fully integrated into code scanning, we are focused on improving CodeQL within the native GitHub code scanning experience. In order to take advantage of current and future improvements to our analysis capabilities, we suggest you enable code scanning on your repository. Please take a look at our [blog post for more information](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).

This pull request enables code scanning by adding an auto-generated [`codeql.yml` workflow file for GitHub Actions](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually) to your repository — take a look! We tested it before opening this pull request, so all should be working :heavy_check_mark:. In fact, you might already have seen some alerts appear on this pull request!

Where needed and if possible, we’ve adjusted the configuration to the needs of your particular repository. But of course, you should feel free to tweak it further! Check [this page](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#editing-a-code-scanning-workflow) for detailed documentation.

Questions? Check out the FAQ below!

### FAQ
<details>
<summary>Click here to expand the FAQ section</summary>

#### How often will the code scanning analysis run?
By default, code scanning will trigger a scan with the CodeQL engine on the following events:
* On every pull request — to flag up potential security problems for you to investigate before merging a PR.
* On every push to your default branch and other protected branches — this keeps the analysis results on your repository’s *Security* tab up to date.
* Once a week at a fixed time — to make sure you benefit from the latest updated security analysis even when no code was committed or PRs were opened.

#### What will this cost?
Nothing! The CodeQL engine will run inside GitHub Actions, making use of your [unlimited free compute minutes for public repositories](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions).

#### What types of problems does CodeQL find?
The CodeQL engine that powers GitHub code scanning is the exact same engine that powers LGTM.com. The exact set of rules has been tweaked slightly, but you should see almost exactly the same types of alerts as you were used to on LGTM.com: we’ve enabled the [`security-and-quality` query suite](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs) for you.

#### How do I upgrade my CodeQL engine?
No need! New versions of the CodeQL analysis are constantly deployed on GitHub.com; your repository will automatically benefit from the most recently released version.

#### The analysis doesn’t seem to be working
If you get an error in GitHub Actions that indicates that CodeQL wasn’t able to analyze your code, please [follow the instructions here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow) to debug the analysis.

#### How do I disable LGTM.com?
If you have LGTM’s automatic pull request analysis enabled, then you can [follow these steps to disable the LGTM pull request analysis](https://lgtm.com/help/lgtm/managing-automated-code-review#disabling-pr-integration). You don’t actually need to remove your repository from LGTM.com; it will automatically be removed in the next few months as part of the deprecation of LGTM.com ([more info here](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/)).

#### Which source code hosting platforms does code scanning support?
GitHub code scanning is deeply integrated within GitHub itself. If you’d like to scan source code that is hosted elsewhere, we suggest that you create a mirror of that code on GitHub.

#### How do I know this PR is legitimate?
This PR is filed by the official LGTM.com GitHub App, in line with the [deprecation timeline that was announced on the official GitHub Blog](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/). The proposed GitHub Action workflow uses the [official open source GitHub CodeQL Action](https://github.com/github/codeql-action/). If you have any other questions or concerns, please join the discussion [here](https://github.com/orgs/community/discussions/29534) in the official GitHub community!

#### I have another question / how do I get in touch?
Please join the discussion [here](https://github.com/orgs/community/discussions/29534) to ask further questions and send us suggestions!

</details>

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks for the PR

I approved the codeql workflow run, and it seems to have worked without problems

I see the results for query at
at https://github.com/statsmodels/statsmodels/security/code-scanning?query=pr%3A8509+tool%3ACodeQL+is%3Aopen

Is there a view of alerts by modules and folders as in LGTM, e.g. https://lgtm.com/projects/g/statsmodels/statsmodels/latest/files/statsmodels/stats/?sort=name&dir=ASC&mode=heatmap

and view for pull request changes by module

Having to go through all alerts separately is a lot of clicking.

I guess we should remove the linkexchange iframe in 
[statsmodels/datasets/scotland/src/scotland_devolution.html](https://github.com/statsmodels/statsmodels/pull/8509/files#annotation_6420008275)

**Comment by p-** [comment]
>Is there a view of alerts by modules and folders as in LGTM, e.g. >https://lgtm.com/projects/g/statsmodels/statsmodels/latest/files/statsmodels/stats/?sort=name&dir=ASC&mode=heatmap

>and view for pull request changes by module

No, that's unfortunately not possible (At least not yet).
What you could do to reduce the initial amount of alerts is to either remove the security query pack by commenting out the line starting with `queries`. Or you could exclude some specific queries from the analysis like as described [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#excluding-specific-queries-from-analysis). At a later point you could enable those queries/packs again.

**Comment by josef-pkt** [comment]
Thanks for the PR, merged

**Comment by josef-pkt** [comment]
@p- 

I asked a question on stackoverflow about excluding specific code lines from the check, i.e. mark as false positive.
https://stackoverflow.com/questions/74694174/can-we-mark-a-code-line-as-ignore-for-github-codeql

our example:
`is` versus `==` comparison
https://github.com/statsmodels/statsmodels/security/code-scanning?query=is%3Aopen+branch%3Amain+rule%3Apy%2Fcomparison-using-is

Our code has one mistake with wrong `is`, but the other 3 are intentionally using `is` to check that it is the same object and not just has the same value.
Check is to avoid memory duplication, or to verify that we have the correct object for inline modification.

**Comment by p-** [comment]
>I asked a question on stackoverflow about excluding specific code lines from the check, i.e. mark as false positive.
https://stackoverflow.com/questions/74694174/can-we-mark-a-code-line-as-ignore-for-github-codeql

I've found a similar **open** issue looking for an inline mechanism in the CodeQL issue tracker: https://github.com/github/codeql/issues/11427.

Instead of dismissing the alerts via UI, you could consider [excluding a query](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#excluding-specific-queries-from-analysis) from running or [exclude certain files](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan) from the analysis. (Admittedly, that's not quite the same.).

If you've found false positives we're happy if you tell us so via the UI. Alternatively, you could open an [issue in the CodeQL repo](https://github.com/github/codeql/issues/new/choose).

**Comment by josef-pkt** [comment]
Thanks,

Actually also the last case of `is` versus `===` was a false alarm. Unit tests failed after I switched.

The problem is that those cases are difficult to verify, Just from looking at the code it is impossible or very difficult to figure out the intention, same object or same value.

We don't really want to skip a rule like this, because LGTM or similar code analysis have found mistakes in the past. However, in the modules I checked now for a few rules with CodeQL or LGTM, the remaining warnings were false alarms or won't fix.

**Pull request merged**
