### PR TITLE
BLD/TST: Add coverage for Cython files

### PR DESCRIPTION
**Pull request by bashtage**
* Final version of #4035.
* Enables coverage of Cython files on all platforms. Only requires minimal changes to modernized setup.py.
* Adds tox support to simplify generating coverage reports with or without Cython. Can produce coverage using `tox -e cython-coverage` for coverage including Cython files or `tox -e coverage` for coverage without.
* Small improvements to coverage rc files.
* Squashed to a manageable number of commits.

### CODE REVIEW

**Comment by bashtage** [comment]
.coveragerc_cython should probably go in tools\ci or tools\coveragerc.  The only reason for the .coveragerc is that (I think) it gets automatically picked up by some coverage runners.  I don't think this is important.  I think .coveragerc_TYPE is easier to spot than .TYPE_coveragerc.

**Comment by josef-pkt** [comment]
Just to see if I understand correctly:
This provides the setup for cython coverage, but does not add it to the CI.
(test times did not increase)

can I merge this now?  (I'm not going to review this)

**Comment by jbrockmendel** [comment]
I,agree .coveragerc_foo is preferable to .foo_coveragerc, but internal consistency is a bigger concern.  Maybe change .travis_coveragerc to .coveragerc_travis? (I’m not clear on why a separate file is needed for that, but that’s a separate discussion).  Note that coverage can find settings in setup.cfg, which should be the default place when feasible.

**Comment by bashtage** [comment]
A follow up can move .coveragerc into setup.cfg and then we can eliminate .coveragerc.

**Comment by jbrockmendel** [comment]
> (and probably OSX, but not tested)

I'll be happy to help out with this one.

**Comment by bashtage** [comment]
@josef-pkt All green and ready.

**Pull request merged**
