### PR TITLE
Wold Representation

### PR DESCRIPTION
**Pull request by jbrockmendel**
The various methods/attributes in the AR/ARMA/ARIMA/VAR/... classes can be segmented based on what information is necessary in order to implement them.  e.g.:

aic?  --> needs degrees of freedom --> needs sample size
forecast_cov --> needs correlation structure of shocks (i.e. sigma_u)
mean --> _only_ needs intercepts and coefs

The idea behind `tsa.wold` is to separate out (and unify, and de-duplicate, and test) the subset of attributes/methods that depend _only_ on the non-stochastic Wold representation of AR/ARMA/...

Fairly thorough (self-contained) tests, none of which are smoke tests.

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request introduces 2 alerts and fixes 3 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-4a56a5b507f14dcc33491635225b3e5ea04f4474)

**new alerts:**

* 1 for __eq__ not overridden when adding attributes
* 1 for Inconsistent equality and hashing

**fixed alerts:**

* 2 for Redundant assignment
* 1 for Missing call to __init__ during object initialization

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
From a brief look this looks pretty reasonable to me. Is this some / mostly / all reorganization? How much of this is new?

**Comment by jbrockmendel** [comment]
> Is this some / mostly / all reorganization?

Mostly.  The main points are:

1) this is to my taste "the right" level of abstraction for these classes and

2) it is a subset of code and tests that:
    a) I have gone over fairly carefully, whereas large portions of non-statespace tsa are relatively unmaintained (discussed in #3884).
    b) Is mostly self-contained, so can be thoroughly tested in isolation.

I think there is a non-trivial change that I should revert that returns empty arrays instead of np.nan for `arfreq` and `mafreq`.

There are a couple of TODO notes that could use a look from a fresh pair of eyes:

1) In `arroots` and `maroots` there's a question about whether the docstrings should say """Roots of lag-polynomial""" or """Inverse of roots of lag-polynomial"""
2) The normalization  by sqrt(2pi) in `arma_periodogram` needs checking/a reference.  There's a note in the docstring asking for a reference.

**Comment by josef-pkt** [comment]
Note #3482 arima process recently got a cleanup and better unit test coverage

**Comment by josef-pkt** [comment]
very superficial skimming only

parts are fine but overall I'm vaguely skeptical. Mainly this adds an additional layer and module, with what was mainly supposed to be covered by the ARMA and VAR process classes.
Some common structure between models can be separated out, but my first impression is that this makes it more difficult to figure out what various models are or should be doing.

**Comment by jbrockmendel** [comment]
@josef-pkt 

> Mainly this adds an additional layer and module

The non-stochastic representation is a layer that is _already_ present in AR/ARMA/ARIMA/VAR/SVAR/... De-duplicating them reduces the amount of code to maintain, makes it easier to maintain internal consistency, and clarifies the relationships between them.  Moreover, because this is a carefully-thought-out level of abstraction, it is almost entirely independent of other layers, so can be _thoroughly tested_ in _isolation_ of those other layers.

You want to finally bury `test_arima111_predict_exog_2127` #3980 once and for all?  So do I.  So let's isolate the problem by testing the ever-loving shit out of the building blocks.  Using teamwork!

I'm pretty frustrated by what I perceive to be an inconsistency between "My main criterion for code style and cleanliness is how long it takes me to understand a piece of code" and an unwillingness to consider/allow/delegate incremental improvements specifically tailored to be be trivially-verifiable.  On the flip side, it was only a [few weeks ago](https://github.com/statsmodels/statsmodels/issues/3884) that someone was saying that ar_model/arma_model/... are basically un-maintained and gee wouldn't it be nice if someone stepped up to take responsibility for them (not to mention varma_process/arme_mle/...).

Not interested in going in circles on this.  Closing.

**Comment by josef-pkt** [comment]
This pull request introduces 2 alerts and fixes 3 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-34da0d96877f36c8fecf0e6e1d3c5ea3485b9550)

**new alerts:**

* 1 for __eq__ not overridden when adding attributes
* 1 for Inconsistent equality and hashing

**fixed alerts:**

* 2 for Redundant assignment
* 1 for Missing call to __init__ during object initialization

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
> someone was saying that ar_model/arma_model/... are basically un-maintained

If you can show me how it help closing existing bugs, then I'm much more interested in reviewing it. For example based on the number of open issues, problems and missing support, I think ARIMA/... predict needs a refactoring that might help to fix and close several bugs, and make the code easier to understand. 
I'm also sure that there are several post-estimation hypothesis or specification test that can be put into a central place that then can be reused by ARIMA (unit variate versions) VAR (multivariate versions) and statespace models that need both.

> this is to my taste "the right" level of abstraction for these classes

My/our thinking (years ago) was that `estimation class` - `results class` - `process class` was the right level of abstraction, with delegation between the three, and some outsourced functionality and specials like IRFAnalysis.

**Pull request closed without merging**
