### PR TITLE
MAINT: statespace cleanup, alphabetically

### PR DESCRIPTION
**Pull request by jbrockmendel**
@ChadFulton this is the second of three statespace branches that have been sitting ready to go for a while, then I'll stop creating more work for you.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@bashtage additional failure mode `ssl.SSLError` for `get_rdataset`.

**Comment by bashtage** [comment]
TBH I don't really see the point of switching existing assert_ to assert or assert_equal to assert A == B.  It creates a lot of churn and there is effectively 0 gain since NumPy will never drop these functions. 

I'm more positive about pytest.raises since this produces more natural function calls.

**Comment by jbrockmendel** [comment]
I didn't count, but many of the asserts are for `assert foo is None` which is a strict (albeit small) improvement over an equality check.  Many others are for regex boolean checks which are really non-idiomatic in the status quo.  For the other cases, I'll keep your comment in mind for future branches.

**Comment by ChadFulton** [comment]
@jbrockmendel sorry about the delay, but TBH you make it somewhat difficult to consider whether or not to accept some of these PRs because you mix things like easy-to-commit pep8 improvements with opinion-based code changes like using the `pytest.raises` context.

I'm undecided here.

**Comment by jbrockmendel** [comment]
You do you buddy.  I just wanted to get this up so it doesn’t rot during my next leave of absence.

**Comment by ChadFulton** [comment]
Just so you know where I'm coming from:

- I would have accepted a pep8 improvement patch and / or one that replaced `assert_equal` with `assert` or `assert_`
- I would have rejected a patch that removed `assert_raises`.

Since you don't seem to be in a compromising mood, we'll close this for now.

**Comment by jbrockmendel** [comment]
Totally happy to compromise, will put together flake8-only version.

Out of curiosity, any idea why the `temp_filename` fixture in test_save is needed?  Doesnt NamedTemporaryFile do exactly the same thing?

**Comment by jbrockmendel** [comment]
in test_mlemodel.test_score_analytic_ar1 approx_fd_centered is defined but never used.  im going to make the opinionated edit and decide it was intended to be part of the assertion in the following line

**Pull request closed without merging**
