### PR TITLE
ENH: Statespace: New / improved Kalman filter, smoother, simulation smoother

### LINKED ISSUE #2761: ENH: Statespace: New / improved Kalman filter, smoother, simulation smoother
Currently the state space library in Statsmodels has a Cython-based conventional Kalman filter and a pure-python conventional Kalman smoother. This issue collects notes about integrating the following features (references to DK refer to Durbin and Koopman, 2012); all features are in Cython:

- State smoother (DK 4.4)
- Disturbance smoother (DK 4.5)
- Simulation smoother (DK 4.9)
- Univariate treatment for all of the above (Kalman filter, state smoother, disturbance smoother, and simulation smoother) (DK 6.4)
- Collapsed treatment, used with large observation vectors, for all of the above (DK 6.5)

These features have already been written and can be found at https://github.com/dismalpy/dismalpy/tree/master/dismalpy/ssm in the Cython files. I have a working paper describing the use of the state space library when these features are available which can be found at http://pages.uoregon.edu/cfulton/files/fulton_dismalpy_2015.pdf; essentially the plan would be to Find/Replace "DismalPy" with "Statsmodels" once these changes are integrated.

Benefits include:

- Allows multivariate models with many (hundreds) endog variables (univariate and/or collapsed approaches)
- Allows fast simulation of or sampling from any state space time series process (simulation smoother)
- Required for possible future implementations of EM algorithm (fast smoother)
- Required for possible future implementation of analytic score (fast smoother)
- Required for some types of Bayesian estimation like Gibbs sampling (simulation smoother)

There are a couple of challenges that will have to be dealt with:

- Dependencies: these features require a more recent Scipy than is required by Statsmodels generally, so these won't (immediately) replace the existing state space code but will have to reside alongside it.
- Build process: right now these libraries use custom Cython definitions for the Fortran BLAS/LAPACK functions, but recently Scipy incorporated all of these definitions into the main package (https://github.com/scipy/scipy/pull/4021), so it might be nice for future maintenance to use theirs as long as Scipy 0.16.0 could be used as the base dependency.

These would probably be integrated slowly and across several PRs so that each step could be well-tested.

### PR DESCRIPTION
**Pull request by ChadFulton**
Closes #2761. See that issue for an overview. Basically, the improvements amount to:

- Perfomance improvements (Cython-based smoother and stationary initialization for the filter)
- New filter methods (univariate, collapsed; both help in the case of a large number of endogenous variables)
- A simulation smoother (faster time series simulation, possibility of Gibbs-sampling)
- The new Cython files should be easier to maintain and extend.

This PR cleans up and augments the state space component written in Cython. Notes on the new cython files:

- Uses the Cython blas and lapack wrappers in Scipy >= v0.16, so we can avoid writing our own wrapping code
- Modularizes the Cython files (rather than sticking everything into one giant Cython file), which allows "plugging in" different filtering and smoothing algorithms (e.g.  univariate vs the conventional)

With this PR there would be two versions of state space "backends" (the Cython-based filtering, smoothing, etc.) served by a single "frontend" (the python-based classes with which users interact).

The two backends are fully compatible, except that the newer one has more features. Thus the frontend classes only needs to check to make sure older systems don't try to use features that are only available with the new backend. Similarly, a single set of unit tests serve both backends, except that the tests with the newer features are only run if those features are available.

The new Cython files cannot be built when the user has Scipy < 0.16, so the `setup.py` file builds a list of exclusions based on the availability of `scipy.linalg.cython_blas` so the `cythonize` script can skip them.

At runtime, the same check (`scipy.linalg.cython_blas`) is used to select the appropriate backend.

### CODE REVIEW

**Comment by ChadFulton** [comment]
There will be some bse failures in Travis, but those will be fixed by the changes from #2844.

**Comment by josef-pkt** [comment]
All green.

just remembered: please use BSD-3 as license shortcut, i.e. 3 clause BSD. `simplified` or `modified` is confusing, and part of the code was for a while BSD-2 because of that confusion.

simplified is BSD-2 while statsmodels used "modified"  https://en.wikipedia.org/wiki/BSD_licenses

**Comment by ChadFulton** [comment]
Good to know, I'll revise the license.

I'm not quite sure what to do with this PR since it's so big. If you have time, the most important things to review might be the changes to `setup.py` and `tools/cythonize.py` allowing exclusions to cythonization, and the conditional selection of the state space classes at the top of `statsmodels/tsa/statespace/models/tools.py` in the `set_mode` function.

**Comment by josef-pkt** [comment]
I don't have much experience with cython, at least not in details.

I will look at it. My main question when I saw this was how robust it is and whether we should merge it for 0.8 or if it needs a longer trial period in master. Assuming 0.8 will be released in something like 3 weeks.

**Comment by josef-pkt** [comment]
@sturlamolden Do you have time and interest to have a brief look at the conditional cython usage?

**Comment by ChadFulton** [comment]
> I will look at it. My main question when I saw this was how robust it is and whether we should merge it for 0.8 or if it needs a longer trial period in master. Assuming 0.8 will be released in something like 3 weeks.

My preference would be to get it in to 0.8, simply because I'd like to try and publish a paper about it sooner than later and would like to include some of these features :)

But obviously it's not good for anyone if the features are in and buggy. I'll work on expanding unit tests and examples, and if it works to get it in that's great. If it doesn't get it, that's not really a big problem either.

**Comment by springcoil** [comment]
I'd recommend some separation of these PR's because it is so big. The Cython code seems to be worthy of a PR all in itself and the other code. I'm not overly familiar with Cython myself but if you could start with some questions which you want to be resolved we could maybe move forward quicker.

**Comment by sturlamolden** [comment]
The use of tempita doesn't make the Cython code nice to read. I am not sure I even want to try 😬

**Comment by ChadFulton** [comment]
> I'd recommend some separation of these PR's because it is so big. The Cython code seems to be worthy of a PR all in itself and the other code.

Separating this into multiple PRs might make make sense, but maybe into separate PRs for the improved Kalman filter, new Kalman smoother, and new Simulation smoother, rather than into Cython vs Python. That's because the Python changes are only to allow for the new Cython code, if that makes sense.

> I'm not overly familiar with Cython myself but if you could start with some questions which you want to be resolved we could maybe move forward quicker.

My main concern is that the particular way that things are being built in `setup.py` will cause problems that I'm not aware of. The problem is that the new files cannot even be built without scipy >= 0.16, so we need some code to prevent trying to build them in the other case. But I don't know if the way I did it will cause any problems for things I don't know much about (Windows builds? binaries? wheels? other?).

**Comment by ChadFulton** [comment]
> The use of tempita doesn't make the Cython code nice to read. I am not sure I even want to try

No problem, thanks for having a look! It would be really great to get your input on the build issues I mentioned above, which hopefully won't require too much Tempita-parsing. If you do find time to look at the Cython, I'm sure you'll find lots (*lots*) of things that could be improved.

**Comment by ChadFulton** [comment]
The regime switching GSoC project will need some of the features implemented in this PR. Rather than merge this PR into master or have Valera work off of my fork, I think it would be good to make a new feature branch with this code in the primary statsmodels repository.

**Comment by ValeryTyumen** [comment]
Hi, me and Chad decided that my GSOC work will be based off of this PR, mostly because Kim Filter uses Kim-Nelson timing convention in Kalman Filter routine, which is implemented here.

**Comment by ChadFulton** [comment]
Substantially increased testing coverage and fixed a number of bugs related to these enhancements.

**Comment by ChadFulton** [comment]
Here are the coverage statistics under the new smoothing methods. `tools` is actually higher than it looks, because part of it is only tested if the Cython versions of some tools are not available.

    statsmodels.tsa.statespace.dynamic_factor       512 1   0   99%
    statsmodels.tsa.statespace.kalman_filter        535 9   0   98%
    statsmodels.tsa.statespace.kalman_smoother      182 4   0   98%
    statsmodels.tsa.statespace.mlemodel             830 19  0   98%
    statsmodels.tsa.statespace.representation       272 2   0   99%
    statsmodels.tsa.statespace.sarimax              753 6   0   99%
    statsmodels.tsa.statespace.simulation_smoother  164 7   0   96%
    statsmodels.tsa.statespace.structural           586 19  0   97%
    statsmodels.tsa.statespace.tools                466 57  6   88%
    statsmodels.tsa.statespace.varmax               388 6   0   98%

**Comment by ChadFulton** [comment]
Rebased on master.

From this thread so far, I assume this won't make it into 0.8. But I have used the improved versions to successfully produce and defend a dissertation :) and @ValeryTyumen has so far been using the improved versions for his code (and I think everything has been fine, let me know if not).

It can either be merged now or else it can wait for 0.9; either way I don't have anything "on my list" for it.

**Comment by josef-pkt** [comment]
I still don't know whether we should merge it for 0.8.

But, it looks like we might have at least 1.5 months in the `0.8rc` phase before a final release. If you are available during summer to fix bugs that might show up, then I think we can merge this.
The main testing for this will be most likely on Debian testing which uses a large number of diverse machines. appveyor is happy with it.

**Comment by josef-pkt** [comment]
If you rebase again, then you should get green on all Travis versions.

**Comment by ChadFulton** [comment]
All green (except coverage, which is misleading since the coverage machine is older and can't test the new features, so they're not "covered").

Really it doesn't matter too much, and 0.8 might just be too early for merging such a big PR (18,000 lines).

If we don't merge it now, then it would be good to have some sort of roadmap for how it could be reviewed / tested better, so that it doesn't just waste away (e.g. if there is a way to do some kind of general machine testing without having it merged for the rc, that would be a good goal I could work towards as well). I'll be around to fix issues during release process if they come up whether or not it's merged.

**Comment by josef-pkt** [comment]
The main problem is that our release planning and timing is awful.

My preferred way to handle this, especially given the lack of reviewers, would be to merge it right after a release so we have it for some time in master to see if anyone is running into problems. TravisCI and appveyor are green. If it's in master, then we also get Ubuntu 32bit and 64bit testing automatically. We have access to Mac testing through nipy @matthew-brett but I haven't tried this yet.

The main problem will be Debian, where, a long time ago, I had to debug various problems that only showed up on ARM processors, or something like that. 
Debian might also be more difficult if they change things to adapt it to their own packaging. However, I don't know any details about that nor whether conditional compilation would cause problems. @yarikoptic is taking care of Debian issues for us.

**Comment by ChadFulton** [comment]
Sounds fine to me, lets plan to merge after release.

**Comment by josef-pkt** [comment]
@ChadFulton  I would like to keep master on 0.8 for another week, so we have a bit of time to see if there any problems with the rc1 (and while I'm at the beach with limited internet access).

After that I think we can start with merging 0.9 things into master.

**Comment by ChadFulton** [comment]
1. Should I plan to merge this soon?
2. Coverage doesn't really fall here, except that the coverage setup has an old Scipy that does not allow testing the new things that rely on later Scipy versions.

**Comment by ChadFulton** [comment]
I guess if these results come back green, I will plan to merge this tomorrow, unless there are concerns.

**Comment by ChadFulton** [comment]
This is green except for the unrelated IO errors. I will merge later today.

**Pull request merged**
