### PR TITLE
[MAINT] move misplaced test_tsa_indexes

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@ChadFulton your domain

**Comment by ChadFulton** [comment]
LGTM, looks like I waited too long and it needs to be rebased, otherwise happy to merge

**Comment by jbrockmendel** [comment]
rebased

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel

**Pull request merged**
