### PR TITLE
Fix Yule Walker to handle singular matrices

### PR DESCRIPTION
**Pull request by jeffhandl**
Written to respond to this issue: https://github.com/statsmodels/statsmodels/issues/8363

- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by bashtage** [comment]
Should probably be `@` not `*`. Overall, I'm not sure about this in general since YW isn't identified when the matrix is singular.  Might be better to raise an explicit exception.  Do you think the solution given by pinv is useful when singular?

**Comment by michaelbrundage** [comment]
There are extensions of YW to the singular case, for example https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1907039
An alternate implementation would be to wrap the original `solve()` line with a try/except, log a warning when the except branch is taken and fall back on `pinv()` in that case.

**Comment by josef-pkt** [comment]
This might be an uncommon enough case that we should warn users.

e.g. try except with solve
if singular, then warnings.warn with message like "matrix is singular, using pinv", and then use pinv

This should make it into 0.14 in the next few days.

**Comment by josef-pkt** [comment]
rewritten and merged in #8567

@jeffhandl @michaelbrundage Thanks for PR and comments

**Pull request closed without merging**
