### PR TITLE
Allow remove_data to work when an attribute is not implemented

### LINKED ISSUE #7510: BUG: remove_data faills if model has non-implemented attributes with cache
#### Describe the bug

If there is a non-implemented attribute in the model with cache, `remove_data` fails at `getattr` call in L2224 of model.py.
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/base/model.py#L2224

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.regression.quantile_regression import QuantReg

X = np.array([[1, 0], [0, 1], [0, 2.1], [0, 3.1]], dtype=np.float64)
y = np.array([0, 1, 2, 3], dtype=np.float64)
res = QuantReg(y, X).fit(0.5)
res.remove_data()
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

The code does not raise `NotImplementedError`

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.9.2.final.0
OS: Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: v0.13.0.dev0+391.g3f6fa5599 (/home/mknz/dev/statsmodels/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.20.3 (/home/mknz/dev/statsmodels/env/lib/python3.9/site-packages/numpy)
scipy: 1.6.3 (/home/mknz/dev/statsmodels/env/lib/python3.9/site-packages/scipy)
pandas: 1.2.4 (/home/mknz/dev/statsmodels/env/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.1 (/home/mknz/dev/statsmodels/env/lib/python3.9/site-packages/dateutil)
patsy: 0.5.1 (/home/mknz/dev/statsmodels/env/lib/python3.9/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.4.2 (/home/mknz/.pyenv/versions/3.9.2/lib/python3.9/site-packages/matplotlib)
    backend: TkAgg
cvxopt: Not installed
joblib: 1.0.1 (/home/mknz/.pyenv/versions/3.9.2/lib/python3.9/site-packages/joblib)

Developer Tools
================

IPython: 7.23.1 (/home/mknz/.pyenv/versions/3.9.2/lib/python3.9/site-packages/IPython)
    jinja2: 3.0.0 (/home/mknz/.pyenv/versions/3.9.2/lib/python3.9/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.9.0 (/home/mknz/.pyenv/versions/3.9.2/lib/python3.9/site-packages/pygments)
pytest: 6.2.4 (/home/mknz/dev/statsmodels/env/lib/python3.9/site-packages/pytest)
virtualenv: 20.4.6 (/home/mknz/.pyenv/versions/3.9.2/lib/python3.9/site-packages/virtualenv)

</details>

### PR DESCRIPTION
**Pull request by mknz**
- [x] closes #7510
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by josef-pkt** [comment]
I need to think whether we shouldn't delete the `getattr` call completely.
This PR looks good, but I don't agree with the underlying access to trigger the lazy evaluation.

Creating extra results statistics for caching is the responsibility of the user.
For the most common use case which is prediction, which motivated the initial implementation, we don't want to compute unnecessary attributes.

This was changed from the original design in #4421

Also I would like to understand why this breaks in the example. 
AFAIU the code it should only affect existing `value_attrs`

**Comment by mknz** [comment]
To me it sounds better if `getattr` can be removed as you said. I was wondering why the lazy evaluation is needed in the first place.

In the example, `QuantReg` has an attribute which is just a placeholder and raises  `NotImplementedError` within.
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/regression/quantile_regression.py#L324

If I understood correctly, the evaluation happens here when the attribute is accessed by `getattr`. Then it raises.
https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/properties.pyx#L37

**Comment by josef-pkt** [comment]
It looks like the distinction between `data` and `value` was another refactoring victim
https://github.com/statsmodels/statsmodels/pull/6056/files#diff-caa0f13bb4c8b24512745dc6ef3d5eb4781a45610dd793ed488e0ece329b6759
with code comments

statsmodels.tools.decorators has

```
cache_readonly = PandasCacheReadonly
cached_data = PandasCacheReadonly
cached_value = PandasCacheReadonly
```

so isinstance check will not be able to distinguish those, they are all the same.

my guess now is that we can remove most of the changes in https://github.com/statsmodels/statsmodels/pull/4421/files#diff-c2e43dabd342f05e2182ad2049b555adfdd6522147c186421f7743a7be871794R2123

and go back to the original behavior.

One question is whether we can still do something useful with `cls_attrs`, the list of attributes that have a cache decorator.

My reading now of the current behavior is that it sets all `cache_xxx` to None, even those that are just scalars, e.g. check if llf is still available. That would be an extra bug that affects more use cases.

**Comment by josef-pkt** [comment]
I don't want to spend the time now to revert whatever we can from #4421

direct fix for current problem is to remove the getattr, IIRC.
I will open a PR with just that, and see how that goes

**Comment by josef-pkt** [comment]
@mknz  you could make the change in this PR
just delete the two lines instead of adding the try except
```
        for name in value_attrs:
            getattr(self, name)
```

**Comment by mknz** [comment]
@josef-pkt 
Thanks for the suggestion. I made the change and also removed this part because `value_attrs` is not used anymore.
```
        value_attrs = [x for x in cls_attrs
                       if isinstance(cls_attrs[x], cached_value)]
```
This change caused  `regression/tests/test_rolling.py` to fail. It is because `RollingRegressionResults.remove_data` lacks `self._cache = {}` in `__init__` So I added it.

**Comment by josef-pkt** [comment]
looks good, thanks.

I will merge when green, unless you see some other changes related to this.

**Comment by josef-pkt** [comment]
@mknz Thanks for the bugfix and PR

**Comment by mknz** [comment]
@josef-pkt Awesome, thanks for the review!

**Pull request merged**
