### PR TITLE
FIX: Check for trend type in VAR models

### LINKED ISSUE #2271: BUG VAR fit with trend='t' raises exception
with example from tutorial 

```
model_t = VAR(data_t)
results = model.fit(4, trend = 't')

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-98-f7328095d596> in <module>()
      1 model_t = VAR(data_t)
----> 2 results = model.fit(4, trend = 't')

e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\tsa\vector_ar\var_model.py in fit(self, maxlags, method, ic, trend, verbose)
    429                 lags = 1
    430 
--> 431         k_trend = util.get_trendorder(trend)
    432         self.exog_names = util.make_lag_names(self.endog_names, lags, k_trend)
    433         self.nobs = len(self.endog) - lags

e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\tsa\vector_ar\util.pyc in get_trendorder(trend)
     45     elif trend == 'ctt':
     46         trendorder = 3
---> 47     return trendorder
     48 
     49 def make_lag_names(names, lag_order, trendorder=1):

UnboundLocalError: local variable 'trendorder' referenced before assignment

```

### PR DESCRIPTION
**Pull request by saketkc**
Fixes #2271
Also, see #2327

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks, looks good for 2271

One extra check that I just remembered, it has been several years since I worked on this. I remember for some functions `trend order` could be given as a string or as an integer.

Is `trend` allowed to be an integer? Just try an example with the master version `trend=1`.

**Comment by saketkc** [comment]
I don't think so. But it is not difficult to do so:
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/util.py#L37
This should be called only if `trend` is not an integer.  Though, I am not convinced it is a good idea to do so, since it leads to incoherency.

**Comment by josef-pkt** [comment]
Yes, I think trend as integer is a similar problem that it is supported in some pieces but not in others.
It's better to raise the ValueError.

**Comment by josef-pkt** [comment]
merged, thanks @saketkc

**Pull request merged**
