### PR TITLE
ENH: Alternative exponential smoothing approach

### PR DESCRIPTION
**Pull request by ChadFulton**
This PR presents an alternative approach to the exponential smoothing models along the lines of my comment https://github.com/statsmodels/statsmodels/pull/3817#issuecomment-340336637.

I want to emphasize that we do not have to use my version, and I am perfectly happy with working with / improving the version currently in Statsmodels. However, in my mind, the version in this PR is more in line with the way most models are done in Statsmodels, and, at least to me, it is more straightforward

It has the added benefit of Cython-based recursions, but of course we could possibly retrofit the current version with Cython also.

@tvanzyl any thoughts you have would be appreciated, and don't hesitate to be critical.

Remaining TODOs:

- [ ] For complex models (e.g. the seasonal models), the optimizer doesn't seem to be able to find parameters that are as good as Hyndman's R package, although this also seems to be the case with the version currently in Statsmodels.
- [ ] more unit test coverage
- [ ] replicate the example notebook

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request introduces 2 alerts and fixes 2 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-6ca30e072c645f251d01e27b2a60f406f2cd5f1f)

**new alerts:**

* 1 for Mismatch between signature and use of an overridden method
* 1 for Potentially uninitialized local variable

**fixed alerts:**

* 2 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
I think we leave this for 0.10 so we have time to decide on the design and whether we want one or two versions.

AFAICS: the merged version has as extra features box-cox transformation and fixing some parameters.

**Comment by ChadFulton** [comment]
That sounds fine. 

> AFAICS: the merged version has as extra features box-cox transformation and fixing some parameters.

That is correct.

**Comment by ChadFulton** [comment]
Since we already have fast working code in Statsmodels, I'll just close this and put this approach in a separate package. Of course we can revisit later if there's any reason to.

**Comment by josef-pkt** [comment]
I thought I had replied here (below is roughly what I had written before).

I think it would be good to have a full Model for it in statsmodels, one that has the usual results based on a MLE or QMLE.
The current exponential smoothing will be a forecasting tool, but the full model will provide more results, diagnostics and inference.

There are other places where we have different classes for the same or overlapping underlying models like GLM/discrete/OLS,

**Pull request closed without merging**
