### PR TITLE
CLN: E131 hanging indentation alignment

### PR DESCRIPTION
**Pull request by jbrockmendel**
One of the codes with only a small number of remaining violations.

### CODE REVIEW

**Comment by bashtage** [comment]
This is mostly test code.  These are more difficult when they actually start touching human-facing code.  The only changes of this type are in areas that can't have bugs, so that type is ok.

**Comment by jbrockmendel** [comment]
Some stats on remaining violations for game-plan purposes:

The files with the most remaining violations are, in order:
 - sandbox.tsa.garch (606) I'd prefer to see the contents of this file replaced with "just use `arch`"
- tsa.tests.test_arima (522)
- discrete.discrete_model (455)
- sandbox.stats.multicomp (453) Since this is used outside of sandbox, I'm making an effort to clean up the used parts and get them out of sandbox.  Most of it is deleteable.
- [... and 24 files with 1 violation apiece, 22 with 2 violations apiece]

There are 25007 remaining violations.  The most common codes are:
- E231 missing whitespace after ',' (6189, includes about 200 for missing whitespace after ':')
- E265 block comment should start with '# ' (4431)
- E501 line too long (4085)
- E128 continuation line under-indented for visual indent (1560)
[...]
- E116 unexpected indentation (comment) (61)
- E115 expected an indented block (comment) (58)
- W605 invalid escape sequence (48)
- E722 do not use bare 'except' (47)
- E701 multiple statements on one line (colon) (40)
- E741 ambiguous variable name 'l', 'I', 'O' (30)
- F821 undefined name 'condent' (15)

My inclination at this point is to focus until the release on F821, sandbox isolation, and salvaging examples.  Thoughts/suggestions?

**Comment by bashtage** [comment]
F821 is a straight bug fix it sounds like. 
E741 with some caution and noqa. 
E722 maybe never, or just noqa.
W605 - aren't these heading to become a bug?
I have E701 but might not be worth it.

**Comment by jbrockmendel** [comment]
F821: agreed.  The trouble is that the remaining ones all involve some level of guessing the original author's intent, and in most of them they are places where deleting the unused code is an attractive option.
E741: same page
E722: many of these are `ImportError` or `(ValueError, TypeError)`.  For the rest, the fact that they are non-obvious points to it being worthwhile to figure them out.  At the very least these should be `except Exception:` so we don't catch `KeyboardInterrupt`.
W605: Yes.  The last of them are all in a sandbox formula example.  5692 gets rid of them.

**Comment by josef-pkt** [comment]
I will revert any changes to multicomp, diagnostics or similar.

We are doing statistics and econometrics here and not a code cuteness contest.
It took me a month or three to figure out this "deletable" parts, and there are still many parts that I have not figured out yet.

**Comment by josef-pkt** [comment]
There is a network algorithm for closed tests that is available in R and described in the book for R multiple comparisons. I have not tried to figure that out.
It would be a great contribution to multiple comparison or multiple testing.

**Comment by josef-pkt** [comment]
The reference for fractional polynomial in Stata mentions that they use a closed test for maintaining the size when searching for the number of polynomial terms to include. I didn't try to figure that out either, the description was a bit vague.
There are no fractional polynomials in statsmodels, or, AFAIK in python.

**Comment by josef-pkt** [comment]
There is also a new issue #5741 if someone wants to figure out how to go from the formula information in design_info to multiple comparison.

**Pull request merged**
