### PR TITLE
FIX failure caused by #5076

### PR DESCRIPTION
**Pull request by jbrockmendel**
@ChadFulton

### CODE REVIEW

**Comment by rgommers** [comment]
The codecov failure is bogus. I would recommend to set the codecov target to 1% so it never fails (there are way too many false positives otherwise). This is what we do for SciPy.

**Comment by jbrockmendel** [comment]
@ChadFulton little help?  The problem this fixes is causes false-positives for _all_ Travis runs.

**Comment by ChadFulton** [comment]
I suppose we should merge this fix so that Travis is green, but this is not my code and so I don't think I'm the right one to ping on this PR.

**Comment by rgommers** [comment]
All right, I'll be assertive and merge this - it's just whitespace after all, and fixes an issue:)

**Comment by ChadFulton** [comment]
Thanks! :)

**Comment by josef-pkt** [comment]
I had misunderstood the failure in my PR and master

merging

**Comment by josef-pkt** [comment]
(I'm too slow, I had to go and check the cooking meat roast)

**Comment by jbrockmendel** [comment]
> The codecov failure is bogus. I would recommend to set the codecov target to 1% so it never fails 

@rgommers +1 on this.  It’ll take some more peer pressure to make this a reality.

**Pull request merged**
