### PR TITLE
DOC: 0.9 release notes for refactored state space models / tsa indexes / exponential smoothing

### PR DESCRIPTION
**Pull request by ChadFulton**
I can expand on these if we prefer more verbose notes.

### CODE REVIEW

**Comment by ChadFulton** [comment]
I also added a brief note about exponential smoothing. @tvanzyl please feel free to write your own if you prefer, or else I can edit it myself if you prefer not to make your own PR.

**Comment by tvanzyl** [comment]
Happy with your short note. Thank you.

**Comment by ChadFulton** [comment]
Thanks for taking a look @tvanzyl

**Comment by ChadFulton** [comment]
I've added a release note for the frequency-domain seasonals in `UnobservedComponents`. Please let me know if there is more you'd like to add or anything that I got wrong, @Noobivsho.

**Comment by ChadFulton** [comment]
Forgot to include PR # and attribution for freq-domain seasonals.

**Comment by Noobivsho** [comment]
Thanks, Chad.  You are very generous with your attribution.

**Comment by josef-pkt** [comment]
I'm merging this, so I can start to combine release notes with draft notes

**Pull request merged**
