### PR TITLE
FIX: Allow statespace models to be pickled in Python 3.6

### PR DESCRIPTION
**Pull request by bashtage**
Minimal patch to allow pickling.
Likely is not correct in the sense that the pickled objects would
not behave the same after pickling.

### CODE REVIEW

**Comment by bashtage** [comment]
Fixes on Python 3.6. Probably doesn't contain enough to actually correctly run the three objects that can now be pickled since there is a lot of state.  Correct method will require `__reduce___` and `__setstate__` to be defined so that the class can be initialized and then any state that can change can be restored.

**Comment by bashtage** [comment]
Pinging @ChadFulton

**Comment by ChadFulton** [comment]
If this fixes the tests, then that sounds great to me.

**Comment by bashtage** [comment]
Unfortunately pickling is much harder than this. Probably not worth it.

**Comment by bashtage** [comment]
I think it words correctly now.  I probably copied more state that was strictly necessary since I wasn't sure what should persist across iterations and what was strictly temporary.

**Comment by bashtage** [comment]
@ChadFulton I think this is ready.  Would be helpful if you could check the variables that I save in `state` in the method `__reduce__`.   If any of these don't need to be saved, I could reduce the size of the pickle.  For example, I am even saving temporary arrays which I suspect are always over written when used.   But in case they are not, it seemed safer to save them. 

I might make one final commit where I add the pickle tests to their own file `test_pickle.py`

**Comment by bashtage** [comment]
closes #3401

**Comment by bashtage** [comment]
@josef-pkt as long as @ChadFulton is happy with this, then it is ready.

**Comment by josef-pkt** [comment]
Thanks, merging,
test failures are unrelated to this

**Comment by bashtage** [comment]
You need to use master.

**Comment by nruchika21** [comment]
Master of what ?

**Comment by bashtage** [comment]
Master version of stats models from github.com.

**Comment by nruchika21** [comment]
I am using what comes with python 3.6, How do I use the master version ?

Thanks,
Ruchika

**Comment by bashtage** [comment]
Somethin like

pip install git+https://github.com/statsmodels/statsmodels

This requires you to a compiler for your version of Python.

**Pull request merged**
