### PR TITLE
remove unused imports; fix gratuitous flake8 errors

### PR DESCRIPTION
**Pull request by jbrockmendel**
Can we please fix this small fraction of flake errors (565 remaining!)?  The indentation crud in the docstrings is really annoying.

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request fixes 1 alert - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-db85af44f8b74b5e4769d36ace993183956e89b7)

**fixed alerts:**

* 1 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by bashtage** [comment]
@josef-pkt LGTM

**Comment by josef-pkt** [comment]
This pull request fixes 1 alert - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-092c06a0985d275051b5c690732026e679adf7cb)

**fixed alerts:**

* 1 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
@josef-pkt coveralls error is a dummy; this should be good to go.

**Comment by josef-pkt** [comment]
rebase looks good, the doc build will need checking to see whether the whitespace correction in the docstrings don't cause problems.

merged

@jbrockmendel @bashtage  Thank you

**Comment by jbrockmendel** [comment]
@josef-pkt Thanks for getting to this; the whitespace in those docstrings was surprisingly bothersome.  If offering checking the doc build will make these maintenance PRs more frictionless for you, then sign me up.

You mentioned "rebase looks good" here and elsewhere.  That's got me thinking: does something distinctive about your workflow make merging more complicated than hitting an "accept" button here on GH?

**Comment by josef-pkt** [comment]
Compared to other packages we don't squash and fast-forward merge automatically, which I think pandas is doing. We merge the branch as is without fast forward. github doesn't have an option to rebase-squash -> merge no-ff.

When we had less than 1000 forks, then https://github.com/statsmodels/statsmodels/network showed the branch tree. github doesn't show the parent in master at which a branch has forked.

Now if I want to see the history, I need to check out the PR branch and look at it with git gui.
This is however trivial because all PRs are automatically added to my fetch (there is a setting for this), if I don't have my local checkout blocked by my own things, e.g. work in progress.

e.g. my recent command line history  (origin for me is statsmodels), (starting when I looked at 4000 the previous time):

git fetch origin
git checkout remotes/origin/pr/4000
git rebase remotes/origin/master
git rebase -i remotes/origin/master
git fetch origin
git checkout remotes/origin/pr/4105
git checkout remotes/origin/pr/4000
git fetch origin
git checkout remotes/origin/pr/4081
git checkout remotes/origin/pr/4068
git checkout remotes/origin/pr/4065

and in between all above calls I look at my open git gui window (rescan, then check history and changes), and hit the green button if it looks good.

**Comment by josef-pkt** [comment]
to add: 
The above is for easy PRs where I assume reading code and relying on unit testing CI is enough.
For most new code I need to run examples to see how it "feels" (e.g. convenience, obvious, good names/API) and whether I can punch holes in it (find bugs or where user mistakes lead to problems that could be avoided.)
(obvious and acceptable user mistakes depend on the problem, but I prefer not to RTFM each time, or preferably not even once.)

**Comment by jbrockmendel** [comment]
@josef-pkt Thanks for explaining.  It sounds like PRs which appear to me (and likely bashtage) as trivial actually take nonzero effort on your part to merge.

Is doing squash+fast-forward differently from e.g. pandas a personal style thing or a GUI thing or...?  Investing some time in making this simpler for you seems like a no-brainer.

Despite my spirit having been broken, I'm hoping you'll delegate pure-cleanup like this to @bashtage and me.  Something like granting him merge privileges on the condition that 1) both he and I review and 2) give our words of honour that the relevant PR is pure-cleanup.  If you were feeling generous you could specify that e.g. #4072 counts as "pure cleanup", or at the other end restrict to things caught by flake8.  Or require that @TomAugspurger also sign off.  We _will_ respond to incentives.

BTW: you've mentioned that github doesn't "track" files that are moved.  I just noticed that after a recent change in dateutil, things _did_ appear to get tracked.  There's a decent chance that I misunderstood something, but also a possibility that features have been improved.

**Comment by bashtage** [comment]
IME github will track moves if you use `git mv ` _original_ _dest_ .  I don't think tracking is guaranteed with just moves and hoping git will make a match,

**Comment by josef-pkt** [comment]
AFAIK there was no move command in the early git versions
actually there was, but it's the same as doing it manually
https://stackoverflow.com/questions/1094269/whats-the-purpose-of-git-mv
unless that changed

**Comment by josef-pkt** [comment]
(note was written a day ago but not send)

> Is doing squash+fast-forward differently from e.g. pandas a personal style thing

The main reason we don't squash is that we need the commit history for large commits.
https://github.com/statsmodels/statsmodels/pull/3246/files 12,500 lines which is very large and a single PR, but we have many in the one to a few thousand lines range. Having those in a single commit would make finding anything in the history e.g. for a specific part or hypothesis test very time consuming and difficult. Partial squashing would be useful but too much work, unless it's necessary to fix a commit problem.

As a consequence we also don't want to use fast-forward because we want to have only merge commits directly in master and the PR commits in the merged branch.

#4072 should switch to ValueError, otherwise I agree it is not dangerous.

no history of moved files: 
https://github.com/mortonjt/statsmodels/commits/96930f415b5e56d72f8d6197da135b57c6540124/statsmodels/compositional/_composition.py
doesn't show commit in it's old location
However, the `blame` view shows all commits. My guess is that this is relatively new, or that I used it without paying enough attention.

**Comment by bashtage** [comment]
man git mv shows that it directly affects the index:

```
In the first form, it renames <source>, which must exist and be either a file, symlink or directory, to <destination>. In the second form, the last argument has to be an existing directory; the given sources will be moved into this directory.

The index is updated after successful completion, but the change must still be committed.
```

**Comment by josef-pkt** [comment]
@bashtage  But this is the same as moving the file directly and staging the deletion and the addition, AFAIU. That shows up as a move/rename in git, and github changes.
At least that is what I always did. Git itself tracks changesets and can follow even clean moves of part of a file. But, AFAIR, older versions of github did not follow this in the blame view, and I used git gui in those cases.

**Comment by bashtage** [comment]
Yes, I just checked  and it doesn't show history.  I suppose it doesn't use the --follow flag (or equivalent).

**Pull request merged**
