### PR TITLE
MAINT: trailing whitespace in tsa.tests.results files

### PR DESCRIPTION
**Pull request by jbrockmendel**
@ChadFulton for when you get back, no hurry.

### CODE REVIEW

**Comment by bashtage** [comment]
That is a lot of trailing whitespace.

**Comment by jbrockmendel** [comment]
> That is a lot of trailing whitespace.

Yep, constitutes about 20% of all outstanding warnings.

**Comment by jbrockmendel** [comment]
> My vote is that we just add an exception at the top of these files

AFAICT putting `# flake8: noqa` at the top of the file will ignore _all_ checks in the file, but there is not a way to ignore a specific check in the file.

**Comment by ChadFulton** [comment]
Can we use flake8 extensions on Travis? (thinking of https://github.com/snoack/flake8-per-file-ignores)

**Comment by jbrockmendel** [comment]
> Can we use flake8 extensions on Travis? 

Yes, that is an option.  It'd be much simpler to just hit "Merge" though.

**Comment by jbrockmendel** [comment]
To elaborate: once these trailing spaces are removed, there remaining cases are measured in the dozens.  We get rid of them, add this to setup.cfg, and never have to think about this again.  The long term solution is to Do It Right just once.

**Comment by ChadFulton** [comment]
I'm not totally opposed to this PR, although on balance I think just adding noqa to the top of these files is better, but either way I'm not planning to merge this until after e-mail chain on style PRs is sorted out.

**Comment by jbrockmendel** [comment]
> but either way I'm not planning to merge this until after e-mail chain on style PRs is sorted out.

Fair.

>  although on balance I think just adding noqa to the top of these files is better

Counter-argument of the day: doing it The Right Way leads to a distribution that is 14k smaller.  That's almost 1e-4 cents worth of hard drive space right there.

**Comment by jbrockmendel** [comment]
> although on balance I think just adding noqa to the top of these files is better

The two main reasons I keep coming back to are:

a) internal consistency: fix the file as if we were writing it from scratch.  Everywhere else in the code we are moving towards using modern conventions (and in fact early on it looks like it was [intended](https://github.com/statsmodels/statsmodels/blob/master/tools/code_maintenance.py#L19))

b) complication: adding a noqa for this filter at the top of these files means getting the appropriate linter plugin into the CI config, requiring contributors to get that plugin, and ongoing job of keeping track of what parts of the codebase are special cased (and really, "ongoing keeping track of X in the codebase" is _not_ a strength of statsmodels).

On the flipside, the solution I'm advocating requires "push the green button".  After this we are a stone's throw from getting rid of all trailing whitespace, at which point it goes into setup.cfg and we Never Think About It Again.

**Comment by josef-pkt** [comment]
I'm against pep-8 cleanup like this.
These were autogenerated most likely from Stata, maybe from R.
The main thing I don't like are the long one column arrays. If we redo those files, then I think we should regenerate them with a different format (e.g. 4 or 5 numbers per line) and put nobs length arrays in csv files. The Stata export do file has been changed to support this

(I had blocked the merge of Skipper's Tobit PR because it contained 200,000 LOC of data arrays in test result py modules. Those kind of modules make LOC count less pretty meaningless.)

**Comment by jbrockmendel** [comment]
> If we redo those files, then I think we should regenerate them with a different format 

Agreed (I think) that sufficiently large arrays should go into csvs in an ideal world.

> The Stata export do file has been changed to support this

Which is the Stata export file?  I expect there are a bunch of copy/pasted implementations scattered around, but ideally there should be exactly one export file for each of Stata/R/Matlab.  (there's also tools.dump2module which looks related, but isn't clear what the use case is (and has undefined names)).

BTW @josef-pkt some PRs that were at least partially your idea:  #4981, #5027, #5004 (pending Appveyor), #5036, #5048,

Bugfixes that happen to be really easy: #5003, #5028, #5103, #4977, #4976,
Some incredibly easy PRs: #4979, #4990, #5047, #5071, #4941, #4979,
Some test fixes: #4980, #4978, #4983,
Following instructions left by our forebearers: #5053, #5050, #5070,
Test improvements (not technically fixes): #5086, #4988, #4936,

Some of these merit your attention, but many could be delegated to Kevin.

**Comment by jbrockmendel** [comment]
> Don't add so many cross-links if they are not connected by topic.

I'm yet to find an effective way to bring these to your attention.  The solution to this problem is to side-step the need for your attention, which is the constraining resource.

> The Stata file that has the function to export and create the py and csv files is in [...]

I'll take a look.  It shouldn't be hard to make these files trim the whitespace (which was apparently the original [intent](https://github.com/statsmodels/statsmodels/blob/master/tools/code_maintenance.py#L19)).

**Comment by jbrockmendel** [comment]
@ChadFulton final argument before I close this:

Relaxing standards has a slippery slope problem, and statsmodels' many strengths do not include Constant Vigilance.

- A test starts failing by a small margin and it's easier to loosen the tolerance than to troubleshoot... and we wind up with tons of tests with looser-than-wanted tolerances (4936)

- It's easier to comment-out an old version of X... and we wind up with `__main__` sections, sandbox, almost every `summary` method, ... (5050, 5049, 5102, 5140, 5047, 5041, 4990, 4940, 5125, 4419, 4348...)

- It's easier to comment-out (or gods help us, docstring-out) a test than xfail it, ... and we wind up with spotty tests (4983, 4980, 4978, 5145, 5115, 5085, 5084, 4862, 4324, ...)

The per-file-ignore approach you're suggesting will have a near-zero marginal cost to ignoring ever more things, which will be often be easier than convincing someone that git history is not sacred.  Let's not step on that slope.

**Comment by jbrockmendel** [comment]
> I spent a huge amount of time over the years on precision and convergence failures across machines, linalg libraries, scipy versions and similar.

> We are not "Relaxing standards", [...]

And you've done a great job buddy.  My claim is that a) after a test is in place, it is much more likely to have its tolerance loosened than tightened (e.g. #4943 "TST: Relax tolerance on failing test") and b) with teamwork we can do even better.

> [...] code that has been contributed by volunteer work over 10 years is "junk".

We're off to a good start so far today, so I'll just point towards https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/tests/test_constrained.py#L522

> xfail is a new invention, I have no idea what it means 

I'd be happy to walk through it with you. (I think there are variants in nose and unnittest, but that's neither here nor there).  The point is that we want to _know_ exactly which tests are failing so we know where attention is needed (and know when to celebrate when something gets fixed).  Commenting out and other implicit-skips obscures these.

**Comment by jbrockmendel** [comment]
> then it needs investigation and e.g. changing optimization 

Shorthand! “Constant Vigilance”.  Glad we’re on the same page.  Enjoy the party.

**Comment by josef-pkt** [comment]
aside to "junk" (scratch examples left in PRs)
 PR 1714 
30 lines named `junk` out of 2514 lines (460 new code and docstrings + 510 lines in unit tests + 1863 lines or results exported from Stata)
(That was a nice PR in my view, even though it has follow-ups and todos for a few more rounds and missing support in some models that need refactoring. And it didn't have enough test cases, so a serious bug slipped through in a model that wasn't covered by the unit test cases. 
IMO, those are the important details, 30 lines of unused junk is a minor issue.)

**Comment by jbrockmendel** [comment]
Really not sure what PR-related point you’re trying to make here.

**Comment by jbrockmendel** [comment]
>It's a followup to your link 

That link was a way to laugh off the "junk" term that _you_ introduced to the conversation.  Don't pin your tone on me.  There is no reason to re-hash the discussion of priorities; we both know that you are more interested in new features and I am more interested in making what exists more reliable (and getting the size of statsmodels down from 110%).  _And there is nothing wrong with that_.

Recall that Chad (at whom my comment about entropy was directed, recall) has mentioned that contentious threads make him less enthusiastic about participating.  De-railing the conversation to defend 1714 or anything else that does not need defending is actively counter-productive.  If you find it cathartic, ping me on it elsewhere.  But for now, Please Just Stop.

**Comment by josef-pkt** [comment]
Then stop being so negative, and I don't have to argue.
(We are not relaxing standards and we are not on a slippery slope to DOOM.)
You can choose a more professional language and still make the same point.

**Comment by jbrockmendel** [comment]
Again, you brought up the word junk, you brought up ever-so-professional word DOOM, and trying to make something better is not the same as being negative.  I’ll trash the notification email unread, so if you have anything productive to say, do it elsewhere like an adult.

**Pull request closed without merging**
