### PR TITLE
DOC: change OLS example to use datasets

### PR DESCRIPTION
**Pull request by sisyphus-quant**
Update the example of OLS by using the dataset.
Rebuild html and the docstring renders properly.

This is my first pull request, please let me know if there is anything I can improve. Thanks!

### CODE REVIEW

**Comment by bashtage** [comment]
Linting failure:

statsmodels/regression/linear_model.py:856:1: W293 blank line contains whitespace
statsmodels/regression/linear_model.py:858:54: W291 trailing whitespace

**Comment by sisyphus-quant** [comment]
> Linting failure:
> 
> statsmodels/regression/linear_model.py:856:1: W293 blank line contains whitespace
> statsmodels/regression/linear_model.py:858:54: W291 trailing whitespace

fixed by autopep8, thanks!

**Comment by bashtage** [comment]
It would be great if you could squash to 1 commit since this is just docs.  If you do this, please ping me when green.

**Comment by sisyphus-quant** [comment]
> It would be great if you could squash to 1 commit since this is just docs. If you do this, please ping me when green.

@bashtage hopefully I did it correctly.

**Comment by bashtage** [comment]
Thanks!

**Pull request merged**
