### PR TITLE
REF: raise early on invalid method

### PR DESCRIPTION
**Pull request by jbrockmendel**
Check for a valid "method" argument before doing anything else, avoiding potentially-expensive calls.

Flesh out a more helpful error message.

### CODE REVIEW

**Comment by bashtage** [comment]
Needs a test that passes an invalid method to fit new code and ensure that it works.

**Comment by jbrockmendel** [comment]
Done

**Comment by jbrockmendel** [comment]
@josef-pkt any chance of movement on this?  There are other improvements in this module I'd like to work on, would prefer to avoid merge conflicts.

**Comment by jbrockmendel** [comment]
@josef-pkt ping

**Comment by josef-pkt** [comment]
looks good

if this is from September, then a rebase on master would be useful. (I didn't check out the branch to see where this branches off)

**Comment by jbrockmendel** [comment]
rebased.  ping on green?

**Comment by josef-pkt** [comment]
all green, merged

@jbrockmendel Thank you

**Pull request merged**
