### PR TITLE
MAINT: Remove unused code

### PR DESCRIPTION
**Pull request by jseabold**
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

Was looking at some code and happened to notice that we weren't normalizing the weights in WLS, though it looked like the intention to do so was there. Maybe a refactoring victim? Shouldn't be a material change but may improve numerical stability in some cases.

### CODE REVIEW

**Comment by josef-pkt** [comment]
I think this should fail the unit tests

in contrast to Stata, we are not normalizeing various weights. weights as variance has an absolute meaning and the scale adjusts in the OLS case.

weights in OLS are equivalent to diagonal cov in GLS. AFAIR we added a unit test for that

**Comment by josef-pkt** [comment]
did fail in unit tests.

something strange

**Comment by josef-pkt** [comment]
the change is a no-op because `weights` is not used

**Comment by josef-pkt** [comment]
improvements for numerical stability should not change the interpretation and meaning of substantive variables

AFAIR, in WLS, GLS and GLM we take user provided weights at face value with the corresponding interpretation as var_weights or freq_weights. Any other use, is so far the responsibility of the user.

related issue #1131 for scaling problems and possibly **internal** transformations.

**Comment by josef-pkt** [comment]
e.g. unit test for meta analysis

```
        # compare with WLS, PM weights
        mod_wls = WLS(eff, np.ones(len(eff)), weights=1 / (var_eff + tau2))
        res_wls = mod_wls.fit(cov_type="fixed_scale")
```

but I don't see an assert that scale is unchanged.

**Comment by jseabold** [comment]
A no-op for a no-op. A fair trade.

Updated to just remove the dead code.

**Pull request merged**
