### PR TITLE
MAINT: unused imports in robust

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt easy, green, no merge conflicts

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@josef-pkt diff is 4 lines.

**Comment by josef-pkt** [comment]
small enough that I don't expect serious merge conflicts with open PRs

docstring of summary sound funny (8? years old)

merging

**Pull request merged**
