### PR TITLE
Replace * imports with specific imports

### PR DESCRIPTION
**Pull request by jbrockmendel**
mostly restricted to test and sandbox modules.

Fixes flake8/pylint  warnings about names not being detected.

Branch name is a misnomer -- got distracted and called an audible.

### CODE REVIEW

**Comment by josef-pkt** [comment]
use parenthesis, and not ` \` for line breaks, 80 character per line limit (I guess some are over)

otherwise looks good, and simple to merge

**Comment by jbrockmendel** [comment]
Done.

**Comment by jbrockmendel** [comment]
@josef-pkt I'm going through to tag the super-obvious PRs so we can whittle down the to-do list.  This one should be good to go.

**Comment by bashtage** [comment]
@josef-pkt Simple cleanup.  Mergeable.

**Comment by josef-pkt** [comment]
needs interactive rebase to remove "Merge branch 'master' into delete__main__errors"
also far behind master

(The commit "Merge branch 'master' into delete__main__errors" was automatically filtered out during interactive rebase, AFAICS)

rebased version in #3724

**Pull request closed without merging**
