### PR TITLE
BUG: update _get_init_kwds in GPP and NBP

### PR DESCRIPTION
**Pull request by josef-pkt**
see #3887 
we need to add extra kwds to `_get_init_kwds`

llnull needs the extra keywords for `model.__init__`

(I don't remember if llnull in NegativeBinomial is correct, IIRC I came across that once)

### CODE REVIEW

**Comment by josef-pkt** [comment]
I'm pretty sure that llnull in NegativeBinomial doesn't take the `loglike_method` into account, based on browsing the code. 
I don't remember where I ran into this. A search doesn't find an issue or comment.

Based on the unit tests, llnull is covered for the different NegativeBinomial versions.
One likely reason: In the regression on a constant the mean prediction and implied variance are constant across observations. In that case the two models might be equivalent with the same llf and just a difference in equivalent parameterization (with different alpha).

**Comment by josef-pkt** [comment]
The same, llnull independent of p, should apply to NBP and GPP. So llnull would not be incorrect and it would not be a test that we have the correct `_get_init_kwds`.

**Comment by josef-pkt** [comment]
another thought: if the parameterization differs across `p`, then if we add start_params_null, then those will differ even if the final llf is the same.

**Comment by josef-pkt** [comment]
Silly, most of the above is irrelevant.

We have an `_init_keys` attribute and `_get_init_keys` was only needed for the exposure transformation.
`NegativeBinomial.__init__` has `self._init_keys.append('loglike_method'), so it is correct.
https://github.com/statsmodels/statsmodels/issues/1608
(I didn't search in closed issues.)

This PR is still correct because currently the internal name is different from the `__init__` keyword so `_init_keys` cannot be used.

**Comment by josef-pkt** [comment]
all red.
NegativeBinomialP in master has a typo in attribute name and I tested locally on top of zero-inflated branch which has the typo fix in `parameterization`   (missing e in parametrization)
https://github.com/statsmodels/statsmodels/pull/3755/files#diff-a494553e88130577065e0b012246ca51L2739

I'm changing to the typo case and then we need to adjust it again when merging #3755.

**Comment by evgenyzhurko** [comment]
@josef-pkt 
I can delete changes `parametrization` to `parameterization` from zero-inflated branch in statsmodels/discrete/discrete_model.py

**Comment by josef-pkt** [comment]
@evgenyzhurko  I will still review the ZI PR today. Then I'll decide which way to go.
If possible I would like to merge the ZI branch, and leave the start_params issue for a follow-up. If we can merge ZI, then we would have the smallest merge conflicts and still get the parameterization typo fix into master before the release.

**Comment by josef-pkt** [comment]
This is now included in #3908   zero-inflated PR with additional changes

**Comment by josef-pkt** [comment]
merged as part of #3908  ec68da350f21ec4501f7fc4742e6277d6bb8419e

**Pull request closed without merging**
