### PR TITLE
MAINT: implement tools.leave_one_out, avoid sandbox LeaveOneOut

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
wrong direction
sandbox iterators are and will be the versions to use and to be updated

**Comment by jbrockmendel** [comment]
whats achieved by using the more complicated version?

I mainly care about not having it be in the sandbox.  Can we get this thing done if I move the needless complicated version to sm.tools.tools?

**Comment by josef-pkt** [comment]
#1498

**Comment by jbrockmendel** [comment]
1498 has some nice discussion of aspirations, doesn’t help with my questions.

**Comment by josef-pkt** [comment]
look at the scikit-learn version and check what is needlessly complicated.
We are not moving things to a temporary location outside the sandbox.
It's either status-quo or moving in the direction where we want and need to go.

**Comment by jbrockmendel** [comment]
> look at the scikit-learn version and check what is needlessly complicated.

Having a class at all is needlessly complicated; having a `__str__` method.  It's not needlessly complicated by a large amount, but it is more cognitive overhead for a reader than the version implemented by this PR.

> moving in the direction where we want and need to go.

And the direction you want to go is to have the existing sandbox version... where exactly?

**Pull request closed without merging**
