### PR TITLE
BUG: State space: memory error if k_posdef > k_states

### LINKED ISSUE #3833: BUG: State space: memory error if k_posdef > k_states
In one place I implicitly assumed that k_states >= k_posdef. If that's not true, one of the arrays (`{{prefix}}Statespace.tmp`) is mis-sized and leads to memory errors.

### PR DESCRIPTION
**Pull request by ChadFulton**
Closes #3833

Fixes an intermittent issue resulting in a segfault if k_posdef > k_states. Adds a test case.

### CODE REVIEW

**Comment by ChadFulton** [comment]
At least these new appveyor segfaults are replicable on my local machine :)

**Comment by ChadFulton** [comment]
A note about these Appveyor failures vs the ones in #3386.

Here, the problem was definitely caused by an operation attempted on memory that hadn't been allocated (e.g. I told dgemm to multiply a 1x2 matrix with a 2x2 matrix and store the result as a 1x2 matrix, but had only allocated a 1x1 matrix for the result). One interesting feature was that the tests passed in Travis, even though there was definitely a problem with array allocation, whereas Appveyor failed. The error code was -1073740940.

In #3386, it's not yet clear what the problem is (@bashtage suspects an alignment issue). Again, Appveyor fails while Travis does not. The error code is -1073741819.

**Comment by ChadFulton** [comment]
Looks like still not completely fixed.

**Comment by bashtage** [comment]
That is passed on Travis only tells you that Python owned the memory in the next 8 bytes past the end of the buffer, while on Windows it did not -- I don't think you can read anything more into it.  Of course result should be wrong (or non sense)

**Comment by ChadFulton** [comment]
@bashtage That's a helpful perspective, thanks.

**Comment by josef-pkt** [comment]
What's the status here?  The PR and corresponding issue didn't have labels.

**Comment by ChadFulton** [comment]
(Sorry, forgot to label - I had thought at the time it would take a few minutes to fix)

I think for now I will make a new patch that will raise an exception if people try to use `k_posdef` > `k_states`. There's no real reason to set up a model that way, and you can always reduce such a model to one in which `k_posdef = k_states`. Technically we could allow it (as this PR tried to do), but the problem is that in various places in the Cython code I made the assumption that `k_posdef` <= `k_states`, and I wasn't able to immediately track them all down, hence the failing tests.

**Comment by ChadFulton** [comment]
I've rebased this and raised an error in the k_posdef > k_states case, but I've kept the fixes I found so far in the Cython code.

In case it's not clear what's meant here, the transition equation is:

\alpha_{t+1} = T \alpha_t + R \eta_t, \eta_t ~ N(0, Q)

and the dimension of \alpha_t is `k_states` while the dimension of \eta_t is `k_posdef`. In any case, the random vector (R \eta_t) will have dimension equal to `k_states`, so any model can still be set up given the restriction.

The usage of R and the different dimension for \eta is to allow specifying a model with fewer disturbance terms than states while at the same time always having Q positive definite.

**Comment by ChadFulton** [comment]
I think the coverage results are not correct here (for example this PR does not touch many of the files in which coverage supposedly decreased).

This PR is then good to merge.

**Comment by josef-pkt** [comment]
You will have to rebase on master.
This is far behind master, and the coverage results are most likely because it was branched before the switch to pytest where coverage is counted differently

**Comment by josef-pkt** [comment]
Sorry, I just read your comment that you already rebased, then I don't know about coverage

**Pull request merged**
