### PR TITLE
PERF: Simplify algebra in discrete_model

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
ping.  There's a bunch more algebra simplification after this step, some of which is perf-relevant.

**Comment by jbrockmendel** [comment]
@josef-pkt let's make this happen before rebasing becomes a hassle

**Comment by josef-pkt** [comment]
the location of the changes will conflict with my score test PR #4716, where I move the code into other methods by adding score_factor and hessian_factor.
The changes will need to be manually combined with my PR, or I need to redo some commits if this is merged.

**Comment by jbrockmendel** [comment]
Sounds like an awfully good reason not to let these sit around for months on end.  Which would be a lot easier if, say, Kevin were allowed to handle a subset of PRs.

Anyhow, as a gesture of goodwill, how about I make a PR on the #4716 branch to make the same algebra simplifications there?

**Comment by bashtage** [comment]
Rebase, this has been milestoned.

**Pull request merged**
