### PR TITLE
Fix small doc errors

### PR DESCRIPTION
**Pull request by bashtage**
Fixes documentation and example errors
Makes the docbuild a bit more robust

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt. This is ready.  Fixes most bugs in notebooks except distributed.  Also fixes vecm documentation not appearing.

**Comment by josef-pkt** [comment]
Looks good to me in a quick read, merging

Do we use r robustbase in one of the notebooks?

**Comment by josef-pkt** [comment]
Thanks @bashtage 
Does this mean the recent big merges don't cause other doc error?

**Comment by bashtage** [comment]
> Does this mean the recent big merges don't cause other doc error?

There are not none in the docbuild.

> Do we use r robustbase in one of the notebooks?

Yes,  Would be good to remove all R code from notebooks IMO.

**Pull request merged**
