### PR TITLE
Cherry pick batch

### PR DESCRIPTION
**Pull request by TomAugspurger**
TODO:

- [x] #3348
- [x] #3217 (open)

xref https://github.com/statsmodels/statsmodels/issues/3075

The latest push should have every merge commit (aside from a couple merges with git snafus that I've cherry-picked commits from) into master that should be backported.

These commits were previously applied backported elsewhere:

commit | PR | backport PR
------ | ---- | ---
42d2f579 | Merge pull request #3341 from ChadFulton/gh-3283                           | #3342
7c723cf1 | Merge pull request #3263 from ChadFulton/ss-simulate                       | #3265
03158f2a | Merge pull request #3113 from ChadFulton/gh-3068                           | #3175
bb1db2b4 | Merge pull request #3140 from ChadFulton/gh-3140                           | #3174
11686550 | Merge pull request #3146 from josef-pkt/coint_aeg                          | #3171
1c6eff48 | Merge pull request #3166 from josef-pkt/bug_discrete_pred_table            | #3171
82bc0449 | Merge pull request #3112 from kshedden/phreg_einsum                        | #3171
1a09acfb | Merge pull request #3164 from josef-pkt/bug_glm_residworking               | #3171
87fd2d3f | Merge pull request #3099 from bashtage/add-eigenvalue-test                 | #3171
3116b589 | Merge pull request #3083 from bashtage/jseabold-pandas-deprecations        | #3171
e0d5807b | Merge pull request #3162 from josef-pkt/covtype_hacpanel_groups            | #3171
5fa4f8ed | Merge pull request #3161 from josef-pkt/multinomial_ci2                    | #3171
ef539151 | Merge pull request #3149 from josef-pkt/predict_missing_3087               | #3171
2a94f9f7 | Merge pull request #3160 from josef-pkt/pandas_compat_x13                  | #3171
a1118869 | Merge pull request #3158 from josef-pkt/bug_influence_plot_3103            | #3171
5c6280bf | Merge pull request #3157 from josef-pkt/bug_ttest_summary_header_3116      | #3171
92da1cd3 | Merge pull request #3102 from bashtage/fix-adf-docs                        | #3171
60bf8a14 | Merge pull request #3147 from josef-pkt/test_scipy08_3128                  | #3171
036ad9f7 | Merge pull request #3120 from N-Wouda/double_key                           | #3171
9ccf83fe | Merge pull request #3110 from ChadFulton/gh-3108                           | #3114
760e446c | Merge pull request #3077 from bashtage/test-missing-plots                  | #3171
f86c0742 | Merge pull request #3104 from ChadFulton/gh-3092                           | #3107
ba01d871 | Merge pull request #3081 from bashtage/jarque-bera-null                    | #3171
2d95be06 | Merge pull request #3088 from bashtage/remove-sourceforge                  | #3171
cb8dd764 | Merge pull request #3100 from kshedden/duration_readme                     | #3171
c914ea5e | Merge pull request #3095 from kshedden/phreg_patsy                         | #3171
35ef6664 | Merge pull request #3084 from bashtage/chelleych-arima_longar_start_params | #3171
c5b2f2ed | Merge pull request #3080 from bashtage/update-pypi-info                    | #3171
032a9abb | Merge pull request #3069 from matthew-brett/relax-statespace-for-32bit     | #3093
075415d6 | Merge pull request #3073 from bashtage/test-datasets                       | #3171
85ec79cf | Merge pull request #3072 from bashtage/correct-test-coverage               | #3171
022a76bb | Merge pull request #3071 from bashtage/appveyor-clone-depth                | #3171

### CODE REVIEW

**Comment by josef-pkt** [comment]
You might want to skip #2959 if the `Merge remote-tracking branch 'upstream/master'` causes the problems. We don't want to merge master into maintenance.
It contains improvements to the documentation, so is not crucial for backporting. (Otherwise we might have to cherry-pick individual commits or create a new interactively rebased PR just for this.)
(I missed the merge of master into the PR branch when I merged #2959)

**Comment by TomAugspurger** [comment]
Added a few more. Aside from the basic merge commits, I had to split #2959 to just grab b97c4211 (and not the merge to master). Same thing happened in 17c1c082 / #3364, but I haven't been able to cleanly split that yet. Will followup before this is ready.

**Comment by TomAugspurger** [comment]
Oh, we also have to leave out 47b7c9de / Merge pull request #3390 from since it's fixing things from #3327, which isn't being backported.

**Comment by josef-pkt** [comment]
@TomAugspurger   don't backport #3370 families_link, (otherwise we disable the deprecation warning in maintenance)

I don't understand your comments about the difference between #2959 and #3364, one is the issue the other the PR, 6a48d34 is the first commit of #3364 (before the master merge)

I had forgotten about 47b7c9d / Merge pull request #3390 That's not relevant for maintenance 0.8, it's fixing new code in master.

**Comment by TomAugspurger** [comment]
breaking up https://github.com/statsmodels/statsmodels/pull/3364/commits

- b97c421170066ff59762bcf6ae5c9515ece63517 is empty
- 621f37e4239b30623578ee00750b32fce09b4d02 is the master merge (no picked)
- b6990747426cb9712707bd0389fbd4318929e0ac picked
- 2eadbfce5a632eadcf0dc3e248eacf769fcd7be0 picked
- cb3f409c1e850ed167865b3ad63e0343b3af17ea picked

**Comment by TomAugspurger** [comment]
> @TomAugspurger don't backport #3370 families_link

Yep, that was an accidental inclusion. Left out of my latest push.

> I don't understand your comments about the difference between #2959 and #3364,

Bad link on my part. "I had to split #2959 to just grab b97c421" should have read "I had to split #3353 to just grab b97c421"

**Comment by TomAugspurger** [comment]
Repushed with Chad's statespace fixes (should be in order).

**Comment by josef-pkt** [comment]
I quickly went through all the merge commits in here and didn't see any problems.
I will check again tomorrow, but this looks good.
Thanks Tom

**Comment by TomAugspurger** [comment]
I'll figure out the test failures tonight.

**Comment by bashtage** [comment]
What is 3417?

**Comment by josef-pkt** [comment]
I guess it was supposed to be #3217 ARIMA pickle which has the backport label

**Comment by TomAugspurger** [comment]
Just cherry-picked a few more from the last couple days. I'll get this passing on Travis and appveyor, and then we should be able to merge before this goes stale.

**Comment by josef-pkt** [comment]
@TomAugspurger  I just merged #3416, then we are down to two open backport issues.

You could add #3416  and then I'll merge this.

**Comment by josef-pkt** [comment]
I just checked out this branch into an empty folder  
(using a Winpython 3.4.4, mingw gcc compiled, pandas.__version__ '0.19.1',  numpy.__version__ '1.11.2')
runs fine, except I also get the 
`statsmodels.tsa.regime_switching.tests.test_markov_autoregression.TestFilardoPandas` failure

nosetests statsmodels  creates a huge number of RuntimeWarning "invalid values encountered in xxx",
many of them come from `scipy\stats\_distn_infrastructure.py`

I thought I still saw some pandas Deprecation warnings running by (but with the runtimewarnings the testrun is too noisy).

**Comment by josef-pkt** [comment]
My guess is that the markov switching pandas failure is because of #3387 It remove the slicing with self.order and now index is too long. Maybe there was an unrelated change that made this slicing obsolete in master but not in 0.8
@ChadFulton  (BTW #3387 has no labels)

**Comment by ChadFulton** [comment]
> My guess is that the markov switching pandas failure is because of #3387 It remove the slicing with self.order and now index is too long. Maybe there was an unrelated change that made this slicing obsolete in master but not in 0.8
@ChadFulton (BTW #3387 has no labels)

> When I add the slicing back in index = self.data.row_labels[self.order:] on line 1834 in this PR version, then all tsa tests pass.

Great, I must have done something in 0.9. If possible, we should then only backport the unit test I added, but not the "fix".

**Comment by TomAugspurger** [comment]
> we should then only backport the unit test I added, but not the "fix".

I've done that now in a223235d, which passes locally. Thanks.

**Comment by bashtage** [comment]
What is left?  Just Chad's fix?

**Comment by TomAugspurger** [comment]
I think so. I'm doing a doc build now to see how that looks.

**Comment by TomAugspurger** [comment]
Is https://github.com/statsmodels/statsmodels/issues/3355 supposed to be marked for backport?

**Comment by TomAugspurger** [comment]
The failure on Appveyor is due to not backporting #3350. @ChadFulton in https://github.com/statsmodels/statsmodels/issues/3075#issuecomment-276849404 you had it under the "Should not be backported" section, as it's related to tsa-dates. Should we mark those tests as skips on windows for 0.8.x?

**Comment by ChadFulton** [comment]
I guess I will need to make a separate fix for this (it's the same
underlying issue as #3350, but the solution will be different because 0.8
is still using the old date handling code).

I'm finishing up #3405 and its backport right now, but I can fix this date
issue afterwards.

**Comment by TomAugspurger** [comment]
>  I'm finishing up #3405 and its backport right now, but I can fix this date
issue afterwards.

Great thanks. @josef-pkt I think this is good to go then. (unless you want to merge the install doc update from #3420 to master first, then I can backport that here. Or as a followup, doesn't matter to me).

**Comment by bashtage** [comment]
You might also consider #3352 which has a more.comprehensive install guide
changes.

**Comment by josef-pkt** [comment]
I'm merging this now, given this is all green, and we can get the remaining things afterwards.

about #3352  we need to check the version requirements, e.g. 0.8 has in release notes that it is the last to support python 2.6

**Comment by josef-pkt** [comment]
BTW: the commit list in maintenance looks good this way, easy to see and link to what PRs have been backported
https://github.com/statsmodels/statsmodels/commits/maintenance/0.8.x

There are a few items that we will need to add explicitly to the release notes, which affect older code and not just within 0.8 release cycle changes, e.g. ARIMA pickling and multinomial  (based on a brief skimming)

**Pull request merged**
