### PR TITLE
Make keyword args explicit

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt  I approve of this cleaning

**Comment by josef-pkt** [comment]
I'm not sure about the general design idea.

If we initialize the attributes in the superset of all models, then we get a large number of attributes that are None. That makes dir(object) less informative, and we carry redundant/unused attributes around.
IMO, all attributes except for a small required intersection set should be optional.

e.g. predict uses
`if transform and hasattr(self.model, 'formula') and exog is not None`

Given that unit tests pass, the data.formula is not automatically transmitted as attribute to the model

`base.Model._handle_data` excludes attaching formula and design_info to the model.
`formula` is explicitly attached to the model in `base.Model.from_formula`

**Comment by jbrockmendel** [comment]
More predictability, fewer special cases -->  Easier to reason about.  Explicit is zen.

**Comment by josef-pkt** [comment]
more attributes to worry about, 
More generic stuff doesn't make special cases less special, it only replaces `hasattr` by `is None`

In any case, it's likely that I agree in this case, after I have time to think about it.
(And maybe not, currently all we need in a fake data instance or class is the xnames or param_names.)

**Comment by jbrockmendel** [comment]
Going on a tangent because this is something interesting I learned about recently: `hasattr` behavior is [subtly different](https://hynek.me/articles/hasattr/) between py2/py3.

`hasattr` (and much worse, `setattr` and `delattr`) make it harder to grep for e.g. "\\.df_model"

And really is `self.foo is not None` more complicated than `hasattr(self, 'foo')`?  Pretty sure the former is more performant.

**Comment by josef-pkt** [comment]
The reason why we or I added many hasattr and getattr is that "everything is a special case", i.e. we are adding many attributes and features that are specific to certain use cases (using formulas) or specific to models. 
As you have seen in many other issues, the question of what should be common, generically required attributes is still open, although the set is increasing over time.

example
`df_resid = getattr(self, 'df_resid_inference', self.df_resid)` (in base.model.LikelihoodModelResults.pvalues and t_test, ...)
handles a correction for panel or cluster robust standard errors if use_t=True, and has currently no other use. I did not promote it to a generically required or initialized attribute.

Some attributes can over time become generically required or initialized if the fraction of special cases that need it becomes large.

(I don't remember any bug that we had because of the behavior of hasattr or getattr, and I don't remember ever running into py 2 versus py 3 problems with them.)

**Pull request closed without merging**
