### PR TITLE
MAINT: Remove kalmanf StateSpace code supplanted by tsa.statespace

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
@ChadFulton  That's up to you
I never looked at the kalman filter implementation, and it's extremely unlikely that I ever will.

**Comment by jbrockmendel** [comment]
Appveyor fail is unrelated httperror

**Comment by jbrockmendel** [comment]
@ChadFulton anything I can do to help out on this?

**Comment by jbrockmendel** [comment]
@ChadFulton ping

**Comment by ChadFulton** [comment]
So if I understand correctly, the deleted code is not used anywhere, and maybe appears to have been part of an early effort to expand to more general state space models than ARIMA that didn't end up getting developed?

**Comment by jbrockmendel** [comment]
> So if I understand correctly, the deleted code is not used anywhere, and maybe appears to have been part of an early effort to expand to more general state space models than ARIMA that didn't end up getting developed?

Among other things that make it unusable, yes.

**Comment by ChadFulton** [comment]
Merging - we can always look at it in git history if we need anything.

Thanks @jbrockmendel

**Pull request merged**
