### PR TITLE
REL: update setup.py for release

### PR DESCRIPTION
**Pull request by josef-pkt**
0.8.0

### CODE REVIEW

**Comment by kernc** [comment]
Could you also fix [line 142](https://github.com/statsmodels/statsmodels/pull/3447/files#diff-2eeaed663bd0d25b7e608891384b7298L142) (the error isn't raised). This made statsmodels fail to install in certain environments, breaking at some later step and with a more misleading message.

**Comment by josef-pkt** [comment]
@kernc   What's the problem and the suggested fix?  I haven't figured out what's going on for different versions.

**Comment by kernc** [comment]
The [marked line](https://github.com/statsmodels/statsmodels/pull/3447/files#diff-2eeaed663bd0d25b7e608891384b7298L142) is just missing a `raise` statement.

**Comment by josef-pkt** [comment]
> The marked line is just missing a raise statement.

oops, that explains why travis works with pandas 0.12 without raising the minimum requirement exception

(aside my old notebook is broken, and I don't have anything older than pandas 0.15 on this computer)

**Comment by josef-pkt** [comment]
I'm trying out the lowest requirements.

**Comment by kernc** [comment]
Sounds reasonable, although v.13 might have been set specifically due to some behavior in that version. Hopefully, tests cover it all.
FWIW, I'd keep the code around the import tidy (that is, indent the line following `raise` to match). Otherwise looking forward to the release. :+1:

**Comment by josef-pkt** [comment]
I think we can stick with these versions for 0.8. That covers old python 2.6, and specifically conda for it, for the last time.

We have some code that requires more recent versions where the unit tests are skipped for the ancient versions.

indent adjustment coming up.

@kernc  Thanks for catching that `raise`

**Pull request merged**
