### PR TITLE
TST: Change appveyor clone depth

### PR DESCRIPTION
**Pull request by bashtage**
Set depth to 50

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt This will change the clone depth to 50 for appveyor

**Comment by josef-pkt** [comment]
looks fine to me
just a question: AFAICS, we have the clone depth in the settings on appveyor (which was 10 and I changed to 50). But the clone depth in the `appveyor.yml` overrides this.
Is there an advantage of sticking to either version? 
Can we just delete the line in appveyor.yml and rely on the appveyor website setting.

**Comment by bashtage** [comment]
The .yml way means you never have to mess with the web interface and
changes to appveyor are just like changes to travis, which seems cleaner to
me.

**Comment by josef-pkt** [comment]
ok, I don't have a preference

I'll merge tomorrow. 
I want to see if I can first merge the maintenance commits to master to bring master in line with maintenance.

**Comment by josef-pkt** [comment]
merged

@bashtage Thank you

**Comment by josef-pkt** [comment]
backport if appveyor doesn't work in maintenance

**Pull request merged**
