### PR TITLE
Arima exog predict 2128 rebased

### LINKED ISSUE #2127: ARIMA.predict does not pass exog in super.
See SO question [here](https://stackoverflow.com/questions/27464703/arima-exogenous-variable-out-of-sample). It's only for this combination of arguments.

### PR DESCRIPTION
**Pull request by josef-pkt**
rebased version of #2128, fixes #2127 
with additional regression test

(code comments in tests about things I didn't understand.)

### CODE REVIEW

**Comment by josef-pkt** [comment]
I'll merge when TravisCI is green

**Comment by ChadFulton** [comment]
Before you do, there's another bug in predict that should be fixed here. Take a look at: 

http://nbviewer.ipython.org/gist/ChadFulton/6d917df65bfbcd4e0c1c/

The problem is that the `_get_predict_out_of_sample` function doesn't subset the `mu` vector correctly in the case of `k_trend == 1 and k_exog > 0`.

I believe that the fix requires changing line 296 from:

`mu = mu + (np.r_[1, -arparams[::-1]] * X).sum(1)[:, None]`

to 

`mu = mu + (np.r_[1, -arparams[::-1]] * X).sum(1)[len(mu)-steps:, None]`

This seems to fix it for me, but I'm not sure what tests to run to make sure it doesn't have negative consequences elsewhere.

**Comment by josef-pkt** [comment]
Thanks for looking into this, i will look at it again (in a few hours).

I couldn't figure out what values of exog are used if it doesn't have the exact length. It doesn't raise an exception if exog in predict is too long, but I couldn't replicate the result of a too long exog with an exact length exog.

**Comment by ChadFulton** [comment]
> I couldn't figure out what values of exog are used if it doesn't have the exact length. It doesn't raise an exception if exog in predict is too long, but I couldn't replicate the result of a too long exog with an exact length exog.

Here's the source of this bug:

`exog` is never subset to the required length, but what happens is that in `_arma_predict_out_of_sample` it iterates from the start of `exog` to `steps-1` (the two for loops). But then for the final forecast, instead of continuing on the iteration, it selects the last element from `exog`. So if exog is too long, the prediction should be correct except for the last element (at least this is what I found).

I think that this can be fixed by changing:

```python
forecast[-1] = mu[-1] + np.dot(arparams, endog[steps - 1:])
```

to

```python
forecast[steps-1] = mu[steps-1] + np.dot(arparams, endog[steps - 1:])
```

**Comment by josef-pkt** [comment]
@ChadFulton  Thanks for the notebook, and the comparison ARIMA SARIMAX. We should add something like this to the documentation notebooks.

I'm not really an expert on our ARIMA implementation.
After playing a bit with the prediction in your notebook, I think we shouldn't try to choose a slice of a too long exog, unless we can get the correct slice via the pandas index.
If the exog is too long, then, mostly based on what you found, it uses the beginning of the exog. but for forecasting this doesn't make sense, if the user accidentially or because of misunderstanding used the entire exog instead of the exog of the prediction time. (as in the initial stackoverflow example in #2127 

my suggestion: Either raise a ValueError for length mismatch, or enhance by using pandas index of the exog.

But this is a separate bug from the one in this PR (and the original issue and PR)

**Comment by josef-pkt** [comment]
new issue for this #2472

**Comment by josef-pkt** [comment]
something looks fishy with the ARIMA(3, 1, 1) prediction for the exog timing. 

The level prediction is shifted down compared to ARMA and OLS, with the same exog.
However this could be a feature and not a bug. (last observation and their forecast errors are "initial conditions" for forecast that don't go away as prediction horizon increases.)

**Comment by josef-pkt** [comment]
to the previous: timing of exog has to be correct, in the seasonal series, I get the predicted peaks and troughs at exactly the same time as OLS and ARMA. If I shift exog, then not only the height shifts up or down but the extremes shift horizontally (in plot) which is wrong.

**Comment by josef-pkt** [comment]
reverse engineering: the shift of the prediction in ARIMA is a feature

In the seasonal data, the last year had low values, lower than average. ARIMA propagates the lower level to future predictions.
If I don't use the last year for estimating the model, and start at the year before which has slightly higher than average values, then the ARIMA prediction is a little bit above the prediction of ARMA and OLS.

**Comment by josef-pkt** [comment]
add latest changes to description

- #2472 Chad's bugfix for last observation, we don't warn or raise on too long exog (yet)
- #2475 dynamic predict didn't use the correct slice, fixed but assumes `start` is index

looks good, but I haven't tried to figure out `start` index yet: What happens if start and end is a datetime or similar index? Is that allowed?

**Comment by josef-pkt** [comment]
correction: I don't know why I didn't see that `start` is already converted to index
`start = self._get_predict_start(start, dynamic)`

**Comment by josef-pkt** [comment]
need to lower precision, all python versions of TravisCI fail, but not all at the same assert.
All tests passed for me with MKL. But I'm not testing the parameter estimates.

**Comment by josef-pkt** [comment]
2 python versions still failed, lowered precision some more, and amended comit, plus small cleanup

**Comment by josef-pkt** [comment]
all green, ready to merge

@ChadFulton @jseabold   any comments?

the only thing that's left of the related issues is whether we raise or warn if prediction exog is longer than needed  #2472 (I haven't figured out where to check the length.)

**Comment by josef-pkt** [comment]
merged

**Pull request merged**
