### PR TITLE
BLD: Update travis for miniconda errors

### PR DESCRIPTION
**Pull request by bashtage**
Skip conda update to avoid errors in recent minicondas

### CODE REVIEW

**Comment by bashtage** [comment]
xref conda/conda#6030

**Comment by josef-pkt** [comment]
@bashtage  Thanks for looking into this.

Can I merge this as is? It will be good to have a working travis again.

**Comment by bashtage** [comment]
Yes, ready.

**Comment by josef-pkt** [comment]
merged

**Pull request merged**
