### PR TITLE
Feature/wilcoxon mann whitney sample size squashed

### PR DESCRIPTION
**Pull request by yangwu1227**
- [x] related to #8382 and #9389
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by josef-pkt** [comment]
one advantage here of returning a holder instance is that we don't have to choose between returning nobs1 or nobs_total.
The generic power classes and functions default to returning nobs1 in the two sample case.

I went through the main part of the Happ et al article to understand the theoretical assumptions a bit better.
The variance of the test statistic under the null is computed from the pooled sample (IIUC, asuming F1 = F2 under the null).
The variance under the alternative uses different variances for each sample, the variance of the test statistic is a linear combination of var1 and var2.
Older articles like Noether use the null variance also for the variance under the alternative.
(This means that the null variance does not apply for testing with a margin or equivalence testing where p_null != 0.5. 
For equivalence we could also reverse the variances, i.e. difference p under the null and homogeneity, p=0, F1=F2, under the alternative.)

merging

@yangwu1227   Thanks again for the PR.

**Comment by josef-pkt** [comment]
Note: this and the original PR #9389 have the same commits

**Comment by yangwu1227** [comment]
@josef-pkt Thanks for looking into it. I also don't find any sample size/power on BM. Seems that Edgar's recent work has focused more on the WMW, with his last work on BM being the 2007 permutation test, which is still widely cited.

Wonder if the lack of literature on sample size/power simulations for BM is because the Behrens-Fisher problem is not typically a scenario designed for in advance but rather a reactive solution-- perhaps, e.g., when assumption of equal variances is violated after the data has been collected. So in most medical studies, ample sizes are usually planned for the ideal case, assuming equal variance between groups.

**Comment by josef-pkt** [comment]
I found several articles that compare power of Brunner-Munzel and other test in simulations. So power considerations are there.

It could also be that the difference in required sample size between BM and MWM is not large enough to get separate attention and publications, and might not be worth the effort.

I don't remember the details for the analogous case for t-test with and without equal variance assumption, and I never checked by how much sample size differs between the two.
It could be that we just need to use the variance under the alternative also for the variance for the test statistic under the null.
We would have the same variance and only the effect size would be different from zero, between null and alternative.


aside quick look at their book
3.8.2 Sample Size Planning for the General Case
The section has the same as the Happ et al article. It looks like only sample size for MWM, no mention of "brunner-munzel" test or heteroscedasticity in the sample size section.

Brunner, Edgar, Arne C. Bathke, and Frank Konietschke. 2018. Rank and Pseudo-Rank Procedures for Independent Observations in Factorial Designs: Using R and SAS. Springer Series in Statistics. Cham: Springer International Publishing. https://doi.org/10.1007/978-3-030-02914-2.

Advantage of Noether is that it does not require variance computation, i.e. we don't need to prespecify data to compute variances. Only `p` is needed and can be used when there is no prior info about distributions. (but it's computed under identical continuous distributions which might be far from reality)

**Comment by josef-pkt** [comment]
Zhao, Yan D., Dewi Rahardja, and Yongming Qu. 2008. “Sample Size Calculation for the Wilcoxon–Mann–Whitney Test Adjusting for Ties.” Statistics in Medicine 27 (3): 462–68. https://doi.org/10.1002/sim.2912.
equation (12) might be a good follow-up
ordered multinomial data provides the reference distributions for the two samples.
(uses only one variance)

also cited in p. 59 equ. (4.8) of  Machin, David, Michael J. Campbell, Say Beng Tan, and Sze Huey Tan. 2018. Sample Sizes for Clinical, Laboratory and Epidemiology Studies. 1st ed. Wiley. https://doi.org/10.1002/9781118874905.


this might be similar to `rank_compare_2ordinal` hypothesis test

**Comment by yangwu1227** [comment]
Interesting, I just got hold of the papers and the book by Edgar and will take a closer look to gain further understanding. As always, really appreciate your sharing the links. It'll be interesting to explore how the closed-form formula in Zhao, Yan D., Dewi Rahardja, and Yongming Qu. 2008 compares to Happ et al.'s approach. I think Happ et al. also cite this work in their references

**Comment by josef-pkt** [comment]
The main advantage is that is easier to specify a full distribution than making up full synthetic samples, and data with a few ordinal categories show up in many applications.

It would also be possible to use Happ et al sample size computation from ordinal distributions by replacing the rank and placement computations.
But I don't remember the details. `rank_compare_2ordinal` is doing something like that for the brunner-munzel test, but AFAIR that case was explicitly included in the brunner, munzel, ... literature.

**Comment by yangwu1227** [comment]
Got it. Just to make sure I'm following, when you say "easier to specify a full distribution," you mean it's simpler to observe, obtain (given count data), or postulate the proportions $p_c$ (prop of group 1 falling into category $c$) and $q_c$ (same for group 2) $\forall c$ in the second part of their equation (13):

$N = \text{another form ..}= \frac{\left(Z_{\alpha / 2}+Z_\beta\right)^2}{12 t(1-t)\left(\sum_{c=2}^D p_c \sum_{d=1}^{c-1} q_d+0.5 \sum_{c=1}^D p_c q_c-0.5\right)^2}$

And this approach is probably easier than generating full synthetic samples for each ordinal category?

**Comment by josef-pkt** [comment]
Yes, say we have 3 or 5 levels of feeling pain. from no pain to extreme pain. Then we can specify the fraction/probability of a patient having a specific level of pain with treatments a and b. 
The fractions can often come from previous data and what we would like to see in an improved treatment.

many examples like likert scale that are ordered categories but not necessarily metric. 

ordinal data is the best case for MWM and BM, because, mean and similar statistics don't have an inherent meaning.

**Comment by yangwu1227** [comment]
Thanks for the clarification. Yes, would be interesting for me to dig in a bit more

- One-tailed (greater or smaller) – correct tail being tested based on user-provided proportions and checking if it aligns with the specified alternative hypothesis (using their $\hat{\mu}_1$ formula)
- Backing out power – based on user-supplied sample sizes and p's and q's

Perhaps it could become another same size computation offering without needing syntehtic data generating (which is flexible for continuous data but may be difficult for ordinal) and especially useful for the ordinal (likert-scale) cases.

**Comment by josef-pkt** [comment]
update to Zhao et al ordinal case

Tang has the computation for variance under alternative, so sigma_alt is not the same as sigma_null
Zhao et al method overestimates the power if p is far from 0.5 or nobs_ratio is far from 1.

Tang, Yongqiang. 2011. “Size and Power Estimation for the Wilcoxon–Mann–Whitney Test for Ordered Categorical Data.” Statistics in Medicine 30 (29): 3461–70. https://doi.org/10.1002/sim.4407.

**Comment by yangwu1227** [comment]
Took a closer look into Zhao et al and Tang. Here's a preliminary take at Zhao's method:

```python
from typing import Optional

import numpy as np
from scipy.stats import norm


def two_sided_sample_size(
    control_prop: np.ndarray[float],
    treatment_prop: np.ndarray[float],
    treatment_fraction: float,
    alpha: Optional[float] = 0.05,
    power: Optional[float] = 0.8,
) -> float:
    treatment_prop = np.asarray(treatment_prop)
    control_prop = np.asarray(control_prop)

    # With equal variance assumption simplification for wmw
    z_alpha = norm.ppf(1 - alpha / 2, loc=0, scale=1)
    z_beta = norm.ppf(power, loc=0, scale=1)
    quantile_term = (z_alpha + z_beta) ** 2

    # Variance under null hypothesis
    cubed_prop_sum = (
        (1 - treatment_fraction) * control_prop + (treatment_fraction * treatment_prop)
    ) ** 3
    adj_term = 12 * treatment_fraction * (1 - treatment_fraction)
    adj_var_null = (1 - cubed_prop_sum.sum()) / adj_term

    prod_term = np.sum(control_prop * treatment_prop)
    mixed_term = np.sum(control_prop[1:] * np.cumsum(treatment_prop)[:-1])
    est_treat_eff = mixed_term + 0.5 * prod_term

    n_total = (quantile_term * adj_var_null) / (est_treat_eff - 0.5) ** 2

    return n_total


def main() -> int:
    treatment_fraction = 0.5
    num_pain_categories = 5
    # Generate random control and treatment proportions and normalize them
    np.random.seed(0)
    control_prop = [0.1, 0.2, 0.3, 0.2, 0.2]
    treatment_prop = [0.2, 0.3, 0.3, 0.1, 0.1]

    n_total = two_sided_sample_size(control_prop, treatment_prop, treatment_fraction)

    print(f"Total sample size: {n_total}")

    return 0


if __name__ == "__main__":
    main()
```

I scanned read Tang's paper and got a big picture that they don't assume $\sigma_{0}=\sigma_{1}$, but may need to read closer to better understand. Their's $\sigma_{0}^2$ and $\sigma_{1}^2$ both require $N$, $n_1$, and $n_2$ to be known and so I'm guessing data samples would have to be given (as compared to Zhao et al where only the proportions are needed).

**Comment by josef-pkt** [comment]
> Their's $\sigma_{0}^2$ and $\sigma_{1}^2$ both require $N$, $n_1$, and $n_2$ to be known

For the power computation those are known
For the sample size computation we have n1 = t * N, n2 = (1-t) * N. And we can split out N, sigma_1 ** 2 * N which only depends on `t`, and solve for N. Tang et al compute using sqrt(N) in `z` variable.

The derivation is essentially the same in all these normal based power and sample size computations, but it has been some time since I went through the details.

we should try to reuse existing helper functions.
For example: I wrote `stats.power.normal_sample_size_one_tail` so I don't have to write the same code each time.

Also I guess sigma_alternative s1 of Tang et al will be similar to using placements, e.g. in `stats.nonparametric.rank_compare_2ordinal`
The problem is Tang et al use a definition directly from the multinomial/ordinal case, while Brunner, Munzel, ... usually derive things using ranks and placements.
My guess is that their tau1, tau2 are (mostly) the same as var1, var2 in `stats.nonparametric.rank_compare_2ordinal`.

(What I often do in these cases: If the formulas are easy enough to code, then I compute both of them to check that different formulas give the same results. Then, pick the one that better fits into statsmodels.)

**Comment by yangwu1227** [comment]
Just an update and still plan on looking into

1. Trying reuse existing helper functions
2. Doing comparisons of their tau1 and tau2 with e.g. var1, var2 in stats.nonparametric.rank_compare_2ordinal

I'm at a conference the next few days and plan on continuing to reading up and working on this as I'm there.

**Pull request merged**
