### PR TITLE
[MAINT] Remove info.py

### PR DESCRIPTION
**Pull request by jbrockmendel**
Discussed in #4973

### CODE REVIEW

**Comment by josef-pkt** [comment]
I prefer to delete this text completely
This hasn't been updated since 2009, and AFAIK is not included in the DOCs
(In this case completely outdated sounds worse than having nothing)

I think it would be better if the api.py contains some information about the `api` structure, eg. parts along the line of http://www.statsmodels.org/devel/importpaths.html#api-import-for-interactive-use 

The api.py docstrings are not part of our DOCs doctrees, so any information here would be mainly for source use or if users explicitly requests an `api` docstring

**Comment by jbrockmendel** [comment]
OK, will update and remove the docstring completely.

**Comment by jbrockmendel** [comment]
@josef-pkt updated as requested and green.

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@josef-pkt this removal was your idea...

**Comment by josef-pkt** [comment]
mergin

@jbrockmendel Thank you

**Pull request merged**
