### PR TITLE
update license year 2018, remove duplicate license file

### LINKED ISSUE #4931: duplicated LICENSE.txt file?
There's one in the top-level directory and one in the statsmodels/ directory.  It looks like the one in statsmodels/ is slightly more up-to-date.

### PR DESCRIPTION
**Pull request by jbrockmendel**
Broken off of #4958 in the hopes this will make it easier on reviewers.

Closes #4931.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt what commit code should this get?

**Comment by josef-pkt** [comment]
MAINT

I just checked and the statsmodels/license.txt is NOT installed.
This is a bug. I don't see any license file in the installed version in python's sitepackages.
I checked an old statsmodels 0.5.0 install and it is also missing there.
numpy, scipy have it (at least the old versions that I checked)
So I'm not sure that file should be deleted, we should add it to the statsmodels distributions (sdist and wheels) instead.

aside there is also an `info.py` file that doesn't seem to have been updated in this decade
(old scipy pattern that scipy dropped in 2012)

**Comment by jbrockmendel** [comment]
> aside there is also an info.py file that doesn't seem to have been updated in this decade

If I understand correctly, `__init__` imports `__doc__` from info.py.  I'd be on board with just putting the docstring directly in `__init__` and removing the extraneous file.

**Comment by bashtage** [comment]
The files should be included in the manifest I suppose.

**Comment by jbrockmendel** [comment]
> The files should be included in the manifest I suppose.

Sounds good.  Is there a standard way to test that this gets distributed correctly?

**Comment by jbrockmendel** [comment]
Shouldn't the `global-include` of `*.txt` get the LICENSE.txt file?

**Comment by bashtage** [comment]
I have added including LICENSE to #4871 .

**Comment by bashtage** [comment]
> Sounds good. Is there a standard way to test that this gets distributed correctly?

Manually check it.  Non trivial to write a test (possibly, would need to install statsmodels, and then find the installation directory, and then check that the file is there).

**Comment by jbrockmendel** [comment]
@josef-pkt should be ready now that setup.py is updated?

**Comment by josef-pkt** [comment]
4871 is not yet merged, I just merged the CI testing changes

**Comment by jbrockmendel** [comment]
Gotcha, my mistake.

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@bashtage mind taking this over after the setup.py PR goes through?  I’m in the doghouse, and simple stuff like this shouldn’t keep getting put off.

**Comment by jbrockmendel** [comment]
@josef-pkt ping; this was waiting for #4871 IIRC.

**Comment by jbrockmendel** [comment]
@rgommers might be nice to have an up-to-date LICENSE yah?

**Comment by rgommers** [comment]
This change is correct and looks like a clear improvement.

> I just checked and the statsmodels/license.txt is NOT installed.

I just checked, it's present in the sdist. Checking the wheels takes a bit long, would be good to do too (`python setup.py bdist_wheel`, then inspect the wheel - it's a standard zip file). It should be included in the wheel and installed I think - just checked an installed numpy version and the license file is present next to the main ``__init__.py``. Could be done in a separate PR though.

**Comment by rgommers** [comment]
> @rgommers might be nice to have an up-to-date LICENSE yah?

Yes. I'm not really the right person to come along and merge PRs that other, more active, maintainers don't want to or haven't merged yet though. So I'll keep my hand off the green button for this one:)

**Comment by bashtage** [comment]
See #5195

**Comment by jbrockmendel** [comment]
Closing in favor of #5195.

**Pull request closed without merging**
