### PR TITLE
TST: Remove __main__ sections in tests

### PR DESCRIPTION
**Pull request by jbrockmendel**
There was in Issue recently about settling on ways to run the test suite, and IIRC one of the takeaways was that we don't want `__main__` sections in test files.

Addresses many of the checkboxes in #5128.

### CODE REVIEW

**Comment by bashtage** [comment]
Simple clean up. LGTM

**Comment by jbrockmendel** [comment]
@josef-pkt ping.  We can avoid having merge conflicts pile up...

**Comment by jbrockmendel** [comment]
@josef-pkt best 90 seconds you'll spend all week

**Comment by josef-pkt** [comment]
I agree, no useful information there and outdated pattern

**Comment by josef-pkt** [comment]
@jbrockmendel Thank you

**Pull request merged**
