### PR TITLE
ENH/CLN: Improve diagnostics

### PR DESCRIPTION
**Pull request by bashtage**
- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by josef-pkt** [comment]
Don't merge this if the move doesn't preserve commit/blame history

**Comment by bashtage** [comment]
It is not going to be possible to preserve this, nor is it needed. It can't
be preserved because the destination file exists already. There may be some
complicate way to preserve blame, but given how extensive these changes are
there isn't much point.

**Comment by josef-pkt** [comment]
we move the module to a private `_diagnostic` and keep `diagnostic` as an api module. There are or will be several other private `_diagnostic_xxx` 

For bug hunting or finding the reason for some implementation choices a blame and history is very useful and needed.
Having it as a new file looses all references to the history.

**Comment by bashtage** [comment]
#6410 retains history

**Pull request closed without merging**
