### PR TITLE
Remove redundant code for dropped Python 2.6

### PR DESCRIPTION
**Pull request by hugovk**
https://github.com/statsmodels/statsmodels/issues/3999#issuecomment-335159392 mentioned the need to clean up and modernise the code, so this PR removes a lot of now-redundant compatibility code that was in there just for 2.6.

### CODE REVIEW

**Comment by josef-pkt** [comment]
similar PR #4008

I will merge the py 2.6 removal after the release, I don't like to do it just before a release.
I don't see a downside to keeping it in for the upcoming release.

**Comment by josef-pkt** [comment]
This pull request fixes 2 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-6d1c7d9230942cf123f3d04ed76d2e18559a6a5a)

**fixed alerts:**

* 2 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
LGTM.  Some nice whitespace/flake8 cleanup in the process.

**Comment by hugovk** [comment]
My editor (TextWrangler) is set to delete trailing whitespace on save :)

**Comment by hugovk** [comment]
Rebased to remove conflicts, and updated one file to use OrderedDict from collections.

Do you have an idea when the last release supporting for Python 2.6 is due out?

Thanks!

**Comment by josef-pkt** [comment]
This pull request fixes 2 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-8c32a86dc43f7f404c74fdd64f09539011778170)

**fixed alerts:**

* 2 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
0.9 was due about two months ago.
Maybe two weeks (> 1) if we/I manage to stick mostly with release preparation and remaining PRs for 0.9.

**Comment by josef-pkt** [comment]
This pull request **fixes 11 alerts** when merging 642d20ab1563947535da61852a85cab710d8cedb into 37cbf3e5eda32101577517d9b94693f49e8e53d6 - [view on LGTM.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-d51ac4e26536360aa29e00c5e661bc0b4adb15db)

**fixed alerts:**

* 6 for Module\-level cyclic import
* 4 for Unused import
* 1 for Except block handles &#39;BaseException&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
Fails currently because there is one more compat OrderedDict in imputation

**Comment by josef-pkt** [comment]
LGTM,
Merge when green

**Comment by josef-pkt** [comment]
This pull request **fixes 11 alerts** when merging cb897925f36bd644ad973a66c2d4b5fac2445daa into 37cbf3e5eda32101577517d9b94693f49e8e53d6 - [view on LGTM.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-b971bea5c69508b50b2d0fc60185837282ab78d2)

**fixed alerts:**

* 6 for Module\-level cyclic import
* 4 for Unused import
* 1 for Except block handles &#39;BaseException&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
@hugovk  Thank you

merged, no more python 2.6

**Comment by jbrockmendel** [comment]
Well done!

**Comment by hugovk** [comment]
Onwards and upwards!

**Pull request merged**
