### PR TITLE
CLEAN: Clean up TSA (pep8, pyflakes, warnings)

### PR DESCRIPTION
**Pull request by ChadFulton**
Just some basic cleanup tasks that have accrued over time. Most visible improvement is the suppression of irrelevant warnings that began in numpy 1.12.

### CODE REVIEW

**Comment by ChadFulton** [comment]
And I should add, this is not meant to be all of TSA - just my parts of TSA :)

**Comment by ChadFulton** [comment]
I am not intending to backport these changes, but I could if that seems like a good idea.

**Comment by ChadFulton** [comment]
Rebased. I guess I will merge this if green, since it's just cleanup related things.

**Comment by bashtage** [comment]
Seems fine.  I wonder if SM should use 99 cols instead of 79.

**Comment by josef-pkt** [comment]
Wouldn't keeping the `self.ssm.` namespace be clearer or cleaner then all the `self['xxx']`?

**Comment by josef-pkt** [comment]
maybe related: Kevin put some `.ssm.` into the docstrings for 0.8.0, IIRC

**Comment by ChadFulton** [comment]
> Seems fine. I wonder if SM should use 99 cols instead of 79.

I also wonder that :)

> Wouldn't keeping the self.ssm. namespace be clearer or cleaner then all the self['xxx']?

I don't have much of a preference either way. In documentation I've been trying to use `self['name']` as a standard way to do things - it seems more straightforward for introductory purposes than having to go into details about the `ssm` object, etc. - , so I thought making the code use that form also would be best. But if you think `self.ssm['name']` is better for the internal classes, that's fine with me

**Comment by josef-pkt** [comment]
It's up to you, and I didn't look much on the details.

My thinking:
Basic users that mainly want to forecast might not care, and might/will not need to see those.
For intermediate users like me, namespaces provide useful information. Similar to the beginning when everything was inherited, it is difficult to keep track of which is which.
For me, a structure like `.data` contains the extra information about the data, `.ssm` contains the statespace representation, the main model contains the probability/stochastic model with loglike and similar, is relatively easy to pick up. 
A large flat namespace is easy to access, but it's difficult to figure out which things belong together and where to search.
For example, I might want to know what the high level attributes are that define a SARIMAX or unobserved component model, but I wouldn't care about the statespace representation unless I need something specific from it.

We do copy/alias some commonly used attributes from one class to another, but not much in general. For example, at the beginning of statsmodels we had a discussion about attaching endog and exog and similar to the results instance as a reference to the model attributes, but we never really started to do it, and I think it's better to restrict those cases.
`res_glm.model.family.link.xxx` is a bit long but the final user doesn't use it, and res_glm.model.loglike is not the same as res_glm.model.family.loglike, so the namespace is part of the name in those cases.

"
Special cases aren't special enough to break the rules.
Although practicality beats purity.
"

We don't have strict rules, except for cases where we need to have model consistency so we can write functions that work with any kind of model.

up to you and what you think might be more useful for the users of those parts.

**Comment by bashtage** [comment]
Isn't dictionary syntax annoying to work with and more-or-less undiscoverable (if one wants to)? Or is the goal to hide implementation details without resorting to lots of `_` or `__`?

**Comment by ChadFulton** [comment]
> Isn't dictionary syntax annoying to work with and more-or-less undiscoverable (if one wants to)? Or is the goal to hide implementation details without resorting to lots of _ or __?

It has to do with potentially switching datatypes, and primarily bites because of complex-step differentiation.

In a nutshell, when you do `mod['design', 0, 0] = 1` we can handle the whole operation atomically in `__setattr__`, but when you do `mod.design[0, 0] = 1`, then that's equivalent to `x = mod.design` followed by `x[0,0] = 1`. So in the latter case, all we can do in the class is give the user an object reference which they can modify.

Usually that's not a problem, but if they're changing data types (e.g. in complex step differentiation, which is the default method for computing the score) then the latter case would require:

```python
x = mod.design.astype(complex)
x[0, 0] = 1j
mod.design = x
```

whereas with the dictionary setting notation, we can do this transparently in `__setattr__`:

```python
mod['design', 0, 0] = 1j
```

If there's a better way to do this, it would be nice to support typical attribute access. Pandas, for example, has made it work. For example, in Pandas 0.13.1:

```python
x = pd.DataFrame(np.zeros((5, 2)), columns=['a', 'b'])
x.a[0] = 2.j
# raises TypeError: 'int' object is not iterable
```

whereas in the recent Pandas:

```python
x = pd.DataFrame(np.zeros((5, 2)), columns=['a', 'b'])
x.a[0] = 2.j
print(x)
#     a    b
# 0  2j  0.0
# 1  0j  0.0
# 2  0j  0.0
# 3  0j  0.0
# 4  0j  0.0
```

I haven't looked into the issue in a long time, but I think Pandas just has a lot more infrastructure involved in their Series objects, so they can do more under the hood, similar to what we're doing in `__setattr__`. But I don't know if we really want to develop an infrastructure for this (e.g. wrapping numpy matrix objects in something that allows us to handle changing dtypes).

Or maybe there's an easy solution I have missed?

**Comment by ChadFulton** [comment]
> My thinking:
Basic users that mainly want to forecast might not care, and might/will not need to see those.
For intermediate users like me, namespaces provide useful information. Similar to the beginning when everything was inherited, it is difficult to keep track of which is which.
For me, a structure like .data contains the extra information about the data, .ssm contains the statespace representation, the main model contains the probability/stochastic model with loglike and similar, is relatively easy to pick up.
A large flat namespace is easy to access, but it's difficult to figure out which things belong together and where to search.
For example, I might want to know what the high level attributes are that define a SARIMAX or unobserved component model, but I wouldn't care about the statespace representation unless I need something specific from it.

I have pretty much no opinion on what the internal classes ought to use. Either works, and if we use `mod.ssm['design']` then that is more clear, and if we use `mod['design']` then that is more consistent with the user documentation. I think just to move forward, I'll change this PR to move everything back to `mod.ssm['...']` syntax, since you've convinced me that the internal models should use the more correct method.

But I do think that it's a good thing that we at least allow accessing the system matrices as part of the MLEModel class, in the same way that in the MLEResults object I put references to many (but not all) of the output of the Kalman Filter and Smoother results.

**Comment by ChadFulton** [comment]
> handle the whole operation atomically in __setattr__

I mean __setitem__

**Comment by ChadFulton** [comment]
I think some of this cleanup will mean a rebase for #3481 since it does some of the same things.

**Comment by ChadFulton** [comment]
Looks like only bug is ongoing Appveyor statespace simulate bug, so I will merge tonight unless there are concerns.

**Comment by ChadFulton** [comment]
Merging, thanks @bashtage and @josef-pkt for your comments!

**Comment by bashtage** [comment]
Should probably skip simulate on Windows.  I'm convinced this is a linear algebra library bug since it doesn't show on Linux ever and the few debugging sessions always showed an access violation in mkl_avx2.dll.

**Comment by ChadFulton** [comment]
> Should probably skip simulate on Windows. I'm convinced this is a linear algebra library bug since it doesn't show on Linux ever and the few debugging sessions always showed an access violation in mkl_avx2.dll.

That's a good idea. I did some investigating and tried to replicate the bug, but even with your suggestions I couldn't. What's strange is that the simulation smoother is using the same BLAS / LAPACK functions as the Kalman filter and smoother, so you'd think the bug would show up somewhere other than in simulation. I need to go through the simulation smoother code carefully to check all my BLAS / LAPACK calls, but I haven't had the time yet.

**Comment by bashtage** [comment]
The strange thing is that it doesn't actually happen inside a function.  Also, AFAICT the main methods being tested were pure python (code from somewhere else, e.g., NumPy).

**Comment by ChadFulton** [comment]
> The strange thing is that it doesn't actually happen inside a function.

Yes, I guess you must be right about garbage collection.

> Also, AFAICT the main methods being tested were pure python (code from somewhere else, e.g., NumPy).

This may be misleading - the `KalmanFilter._simulate` method is overridden in `SimulationSmoother` where it uses Cython code in the newer versions (`_simulation_smoother.pyx.in`),

**Pull request merged**
