### PR TITLE
raise earlier, and raise correct exception

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
NotimplementedError in summary method causes unit tests to error/fail
(looks like we have unit tests even if summary returns None)

discrete changes look fine

**Comment by jbrockmendel** [comment]
> NotimplementedError in summary method causes unit tests to error/fail

OK, I'm happy to revert that and handle it separately, but that _should_ raise.

**Comment by jbrockmendel** [comment]
CI failure is false-positive.

**Comment by jbrockmendel** [comment]
The complaint about summary raising been reverted.

**Comment by josef-pkt** [comment]
many merges behind far behind master 
should be rebased

otherwise, green and good to merge

**Comment by jbrockmendel** [comment]
Can't use the "squash and merge" button?

**Comment by josef-pkt** [comment]
> Can't use the "squash and merge" button? (or "rebase and merge")

No, I only want no-ff merge commits to go into master, and github doesn't have an option for it. 
(That's a consequence that always squashing is not useful for us, and a mix of ff and no-ff merges is a mess for searching the git log.)

But I can rebase a PR branch myself, if I remind myself how to push to a PR on someone else's repo.

**Comment by jbrockmendel** [comment]
> No, I only want no-ff merge commits to go into master 

What's the reasoning here?  ("Personal preference" is a valid answer)  It seems like it adds a significant overhead to the review/merge process.

**Comment by josef-pkt** [comment]
The why was in the next sentence in parenthesis.

It has been our policy since soon after we switched to github and I have a very strong preference for it as  a maintainer.
(Did you ever try to find a relevant piece of information in an 800 or 3000 line commit?
or 12000 lines https://github.com/statsmodels/statsmodels/pull/3246/files 
That's all you might get if you follow up on a blame.)

It does add some overhead to merging, but it makes the git history a lot more readable and searchable.
Adding labels to issues also adds overhead to the maintainers, but issues would be almost useless without them.

**Comment by jbrockmendel** [comment]
Does the problem with "rebase and merge" also apply to single-commit PRs?

**Comment by jbrockmendel** [comment]
> Adding labels to issues also adds overhead to the maintainers

This is another place where allowing junior-maintainers could take some stuff off your plate.  Think of the pandas model, where most Big Things go through jreback while other team members help out with labels and can merge Sufficiently Obvious PRs.  #4378, #4371... could absolutely be entrusted to e.g. bashtage.

**Comment by jbrockmendel** [comment]
Big green button.

**Comment by jbrockmendel** [comment]
@josef-pkt 2 months old and a clear win; let's clear this before merge conflicts build up

**Comment by jbrockmendel** [comment]
@kshedden raise the correct exception, yah?

**Comment by jbrockmendel** [comment]
Rebased, should be spotless history.

Raising the wrong exception is a bug.

**Pull request closed without merging**
