### PR TITLE
TST: Update travis to newer packages

### PR DESCRIPTION
**Pull request by bashtage**
Change package defaults to ensure that the most recently released packages
are tested

### CODE REVIEW

**Comment by bashtage** [comment]
Simply modified one environment to always use the latest available packages. Good news is that is passes, although there is at least one warning that needs to be looked at.

**Comment by bashtage** [comment]
This has testing of

- Numpy: 1.6, 1.7,  1.8, 1.9
- Scipy: 0.11, 0.12, 0.13, 0.14, 0.15
- Pandas: 0.12, 0.13, 0.14, 0.15
- Matplotlib: 1.2, 1.3, 1.4
- cvxopt
- patsy: 0.2, 0.3

**Comment by jseabold** [comment]
We need to bump our minimum requirements in INSTALL.txt and docs/source/install.rst in particular for pandas, numpy, and scipy. Do you think you could do that in this PR, so we can keep everything together?

**Comment by jseabold** [comment]
Oh, and matplotlib.

**Comment by bashtage** [comment]
This is not an increase in the minimum version being tested.  The only change is that it adds a "bleeding" edge (but still released) test case.

Of course, minimum versions needs to be communicated.  I assume the minimums are , as of now:

Python: 2.6
Numpy: 1.6
Scipy: 0.11
Pandas: 0.12
Matplotlib: 1.2
patsy: 0.2

**Comment by josef-pkt** [comment]
TravisCI looks fine with this
merging

Thanks @bashtage

**Comment by jseabold** [comment]
It looks like our "minimum" as tested by travis are different than what we list in the places I mentioned, no?

**Comment by josef-pkt** [comment]
This PR didn't change the tested minimum version.

But the minimum versions in the docs are outdated, and need to be changed before the release.

statsmodels might be compatible with more than we test on TravisCI, but it won't be guaranteed.

**Comment by josef-pkt** [comment]
nipy debian has no test failures with scipy: 0.10.1

http://nipy.bic.berkeley.edu/builders/statsmodels-py2.7-wheezy-sparc/builds/147/steps/shell_5/logs/stdio

although it didn't manage to cythonize
http://nipy.bic.berkeley.edu/builders/statsmodels-py2.7-wheezy-sparc/builds/147/steps/shell_4/logs/stdio

I don't know why tests still run

log with versions is http://nipy.bic.berkeley.edu/builders/statsmodels-py2.7-wheezy-sparc/builds/147/steps/shell_6/logs/stdio

main page is http://nipy.bic.berkeley.edu/waterfall?category=statsmodels

**Pull request merged**
