### PR TITLE
catch the correct exception, make assertions not-pointless

### PR DESCRIPTION
**Pull request by jbrockmendel**
Gesture of goodwill

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt free lunch

**Comment by jbrockmendel** [comment]
@kshedden little help?

**Comment by jbrockmendel** [comment]
@josef-pkt easy win here, would be nice to get it out of the way before rebasing becomes necessary.

**Comment by jbrockmendel** [comment]
@josef-pkt I'm volunteering to maintain/modernize tests.  I have domain expertise in "giving a darn".

**Comment by jbrockmendel** [comment]
@josef-pkt trivial PRs get merged in a timely manner, yah?

**Comment by josef-pkt** [comment]
Sorry, I'm still stuck in outlier_influence for MLE. I needed to read around a bit to understand some of the small print that I had misinterpreted in fast reading. 
(What are the common features and methods that we need so we can inherit Influence for ZINB, accelerated failure time, beta regression, censored models like tobit, and so on, plus for the case when we add in some penalization or robust estimation.)

**Comment by jbrockmendel** [comment]
Seriously buddy, empower Kevin to handle these so we can fix this stuff without bothering you.  This is a 5 line diff, not at all a Design Decision.

**Comment by josef-pkt** [comment]
trying out my updated git for windows (and getting notebook ready for vacation)

I rebased this branch and force pushed to `https://github.com/jbrockmendel/statsmodels.git catcher`

**Comment by jbrockmendel** [comment]
so... green button?

**Comment by josef-pkt** [comment]
Yes, green button

Thanks for the fix

**Pull request merged**
