### PR TITLE
DOC: Updated duration.rst to display output

### PR DESCRIPTION
**Pull request by kryptec**
duration.rst was using the "code-block" tag instead of the "ipython" tag used elsewhere in the documentation, causing the python output to not appear. I switched the "code-block" tags to "ipython" tags, added okwarning/okexcept flags so it would run, and savefig flags so the figures would be saved. The code itself had to be slightly modified so sphinx would run it as well.

### CODE REVIEW

**Comment by kryptec** [comment]
@bashtage I'm not sure why this is failing now since I only touched the documentation?

**Comment by bashtage** [comment]
@kryptec The failure is unrelated to you.  Some upstream issues.

**Comment by bashtage** [comment]
I'll merge if the doc build is OK.

**Comment by bashtage** [comment]
DOc build passes, thanks.

**Pull request merged**
