### PR TITLE
MAINT: Fix UserWarning: marker is redundantly defined (Matplotlib v 3.4.1) 

### PR DESCRIPTION
**Pull request by CrafterKolyan**
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

Matplotlib version: **3.4.1** (released 31.03.2021)

Code to reproduce:
```
import numpy as np
from statsmodels.graphics.gofplots import qqplot

qqplot(np.random.randn(5))
```

image

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by CrafterKolyan** [comment]
Another possible fix may be deleting line 979 in `statsmodels/graphics/gofplots.py`

https://github.com/statsmodels/statsmodels/blob/d42dc3f3c63edf0e2eb08f9297705ed9333c4357/statsmodels/graphics/gofplots.py#L978-L983

**Comment by josef-pkt** [comment]
Thanks for the fix

looks good to me, 
can you check that all calls to do_plot use the marker or plot_style argument?

**Comment by CrafterKolyan** [comment]
Just checked all the calls. None of them use any of `fmt` or `marker` keywords (all of them are just passing extra keywords given to them to `_do_plot`). Maybe that means that we should put `fmt` keyword inside `plot_style` dict as unification.

**Comment by josef-pkt** [comment]
What does fmt do in the matplotlib `step` function?

If `fmt` is only useful for non-step `plot`, we could treat it the same way as `where` and `pop` it from `plot_style`

**Comment by CrafterKolyan** [comment]
The same as for `plot`: defines some formatting of plot (like color of line):
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.step.html

**Comment by CrafterKolyan** [comment]
Looking at the tests seems that this actually doesn't work. Will revert latest commit

**Comment by josef-pkt** [comment]
The way you had it in the previous, reverted commit, `fmt` only specified the color in the default.
AFAIU, this would work with both step and plot functions.

What was the problem with the previous commit then?

**Comment by CrafterKolyan** [comment]
Azure tests failed https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=3268&view=results

**Comment by CrafterKolyan** [comment]
Oh, I actually understood what is the problem. `fmt` should be not a keyword argument to `step` function. I will add extra PR for this.

**Comment by josef-pkt** [comment]
ok, looks like `fmt` is a positional argument and not a keyword argument in the plot and step functions.

we can just use your first commit then.
can you squash or remove the reverted commit, or do you have other ideas

**Comment by CrafterKolyan** [comment]
I don't have any other ideas and I think that PRs should small enough. As I know maintaners have button `Squash & Merge` so that I wouldn't need to delete commits by myself but as you said that explicitly I'll just `reset HEAD` to `HEAD~2`

**Comment by josef-pkt** [comment]
combine the two PRs

we don't use squash merges, because that doesn't show a "merge" anymore, it makes a direct commit to master/main

**Comment by CrafterKolyan** [comment]
Ok, merged two PRs

**Comment by josef-pkt** [comment]
Thanks, LGTM

will merge when green

**Comment by josef-pkt** [comment]
all green, merged

**Pull request merged**
