### PR TITLE
Fix converged key type from string True to bool True

### PR DESCRIPTION
**Pull request by jbrockmendel**
Addresses #3857
correct issue #2857

### CODE REVIEW

**Comment by josef-pkt** [comment]
@jbrockmendel  Do you know how to rebase your PRs? If not, then I will take over some of your PRs.
I would like to merge some PRs over the next week, at least those that I can fit in a half hour or one hour time slot.

This looks ready to merge after rebase. rebase because it is far behind master, and it had one broken test run (which was presumably unrelated to this PR).

**Comment by jbrockmendel** [comment]
Still getting the hang of it, appreciate the gentle nudge.  Let's see if the [collection of git commands] i just did achieved the desired result.

**Comment by josef-pkt** [comment]
you can use git gui to inspect your branch before pushing and before committing. That's what I usually do because I like the visual window to browse what is currently staged for commit, before committing.

Based on the commit messages here it looks more like you merged master into your branch

git rebase upstream/master 
in the current checkout of the feature branch and after fetching from remote

Now, it will take more to recover, unless you kept a backup branch. Always experiment on a temp branch until you are sure what to do. (I still do it maybe a third of the time where I need several tries until I get what I wanted.)

**Comment by josef-pkt** [comment]
Unless you have a backup branch, I can use the PR branch I fetched earlier today and push it to a new PR for merging. Then we don't have to clean up this one.

**Comment by jbrockmendel** [comment]
The closest thing I have to a backup branch has a ton of other edits in it that don't belong in this PR.  It sounds like solving this yourself is faster/easier than reviewing more of my fumbling.  If so, go for it.

**Comment by josef-pkt** [comment]
rebased version is at 3781

**Pull request closed without merging**
