### PR TITLE
FIX: Remove unnecessary sort in seasonal plot

### LINKED ISSUE #2110: [tsa] Why is the data sorted in the seasonal plot
At first, it seems counter intuitive to sort the Series when plotting a seasonal_plot (month- or quarter-, e.g.), what is the reason for this ? https://github.com/statsmodels/statsmodels/blob/master/statsmodels/graphics/tsaplots.py#L190

The result of a month plot makes more sense (to me) when it is not sorted. Maybe it should be optional ?

I've also added a trendline to each group, which adds some info on the behaviour of the changes through the years: this is an example of 30 years temperature data, monthly plotted: 

temp

What do you reckon ?

### PR DESCRIPTION
**Pull request by bashtage**
Replace sort/sort_values with sort_index
Fix documentation
Change average line color to red by default to improve aesthetics

closes #2110

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks, do you know what's the minimum pandas version for this?

**Comment by bashtage** [comment]
pandas 0.12 has inplace=True, at least for DataFrame. I need to test against 0.12 for Series since I think this is causing problems.

**Comment by bashtage** [comment]
@josef-pkt Works with all tested pandas now, at the cost of a tiny amount of inefficiency.

**Comment by josef-pkt** [comment]
good, merging

@bashtage  thank you, I didn't understand that issue

**Pull request merged**
