### PR TITLE
BLD: Make appveyor wheels as artifacts

### LINKED ISSUE #3786: Any interest in appveyor wheels?
We live in a Windows world, and building statsmodels on windows can be a little confusing, especially because the compiler is python version-specific. Additionally, we don't have wheels on pypi for windows and statsmodels 0.8.0. (Kind of some self-interest here because at work my personal desktop I can install the windows build tools. On some other machines, I can't but I can install wheels. I love statsmodels, but lacking the ability to `pip install statsmodels` always makes me do some extra steps.)

I played with having appveyor build wheels and it seems to add about 1 minute per build... so a total of 3 minutes for the current setup. That would get us windows wheels for python 2.7 and 3.6 (most of the time... when the whole statespace bug doesn't crash). 

Appveyor  could also theoretically upload the wheels to pypi only when master is compiled (and/or on a tag).

### PR DESCRIPTION
**Pull request by thequackdaddy**
Here's a potential way of getting wheels using appveyor. 

Closes #3786

A few notes:
* From #3728, #3386 and others, `statsmodels.tsa.statespace.tests.test_simulate` has some unexplained errors. I separated the nosetests out... once where I run everything but `statsmodels.tsa.statespace.tests.test_simulate`, and again where I only run `statsmodels.tsa.statespace.tests.test_simulate`. On 16 different runs, I've yet to get a failure... It may be best to just drop testing that module on appveyor. Given that getting the failure to trigger is quite temperamental, this might not "fix" the problem... but it seems more stable to me. 
* The build has taken anywhwere between 40 minutes and 55 minutes. I'm testing on 2.7, 3.4, 3.5, and 3.6. Potential speedups include only doing a build on certain platforms and skipping tests. I'm using the appvyor pre-installed miniconda to save some build time. 
* The wheels are saved as artifacts in appveyor. Below are wheels of interest
  * [python27](https://ci.appveyor.com/api/buildjobs/qwmta8vyg1sudf67/artifacts/dist%2Fstatsmodels-0.8.0-cp27-cp27m-win_amd64.whl)
  * [python34](https://ci.appveyor.com/api/buildjobs/8dax9clsa38jyrd0/artifacts/dist%2Fstatsmodels-0.8.0-cp34-cp34m-win_amd64.whl)
  * [python35](https://ci.appveyor.com/api/buildjobs/w6l130ltrl46uns1/artifacts/dist%2Fstatsmodels-0.8.0-cp35-cp35m-win_amd64.whl)
  * [python36](https://ci.appveyor.com/api/buildjobs/xkhcfs79sdqmu6yk/artifacts/dist%2Fstatsmodels-0.8.0-cp36-cp36m-win_amd64.whl)
* These artifacts could be auto-uploaded somewhere (S3, Azure Blobs, even pypi using twine).
* I get some warning messages saying, `C:\Miniconda36-x64\lib\site-packages\wheel\pep425tags.py:77: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\Miniconda36-x64\lib\site-packages\wheel\pep425tags.py:81: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect` This sounds serious to me, but I don't understand it. 

Let me know if you think I'm on the right path here.

### CODE REVIEW

**Comment by josef-pkt** [comment]
the wheels show 0.8 instead of 0.9-dev in the filename.
setup.py shows minor version at 8, so most likely I forgot to change that.
yes, my current master checkout shows
>>> statsmodels.__version__
'0.8.0.dev0+8953227'

**Comment by josef-pkt** [comment]
PY_DEBUG and WITH_PYMALLOC sound like noisy warnings, and should default to the right options (standard cpython binaries)
https://mail.python.org/pipermail/distutils-sig/2017-January/029965.html https://github.com/pypa/pip/issues/3383
Google doesn't find any recent messages on this so the build environment on appveyor might be older where this was not correctly silenced or inferred.

**Comment by josef-pkt** [comment]
`statsmodels.tsa.statespace.tests.test_simulate` can be skipped on appveyor
at least for now, until somebody want to play the guessing game, then it can be re-enabled in a PR.

About the rest I have pretty much no information

**Comment by josef-pkt** [comment]
`statsmodels.tsa.statespace.tests.test_simulate` can be skipped on appveyor
at least for now, until somebody want to play the guessing game, then it can be re-enabled in a PR.

About the rest I have pretty much no information

**Comment by thequackdaddy** [comment]
@josef-pkt Thanks for looking into the warnings. Sounds like they are benign. I noticed the same errors in some other projects that were producing windows wheels (scikit-learn is an example.) If its good enough for them, its good enough for me. 

I changed the version number to 0.9.0, but I notice that the wheel doesn't put "dev" in the filename. Haven't played with it much, but that would be nice. 

As for uploading this to the "cloud storage", I presume (after reading about this) we are talking about this:
http://wheels.scipy.org/ There's some code that scikit-learn is using in their appveyor that seems pretty straightforward to implement. However, we'd need some kind of a login. Any idea how to get that?

**Comment by thequackdaddy** [comment]
@josef-pkt If I've done this right, I think it will create windows wheels for 2.7, 3.4, 3.5, and 3.6 as artifacts which i guess we could download for pypi

**Comment by thequackdaddy** [comment]
They should be available for downlaod here:

https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.3194

On the artifacts tab

**Comment by thequackdaddy** [comment]
Tehre's a few zombie appveyor runs... they can be killed i fyou are impatient.

**Comment by josef-pkt** [comment]
I didn't know.
I just checked an old build of this PR and saw the wheels.

**Comment by thequackdaddy** [comment]
Win amd64 0.9.0rc1 wheels are here:

[python 2.7](https://ci.appveyor.com/api/buildjobs/oeonww4agwof3hpj/artifacts/dist%2Fstatsmodels-0.9.0rc1-cp27-cp27m-win_amd64.whl)
[python 3.4](https://ci.appveyor.com/api/buildjobs/ana69ws3sw9lbow9/artifacts/dist%2Fstatsmodels-0.9.0rc1-cp34-cp34m-win_amd64.whl)
[python 3.5](https://ci.appveyor.com/api/buildjobs/u9eyq29org4v9x82/artifacts/dist%2Fstatsmodels-0.9.0rc1-cp35-cp35m-win_amd64.whl)
[python 3.6](https://ci.appveyor.com/api/buildjobs/ra2nkq0849qlp72v/artifacts/dist%2Fstatsmodels-0.9.0rc1-cp36-cp36m-win_amd64.whl)

**Comment by josef-pkt** [comment]
I tried the python 3.4 wheel
It looks like there are some pyd binary extension files missing in statespace, there is only one in the wheel in tsa/statespace but I have 6 in my local inplace build

maybe missing in manifest or package data

**Comment by josef-pkt** [comment]
this might also be that the binary is scipy version dependent.
The python 3.4 on appveyor uses a scipy that is to old
scipy:           0.14.0-np19py34_0

I think we need to build against newer scipy, e.g. I'm using scipy 0.18.1 with python 3.4
AFAIU, The break in how the statespace is compiled against scipy is with >= 0.16
If someone wants statsmodels compatible with scipy < 0.16, then they have to compile statsmodels themselves.

I will try more tomorrow.

**Comment by thequackdaddy** [comment]
From some google searching, maybe we need to lock down against the more common spicy/numpy versions and build a variety of wheels for each?

**Comment by josef-pkt** [comment]
So, from what I can see we need to fix the numpy and scipy version for the wheel build.
I guess we could use winpython as reference, i.e. versions of numpy and scipy that were current when the corresponding Python was released, or maybe stay one version below that if that's not too old.

**Comment by josef-pkt** [comment]
as background see my second most voted stackoverflow answer
https://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling/18369312#18369312
(where I don't get the same error message now with pip install)

**Comment by thequackdaddy** [comment]
I followed Winpython's versions from here:

https://github.com/winpython/winpython/tree/master/changelogs

Testing this:

```
environment:
  matrix:
    - CONDA: C:\Miniconda-x64
      NUMPY: "1.9.1"
      SCIPY: "0.14.0"
    - CONDA: C:\Miniconda34-x64
      NUMPY: "1.9"
      SCIPY: "0.15.1"
    - CONDA: C:\Miniconda35-x64
      NUMPY: "1.11.1"
      SCIPY: "0.18"
    - CONDA: C:\Miniconda36-x64
      NUMPY: "1.11.2"
      SCIPY: "0.18.1"
```

Doing it on my personal appvyeor so I won't screw over other people:

https://ci.appveyor.com/project/thequackdaddy/statsmodels/build/1.0.233

**Comment by josef-pkt** [comment]
https://pypi.org/project/numpy/#history
1.14.2 Mar 12, 2018
1.13.3 Sep 29, 2017
1.12.1 Mar 18, 2017
1.11.3 Dec 19, 2016

https://pypi.org/project/scipy/#history
1.0.1 Mar 24, 2018
0.19.1 Jun 23, 2017
0.18.1 Sep 19, 2016

**Comment by josef-pkt** [comment]
scipy should be > 0.16

I would go for 1.11 and 0.18 latest micro release (i.e. 1.11.3 and 0.18.1 if it needs to be fully specified) for all python
(around 1.5 years old)

**Comment by thequackdaddy** [comment]
Shoot I missed your comment. BRB

**Comment by thequackdaddy** [comment]
OK building here sans tests to save time:

https://ci.appveyor.com/project/thequackdaddy/statsmodels/build/1.0.236

2.7 and 3.4 are built. I can rerun with tests, if wanted.

Unfortunately, only my work computers are windows, so I can't test locally until Monday.

**Comment by josef-pkt** [comment]
I'm running the 3.4 tests right now, and will try 3.6 a bit later.
the 3.4 wheel pip installed without problems in my virtualenv, and tests are running without problems so far.

I don't have a 3.5 version yet, and the python 2.7 that I have are too old and 32bit, which we don't want to support (early 2015, 3 years old, scipy < 0.16)

**Comment by josef-pkt** [comment]
It didn't last, the unit test segfaulted in statespace\tests\test_simulate.py running the test suite based on an appveyor 3.4 wheel.
(Yesterday I got a test failure with shape mismatch in one of the simulate tests, but I thought this was my screwed up build process.)

**Comment by josef-pkt** [comment]
When I remove the test_simulate from the test run, then it finishes without problems but one test failure with cvxopt

long pytest failure message

```
================================== FAILURES ===================================
________________________________ test_testers _________________________________

    def test_testers():
        # Smoke test

        np.random.seed(2432)

        n = 200
        p = 50

        y = np.random.normal(size=n)
        x = np.random.normal(size=(n, p))

        testers = [kr.CorrelationEffects(),
                   kr.ForwardEffects(pursuit=False),
                   kr.ForwardEffects(pursuit=True),
                   kr.OLSEffects()]

        for method in "equi", "sdp":

            if method == "sdp" and not has_cvxopt:
                continue

            for tv in testers:
>               RegressionFDR(y, x, tv, design_method=method)

..\try_py34\lib\site-packages\statsmodels\stats\tests\test_knockoff.py:81:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\try_py34\Lib\site-packages\statsmodels\stats\_knockoff.py:83: in __init__
    exog1, exog2, _ = _design_knockoff_sdp(exog)
..\try_py34\Lib\site-packages\statsmodels\stats\_knockoff.py:161: in _design_kn
ckoff_sdp
    sol = solvers.sdp(c, G0, h0, [G1], [h1])
c:\users\josef\downloads\winpython-64bit-3.4.4.5qt5\python-3.4.4.amd64\lib\site
packages\cvxopt\coneprog.py:4129: in sdp
    = ds)
c:\users\josef\downloads\winpython-64bit-3.4.4.5qt5\python-3.4.4.amd64\lib\site
packages\cvxopt\coneprog.py:1396: in conelp
    misc.update_scaling(W, lmbda, ds, dz)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

W = {'beta': [], 'd': <100x1 matrix, tc='d'>, 'di': <100x1 matrix, tc='d'>, 'dn
': <0x1 matrix, tc='d'>, ...}
lmbda = <151x1 matrix, tc='d'>, s = <2600x1 matrix, tc='d'>
z = <2600x1 matrix, tc='d'>

    def update_scaling(W, lmbda, s, z):
        """
        Updates the Nesterov-Todd scaling matrix W and the scaled variable
        lmbda so that on exit

              W * zt = W^{-T} * st = lmbda.

        On entry, the nonlinear, 'l' and 'q' components of the arguments s
        and z contain W^{-T}*st and W*zt, i.e, the new iterates in the current
        scaling.

        The 's' components contain the factors Ls, Lz in a factorization of
        the new iterates in the current scaling, W^{-T}*st = Ls*Ls',
        W*zt = Lz*Lz'.
        """


        # Nonlinear and 'l' blocks
        #
        #    d :=  d .* sqrt( s ./ z )
        #    lmbda := lmbda .* sqrt(s) .* sqrt(z)

        if 'dnl' in W:
            mnl = len(W['dnl'])
        else:
            mnl = 0
        ml = len(W['d'])
        m = mnl + ml
        s[:m] = base.sqrt( s[:m] )
        z[:m] = base.sqrt( z[:m] )

        # d := d .* s .* z
        if 'dnl' in W:
            blas.tbmv(s, W['dnl'], n = mnl, k = 0, ldA = 1)
            blas.tbsv(z, W['dnl'], n = mnl, k = 0, ldA = 1)
            W['dnli'][:] = W['dnl'][:] ** -1
        blas.tbmv(s, W['d'], n = ml, k = 0, ldA = 1, offsetA = mnl)
        blas.tbsv(z, W['d'], n = ml, k = 0, ldA = 1, offsetA = mnl)
        W['di'][:] = W['d'][:] ** -1

        # lmbda := s .* z
        blas.copy(s, lmbda, n = m)
        blas.tbmv(z, lmbda, n = m, k = 0, ldA = 1)


        # 'q' blocks.
        #
        # Let st and zt be the new variables in the old scaling:
        #
        #     st = s_k,   zt = z_k
        #
        # and a = sqrt(st' * J * st),  b = sqrt(zt' * J * zt).
        #
        # 1. Compute the hyperbolic Householder transformation 2*q*q' - J
        #    that maps st/a to zt/b.
        #
        #        c = sqrt( (1 + st'*zt/(a*b)) / 2 )
        #        q = (st/a + J*zt/b) / (2*c).
        #
        #    The new scaling point is
        #
        #        wk := betak * sqrt(a/b) * (2*v[k]*v[k]' - J) * q
        #
        #    with betak = W['beta'][k].
        #
        # 3. The scaled variable:
        #
        #        lambda_k0 = sqrt(a*b) * c
        #        lambda_k1 = sqrt(a*b) * ( (2vk*vk' - J) * (-d*q + u/2) )_1
        #
        #    where
        #
        #        u = st/a - J*zt/b
        #        d = ( vk0 * (vk'*u) + u0/2 ) / (2*vk0 *(vk'*q) - q0 + 1).
        #
        # 4. Update scaling
        #
        #        v[k] := wk^1/2
        #              = 1 / sqrt(2*(wk0 + 1)) * (wk + e).
        #        beta[k] *=  sqrt(a/b)

        ind = m
        for k in range(len(W['v'])):

            v = W['v'][k]
            m = len(v)

            # ln = sqrt( lambda_k' * J * lambda_k )
            ln = jnrm2(lmbda, n = m, offset = ind)

            # a = sqrt( sk' * J * sk ) = sqrt( st' * J * st )
            # s := s / a = st / a
            aa = jnrm2(s, offset = ind, n = m)
            blas.scal(1.0/aa, s, offset = ind, n = m)

            # b = sqrt( zk' * J * zk ) = sqrt( zt' * J * zt )
            # z := z / a = zt / b
            bb = jnrm2(z, offset = ind, n = m)
            blas.scal(1.0/bb, z, offset = ind, n = m)

            # c = sqrt( ( 1 + (st'*zt) / (a*b) ) / 2 )
            cc = math.sqrt( ( 1.0 + blas.dot(s, z, offsetx = ind, offsety =
                ind, n = m) ) / 2.0 )

            # vs = v' * st / a
            vs = blas.dot(v, s, offsety = ind, n = m)

            # vz = v' * J *zt / b
            vz = jdot(v, z, offsety = ind, n = m)

            # vq = v' * q where q = (st/a + J * zt/b) / (2 * c)
            vq = (vs + vz ) / 2.0 / cc

            # vu = v' * u  where u =  st/a - J * zt/b
            vu = vs - vz

            # lambda_k0 = c
            lmbda[ind] = cc

            # wk0 = 2 * vk0 * (vk' * q) - q0
            wk0 = 2 * v[0] * vq - ( s[ind] + z[ind] ) / 2.0 / cc

            # d = (v[0] * (vk' * u) - u0/2) / (wk0 + 1)
            dd = (v[0] * vu - s[ind]/2.0 + z[ind]/2.0) / (wk0 + 1.0)

            # lambda_k1 = 2 * v_k1 * vk' * (-d*q + u/2) - d*q1 + u1/2
            blas.copy(v, lmbda, offsetx = 1, offsety = ind+1, n = m-1)
            blas.scal(2.0 * (-dd * vq + 0.5 * vu), lmbda, offset = ind+1,
               n = m-1)
            blas.axpy(s, lmbda, 0.5 * (1.0 - dd/cc), offsetx = ind+1, offsety
               = ind+1, n = m-1)
            blas.axpy(z, lmbda, 0.5 * (1.0 + dd/cc), offsetx = ind+1, offsety
               = ind+1, n = m-1)

            # Scale so that sqrt(lambda_k' * J * lambda_k) = sqrt(aa*bb).
            blas.scal(math.sqrt(aa*bb), lmbda, offset = ind, n = m)

            # v := (2*v*v' - J) * q
            #    = 2 * (v'*q) * v' - (J* st/a + zt/b) / (2*c)
            blas.scal(2.0 * vq, v)
            v[0] -= s[ind] / 2.0 / cc
            blas.axpy(s, v,  0.5/cc, offsetx = ind+1, offsety = 1, n = m-1)
            blas.axpy(z, v, -0.5/cc, offsetx = ind, n = m)

            # v := v^{1/2} = 1/sqrt(2 * (v0 + 1)) * (v + e)
            v[0] += 1.0
            blas.scal(1.0 / math.sqrt(2.0 * v[0]), v)

            # beta[k] *= ( aa / bb )**1/2
            W['beta'][k] *= math.sqrt( aa / bb )

            ind += m


        # 's' blocks
        #
        # Let st, zt be the updated variables in the old scaling:
        #
        #     st = Ls * Ls', zt = Lz * Lz'.
        #
        # where Ls and Lz are the 's' components of s, z.
        #
        # 1.  SVD Lz'*Ls = Uk * lambda_k^+ * Vk'.
        #
        # 2.  New scaling is
        #
        #         r[k] := r[k] * Ls * Vk * diag(lambda_k^+)^{-1/2}
        #         rti[k] := r[k] * Lz * Uk * diag(lambda_k^+)^{-1/2}.
        #

        work = matrix(0.0, (max( [0] + [r.size[0] for r in W['r']])**2, 1))
        ind = mnl + ml + sum([ len(v) for v in W['v'] ])
        ind2, ind3 = ind, 0
        for k in range(len(W['r'])):
            r, rti = W['r'][k], W['rti'][k]
            m = r.size[0]

            # r := r*sk = r*Ls
            blas.gemm(r, s, work, m = m, n = m, k = m, ldB = m, ldC = m,
                offsetB = ind2)
            blas.copy(work, r, n = m**2)

            # rti := rti*zk = rti*Lz
            blas.gemm(rti, z, work, m = m, n = m, k = m, ldB = m, ldC = m,
                offsetB = ind2)
            blas.copy(work, rti, n = m**2)

            # SVD Lz'*Ls = U * lmbds^+ * V'; store U in sk and V' in zk.
            blas.gemm(z, s, work, transA = 'T', m = m, n = m, k = m, ldA = m,
                ldB = m, ldC = m, offsetA = ind2, offsetB = ind2)
            lapack.gesvd(work, lmbda, jobu = 'A', jobvt = 'A', m = m, n = m,
                ldA = m, U = s, Vt = z, ldU = m, ldVt = m, offsetS = ind,
>               offsetU = ind2, offsetVt = ind2)
E           ArithmeticError: 49

c:\users\josef\downloads\winpython-64bit-3.4.4.5qt5\python-3.4.4.amd64\lib\site
packages\cvxopt\misc.py:614: ArithmeticError
```

**Comment by thequackdaddy** [comment]
Most recent master including the `test_simulate` and `pandas` changes:

https://ci.appveyor.com/project/thequackdaddy/statsmodels/build/1.0.237

**Comment by thequackdaddy** [comment]
As always, I forgot something... here is where the new wheels will be:

https://ci.appveyor.com/project/thequackdaddy/statsmodels/build/1.0.238

**Comment by thequackdaddy** [comment]
OK for real this time... 

Wheels of master's hash...

https://ci.appveyor.com/project/thequackdaddy/statsmodels/build/1.0.239

**Comment by josef-pkt** [comment]
again a segfault in py 3.4 with the new wheel. It looks like I didn't skip enough of the tests (and didn't remember correctly in which tests appveyor sometimes hangs.
py 3.4 virtualenv
same as before:
pip uninstall statsmodels
pip install new wheel
the sm.test() segfault
running again statespace  ss.test() then everything is fine.

as check open new command window
uninstall
install
pytest path to statespace
no segfault

on python 3.6 (winpython install):

uninstall statsmodels and install new wheel

`>`pytest path to test_simulate 
pass, no segfault

```
>>> import statsmodels.tsa.statespace as ss
>>> ss.test
```
pass, no segfault

```
>>> import statsmodels.api as sm
>>` sm.test()
```
segfault in test_simulate

repeating the sm.test() - all test pass, no segfault

I'm just going to skip all tests in test_simulate on WIN

**Comment by josef-pkt** [comment]
thanks @thequackdaddy 

hopefully the last try
sdist with Mingw looks fine

**Comment by josef-pkt** [comment]
success, `ssss` helps, no more test_simulate crashes

pip install latest wheels
python 3.6 is completely green
python 3.4 is green except for the cvxopt failure

(almost ready, I'm updating the info in setup.py and README.rst, which I had forgotten.)

**Comment by thequackdaddy** [comment]
Next set of wheels:

https://ci.appveyor.com/project/thequackdaddy/statsmodels/build/1.0.243

**Comment by thequackdaddy** [comment]
I think Matthew Brett's solution is far superior... closing.

**Pull request closed without merging**
