### PR TITLE
get rid of redundant import

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt super-easy

**Comment by jbrockmendel** [comment]
free lunch

**Comment by jbrockmendel** [comment]
@ChadFulton little help?

**Comment by ChadFulton** [comment]
LGTM, very straightforward, will merge later tonight unless there are concerns.

**Comment by jbrockmendel** [comment]
Ping

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel

**Pull request merged**
