### PR TITLE
De-duplicate a bunch of identical code

### PR DESCRIPTION
**Pull request by jbrockmendel**
The first half of `irf_errband_mc` is copy/paste identical to `irf_resim`, so let's go ahead and use that instead.

Also make a helper method for a commonly-used expression in irf.

This does _not_:
- clean up any formatting
- fix the `AttributeError` that `irf_errband_mc` or `irf_resim` would raise if it were ever called.
- fix the `TypeError` that `irf_errband_mc` would raise if it that `AttributeError` were fixed.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@ChadFulton pls take a look when you get a chance

**Comment by ChadFulton** [comment]
LGTM, I think very straightforward, will merge tonight (or tomorrow if I forget) unless I hear otherwise.

**Comment by josef-pkt** [comment]
LGTM

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel for cleanup and @josef-pkt for review!

**Pull request merged**
