### PR TITLE
Use pytest.raises, pytest.mark

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
this has now a merge conflict, otherwise looks good (no changes that might have unintended side effects)

Can you rebase, then I will merge it.

**Comment by jbrockmendel** [comment]
Done.

**Comment by josef-pkt** [comment]
rebase looks good
(you missed a fetch before rebase, but it's only one merge behind, so no problem at all)

I will merge it when ci testing comes back green

**Comment by josef-pkt** [comment]
all green, merged
@jbrockmendel  Thank you

**Pull request merged**
