### PR TITLE
ENH: Add nan- and inf-protected matrix_rank

### PR DESCRIPTION
**Pull request by bashtage**
Add a matrix rank that protects against inf anf nan to
prevent LinearAlgebraErrors in NumPy

### CODE REVIEW

**Comment by bashtage** [comment]
This was needed in the distributed notebook to fix the bug.  Presumably this is really a bug in the distributed estimation code that is in the notebook since it shouldn't try and estimate a model using matrices with `nan`s

**Comment by josef-pkt** [comment]
I looked at this.  I think we check for nans when we compute ptp in this case which is cheaper, and doesn't require some duplicate computation.

Also, I think we need to put nan policy as prio-high for 0.9, i.e. change the default behavior.

In the distributed notebook: Was this in an example, where we could use `missing='drop'` or is this a consequence of internal computation?

**Comment by bashtage** [comment]
It came from something inside the distributor    original data is nan
free.  So probably a bug.  May be coming from the iteration of GLM though
for one of the group's fitted.

**Comment by josef-pkt** [comment]
Thanks, that sounds like a bug in distributed and we need an issue for it.

**Comment by bashtage** [comment]
I think it happens because of a nan entering the calculations in an interative step -- since this checks rank when creating a new model to estimate, the bug is tripped. Probably need to stop the nan somewhere much earlier -- this fix doesn't actually stop the fit from working.

**Comment by bashtage** [comment]
> Also, I think we need to put nan policy as prio-high for 0.9, i.e. change the default behavior.

IMO models that doesn't want to explicitly handle NaNs (e.g., not PCA) should simply raise and return.

**Pull request closed without merging**
