### PR TITLE
ENH: Add function HDR functional boxplot

### PR DESCRIPTION
**Pull request by josef-pkt**
rebased and squashed version of #3876

### CODE REVIEW

**Comment by josef-pkt** [comment]
for the record

```
M:\...\statsmodels_py34_pr>git gui
< I always use it to cross-check the status of the checked out branch >

M:\...\statsmodels_py34_pr>git checkout remotes/origin/pr/3876
HEAD is now at 07313ea... FIX: remove pop of dataset label
< I can to pr/#### checkout because I have it set up to fetch all PR branches >

> git checkout -b hdr-boxplot_rebased
< I had forgotten to do this, so I did it at the end in git gui before pushing>

M:\...\statsmodels_py34_pr>git fetch origin
Enter passphrase for key '/c/Users/josef/.ssh/id_rsa':

M:\...\statsmodels_py34_pr>git rebase -i master
< edit the rebase txt file that pops up in the editor>

[detached HEAD 12bcd75] ENH: Add function HDR functional boxplot
 Author: Pamphile ROY <roy@cerfacs.fr>
 5 files changed, 613 insertions(+), 12 deletions(-)
 create mode 100644 docs/source/plots/graphics_functional_hdrboxplot.py
Successfully rebased and updated detached HEAD.

< then push to remote, which I always do through git gui>
```

**Comment by tupui** [comment]
@josef-pkt thanks for the details. Will do this next time :) Btw, from what you have seen I was able to produce, if you can think about something that I can handle, don't hesitate.

**Comment by josef-pkt** [comment]
another
`>git rebase remotes/origin/master`
and force push

merge when green

**Comment by josef-pkt** [comment]
merging, green on travis, appveyor has long queue

@tupui Thanks for the new functions.

**Comment by tupui** [comment]
@josef-pkt Plesure is mine 👍 Looking forward to helping again!

**Pull request merged**
