### PR TITLE
TST: Silence warnings

### PR DESCRIPTION
**Pull request by jseabold**

### CODE REVIEW

**Comment by josef-pkt** [comment]
What are they catching?
From the log for python 3.4 on TravisCI, it doesn't reduce the warnings compared to master, e.g. https://travis-ci.org/statsmodels/statsmodels/jobs/70523150

On several python versions TravisCI doesn't show any warnings, and I get again warning at different functions in my current settings (py 2.7, scipy 0.13.3, numpy 1.6.1)

**Comment by jseabold** [comment]
Just mle convergence warnings.

**Comment by jseabold** [comment]
I saw them locally.

**Comment by josef-pkt** [comment]
OK, merging.

**Pull request merged**
