### PR TITLE
Fix small typo in error message

### PR DESCRIPTION
**Pull request by fisadev**
Just that, nothing complicated.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Thanks for the PR! I was thinking that it was meant to say "Please report if you think this **is in error**", rather than "**is an error**".

**Comment by fisadev** [comment]
Oh, you are probably right (not a native english speaker, I didn't think of that option). Do you want me to change it to that?

**Comment by ChadFulton** [comment]
That would be great if you could. Thanks again!

**Comment by fisadev** [comment]
Done!

**Comment by ChadFulton** [comment]
Thanks!

**Pull request merged**
