### PR TITLE
MAINT: Add decorator for tests that use matplotlib

### PR DESCRIPTION
**Pull request by bashtage**
Add decorator for tests requirign matplotlib
Automatically skip if mpl is missing
Add option to skip from the command line

### CODE REVIEW

**Comment by bashtage** [comment]
xref #5161

**Comment by jbrockmendel** [comment]
Might be worth copying the pandas implementation?  pandas.util._test_decorators I think.  It doesn't exist in the oldest-sm-supported pandas, but will eventually.  When it does, might as well use "upstream" version.  (close enough ties between sm and pd that I think we can ignore the `_`)

**Comment by bashtage** [comment]
> Might be worth copying the pandas implementation? pandas.util._test_decorators I think. It doesn't exist in the oldest-sm-supported pandas, but will eventually. When it does, might as well use "upstream" version. (close enough ties between sm and pd that I think we can ignore the `_`)

I think this is a bit "neater" since it works both as a skipif and exposes a command line option to skip matplotlib tests. The pandas approach is pretty standard and requires importing the decorator explicitly. Both are improvements over the status quo which leaves it up to writers to roll their own.

**Comment by jbrockmendel** [comment]
Fair enough; I'm a fan of this PR's implementation.

**Comment by josef-pkt** [comment]
looks fine to me (I haven't tried how to call the functions/methods directly from code after these changes)

@bashtage Thank you

**Pull request merged**
