### PR TITLE
BUG: seasonal_decompose creates duplicates plots when used without plt.show()

### PR DESCRIPTION
**Pull request by statistactics**
Minor quality of life fix, but 
```python
import random
from statsmodels.tsa.seasonal import seasonal_decompose
idx = pd.date_range(start="2020-01-01", end ="2022-01-01", freq ="M")
test_df = pd.DataFrame({"values": [random.randint(0,100) for x in range(0,24)]}, index = idx)
seasonal_decompose(test_df).plot()
``` 

without an accompanying `plt.show()` line creates two copies of the same plot. A simple edit in the DecomposeResult class addresses this.

It's a quick one line fix so I'm not sure it warrants opening an issue. It's my first time contributing to a project, so let me know, thanks.

- [x] Closes None (Not Applicable)
- [x ] No tests added / passed. (Not Applicable
- [ x] code/documentation is well formatted.  
- [x ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by bashtage** [comment]
Doesn't tight_layout return None?

**Comment by statistactics** [comment]
> Doesn't tight_layout return None?

Yeah, it doesn't. I'm not sure why the interaction is as such, but `return fig` and `return` all lead to padding issues as shown below. I speculate that `fig.tight_layout()` edits the figure in place.

 
image

**Comment by josef-pkt** [comment]
Is this just in a jupyter notebook?
We won't fix that, it's notebook behavior

see #1265 and similar

**Comment by statistactics** [comment]
> Is this just in a jupyter notebook? We won't fix that, it's notebook behavior
> 
> see #1265 and similar

I tested this with script and you're right - it's notebook behaviour. However, my change doesn't appear to impact the script negatively. 

I fully understand though, thanks for pointing out past issues.

**Pull request closed without merging**
