### PR TITLE
cleanup robust

### PR DESCRIPTION
**Pull request by jbrockmendel**
Leaves a bunch of sub-optimal whitespace uncorrected

### CODE REVIEW

**Comment by josef-pkt** [comment]
merging this would most likely cause too many merge conflicts with ope PRs (that are waiting for some R robustbase experience and unit tests)

**Comment by jbrockmendel** [comment]
If only there were a way to "rebase" a PR...

**Comment by josef-pkt** [comment]
How often did you rebase a PR branch that has merge conflicts in every second commit, and where it is not always clear what the conflict resolution should be?

It's fun that I could do without, if I could.

**Comment by jbrockmendel** [comment]
Can you point to which PRs you have in mind?  I'll take a look and see what the rebasing would _actually_ look like.  I expect FUD is at work here.  A bullet will have to be bitten if this kind of readability-cleanup is ever going to happen.

**Comment by josef-pkt** [comment]
https://github.com/statsmodels/statsmodels/pulls?q=is%3Aopen+is%3Apr+author%3Ajosef-pkt+label%3Acomp-robust
the main PR with code overlap is #1341

**Comment by jbrockmendel** [comment]
#1341 is 4 years old and needs significant cleanup/modernization anyway.  Besides which it doesn't _actually_ overlap that much with this PR.

**Comment by jbrockmendel** [comment]
Another reason to push these cleanups through: it makes it much easier to distinguish parts of the code that need attention from those that are in good shape.

**Pull request closed without merging**
