### PR TITLE
BUG: Changed to 'inverse of sigma (np.linalg.inv)' instead …

### PR DESCRIPTION
**Pull request by molgor**
…of the 'pseudo-inverse (np.linalg.pinv)'. Pseudo-inverse does not always preserve positive definiteness of sigma.

### CODE REVIEW

**Comment by josef-pkt** [comment]
changing to inv looks good to me. (cholesky won't work with singular matrix anyway, so pinv is not helpful)
We don't need so many comments in the code. Larger comments can be added to PR comments or issues, and if needed a link (#xxxx) to the PR or issue added.

more general:
How did you run into this? Do you have an example or can you explain what correlation structure you are using?

I never thought about a near singular case here, and it never came up. AFAIR, we don't have a model that uses this directly because in most cases we can `whiten` without constructing a full sigma or cholsigmainv.

I think if singular or almost signular sigma is a possible case, then we might also be able to use an SVD based matrix half instead of cholesky.

**Comment by molgor** [comment]
Hi @josef-pkt ,
Thank you, I´ll remove the comments and resubmit the pull request. 

Indeed it was a strange phenomenon. I was trying to perform the GLS on a relatively large dataset c.a. 35k observations. The structure was a spatial autocorrelation derived from a Whittle semi-variogram ( $\gamma (h)=(s-n)\left(1-\exp \left(-{\frac  {h^{\alpha}}{r^{\alpha}a}}\right)\right)+n1_{{(0,\infty )}}(h)$ ) with parameters: s = 0.340274656891, r = 41061.6971399, n = 0.329817414704, alpha = 1.12113685018 
When I tried to instantiate the GLS model using the covariance matrix  (35k x 35k) derived from the spatial model; a `Linear Algebra` exception for `Non Positive Definiteness` appeared .
The matrix size made difficult to replicate or inspect throughly the problem so I created subsets based on systematic and random samples. The strange thing was that in all of these samples, the GLS model, in particular the Cholesky(pseudo inverse( ) ) function composition worked without problem. The problem appeared only when using the complete matrix (~10GB size).  

I made a Cholesky decomposition for this matrix. The function returned a matrix factorization, eliminating the hypothesis that this matrix was not positive definite. I tried then to use Cholesky on  the inverse of the matrix ( using: numpy.linalg.inv ). The test passed, concluding that the numpy.linalg.pinv did not preserve the Positive Definite feature of the input matrix. 

Soon after I´ve modified the` _get_sigma` function in `regressor.linear_model.py`  to use inv instead of pinv. The GLS model gave no problems afterwards returning a satisfying  summary. 

At the moment I'm inspecting the  matrix looking for a small enough subset that can show the problem in pinv(). But it may take some time. If you want the original matrix I can try to give it to you but it´s quite heavy.

**Comment by josef-pkt** [comment]
That sounds a large problem for this that I wouldn't have expected to work. (I don't think my computer could handle it.)

Thanks for the description. I don't think an explicit sample is necessary. I might be able to construct something from random numbers. What I guess is going on is that in large samples (large number of variables) with many covariance there could be some eigenvalues that are very small and bump into the pinv  relative condition number threshold. 

The problem in this case could be that inv also becomes numerically unstable, and adding some regularization (and maybe transformation) to keep the condition number from getting too large might be computationally more robust.
 
If you run into other related problems, then I can look more into this. We have some helper functions to make covariance or correlation matrices positive (semi-) definite. 
Improved covariance/weight matrices are on my medium-term wishlist, e.g. #2942 #3197

**Comment by molgor** [comment]
Maybe a solution could be to allow the user to give either sigma or the inverted sigma instead ?
best wishes!

**Comment by ChadFulton** [comment]
I guess an example of the problem is:

```python
d = np.array([1., 0.])

q11 = 0.4
q1 = np.array([[q11, (1 - q11**2)**0.5]]).T
q2 = np.array([[-(1 - q11**2)**0.5, q11]]).T
Q = np.c_[q1, q2]

X = Q.dot(np.diag(d)).dot(Q.T)
Y = np.linalg.pinv(X)
print(np.linalg.eigh(Y))
```

gives:

```
(array([ -1.66533454e-16,   1.00000000e+00]),
 array([[-0.91651514,  0.4       ],
            [ 0.4       ,  0.91651514]]))
```

It might be nice to have a `pinvh` function for Hermitian matrices that was based on `eigh` rather than on an SVD.

**Comment by josef-pkt** [comment]
scipy has several pinv functions that should work better for different cases.
Also, in some of my newer code, I add the option of providing sigma or sigma_inv or the corresponding versions.

All those things can be changed or options added. In the past there was never an issue or usecase in many of these areas, so they got whatever default implementation that looked reasonable or is commonly used without thinking or knowing much about the numerical details and corner cases. 
We need test cases to become aware of those cases, and then PRs to make them numerically more robust.

> Edit: of course with small enough eigenvalues, surely numerical problems can pop up in just about any implementation

Numerical problems can be worked around with reparameterization, regularization/shrinkage to a target using closes strictly positive definite matrices and so on. The difficulty is to figure out when to use those, and then to implement them as an option.
(The only model case where I know the literature a bit better is for the weight matrix in GMM with many instruments. There are various proposals for regularization in general, but I haven't implemented anything yet. My other target are multivariate methods based on outlier/heavy tail robust or regularized covariance matrices instead of using the standard Pearson correlation matrix.)


Another issue: We might get several "expert options" if we want to make those decisions available to users. One example that we haven't added yet is to add a `rcond` option for users to choose the truncation threshold for relative condition number in pinv and similar linalg functions, e.g. setting rcond=0 to keep all strictly positive eigenvalues.

**Comment by josef-pkt** [comment]
merging as is. Thanks @molgor 

We can open a new issue for more general changes and improved numerical robustness.

**Comment by josef-pkt** [comment]
@molgor  To come back to your use case:

- A PR to add sigma_inv as additional optional keyword could be merged fast, and just needs a unit test that the computed cholsigmainv is the same with specifying sigma or sigma_inv

- A sparse cholsigma_inv would be possible but a more difficult decision to add. Specifically, Python doesn't have a sparse cholesky function that is license compatible (CHOLMOD has a restrictive/commercial license). Also, `whiten` can be overwritten directly, see next

- In GLSAR and other cases we can `whiten`  without computing cholsigmainv. In general a GLS subclass just needs to overwrite the `whiten` method, and add whatever extra parameters are needed for whiten to the subclass. Those are useful when there is an explicit function to whiten or we have an analytical sparse inverse matrix half   sigma^(-0.5)

**Comment by molgor** [comment]
@josef-pkt  Thank you for your comments and for merging my commit.
I'll try to add the sigma_inv keyword improvement during the forthcoming days when I find a gap. 
If I understood you correctly, are you suggesting to modify the whiten method in GLSAR. I was thinking on adding a keyword (something like using_sigma_inv='Boolean')  to the GLS constructor.

**Comment by josef-pkt** [comment]
> If I understood you correctly, are you suggesting to modify the whiten method in GLSAR. I was thinking on adding a keyword (something like using_sigma_inv='Boolean') to the GLS constructor.

No, I meant what your suggested add `sigma_inv=None` as keyword and use it if it is not None. Mention that in that case sigma is ignored.

overwriting `whiten` is a separate way for users or developers to have more flexibility in doing this

**Pull request merged**
