### PR TITLE
Bug MixedLMResults.resid for vc fix #2901

### LINKED ISSUE #2901: MixedLMResults.resid broken when vc_formula used
[example_data.txt](https://github.com/statsmodels/statsmodels/files/232593/example_data.txt)

Sample data attached. Use with the following code:

    x = pd.io.parsers.read_csv('example_data.txt') 
    m = smf.MixedLM.from_formula('sf~area*phase*stream', data=x, groups=x['cell'],
                                 vc_formula={'target': '0+target'})
    fit = m.fit()
    fit.resid

Traceback:

    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/base/wrapper.py in __getattribute__(self, attr)
         33             pass
         34 
    ---> 35         obj = getattr(results, attr)
         36         data = results.model.data
         37         how = self._wrap_attrs.get(attr)
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/tools/decorators.py in __get__(self, obj, type)
         95         if _cachedval is None:
         96             # Call the "fget" function
    ---> 97             _cachedval = self.fget(obj)
         98             # Set the attribute in obj
         99             # print("Setting %s in cache to %s" % (name, _cachedval))
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/regression/mixed_linear_model.py in resid(self)
       2132         fixed effects and the predicted random effects.
       2133         """
    -> 2134         return self.model.endog - self.fittedvalues
       2135 
       2136 
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/tools/decorators.py in __get__(self, obj, type)
         95         if _cachedval is None:
         96             # Call the "fget" function
    ---> 97             _cachedval = self.fget(obj)
         98             # Set the attribute in obj
         99             # print("Setting %s in cache to %s" % (name, _cachedval))
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/regression/mixed_linear_model.py in fittedvalues(self)
       2113             ix = self.model.row_indices[group]
       2114 
    -> 2115             mat = [self.model.exog_re_li[group_ix]]
       2116             for c in self.model._vc_names:
       2117                 if group in self.model.exog_vc[c]:
    
    TypeError: 'NoneType' object is not subscriptable

    ---> 97             _cachedval = self.fget(obj)
         98             # Set the attribute in obj
         99             # print("Setting %s in cache to %s" % (name, _cachedval))

    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/regression/mixed_linear_model.py in fittedvalues(self)
       2113             ix = self.model.row_indices[group]
       2114 
    -> 2115             mat = [self.model.exog_re_li[group_ix]]
       2116             for c in self.model._vc_names:
       2117                 if group in self.model.exog_vc[c]:

TypeError: 'NoneType' object is not subscriptable

### PR DESCRIPTION
**Pull request by kshedden**
This should close #2901 

@bburan thanks for the report

### CODE REVIEW

**Comment by josef-pkt** [comment]
change looks fine to me, merging

**Comment by bburan** [comment]
This works. Thanks!

**Comment by josef-pkt** [comment]
oops, I didn't look carefully enough.
fails on two oldest versions on travisci
https://travis-ci.org/statsmodels/statsmodels/jobs/125912018 (in master)

most likely a nan somewhere

```
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/regression/mixed_linear_model.py", line 1524, in score_full
    cov_re_inv = np.linalg.inv(cov_re)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/numpy/linalg/linalg.py", line 445, in inv
    return wrap(solve(a, identity(a.shape[0], dtype=a.dtype)))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/numpy/linalg/linalg.py", line 332, in solve
    return wrap(b.transpose().astype(result_t))
ValueError: On entry to DGESV parameter number 4 had an illegal value
```

**Comment by kshedden** [comment]
Is this failure specific to changes in this PR?

**Comment by josef-pkt** [comment]
Yes, the error is in the test that has been added in this PR.
It might be behavior in numpy <= 1.7, or I guess less likely in scipy <= 0.12

BTW: Kerby, Don't use doc strings in test functions or classes, use `#` for comments. nose uses the docstring as header instead of the function/class/method name if there is a docstring. This makes it more difficult to find out which test fails or errors.

**Comment by kshedden** [comment]
I remember now that we have to skip some other mixedlm tests with old
scipy.  I added the same skip logic to the new test.  We'll see how it does.

I removed the doc strings from the tests in test_lme.py

Kerby

**Pull request merged**
