### PR TITLE
CLN: cython cleanups

### PR DESCRIPTION
**Pull request by jbrockmendel**
trailing whitespace, `cimport numpy as cnp` instead of as `np` to disambiguate the namespaces

### CODE REVIEW

**Comment by ChadFulton** [comment]
As I have mentioned before, I do not want to change `cimport numpy as cnp` even if Pandas does that. Cython's own documentation shows otherwise: https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html.

**Comment by bashtage** [comment]
I'm also -1 on cnp since it doesn't seem to be canonical Cython and I don't
really see any meaningful gain since cython automatically intercepts the
words that are in the pxd.

**Comment by jbrockmendel** [comment]
> As I have mentioned before

[Here](https://github.com/statsmodels/statsmodels/pull/5360#discussion_r238082265) you said the exact opposite.

> since it doesn't seem to be canonical Cython

The benefit is for readers who are not familiar with the cythonc canon.

**Comment by ChadFulton** [comment]
> Here you said the exact opposite.

Wow! Sorry about causing confusion about this!

Still I stand by this viewpoint here, I think we should follow the Cython docs. I can follow up with a PR to fix my mistake in _arma_innovations.

**Comment by jbrockmendel** [comment]
> in _arma_innovations.

Also kalman_loglike.  Should grep for others (even if you're making a decision we'll all rue)

**Comment by jbrockmendel** [comment]
reverted cnp, now mostly just removing trailing whitespace

**Comment by bashtage** [comment]
LGMT. leave this for @ChadFulton.

**Comment by ChadFulton** [comment]
Would merge but there seems to be a conflict?

**Comment by bashtage** [comment]
Since @ChadFulton approved, in it goes.

**Comment by bashtage** [comment]
Thanks.

**Pull request merged**
