### PR TITLE
ENH: State space models

### PR DESCRIPTION
**Pull request by ChadFulton**
Adds state space model estimation via a Cython Kalman filter implementation along with Python wrappers and an SARIMAX estimation class.

See #1698 for development details, discussion.

### CODE REVIEW

**Comment by josef-pkt** [comment]
merging this

Thanks to Chad and everyone that helped and reviewed

**Comment by bashtage** [comment]
@josef-pkt @ChadFulton FWIW this has broken Travis with Cythonize errors.

**Comment by bashtage** [comment]
This appears to be an issue with cython 0.22.  It built fine on cython 0.21.2 on my machine.

**Comment by josef-pkt** [comment]
@bashtage  where do you see those errors?
The test runs are green and I don't see anything spot checking the logs

**Comment by bashtage** [comment]
https://travis-ci.org/statsmodels/statsmodels

**Comment by bashtage** [comment]
Cython was updated on Anaconda in the last couple of hours.

Maybe these should be `Py_ssize_t` ?

**Comment by josef-pkt** [comment]
> Cython was updated on Anaconda in the last couple of hours.

That explains why it didn't fail a few hours ago.

> Maybe these should be Py_ssize_t ?

something like this for indices.

@jseabold ?

**Comment by ChadFulton** [comment]
Simple fix, which I will submit a PR for in a sec.

**Pull request merged**
