### PR TITLE
MAINT: Consolidate "Remove Defunct X" PRs

### LINKED ISSUE #4470: Whats the point of ConstrastResults.__array__?

### LINKED ISSUE #5100: sm.examples.t_est_rlm --> supposed to be a test?

### LINKED ISSUE #5126: Identical `strip_rc` defined in setup, tools.testing, used nowhere

### LINKED ISSUE #5134: is sm.open_help ever defined?
Near the end of `statsmodels.api`:

```
chmpath = os.path.join(os.path.dirname(__file__), 'statsmodelsdoc.chm')
if os.path.exists(chmpath):
    def open_help(chmpath=chmpath):
        from subprocess import Popen

        p = Popen(chmpath, shell=True)
```

I'm not familiar with "statsmodelsdoc.chm".  Under what conditions does that exist?

### PR DESCRIPTION
**Pull request by jbrockmendel**
@josef-pkt @bashtage I'm hoping this makes it easier to get a bunch of stuff out of the way.  This closes a bunch of similarly-themed PRs and Issues.  Might be easiest to review commit-by-commit, since they are each viable standalone, and commit messages should be clear.

closes #5134 
closes #5070 
closes #4941 
closes #5109 
closes #5100
closes #5047 
closes #5126 
closes #4470

### CODE REVIEW

**Comment by bashtage** [comment]
Looks completely straightforward to me. Nothing objectionable.

**Comment by jbrockmendel** [comment]
@josef-pkt appveyor fail is false positive, de facto green

**Comment by jbrockmendel** [comment]
De facto green

**Comment by jbrockmendel** [comment]
@josef-pkt can close a bunch of stuff in one gravity-defying swoop

**Comment by jbrockmendel** [comment]
Reverted removal of undefined `open_help` per conversation in #5134.

**Pull request closed without merging**
