### PR TITLE
TST: Switch appveyor 64bit

### PR DESCRIPTION
**Pull request by bashtage**
Switched Python 2.7 to 64 bit which mostly elimiates noise which seems to be driven by small integer types.  

@ChadFulton Also found an incorrect practice of using `isinstance(*, int)` which should usually be `isinstance(*, (int, long))` for older Python.  Fixed all instances where I though it could be hit, even it accidentally.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Great, thanks for catching that!

**Comment by josef-pkt** [comment]
I assume this is good, I didn't try to check this.

merge conflict needs to be resolved, then we merge

**Comment by josef-pkt** [comment]
PR title is not really appropriate anymore, since main changes are in second commit.
I will open a new issue for Windows 32 bit, since there might be more problems hiding.

**Comment by bashtage** [comment]
These all his tsatools and so there might be some merge conflicts after you
merge one or two.  Let me know and I can rebase.  It is all imports so easy.

**Comment by bashtage** [comment]
In fairness to the title, these fixes only are needed to pass tests on Python 2.7/Windows 64

**Comment by josef-pkt** [comment]
> In fairness to the title, these fixes only are needed to pass tests on Python 2.7/Windows 64

I thought it was a 32bit problem. What kind of errors where they? (I didn't find an appveyor run with it.)
I have python 2.7 on windows 64 bit and don't remember any failures, but I haven't tested with it in a while.

**Comment by bashtage** [comment]
Win32 has problems due to multiplication of fixed precision integers, as far as I could tell. These lead to small precision errors - no outright failures.

Wind64 doesn't have these but does often return long on Python 2.7 rather than integer.  This mostly happens when inteerfacing with cython since the number of bits in a type can differ between Win32 and Win64, and so Cython uses different converters on these which can produce a long on Win64 and an int (even for very small numbers like 40, which were causing the failures).

Win32 is worth watching, but it is probably hard to replicate the failures.

**Comment by josef-pkt** [comment]
I will merge #2240 before this (when it's green), so rebase can wait a bit.

**Comment by josef-pkt** [comment]
I will merge after rebase and green Travis

**Comment by josef-pkt** [comment]
appveyor 2.7 is also green, py3 will still run for a while

merging

@bashtage Thank you

**Pull request merged**
