### PR TITLE
WIP Use SciPy to update logistic functions

### LINKED ISSUE #1442: Use expit
Maybe get micro-speedups from using expit (added in scipy 0.10) in places where we have

```
1/(1+np.exp(np.asarray(-x)))
```

In discrete. I see about a 1.15x speed-up in the operation. Might gain more after

https://github.com/scipy/scipy/pull/3426

### PR DESCRIPTION
**Pull request by PavloFesenko**
- [x] closes #1442
- [ ] tests added / passed.
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by PavloFesenko** [comment]
@josef-pkt, @bashtage Guys, could you please help me to figure this out since it's my first PR and the "good first issue" seems to be not as easy as I thought? 😅

I ran the tests locally and they break when I replace `np.exp(-X)/(1+np.exp(-X))**2` to `stats.logistic.pdf(X)` although they should be identical according to the SciPy [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.logistic.html).
https://github.com/statsmodels/statsmodels/blob/ee14184ff755cdd7818dd5d11e9e4bdf3ede0a88/statsmodels/discrete/discrete_model.py#L2355

When I run the following script in the notebook, I get almost the same results:

```python
import scipy
import numpy as np

X = np.array([-np.inf, -1.5, 0, 1.5, np.inf])

print(np.exp(-X)/(1+np.exp(-X))**2)
print(scipy.stats.logistic.pdf(X))

# [       nan 0.14914645 0.25       0.14914645 0.        ]
# [0.         0.14914645 0.25       0.14914645 0.        ]
```

However, a lot of tests fail for the following classes:

- `statsmodels/discrete/tests/test_discrete.py::TestLogitNewtonPrepend`
- `statsmodels/discrete/tests/test_discrete.py::TestLogitNewton`
- `statsmodels/discrete/tests/test_discrete.py::TestLogitBFGS`

What am I missing here? 🤔

**Comment by josef-pkt** [comment]
Sorry, but I think we are not making any of these changes.
We are keeping simple functions like logit/logistic in statsmodels so we have better control over the implementation, unless there is a specific numerical reason not to.
Also, the public methods of scipy distributions have a relatively large overhead that we want to avoid in an optimization loop.

e.g.
```
    def _cdf(self, x):
>       return sc.expit(x)
E       TypeError: ufunc 'expit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
error in a complex step derivative unit test

I didn't look yet why there are so many other test failures.

most of them are in `margins`, e.g. test_count_dummy_dydxoverall
so there is either a mistake here or another problem with derivatives

**Comment by PavloFesenko** [comment]
@josef-pkt No problem, I will close this PR then. Could you please also close the corresponding issue #1442 to avoid the confusion in the future?

**Comment by josef-pkt** [comment]
if expit is really faster, then we would need to check where we don't need complex step derivatives.
However, for new nonlinear get_prediction, we will also run into the problem similar to margins and need numerical derivatives.
So, new applications would still be "safer" with our own implementation.

We still have open issue with norm._cdf which also raises with complex values, while using another scipy.special function would not.

**Comment by josef-pkt** [comment]
Thanks, and sorry about the "good first issue" issues.
I need to go through that list, some issues are pretty old, and by now I have a better idea what works and what didn't or doesn't, and which would still be relevant.

**Pull request closed without merging**
