### PR TITLE
MAINT: Update requirements

### PR DESCRIPTION
**Pull request by bashtage**
Update requirements in setup and pyproject

- [X] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by ChadFulton** [comment]
+1 on this, thanks for keeping up with it

**Comment by josef-pkt** [comment]
is the big jump in the cython version required?

**Comment by bashtage** [comment]
With Cython it makes sense to have the latest point release of any major. There are a number of platform specific changes that may affect more exotic platforms.

**Comment by ChadFulton** [comment]
Based on our usual policies at https://www.statsmodels.org/stable/install.html, for the v0.13 release we may want to bump dependencies to:

- Numpy >= 1.17 (released July 2019)
- Pandas >= 0.25 (released July 2019)
- Scipy >= 1.3 (released May 2019)

**Pull request merged**
