### PR TITLE
implement _get_start_params

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt this is already implemented in count_model, will make life better.

**Comment by josef-pkt** [comment]
looks fine in general

AFAICS, we don't have a consistent pattern

statespace mlemodel has `start_params` property and `_start_params` in subclasses
ARMA/ARIMA uses `_fit_start_params`
MixedLM has start_params handling in `fit`  (no subclasses)
GEE uses `._starting_params()` in fit


one design question is whether `if start_params is None` should be in fit or in the helper method.
In general I prefer that the simplest path doesn't go through helper functions, which makes that case much easier to understand when reading the source of `fit` (or other method)
(e.g. we had a bug in seasonal_decompose because some `if` condition was hiding in a helper function)

**Comment by jbrockmendel** [comment]
> AFAICS, we don't have a consistent pattern

This is a case where i am _totally_ happy to pump the brakes on this if it means getting a consistent pattern.  Especially w/r/t tsa, these are sorely lacking.  Aside from the "simplest past shouldnt go through the method", any particular thoughts?

**Comment by josef-pkt** [comment]
It's one typical design problem, code is written locally by different authors (in this case 4 authors) using different names and patterns for secondary function/methods/objects.

The tasks is coming up with a convention that fits all or at least most cases. Then, it can be added to a higher level class.

In this case it hasn't been a problem so far because those are currently only local, mainly internal methods.

**Comment by jbrockmendel** [comment]
After implementing _get_start_params for `Poisson` (just taking the lines Poisson.fit uses to build start_params and turning it into a method), a test_fit_regularized test fails, with a param coming back as `0.010672` instead of `0.010673`.  This suggests a) there may be a convergence-criteria issue with `Poisson.fit_regularized` and b) it may make sense for `_get_start_params` to take an argument indicating whether it is being called from fit_regularized vs from fit.

**Comment by jbrockmendel** [comment]
@TomAugspurger @ChadFulton @jseabold anybody want to weigh in on this?

The relevant code is already at the top of `LikelihoodModel.fit`; many models override `fit` _just_ to override these few lines.  This should be an obvious win.

**Comment by ChadFulton** [comment]
I don't really have a strong opinion here. Personally I like the state space models approach, because I often end up checking `start_params` to see what is going on there and I don't see why it should necessarily be private. Of course this approach falls on the side of having the `if start_params is None` check in `fit`.

**Pull request closed without merging**
