### PR TITLE
MAINT: remove example-like file that could never run

### PR DESCRIPTION
**Pull request by jbrockmendel**
Tries to load
```
koul_data = np.genfromtxt('/home/justin/rverify.csv', delimiter=';')
```

Even if the home/justin were fixed, there is no rverify anywhere else in the repo.

### CODE REVIEW

**Comment by josef-pkt** [comment]
The point of cleanup is not to just delete examples when they are not working.

Do we have other similar examples for that functionality, or is this the only example?
Is it easy to find the data on the internet?  E.g., my guess it's either in R or available from the authors of the underlying article.

**Comment by jbrockmendel** [comment]
> The point of cleanup is not to just delete examples when they are not working.

Again, you seem to think I'm doing this thoughtlessly.  Please consider alternatives.

> Is it easy to find the data on the internet?

Googling rverify.csv shows... this file on GH and sentences that end in "R" followed by sentences starting with "Verify".

At the very least this file belongs in sandbox or some examples directory with other code not expected to be usable.

**Comment by josef-pkt** [comment]
I don't know or remember any details

the website of the R package and cited author is http://www.ms.uky.edu/~mai/EmpLik.html
R package is https://cran.r-project.org/web/packages/emplik/emplik.pdf
most likely there is more info in the GSOC PRs that added emplik
there are also open issues for emplike

**Comment by josef-pkt** [comment]
A bit of digging (given that I already started)
blame leads to the commit
https://github.com/statsmodels/statsmodels/commit/4d3460764a071d2bb4ce1295fde8489d14ed8ab9
the csv file is likely the heartdata.csv
There is a unit test with test results.
AFT with heartdata example is in statsmodels\statsmodels\examples\ex_emplike_3.py

so the only unique part in koul_and_mc seems to be the Monte Carlo, which should be in a statsmodels\statsmodels\examples

(So that makes it around 1 or 2 hours to go back to see what `emplike` is doing)

aside: MLE based parametric AFT is scheduled for the near future (one of the GSOC ideas)

**Comment by jbrockmendel** [comment]
> so the only unique part in koul_and_mc seems to be the Monte Carlo, which should be in a statsmodels\statsmodels\examples

So... move the file to statsmodels/examples/koul_and_mc.py and be done with it?

**Comment by jbrockmendel** [comment]
Verdict about where to put this?

**Comment by bashtage** [comment]
Noncontroversial, but need a rebase (you shouldn't mod example files that have a notebook, since these are autogenerated).

**Pull request merged**
