### PR TITLE
BUG: Rework resid_dev for each family

### LINKED ISSUE #4209: BUG/TST: resid_deviance, GEE, GLM, family
https://github.com/statsmodels/statsmodels/issues/4208#issuecomment-357811452

https://github.com/statsmodels/statsmodels/commit/6b8a24b68f8b1ade2dcba7740d7f96a4e2ca6739#diff-20016798d17fceba2ff1d3dfec9f2e61
has most likely introduced a bug in GEEResults.resid_deviance by changing the behavior of the family resid method. GLMResults has a compensating change but not GEEResults.

AFAIR, there are no unit tests for GEEResults resid_xxx. Those could be compared to the GLM counterparts by using independence covariance structure.

families don't have unit tests by themselves

Needs checking before 0.9

### PR DESCRIPTION
**Pull request by thequackdaddy**
Here's an attempt to close #4209 

This should make it so resid_dev in GLM and GEE will give the same answer. 

Probably need a unit test or two... any ideas?

### CODE REVIEW

**Comment by josef-pkt** [comment]
LGTM

another notebook in a gist, I used it to compare and check the resids
https://gist.github.com/josef-pkt/ef0e25b623abea97db2c56ce8d44f283

I will post here a draft for a new `test_gee_glm.py` in a few minutes, based on the notebook

**Comment by josef-pkt** [comment]
New test module so we can make more comparison tests between GEE and GLM
I didn't really proof read it.
I ran it but it fails with resid_deviance in my current checkout

"...\statsmodels\genmod\tests\test_gee_glm.py"

```
import numpy as np
import pandas as pd


from statsmodels.genmod.generalized_linear_model import GLM
from statsmodels.genmod import families
from statsmodels.genmod.families import links
from statsmodels.genmod.generalized_estimating_equations import GEE
from statsmodels.genmod.cov_struct import Independence

from numpy.testing import assert_allclose


class CheckGEEGLM(object):

    def test_basic(self):
        res1 = self.result1
        res2 = self.result2
        assert_allclose(res1.params.values, res2.params.values,
                        rtol=1e-6, atol=1e-10)


    def test_resid(self):
        res1 = self.result1
        res2 = self.result2
        assert_allclose(res1.resid_response, res2.resid_response,
                        rtol=1e-6, atol=1e-10)
        assert_allclose(res1.resid_pearson, res2.resid_pearson,
                        rtol=1e-6, atol=1e-10)
        assert_allclose(res1.resid_deviance, res2.resid_deviance,
                        rtol=1e-6, atol=1e-10)
        assert_allclose(res1.resid_anscombe, res2.resid_anscombe,
                        rtol=1e-6, atol=1e-10)
        assert_allclose(res1.resid_working, res2.resid_working,
                        rtol=1e-6, atol=1e-10)


#def test_compare_logit(self):
class TestCompareLogit(CheckGEEGLM):

    @classmethod
    def setup_class(cls):
        vs = Independence()
        family = families.Binomial()
        np.random.seed(987126)
        Y = 1 * (np.random.normal(size=100) < 0)
        X1 = np.random.normal(size=100)
        X2 = np.random.normal(size=100)
        X3 = np.random.normal(size=100)
        groups = np.random.randint(0, 4, size=100)

        D = pd.DataFrame({"Y": Y, "X1": X1, "X2": X2, "X3": X3})

        mod1 = GEE.from_formula("Y ~ X1 + X2 + X3", groups, D,
                            family=family, cov_struct=vs)
        cls.result1 = mod1.fit()

        mod2 = GLM.from_formula("Y ~ X1 + X2 + X3", data=D, family=family)
        cls.result2 = mod2.fit(disp=False)


class TestComparePoisson(CheckGEEGLM):

    @classmethod
    def setup_class(cls):
        vs = Independence()
        family = families.Poisson()
        np.random.seed(987126)
        Y = np.exp(1 + np.random.normal(size=100))
        X1 = np.random.normal(size=100)
        X2 = np.random.normal(size=100)
        X3 = np.random.normal(size=100)
        groups = np.random.randint(0, 4, size=100)

        D = pd.DataFrame({"Y": Y, "X1": X1, "X2": X2, "X3": X3})

        mod1 = GEE.from_formula("Y ~ X1 + X2 + X3", groups, D,
                            family=family, cov_struct=vs)
        cls.result1 = mod1.fit()

        mod2 = GLM.from_formula("Y ~ X1 + X2 + X3", data=D, family=family)
        cls.result2 = mod2.fit(disp=False)


class TestCompareGaussian(CheckGEEGLM):

    @classmethod
    def setup_class(cls):

        vs = Independence()
        family = families.Gaussian()
        np.random.seed(987126)
        Y = np.random.normal(size=100)
        X1 = np.random.normal(size=100)
        X2 = np.random.normal(size=100)
        X3 = np.random.normal(size=100)
        groups = np.kron(np.arange(20), np.ones(5))

        D = pd.DataFrame({"Y": Y, "X1": X1, "X2": X2, "X3": X3})

        md = GEE.from_formula("Y ~ X1 + X2 + X3", groups, D,
                              family=family, cov_struct=vs)
        cls.result1 = md.fit()

        cls.result2 = GLM.from_formula("Y ~ X1 + X2 + X3", data=D).fit()


class TestCompareGamma(CheckGEEGLM):

    @classmethod
    def setup_class(cls):
        # adjusted for Gamma, not in test_gee.py
        vs = Independence()
        family = families.Gamma(link=links.log)
        np.random.seed(987126)
        #Y = np.random.normal(size=100)**2
        Y = np.exp(0.1 + np.random.normal(size=100))   # log-normal
        X1 = np.random.normal(size=100)
        X2 = np.random.normal(size=100)
        X3 = np.random.normal(size=100)
        groups = np.random.randint(0, 4, size=100)

        D = pd.DataFrame({"Y": Y, "X1": X1, "X2": X2, "X3": X3})

        mod1 = GEE.from_formula("Y ~ X1 + X2 + X3", groups, D,
                                family=family, cov_struct=vs)
        cls.result1 = mod1.fit()

        mod2 = GLM.from_formula("Y ~ X1 + X2 + X3", data=D, family=family)
        cls.result2 = mod2.fit(disp=False)
```

**Comment by josef-pkt** [comment]
travisCI doesn't want to run our code. I canceled and restarted the job, but that doesn't seem to help.
In case it doesn't get better, I will merge this based on a green appveyor.

**Comment by josef-pkt** [comment]
this also closes #4208 by adding the clip in resid_dev

**Comment by thequackdaddy** [comment]
I think Travis CI is having problems... 

traviscistatus.com

**Comment by josef-pkt** [comment]
Yes, I checked their status pages

Merging
Thanks @thequackdaddy

**Pull request merged**
