### PR TITLE
BUG: Do not attach log(exposure) to GLM

### LINKED ISSUE #2019: BUG: logged exposure is attached to GLM
If we re-create the model from _init keys that includes exposure, exposure will be logged twice.

### PR DESCRIPTION
**Pull request by jseabold**
Closes #2019. Just #2020 applied to master.

### CODE REVIEW

**Comment by jseabold** [comment]
Should we go ahead and merge this, so we can get other exposure changes in?

**Comment by josef-pkt** [comment]
which other exposure changes?

I don't think we will/should merge this without a general exposure redefinition. 
I think refactoring PRs should go into the direction of unifying definitions and consistency across models not move away from it.

**Comment by jseabold** [comment]
The ones linked above #2194 and I thought #2175 was also a PR.

I see this as mainly a bug fix PR. I'm not going to think more on design and generalize this, so feel free to close if you want to do more general refactoring.

**Comment by josef-pkt** [comment]
superseded for now by #2222 which doesn't change the attached exposure.

However, a future refactoring will make the change in the attached exposure as in this PR, but including discrete CountModels so it's handled consistently. That will be backwards incompatible **if** someone accesses the exposure attribute.

**Comment by josef-pkt** [comment]
I kept it open with milestone 0.8.
I didn't use the test in here in #2222, I just reused an existing test and only tested attributes not the fit.

**Pull request closed without merging**
