### PR TITLE
MAINT: Ensure statsmodels test suite passes with pandas CoW

### PR DESCRIPTION
**Pull request by bashtage**
- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by bashtage** [comment]
This is just a start.  There are many areas that need attention with changes coming in pandas.

**Comment by josef-pkt** [comment]
Is there a context manager for CoW, so we can turn it off locally for some computation, if needed?

(With all the changes in pandas 2.0 I'm glad I have almost all my code, core statsmodels computation, in numpy)

**Comment by josef-pkt** [comment]
Is there a way to disable copy on write for just one dataframe when creating it?

**Comment by bashtage** [comment]
As far as I know, there is not.

**Comment by bashtage** [comment]
CoW and extension types are both going to bring quite a put of pain.  I hope pandas will improve the export API towards numpy to make it simpler.

Some thoughts:

1. Never use `.values`. Either `.to_numpy()`, `asarray` or `np.require(df, requirements="W")` if writability is needed.
2. Might want an internal helper function to ensure that we get a writeable array.
3. Need to test more with pandas
4. In cython, arrays should be marked as `const`, as in `const double[::1]` as much as possible.  This is especially true for input arrays since these rarely change.

**Comment by josef-pkt** [comment]
Maybe we should add a warning to the release notes that pandas nullable and CoW are not fully supported or verified to work with statsmodels.

AFAICS, `np.require(df, requirements="W")` always makes a copy of the memory if CoW non-writable flag is set.
To avoid the copy we cannot use it by default, which I thought initially would be a way to avoid non-writable CoW arrays.

We are, in general, not supposed to modify user data and we usually don't. However, all the internal usage of DataFrames will have to be checked to see whether it works correctly with CoW.

**Comment by josef-pkt** [comment]
> As for the warning, I was wondering if we should detect if CoW is set on import and warn loudly there that CoW is incomplete and experimental in pandas and not fully tested in statsmodels, and asking users to verify bugs related to arrays with CoW off.

We could add the warning to statsmodels.api which will catch most standard users, and maybe to statsmodels.base.data for when users create a model.
Full coverage for the warning would require that we put it in all relevant modules.

**Pull request merged**
