### PR TITLE
Ros pandas compat rebased

### PR DESCRIPTION
**Pull request by josef-pkt**
rebased #3034 plus 
try disable test_ros for pandas < 0.14

### CODE REVIEW

**Comment by josef-pkt** [comment]
green, but I'm getting a warning for which I didn't find the source

```
statsmodels.imputation.tests.test_ros.Test_HaflDLs_OneUncensored.test_ros_arrays ... /home/travis/miniconda2/envs/statsmodels-test/lib/python3.4/site-packages/pandas/core/indexing.py:389: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_index,col_indexer] = value instead
  self.obj[item] = s
ok
```

@phobson  other than the warning this looks fine

I need to add a note to the docstring requires pandas >=0.14

**Comment by josef-pkt** [comment]
needed for 0.8

**Comment by josef-pkt** [comment]
output should be a copy of the dataframe, otherwise we get the SettingWithCopyWarning
also a small code simplification

should come back green and be ready to merge

**Comment by phobson** [comment]
Thanks Josef! I got back into town late last night after a quick camping trip. Give me a shout if anything comes up.

**Pull request merged**
