### PR TITLE
REF: Remove pandas dependency from tsa.arma_order_select_ic

### PR DESCRIPTION
**Pull request by kernc**
Tagging previous author, @jseabold as potential reviewer. Thanks. :beer:

### CODE REVIEW

**Comment by kernc** [comment]
Coverage percent decreased only due to _reduced total number of lines_. This build is _not_ failing. :unamused:

**Comment by josef-pkt** [comment]
BTW: https://en.wikipedia.org/wiki/Strafgesetzbuch_section_86a

I'm Austrian and I don't want to have any swastikas visible on the statsmodels pages (nor anywhere else except history related material)

**Comment by kernc** [comment]
@josef-pkt I understand. Perhaps you can too?

https://en.wikipedia.org/wiki/Swastika
http://www.sharenator.com/All_the_world_loved_Swastika_before_WWII/

**Comment by josef-pkt** [comment]
Maybe in 50 years it can be used again as regular symbol.
For now it's off-limits, at least in an international and European context, even if some villages in India are not bothered by it, and don't have the same historical context.

**Comment by kernc** [comment]
Skimming through the translation, I don't think the linked legalese applies here. The symbol bears no similarity with Nazi propaganda and shares no context with it. :innocent:

**Comment by josef-pkt** [comment]
The avatar clearly shows up as swastika. I never read the law for it, but any use of it is illegal in Germany and Austria, with some exception like making a movie or a documentary work about Nazi-Germany.
Independent of the law, I find it inappropriate and I don't want to see it in the statsmodels pages, and will be banned if necessary.

**Comment by kernc** [comment]
It shows up as swastika, but not as Nazi-Germany swastika or any symbol of related party or organizations. If it bears enough similarity, perhaps so does the [NATO symbol](http://bilderberg.org/nato.gif)? :smiley: 

Would you consider considering the PR on its technical merits if I switched the avatar?

**Comment by josef-pkt** [comment]
Like a trademark, symbols are in the eye of the viewer. For now, anything that looks similar to a swastika is a "trademark" of the Nazi or similar organizations (again, in an international or European context. There might be areas in the world where an Apple is a fruit).

Yes, I will look at the PR. The code is Skipper's but I don't think he will have time for it. I'm planning to get back into time series, statsmodel.tsa, for some time soon, in preparation for a presentation that I will be giving and for a GSOC project.

**Comment by kernc** [comment]
Pandas is a hard dependency; no need to remove it. Closing.

**Comment by josef-pkt** [comment]
@kernc  Was your initial motivation to remove pandas usage from the specific function, or as a general dependency?

pandas has been a hard install dependency for many years, but individual modules can be imported without needing to import all modules and all dependencies. Which modules and packages are imported in this case is module specific.

**Comment by kernc** [comment]
From this function only. For some reason, I was under the impression that some parts of statsmodels work without pandas (which later proved to not be the case).

**Pull request closed without merging**
