### PR TITLE
REF/ENH: more copula improvements for 0.13

### PR DESCRIPTION
**Pull request by josef-pkt**
This is mostly refactoring for a more consistent API across models.

### CODE REVIEW

**Comment by josef-pkt** [comment]
still not enough test coverage. I have a typo and unit tests didn't raise on my computer

**Comment by josef-pkt** [comment]
docs:

distribution.rst is missing BernsteinDistribution

In archimedean, most docstrings for methods are automatically inherited, still incomplete, e.g. missing Parameters, Returns sections

Do we include distributions.tools in docs? maybe not in 0.13, 
Some functions are public, no leading underscore. Many docstring include a "for internal use" comment.
Most functions are in support of Bernstein or histogram distribution.

**Comment by josef-pkt** [comment]
more args:

Copula base class has no args in `__init__`, only k_dim is added in super calls of subclasses
Archimedean and EV base classes add `self.args` in `__init__`
elliptical and Independence copulas don't have args attribute

current problem, base Copula plot functions don't handle args and assume those are implicit in methods of subclasses.

I now have `args=()` in main methods rvs, pdf, cdf, logpdf, ..., in all copulas except base Copula
In elliptical and Indepence `args` in methods are ignored, added just for consistent signature.
Elliptical needs decision how to handle correlation coefficients instead of corr matrix  as arguments/parameters.

**Comment by josef-pkt** [comment]
I guess the notebook in docs will need to be updated again after the renaming, refactoring in this PR

**Comment by bashtage** [comment]
```
waiting for workers...
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Parameter in the docstring of <function GaussianCopula.corr_from_tau at 0x7f61060b6a60> in /home/runner/work/statsmodels/statsmodels/statsmodels/distributions/copula/elliptical.py.
  warn(msg)
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Parameter in the docstring of <function GaussianCopula.corr_from_tau at 0x7f61060b6a60> in /home/runner/work/statsmodels/statsmodels/statsmodels/distributions/copula/elliptical.py.
  warn(msg)
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Parameter in the docstring of <function StudentTCopula.corr_from_tau at 0x7f61060b6f70> in /home/runner/work/statsmodels/statsmodels/statsmodels/distributions/copula/elliptical.py.
  warn(msg)
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Parameter in the docstring of <function StudentTCopula.corr_from_tau at 0x7f61060b6f70> in /home/runner/work/statsmodels/statsmodels/statsmodels/distributions/copula/elliptical.py.
  warn(msg)
/home/runner/work/statsmodels/statsmodel
```

**Comment by bashtage** [comment]
copula.ipynb is also broken.

**Comment by josef-pkt** [comment]
Thanks,
I'm refactoring elliptical right now, That should be the last refactorings in copula for now.

**Comment by josef-pkt** [comment]
This PR should be ready. Maybe one final check.

**Comment by josef-pkt** [comment]
all green and no related doc build problem
merging

**Pull request merged**
