### PR TITLE
ENH: Allow SARIMAX models with no AR or MA parts

### PR DESCRIPTION
**Pull request by ChadFulton**
This is just a corner case, which may be useful e.g. when doing some automatic model selection things.

Basically this just allows e.g. using SARIMAX to fit regression models.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Seems to pass tests. Not sure about appveyor. Fails with an abrupt "Command exited with code -1073741819" that does not looks related to these changes. @josef-pkt is this something I should be worried about?

**Comment by josef-pkt** [comment]
@ChadFulton  I have seen this several times, but it is not consistently showing up. I restarted the appveyor job just now.  Trying to search for that appveyor error code wasn't informative. It's just "some" problem with the test run, as far as I could figure out.
This **might** indicate that there are some (?) difficulties with that unit test.
(vague because I don't have any specific information)

**Comment by ChadFulton** [comment]
Appveyor is green after restart. I will merge tonight.

**Comment by josef-pkt** [comment]
I got the same error code now on my PR. I think it always stops at the same unit test
`statsmodels.tsa.statespace.tests.test_simulate.test_structural ... Command exited with code -1073741819`
maybe you could break up that test into several tests to see if it helps, and it would narrow down the possible candidates for "some problems".  The unit test looks pretty long (without checking the details).

**Comment by ChadFulton** [comment]
Good to know that it always stops there. I'll make a new issue for that.

**Pull request merged**
