### PR TITLE
ENH/DOC: Notebook describing how to create state space custom models

### PR DESCRIPTION
**Pull request by cdagnino**
… models

I'm adding an example notebook that considers different versions of state space custom models.
I start with something relatively simple and then add complexity and explain the changes

- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by cdagnino** [comment]
@ChadFulton Let me know if you have some time to comment on this :D

**Comment by bashtage** [comment]
Some of the math seems to have issues:

https://github.com/statsmodels/statsmodels/blob/9f589231162aa7151065a15ec343690e5ba91c3f/examples/notebooks/statespace_custom_models.ipynb

**Comment by ChadFulton** [comment]
> Some of the math seems to have issues:


Strange - the math doesn't render for me on Github, but when I download the notebook it rendered fine in Jupyter.  I wonder what will happen when it's rendered for the website?

**Comment by ChadFulton** [comment]
Basically, this looks great to me.  We've had a number of people with questions about custom state space models and time-varying models in particular, and I think this will be really useful. Thanks for submitting this.

- There are two things I noticed in the notebook, but I'm having trouble with Github putting the comments inline in the file, so I'll put them below.
- We need to clear the output of the notebook before we merge it in (to e.g. avoid having megabytes of images from the notebooks in Github).  You can do that when you're running the notebook, using "Cell > All Output > Clear". Then commit that clean version of the notebook.
- Finally, we need to add it in the manifest file for the web page and create an image that goes along with the title. You can take a look at https://github.com/statsmodels/statsmodels/pull/6614/files for a recent notebook addition that did this. The image isn't too important, but it's usually nice to have a graph or something to catch the eye.  Maybe the figure from the first example showing the coefficients?

The two things I noticed were:

1. Just after the "Model 2" header, you have "explain how it's an extension", which I guess maybe is a placeholder that should be removed or filled in?
2. In the "Model 3" section, under "1) The __init__ function ...", you have "Note that we didn't have to specify `k_endog` anywhere. The initialization does this for us after checking the dimensions of the `exog` matrix."  but I think maybe you meant the "`endog` matrix" instead of "`exog` matrix"?

**Comment by ChadFulton** [comment]
Two more things:

1. We haven't used type hints anywhere else, so it might be cleaner to remove those.
2. It looks like the actual definition of `TVRegressionExtended` doesn't currently take into account all of the improvements described above it (e.g. to transform/untransform).

**Comment by bashtage** [comment]
FWIW I've started adding type hints in my most recent code. I've found it provides better quality code and improves intellisense in PyCharm.

**Comment by cdagnino** [comment]
> Some of the math seems to have issues:
> 
> https://github.com/statsmodels/statsmodels/blob/9f589231162aa7151065a15ec343690e5ba91c3f/examples/notebooks/statespace_custom_models.ipynb

It looks good in my notebook! I guess it might be some edge case that Jupyter knows how to render but Github doesn't?

**Comment by cdagnino** [comment]
Thanks for the comments!

> * We need to clear the output of the notebook before we merge it in (to e.g. avoid having megabytes of images from the notebooks in Github).  You can do that when you're running the notebook, using "Cell > All Output > Clear". Then commit that clean version of the notebook. 

[DONE]

> * Finally, we need to add it in the manifest file for the web page and create an image that goes along with the title. You can take a look at https://github.com/statsmodels/statsmodels/pull/6614/files for a recent notebook addition that did this. The image isn't too important, but it's usually nice to have a graph or something to catch the eye.  Maybe the figure from the first example showing the coefficients?

 [DONE, I think]


> 1. Just after the "Model 2" header, you have "explain how it's an extension", which I guess maybe is a placeholder that should be removed or filled in?

[Yep! Filled in]

> 2. In the "Model 3" section, under "1) The **init** function ...", you have "Note that we didn't have to specify `k_endog` anywhere. The initialization does this for us after checking the dimensions of the `exog` matrix."  but I think maybe you meant the "`endog` matrix" instead of "`exog` matrix"?

[Yep, Done]

**Comment by ChadFulton** [comment]
Looks good to me, thanks for this addition! Notwithstanding my slow response, I hope you'll consider submitting additional notebooks if something occurs to you.

After merge, I'll check the website to see whether we need to resize the image (I'm not sure how it'll end up looking on the website, since it's 1000 x 300 resolution), and that the math shows up correctly.

**Comment by cdagnino** [comment]
@ChadFulton Happy to contribute! I'd be happy to talk and see if there's something else I can add.

**Comment by bashtage** [comment]
This notebook has broken the documentation build.  It is too slow and the documentation build is timing out.

**Comment by bashtage** [comment]
Will  have to omit the PyMC3 cell. 14400 draws / 15-20 draws/second > 10 minutes for a single cell.  These PyMC3 notebooks are problems for the docbuild in general. We probably need to store them as rendered.

**Comment by cdagnino** [comment]
@bashtage Do I need to change stuff on my end? The pull request says it's closed
(In any case, I can probably reduce the draws and write that they should do X number of draws to get something sensible)

**Comment by bashtage** [comment]
I have disabled building it for now, so it will appear without being run.  We need to think about how we can accommodate more complex notebooks without boring down the overall build

Nothing for you to do, and thanks for submitting the excellent notebooks.

**Pull request merged**
