### PR TITLE
ENH: Make PCA a class and add features

### PR DESCRIPTION
**Pull request by bashtage**
Encompasses all sandbox PCA routines and added features for plotting, selecting
the number of components and rapidly re-projecting on a subset of factors

### CODE REVIEW

**Comment by josef-pkt** [comment]
Another PR with a single commit and disconnected history. However, in this case I don't really care (much), and I don't think there was much history to loose.

I'm fine with merging this as is, I didn't really look at the details. For now we still need to keep the old sandbox versions around for backwards compatibility and limited use cases, but we might won't to deprecate those, to redirect current sandbox users to this.

Looks very good overall, With the additional features it looks useful for standalone PCA analysis, and might be a good starting point to expand into the multivariate statistical analysis area (with Factor analysis and similar), instead of being a just a `tools` class, especially with the expanded `data` handling.

@bashtage  can you rebase and force push again, and we hit the green merge button

Thanks

**Comment by bashtage** [comment]
Rebased so should be good once green.

**Comment by josef-pkt** [comment]
merging

Thanks @bashtage   Can you still write a short announcement for the release notes?

**Comment by bashtage** [comment]
I'll do something tonight.

**Comment by jseabold** [comment]
Release notes blurb/example/sexy graph for this would still be helpful.

**Pull request merged**
