### PR TITLE
BUG: Fix complex step score, Hessian calculations

### LINKED ISSUE #2839: BUG: Statespace: complex step differentiation with stationary initialization
Stationary initialization computes the initial state covariance matrix for the Kalman filter by solving a discrete Lyapunov equation. The discrete Lyapunov solver (in this case from Scipy) explicitly supports complex matrices, meaning that it supports operation as a complex function.

As I understand it, complex step differentiation requires the underlying function to be a real function of real variables (e.g. http://www.math.u-psud.fr/~maury/paps/NUM_CompDiff.pdf) and so when computing the initial state covariance matrix for the complex step derivative, we want the Lyapunov solver to *not* act as a complex function.

In practice, this means we want it to *not* do conjugate transposes (as it would if it were a complex function) but just regular transposes, even though the input matrices will be complex.

In a related issue, complex step differentiation is only appropriate when the underlying data and parameters are real; if they are complex, then we need to initialize the model using the Lyapunov solver operating as a complex function and compute numerical derivatives using finite differencing.

One implication of this is that the state space models need to distinguish between `loglike` calls performed as usual (in which case complex input parameters would preclude using complex step differentiation and the Lyapunov-as-complex function would be used for initialization) and `loglike` calls performed in gradient approximations (in which case complex input parameters are a result of the differentiation process and the and the Lyapunov-as-real function would be used).

### PR DESCRIPTION
**Pull request by ChadFulton**
Closes #2839.

### CODE REVIEW

**Comment by ChadFulton** [comment]
This is fine to merge after review.

**Comment by josef-pkt** [comment]
@ChadFulton I tried to read a bit through it, but it's too large for me, and I'm not familiar enough with the details.
Is there anything specific to look at, or can we just merge as is?

It would be useful for future reference, if you briefly summarize which way you went in the refactoring to work around #2839

**Comment by josef-pkt** [comment]
I merged #2836 which should work around the conda error. 

There were some SARIMAX related test failures in #2836 python 2.7.

It might be useful to rebase this if it's related
statsmodels.tsa.statespace.tests.test_sarimax.TestFriedmanStateRegression.test_mle
https://travis-ci.org/statsmodels/statsmodels/jobs/110699316

**Comment by josef-pkt** [comment]
#2836 didn't work in master, so nothing has improved yet with the two broken condas

**Comment by josef-pkt** [comment]
now master runs green again, I fixed the mkl problems (except cvxopt)

BTW: "PR" label is not needed anymore, that was before github provided the information automatically.
I will delete the label

**Comment by ChadFulton** [comment]
Rebased.

**Comment by josef-pkt** [comment]
all green

merge when you think it's ready

**Comment by ChadFulton** [comment]
Will merge if this comes back green. In the meantime, I'll explain what the refactoring did.

**Comment by ChadFulton** [comment]
> It would be useful for future reference, if you briefly summarize which way you went in the refactoring to work around #2839

Good idea. The basic idea (as far as I understand it) is that complex-step derivatives require the underlying function to be defined as a real function of real variables, but it should be possible to extend into the complex plane. This means that the underlying function shouldn't "know about" complex numbers, but should work if they are there. For example, a function which performs a conjugate tranpose wouldn't work (because it already "knows about" complex numbers), but a function which takes a regular transpose would (because it "works" on complex numbers).

There were three separate issues where complex functions show up in the state space code:

1. Discrete Lyapunov solver in stationary state initialization
2. Cholesky decomposition for matrix inversion in Kalman filter iterations
3. Parameter transformations in optimization (usually the problem comes if the transformation in question uses Cholesky decomposition, e.g. the VAR constraint)

In each of these cases, complex step differentiation will fail, as demonstrated in #2839. Below I'll talk about the solutions to these problems, but first I'll note that I have constructed unit tests against the analytic score in a very simple model (see `statsmodels.tsa.statespace.tests.test_mlemodel.test_score_analytic_ar1`), so I can check that the solution does in fact work.

**1. Discrete Lyapunov solver**

To solve the first problem, notice that one way to solve a discrete Lyapunov equation is (from `scipy.linalg_solvers`):

```
kron(a, a.conj())
lhs = np.eye(lhs.shape[0]) - lhs
x = solve(lhs, q.flatten())
```

The problem here is that the conjugation makes this into a complex function. In order to use complex step differentiation, we can simply remove the conjugation. The actual discrete Lyapunov solver used is a little more complex than this (to avoid solving a system of equations which grows with the square of the shape of `a`), but the principle is the same (see `statsmodels.tsa.statespace.tools.solve_discrete_lyapunov`).

Unfortunately, if the state space model is actually complex (e.g. complex data, complex parameters) then this approach does not work because the complex version of the function ought to be used. 66fa63f makes sure finite differencing is used if this is the case.

**2. Cholesky decomposition in Kalman filter iterations**

The Kalman filter is already equipped to optionally use LU decomposition, so if complex step differentiation is performed, the code selects the LU decomposition. The only downside is that it is a little slower than Cholesky decomposition.

The upside is that this only has any effect in multivariate models; in univariate models we can just use division (rather than matrix inversion) so we don't need either decomposition.

Furthermore, if a model uses the univariate method (added in #2845), even multivariate models can use division.

**3. Parameter transformations**

The problem here is that the optimizer uses parameters that can take on any value ("untransformed parameters"), but not all parameters are valid (e.g. negative variances), so before the parameters are put into the model they are transformed. These transformations depend on the actual model, but may in general not be consistent with complex step derivatives (e.g. the VARMAX and DynamicFactors models, both for VAR coefficient matrices and for non-diagonal covariance matrices).

The solution is to use the chain rule. Denote the loglikelihood as `l(p)` where `p` are "transformed parameters". Then we can write `L(u) = l(t(u))` is the loglikelihood in terms of untransformed parameters `u` and `t()` is the transformation function. by the chain rule, we have `L'(u) = l'(t(u)) * t'(u)`. The first term is evaluated using complex-step differentiation and the second term (for which complex step methods may be invalid, but which is typically a much less complex function) is evaluated using finite-differencing.

In models where the transform does not interfere with complex-step differentiation, a flag can be passed so that only complex-step methods are used (this is done in SARIMAX and UnobservedComponents).

**Pull request merged**
