### PR TITLE
TST: Add older scipy to Appveyor

### PR DESCRIPTION
**Pull request by bashtage**
Add SciPy 0.14 to Appveyor to catch any Windows-specific issues

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt @ChadFulton Shows the build bug on Windows with old SciPy.

**Comment by bashtage** [comment]
Obviously it is failing for now, but if it gets in then you will be able to confirm the fix.

**Comment by josef-pkt** [comment]
@bashtage Thank you

very good, we can merge as soon as we see how travis ran this

**Comment by ChadFulton** [comment]
@bashtage Thanks!

**Comment by bashtage** [comment]
@josef-pkt unlike many of my PRs, this is a single file change that has no impact on Travis.  It will predictably fail on Appveyor.

**Comment by josef-pkt** [comment]
The failure is informative because it confirms #3499 
It's good to see the test failure before fixing it

**Comment by josef-pkt** [comment]
2 green, 1 red as expected, merging

**Pull request merged**
