### PR TITLE
move linalg funcs to linalg module

### PR DESCRIPTION
**Pull request by jbrockmendel**
@kshedden we discussed this briefly in #4686.  This is nearly cut/paste, the exceptions being:

- flake8 fixups to whitespace in the smw functions
- de-privatized each of the moved functions except for `_dot` (because numpy's `dot` is already in the namespace)

### CODE REVIEW

**Comment by josef-pkt** [comment]
If you do a reformatting during move, then git will not be able to keep track of the move.
moving should usually be a clean copy first and then the fixup, then git can figure out the the clean copy is just delete and add somewhere elst the same piece of code.
(that's in git, although github doesn't follow moves)

**Comment by jbrockmendel** [comment]
OK, I'll revert the small edits for this round, thanks.

**Comment by josef-pkt** [comment]
You can still make the edits and required adjustments. But do them in a second commit after the cut-paste, then it will go into the git history as regular change to the moved code.

(I said "copy" in my previous comment, I meant "move", which in terms of git is cut and paste or delete and add.)

**Comment by jbrockmendel** [comment]
@kshedden I think the git-history concerns have been addressed, so it's all you buddy

**Pull request closed without merging**
