### PR TITLE
Fix VIF add a new function 'feature_selection_vif'

### PR DESCRIPTION
**Pull request by pydemia**
1. Fix 'variance_inflation_factor' in stats.outliers_influence :  Apply sm.add_constant process for proper results.
2. Add 'feature_selection_vif' in stats.multivariate_tools : A Function of Stepwise Feature Elimination with VIF

### CODE REVIEW

**Comment by pydemia** [comment]
The Travis CI throws 2 errors on Python 2.6, which are irrelevant to my commit :

1. KeyError: 'Canonical Correlation'
ERROR: statsmodels.multivariate.tests.test_cancorr.test_cancorr

2. KeyError: 'Wilks\xe2\x80\x99 lambda'
ERROR: statsmodels.multivariate.tests.test_manova.test_manova_sas_example
ERROR: statsmodels.multivariate.tests.test_manova.test_manova_test_input_validation
ERROR: statsmodels.multivariate.tests.test_multivariate_ols.test_glm_dogs_example
ERROR: statsmodels.multivariate.tests.test_multivariate_ols.test_specify_L_M_by_string
ERROR: statsmodels.multivariate.tests.test_multivariate_ols.test_from_formula_vs_no_formula

**Comment by josef-pkt** [comment]
Sorry for the slow response. I need to think about this and it's too far away from what I'm currently looking at.

e.g. adding the `sm.add_constant` is not backwards compatible and will most likely break current use cases.

**Comment by josef-pkt** [comment]
The `feature_selection_vif` looks fine in general. There should be no `print` in the code.

Unit tests are missing.

**Comment by josef-pkt** [comment]
This pull request **introduces 1 alert** when merging 176d5bfab88a0d0851981ac2d5a19d18848dbcc0 into 22f27667729af3e07ad4ff8a48e0e7a5570b181e - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-af6bfdf96dc27e511691d2fb1b97d89f1ef4b167)

**new alerts:**

* 1 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by pydemia** [comment]
I should apply your mentions and retry the pull request.

**Pull request closed without merging**
