### PR TITLE
Minor documentation update for regression.

### PR DESCRIPTION
**Pull request by chebee7i**
Some minor documentation cleanup for the regression module.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks, looks good

I read through the changes once, and will merge most likely on Tuesday, after another look

**Comment by josef-pkt** [comment]
Read again, looks good, and sorry for the delay

Can you rebase on current master?  Otherwise I will do it before merging.

**Comment by josef-pkt** [comment]
temporary prio-high to get it on my merge list

**Comment by chebee7i** [comment]
Done.

**Comment by josef-pkt** [comment]
@chebee7i  Thanks you, merging

**Pull request merged**
