### PR TITLE
ENH: Improve numerical stability of _ar_transparams, _ar_invtransparams

### PR DESCRIPTION
**Pull request by jcdang**
(1 - e^-x)/(1 + e^-x) = tanh(x/2) 

I modified the code to use numpy's tanh since it doesn't have the issue with large scale numbers.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Thanks! Would you mind also updating `_ar_invtransparams` to use arctanh?

**Comment by jcdang** [comment]
> Thanks! Would you mind also updating `_ar_invtransparams` to use arctanh?

I can update that specific part of the code but I don't think `_ar_invtransparams` looks correct as a whole.  [This](https://github.com/statsmodels/statsmodels/blob/599c76251354958bb72625c80eb9a3152167b680/statsmodels/tsa/tsatools.py#L645-L646) is questionable.

@jseabold Can you help?

This my proposed change:
```
    invarcoefs = -np.log((1-params)/(1+params))
```
to
```
    invarcoefs = 2*np.arctanh(params)
```

**Comment by ChadFulton** [comment]
That looks good to me. The code you referenced is a little less clear than it could be, but it seems to be computing the partial autocorrelations just fine, which is what it is intended to do.

**Comment by jcdang** [comment]
> That looks good to me. The code you referenced is a little less clear than it could be, but it seems to be computing the partial autocorrelations just fine, which is what it is intended to do.

I can tell you for a fact that `_ar_transparams` and `_ar_invtransparams` are not inverses of each other (both before and after the hyperbolic tangent changes).  I was unable to write a unit test that covers the inverse transparams because I'm uncertain how it is suppose to work.

**Comment by ChadFulton** [comment]
> I can tell you for a fact that _ar_transparams and _ar_invtransparams are not inverses of each other (both before and after the hyperbolic tangent changes). 

Can you expand on this? In practice, they seem to work as inverses.

```python
import numpy as np
from numpy.testing import assert_allclose
from statsmodels.tsa.tsatools import _ar_transparams, _ar_invtransparams

ar_params = np.r_[0.3, 0.2123, -0.1]
assert_allclose(ar_params, _ar_invtransparams(_ar_transparams(ar_params)))
```

**Comment by jcdang** [comment]
Here's one of the param inputs I caught while running ARIMA:
```
ar_params = np.r_[[63.07415068, -4.5933353, -6.1342963, -7.82067222, -9.73510476, -12.0269079, -14.95639924]]
```

It seems to be okay for params between 0 and 1 but larger numbers will throw it off

Maybe what I'm using is not a valid test scenario?
```
import statsmodels.api as sm
import numpy as np

values = np.array([x / 100.0 for x in range(0, 20)])
mod = sm.tsa.ARIMA(values, order=(7, 0, 0))
res = mod.fit()
```

**Comment by ChadFulton** [comment]
I see, thanks for the example. After applying `_ar_transparams(ar_params)`, the transformed parameters are right at the boundary of the transformation space (i.e. the roots of the associated lag polynomial are all very close to 1).

```python
ar_params = np.r_[63.07415068, -4.5933353, -6.1342963, -7.82067222, -9.73510476, -12.0269079, -14.95639924]
transformed = _ar_transparams(ar_params.copy())
p = np.polynomial.Polynomial(np.r_[1, -transformed])
print(np.abs(1 / p.roots()))
```

yields:

    [0.9999994298 0.9999999656 0.9999999656 1.           1.           1.           1.          ]

I think probably the issue is that we're losing some precision somewhere.

It's not surprising that it pops up in your example, since the transformation is to require the parameters to correspond to a stationary process, while the process that you are fitting is definitely non-stationary.

The version of the transformation in the state space library (`sm.tsa.statespace.tools.constrain_stationary_univariate` and `sm.tsa.statespace.tools.unconstrain_stationary_univariate`) work somewhat better in this particular example, but they're still not perfect.

**Comment by bashtage** [comment]
@jcdang Any chance you could implement the other direction and then we can get this merged for the upcoming release?

**Comment by jcdang** [comment]
@bashtage It's implemented already.  I didn't write a test for it.  Do you want me to add the  composed inverse test @ChadFulton gave?

**Comment by bashtage** [comment]
@jcdang Nope, goo to go then.

**Pull request merged**
