### PR TITLE
ENH: Add extra lines to summary HTML output

### PR DESCRIPTION
**Pull request by bashtage**
Ensure extra text is written to html for use in IPython

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Can you post a before / after screenshot of what this looks like? Was the extra text not showing before?

**Comment by bashtage** [comment]
Was silently dropped in html IPython.  It also dropped in LaTeX output.

**Comment by bashtage** [comment]
**Before**:

image

**After**:
image

**Comment by josef-pkt** [comment]
Most likely there is an open issue for this

**Comment by bashtage** [comment]
xref #1448

**Comment by josef-pkt** [comment]
looks good to me, seems to be far behind master

**Comment by bashtage** [comment]
Fixes all of the output types.
Additional change is to silence some noise that comes up in PyCharm due to incorrect description of input

**Comment by bashtage** [comment]
Should be ready now.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
