### PR TITLE
ENH: add Nash–Sutcliffe model efficiency coefficient to tools/eval_measures

### PR DESCRIPTION
**Pull request by jhamman**
tests and docs are included.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks,

I think we need a more informative name. maybe `rsquared` if it's the same as an out of sample rsquared in the case of linear regression.

I recently ran into using the usual insample results statistics like rsquared for use with out of sample (test or cross-validation) data both on stackoverflow and in articles that I was reading.
I think it will be useful to add a set of those with equivalent names to the in sample statistics. 
Some other examples I have seen are calculating the loglikelihood and information criteria based on llf or ssr, and deviance residual sum of squares or similar for GLM models.

**Comment by jhamman** [comment]
I'd be fine with `rsquared()` or `nash_sutcliffe()`.  

What other in/out of sample statistics were you thinking of.  In hydrology, which is my field of study, we also use the Kling-Gupta Efficiency measure quite regularly.

**Comment by jhamman** [comment]
@josef-pkt - just to clarify, were you suggesting that we should use this PR as an opportunity to add more out of sample statistics or would renaming `nash_sutcliff` to `rsquared` be sufficient to close this?

For my work, the other statistic I'm interested in adding is the [Kling-Gupta efficiency (KGE)](https://www.rforge.net/doc/packages/hydroGOF/KGE.html).

**Comment by josef-pkt** [comment]
@jhamman  Sorry, I have a very short attention span these days, except for whatever I'm trying to figure out for future additions to statsmodels.

We will add `rsquared` for sure, however master is currently on hold hoping for an 0.7 release or at least tagging.

I had browsed a bit the hydrogof package documentation.
My impression is that there are many variation on measures that might not be used much outside of hydrology. Based on my quick browsing I didn't figure out if they have more widely used or known equivalents.

Given that the functions will be low maintenance once they have enough unit tests, I don't see a real problem to add one or some of them.

I was thinking of three possibilities
- add individual measures: but then they need descriptive names and they will be in the common namespace
- add a main one that combines several, like `kgefficiency` (or similar)
- add many of them but put them in a common namespace (e.g. a HydroGof class) but then they won't get advertising for individual measures.

**Comment by jhamman** [comment]
First, I'm not in any rush to get this into `statsmodels`, lets wait until 0.8 or whatever comes after 0.7. My larger motivation for this PR was to make a connection here and see if we can get a few of the most commonly used statistical measures in hydrology into a widely used and maintained project like `statsmodels`.

I'm not particularly interested in developing a HydroGof class. These measures are not unique to the R package that I pointed you to, rather, they were the first reference I found that showed you the KGE measure.

How do you feel about creating a new module called `gof` or `goodness_of_fit` (or something else) and using many of the HydroGOF functions, and allow for the inclusion of other measures from outside hydrology?

**Comment by josef-pkt** [comment]
I saw KGE also in some other packages, in a wider range but mostly hydro or environmental or climate, IIRC

There are already `gof` modules, but those are for full hypothesis testing, like kolmogorov-smirnov or chisquare tests.
I started the `eval_measures` to have a collection of functions that can be used to compare simulations with true data. But the more recent use cases are as cross-validation prediction accuracy measures. (There is also an open issue for more classification accuracy measures to complement those for continuous variables.)

So, if it's mainly a collection of goodness of fit measures instead of hypothesis tests, then I would prefer to keep them with eval_measures, or a similar module.

You could prepare a PR and see if you can find some reasonably informative names, and I will review and merge for 0.8.

-----
another thought:

These eval measures were intended for use as helper functions where any data handling is taken care of by the caller or the data are already in clean arrays, for example after a MonteCarlo run. So far, the information criteria are the only ones directly reused in the model or results classes.

I don't know if it's useful to extend them with missing value and pandas data handling, similar to the R function.

**Comment by jhamman** [comment]
@josef-pkt - I just spent a few minutes and cleaned this PR up. I went with your option 1 from https://github.com/statsmodels/statsmodels/pull/2433#issuecomment-111236173 as these two functions fit best in `eval_measures`. I'm not really prepared to go much further on this right now but a colleague (@lizaclark) was recently looking for these functions so I figured I'd get this completed.

**Pull request closed without merging**
