### PR TITLE
CLN: Lint for missing whitespace around modulo operator E228,E401

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@ChadFulton no merge conflict here if we can keep some momentum going

**Comment by ChadFulton** [comment]
LGTM, will merge tomorrow unless concerns.

**Comment by jbrockmendel** [comment]
@ChadFulton ping; no concerns have been raised

**Comment by ChadFulton** [comment]
Will merge now. BTW will be busy for next two weeks. Limited response to pings.

**Pull request merged**
