### PR TITLE
DOC: Verify doctests

### PR DESCRIPTION
**Pull request by bashtage**
Verify doc tests execute.  Final result is not verified due to
precision issues across platforms/BLAS implementation

### CODE REVIEW

**Comment by bashtage** [comment]
Does some initial clean up by runnign doc tests to see if examples actually work.  Biggest issue is missing data.

In particular `datasets.bc` is referenced but not available.  Another examples uses formulas and `Days` and `Weight` as variables but this doesn't match any dataset. 

GEE doesn't load data in the examples and so it isn't possible to tell if these work correctly.

**Comment by josef-pkt** [comment]
The problem is that requiring doctests to pass makes examples really ugly, so we never decided to do that (nor numpy and scipy if my information is still up to date).

I haven't tried running doctest over our docstrings in several years. The trend is that we put more examples into notebooks which are easier to run.

**Comment by bashtage** [comment]
The issue is that lots of doctests are simply wrong - not just not working,
because things have moved.  Wrong doctests end up in docs, which makes docs
wrong.

So far having working doctests doesn't really make things ugly.  Maybe a
line or two more.

**Comment by bashtage** [comment]
One can always say "See Example Notebooks" rather than putting in an example that may become broken.

**Comment by josef-pkt** [comment]
Related: 
Debian is checking whether building the documentation is reproducable, and statsmodels and many other python packages fail in this. Some of the problems are datetimes in `summary`, floating point noise, indeterministic order in python dictionaries, cases where an `id` of a variable is printed (eg. `repr`) and so on.

**Comment by bashtage** [comment]
I agree that it isn't reproducible.  One other obvious reason is that
different BLAS implementation will produce different numbers.

I think this is OK to not be reproducible.  This said, it is easy enough to
check for errors that are not just mismatches in output.

Really need a flag to tell doctest to not care about output so that it can
be run in a smoke test mode.

**Comment by josef-pkt** [comment]
Does doctest show errors separate or distinguishable from failure so we could use doctest for smoke testing?  I never thought of restricting it to this.

Changes look good (with minor formatting quibbles that can be ignored), and as far as I can tell this shouldn't cause (m)any merge conflicts with open PRs.

If your are finished with this, then I'll merge

**Comment by josef-pkt** [comment]
merging, the only potential merge conflict is that we have several PRs for survfunc, but in different parts of the modul, AFAIK

@bashtage Thank you

**Pull request merged**
