### PR TITLE
fix flake8 complaints about whitespace before commas and colons

### PR DESCRIPTION
**Pull request by jbrockmendel**
discrete_model is a disaster zone flake8-wise.  This addresses complaints about whitespace before colons and commas.

### CODE REVIEW

**Comment by josef-pkt** [comment]
what rule is this?
Doesn't look obvious to me that this should be an improvement.

If we start large scale "deflaking", then we need to check which rules we want to use. E.g scipy enforces it in the continuous integration test runs, but uses a blacklist for ignored "violations".

**Comment by jbrockmendel** [comment]
> what rule is this?

E203.

Closing.  Not sure why I thought code quality mattered.

**Comment by josef-pkt** [comment]
this breaks our numpy docstring standard compatibility which is more important to us than pep-8/flake-8

see examples in item 4
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by jbrockmendel** [comment]
This isn't _inside_ docstrings, this is in the dictionaries that get passed via "%" _to_ the docstring formatters.

**Comment by josef-pkt** [comment]
corrections: these are dicts for templated docstrings and not the docstrings themselves

AFAICS, this is the ignore list of scipy, which does not ignore 203
https://github.com/scipy/scipy/blob/master/tox.ini#L44

**Pull request closed without merging**
