### PR TITLE
WIP: TST close plots

### PR DESCRIPTION
**Pull request by josef-pkt**
only the last commit is relevant

change on top of #3804 which is included here

I'm still running full test suite to see of other plots or things have problems on my Windows

### CODE REVIEW

**Comment by josef-pkt** [comment]
pytest finished without segfault, but  output of pytest run is useless

M:\>pytest M:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels

= 6 failed, 7621 passed, 38 skipped, 1747 pytest-warnings in 1082.39 seconds ==
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='nul' mode='w' enc
oding='cp1252'>

all I see in the console are the yield deprecation warnings (printing 1747 warnings?) 

No idea what the 6 failed are, but while I was watching some of the tests I saw "F"s in test notebooks

`pytest  --disable-pytest-warnings`   ?

**Comment by josef-pkt** [comment]
running only notebook tests, I get 5 failures, some are timeouts

```E                   TimeoutError: Cell execution timed out, see log for details.

C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\nbconvert\preprocessors\execute.py:207: TimeoutError
==================== 5 failed, 35 passed in 434.55 seconds ====================
```

that leaves one failure somewhere else

**Comment by josef-pkt** [comment]
```
M:\>pytest -s  --disable-pytest-warnings "M:\josef_new\eclipse_ws\statsmodels\st
atsmodels_py34_pr\statsmodels\tsa\statespace"
```
1595 passed, 15 skipped in 87.50 seconds
with a huge number of RuntimeWarnings

**Comment by josef-pkt** [comment]
output of a test failure is ridiculous
It shows the entire code of the function where the problem occured, including the full source of the GPL cvxopt function.

`M:\>pytest -s  --disable-pytest-warnings "M:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats"`
```
...
            for tv in testers:
>               RegressionFDR(y, x, tv, design_method=method)

josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\tests\tes
t_knockoff.py:81:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\_knockoff
.py:83: in __init__
    exog1, exog2, _ = _design_knockoff_sdp(exog)
josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\_knockoff
.py:161: in _design_knockoff_sdp
    sol = solvers.sdp(c, G0, h0, [G1], [h1])
C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\cvxopt\coneprog.py:4129: in sdp
    = ds)
C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\cvxopt\coneprog.py:1396: in conelp
    misc.update_scaling(W, lmbda, ds, dz)
...
E           ArithmeticError: 49

C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\cvxopt\misc.py:614: ArithmeticError

**Comment by bashtage** [comment]
Ideally a decorator for graphics plot tests that would call plt.close at the end of the run could be used

**Comment by josef-pkt** [comment]
We have a `close_or_save` function for closing, but it is not always used.
The problem seems to be that `plt.close('all')` didn't work with pytest, and I had to close individual figures with `plt.close(fig)`. A decorator would not have access to all the figure handles.
(I never really understood the figure closing problems with nosetests either and I just kept adding close statements until the segfaults went away.)

**Comment by josef-pkt** [comment]
a few more options later

`pytest -s --tb=short  --disable-pytest-warnings --color=no`
is close to nosetests

```
M:\>pytest -s --tb=short  --disable-pytest-warnings --color=no "M:\josef_new\ecl
ipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\tests\test_knockoff.py
"
============================= test session starts =============================
platform win32 -- Python 3.4.4, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: M:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr, inifile:
collected 4 items

josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\tests\tes
t_knockoff.py ..F.

================================== FAILURES ===================================
________________________________ test_testers _________________________________
josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\tests\tes
t_knockoff.py:81: in test_testers
    RegressionFDR(y, x, tv, design_method=method)
josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\_knockoff
.py:83: in __init__
    exog1, exog2, _ = _design_knockoff_sdp(exog)
josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\stats\_knockoff
.py:161: in _design_knockoff_sdp
    sol = solvers.sdp(c, G0, h0, [G1], [h1])
C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\cvxopt\coneprog.py:4129: in sdp
    = ds)
C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\cvxopt\coneprog.py:1396: in conelp
    misc.update_scaling(W, lmbda, ds, dz)
C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\cvxopt\misc.py:614: in update_scaling
    offsetU = ind2, offsetVt = ind2)
E   ArithmeticError: 49
===================== 1 failed, 3 passed in 8.69 seconds ======================
```

**Comment by josef-pkt** [comment]
test_lme also has yield based tests

WC1 M:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\regressi
on\tests\test_lme.py yield tests are deprecated, and scheduled to be removed in
pytest 4.0

48 pytest-warnings

**Comment by josef-pkt** [comment]
running
```
>>> import statsmodels as stm
>>> stm.test(extra_args=['--tb=short'])
```

= 7 failed, 7620 passed, 38 skipped, 1747 pytest-warnings in 1138.90 seconds ==
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='nul' mode='w' enc
oding='cp1252'>

one additional failed test compared to the commandline in comment above

**Comment by josef-pkt** [comment]
obsolete now, Kevin's PR is merged.

**Pull request closed without merging**
