### PR TITLE
Document and cleanup bits of cython code

### PR DESCRIPTION
**Pull request by jbrockmendel**
@ChadFulton It took me a while to figure out what parts of kalman_loglike were doing, so I went ahead and wrote up comments to clarify it for the next reader.  In many cases the existing comments appear to be doing something similar, but I find this much clearer.

There is some remaining commented-out code that I'd like to document/clean up in a similar way, some of which I can do after looking up blas functions; other parts would require your input.

While I was at it I deleted a commented-out implementation of solve_discrete_lyapunov, since it has been replaced by a version immediately below it.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Thanks, that looks a lot nicer. @josef-pkt would it cause any problems if I were to merge this now?

**Comment by ChadFulton** [comment]
>  @josef-pkt would it cause any problems if I were to merge this now?

(meaning, would I mess up any release-related things. The PR itself is just documentation)

**Comment by josef-pkt** [comment]
Yes it would mess up release preparation.
No merges until I have branched 0.9, unless they are related to fixing the release.

@thequackdaddy and I are just working on the appveyor binary builds
I just got a segfault in statespace\tests\test_simulate.py running the test suite based on an appveyor 3.4 wheel.

**Comment by ChadFulton** [comment]
> I just got a segfault in statespace\tests\test_simulate.py running the test suite based on an appveyor 3.4 wheel.

Is this a reproducible segfault using a process that I can replicate (e.g. build wheel in such and such a way, install wheel, run test suite, get segfault)?

I'm going to try and take another look at the simulation smoother this week to see if I can figure out what's wrong while 0.9 is in rc1.

**Comment by jbrockmendel** [comment]
@ChadFulton given that this can't be merged for a few days/weeks(?), want to try to address the remaining commented-out code in this file?

The places where I could use help/clarification:

https://github.com/statsmodels/statsmodels/pull/4560/files#diff-c68c23aaa0e4d1d56292724d346fd3a1R84

```
         #ndarray[DOUBLE, ndim=2] v_mat = cnp.PyArray_Zeros(2, [1,1], cnp.NPY_FLOAT64,
         #                                                   0)
         double v_mat = 0
```

Should this be retained with a comment like "A multivariate implementation would use ..."?  Or just delete the ndarray line?

https://github.com/statsmodels/statsmodels/pull/4560/files#diff-c68c23aaa0e4d1d56292724d346fd3a1R110
```
         #v_mat = ddot(&r, &Z_mat[0,0], &one, &alpha[0,0], &one)
         #v_mat = y[i] - v_mat # copies?
         # Z_mat is just a selector matrix
         v_mat = y[i] - alpha[0,0]
         v[i, 0] = v_mat
```

Again not clear if the commented-out code should be retained/deleted.  Please advise.

https://github.com/statsmodels/statsmodels/pull/4560/files#diff-c68c23aaa0e4d1d56292724d346fd3a1R118
```
         # one-step forecast error
         #dgemm("N", "N", &one, &r, &r, &alph, &Z_mat[0,0], &ldz, &P[0,0], &ldp,
         #      &beta, &tmp1[0,0], &ldt1)
         #F_mat = ddot(&r, &tmp1[0,0], &one, &Z_mat[0,0], &one)
         #Z_mat is just a selector matrix
         F_mat = P[0,0]
         F[i,0] = F_mat
```

Don't even have a particular good guess here.

https://github.com/statsmodels/statsmodels/pull/4560/files#diff-c68c23aaa0e4d1d56292724d346fd3a1R167
```
         # 101 = c-order, 122 - lower triangular of R, "N" - no trans (XX')
         #dsyrk(101, 122, "N", r, 1, 1.0, &R_mat[0,0],
         #      &ldr, 1.0, &P[0,0], &ldp )
```

**Comment by ChadFulton** [comment]
Since this file predates me (maybe written by Skipper I think?) I will just be guessing also. In general I think you're right, these look like they were originally in the direction of a fuller (multivariate or just non-ARMA?) Kalman filter representation.

>         #ndarray[DOUBLE, ndim=2] v_mat = cnp.PyArray_Zeros(2, [1,1], cnp.NPY_FLOAT64,
>         #                                                   0)
>         double v_mat = 0

^ could probably delete the commented out section. It wouldn't support multivariate anyway, since it's just a 1x1 matrix. I guess the thought was that it might be used in an array context, and then it turned out that it didn't need to be.

>         #v_mat = ddot(&r, &Z_mat[0,0], &one, &alpha[0,0], &one)
>         #v_mat = y[i] - v_mat # copies?
>         # Z_mat is just a selector matrix
>         v_mat = y[i] - alpha[0,0]
>         v[i, 0] = v_mat

^ I guess the commented lines can be deleted. What's going on is that `v_mat` is supposed to hold the forecast error (not sure why it's different than `v`), and the `ddot` line first constructs the forecast as `np.dot(Z, alpha)`. But since this code is specialized to ARMA models, Z will always be a matrix [1, 0, ..., 0], so that the forecast will always just be the first element of the state vector, `alpha[0, 0]`.

>         # one-step forecast error
>         #dgemm("N", "N", &one, &r, &r, &alph, &Z_mat[0,0], &ldz, &P[0,0], &ldp,
>         #      &beta, &tmp1[0,0], &ldt1)
>         #F_mat = ddot(&r, &tmp1[0,0], &one, &Z_mat[0,0], &one)
>         #Z_mat is just a selector matrix
>         F_mat = P[0,0]
>         F[i,0] = F_mat

^ The comment here should probably be "one-step forecast error covariance", since the forecast error itself was computed above.

The forecast error covariance is `Z P Z' + H`, where H is the observation covariance. In ARMA models `Z = [1, 0, ..., 0]` and `H = 0`, so there's no need to do any matrix multiplication. The commented lines could surely be deleted, since they're not even for the general filter (i.e. they don't take H into account).

>         # 101 = c-order, 122 - lower triangular of R, "N" - no trans (XX')
>         #dsyrk(101, 122, "N", r, 1, 1.0, &R_mat[0,0],
>         #      &ldr, 1.0, &P[0,0], &ldp )

^ This is something of a mystery to me. The dsyrk LAPACK function only has 10 arguments, and the memory layout is not one of them, so I'm guessing that this must have been referencing a C-based wrapper of dsyrk that accepted the memory layout as the first argument.

The idea of the code appears to be that to construct `P = np.dot(np.dot(T_mat, P), L.T) + np.dot(R_mat, R_mat.T)`, you could first construct `np.dot(np.dot(T_mat, P), L.T)` and then use dsyrk to do the `np.dot(R_mat, R_mat.T)` part more quickly than would be achieved with dgemm.

But I see no reason why we'd need to keep it.

**Comment by ChadFulton** [comment]
> Since we've got a window of time before anything is merge-able

Is this true @josef-pkt ? I thought maybe now that 0.9 is branched we can merge again?

>  what do you think about fixing up kalmanf.kalman_filter? It's kind of a catastrophe, but a pretty easily-fixed one. It'd be nice to add the kalmanf directory to the "presentable and recently reviewed" list.

That sounds okay to me. I've been hoping that we will eventually move away from this file and the associated only-part-finished filtering implementation, but if you wanted to make some improvements in the meantime (and maybe my hope will never come to pass :) that would be even better.

**Comment by josef-pkt** [comment]
>  I thought maybe now that 0.9 is branched we can merge again?

yes, master is open for 0.10 development. The only inconvenience is changes for 0.10 that touch possible backports, where we would have to separate out the 0.9 from the 0.10 parts.
However feedback is slow, maybe not enough advertising for the rc, so we only have three backports so far. I only found one numpy incompatibility.

(and don't forget adding the appropriate milestone. We still have some merged PRs where there is no milestone and I didn't figure out whether it was included in 0.8 or merged for 0.9)

**Comment by ChadFulton** [comment]
> I expect this is supposed to be np.sum instead of sum, since the former is much faster. Merits checking before changing.

I think this is `np.sum`, since there is the import:

```python
from numpy import (identity, dot, kron, pi, sum, zeros_like, ones, asarray,
                   complex128, float64, asfortranarray)
```

> I made some preliminary fixups in the KalmanFilter class.

Thanks! and LGTM. If you don't mind, let's not add more to this PR since I have already reviewed is as good-to-be-merged whenever the time is right for that.

> AFAICT the rest of the module should be deleted; I'd rather leave that to you since you've got g_{64} times more pull with the maintainer than I do when it comes to this kind of thing.

One thing I forgot earlier is that if I remember right, this is a bit faster for pure ARMA models than the general state space code. In any case, even if we do want to, dropping support for it is quite a ways away. But I do have some plans for the ARIMA and VAR models once the exact diffuse initialization is merged.

**Comment by jbrockmendel** [comment]
> I think this is np.sum, since there is the import:

Good catch.  I really don't like the "let's import everything and switch back and forth between `sum` and `np.sum` approach"...

> If you don't mind, let's not add more to this PR

Sounds good.

> this is a bit faster for pure ARMA models than the general state space code. In any case, even if we do want to, dropping support for it is quite a ways away.

I'm all for de-duplicating code.  One nice thing about this version is its much easier to follow than the statespace cython.

**Comment by ChadFulton** [comment]
Will merge when I confirm that there are no problems from merging now.

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel!

**Pull request merged**
