### PR TITLE
TST: Add appveyor support

### LINKED ISSUE #1799: add `appveyor` testing on windows
another continuous integration tool, testing for Windows
free for open source

this looks like a working example with similar dependencies
https://github.com/rmcgibbo/mdtraj/blob/master/appveyor.yml
https://ci.appveyor.com/project/rmcgibbo/mdtraj

this one might also work, but I don't find the appveyor results
https://github.com/ifa-ethz/ecos/blob/master/appveyor.yml

an option for shallow clones
http://blog.appveyor.com/2014/06/04/shallow-clone-for-git-repositories/

### PR DESCRIPTION
**Pull request by bashtage**
Add support for running on appveyor

If this is still interesting, passes with one `skipif` needed for 32 bit Windows (a non-failure but tiny difference).

https://ci.appveyor.com/project/bashtage/statsmodels/build/1.0.2

closes #1799
closes #1800

### CODE REVIEW

**Comment by josef-pkt** [comment]
@bashtage  Thanks, that looks really good, only 17 and 18 minutes for the test runs.

I guess removing `.travis.yml` was just for the experiment, was it? Can you remove those changes and I'll merge.

**Comment by bashtage** [comment]
@josef-pkt Fixed now forgot to re-enable travis.

**Comment by josef-pkt** [comment]
@bashtage  I had forgotten that this has changes in PCA. Sorry.
I just merged the PCA move to multivariate. I didn't change anything in the move except import paths and doc location.

Can you rebase and resolve the merge conflict in statsmodels/tools/tests/test_pca.py ?
which is now at statsmodels/multivariate/tests/test_pca.py

**Comment by bashtage** [comment]
@josef-pkt Three way merge worked.

**Comment by josef-pkt** [comment]
There is a SVD not converged error in `ERROR: statsmodels.tsa.tests.test_arima.test_1dexog`
needs investigation if it persists.

merging this
@bashtage  Thank you

**Pull request merged**
