### PR TITLE
WIP: Genpoisson, checking tests

### PR DESCRIPTION
**Pull request by josef-pkt**
this is #3727 with some additional unit tests

this is currently just to investigate possible failures on travis that don't show up locally

### CODE REVIEW

**Comment by josef-pkt** [comment]
all green now, (with usual appveyor hang in one python)

The problem with scipy rvs is broadcasting without generating the correct number of random draws
I don't know why this didn't fail locally. I don't remember what changes were made in scipy for rvs size.

maybe add the size workaround in genpoisson_p.rvs?

**Comment by josef-pkt** [comment]
missing test coverage
https://coveralls.io/builds/12148556/source?filename=%2Fhome%2Ftravis%2Fbuild%2Fstatsmodels%2Fstatsmodels%2Fstatsmodels%2Fdiscrete%2Fdiscrete_model.py

methods: `fit_regularized` and `_score_p`
usage of transparams
also has a `__main__` part that should be deleted

**Comment by evgenyzhurko** [comment]
I added tests for transparams and deleted `__main__` part.
I don't know how to test `fit_regularized`, because there is no package that i can use to compare results. Same problem for `_score_p`.

**Comment by josef-pkt** [comment]
@evgenyzhurko  I don't know if I manage to finish tonight.

I started to try out `fit_regularized` on one of the test cases. It seems to work fine (with some warnings if alpha is not appropriate, but that's generally the case).
I would like to add two types of cases, one with little penalization that has values close to regular fit, and one with larger penalization, but only a rough check that the values make sense (plus a regression test but without verified comparison to another package).
The regularization code is all inherited, so I don't think it's necessary to verify the results in detail. We mainly need to check that there are no model specific problems and that fit_regularized is wired up correctly.

**Comment by josef-pkt** [comment]
all green, needs rebase on #3727, then GP-P should be ready for merge

**Comment by josef-pkt** [comment]
the commits from this PR have been merged as part of #3795

**Pull request closed without merging**
