### PR TITLE
DEV: Use ubuntu image for CI build env.

### PR DESCRIPTION
**Pull request by jseabold**
Trying this out.

### CODE REVIEW

**Comment by josef-pkt** [comment]
This looks great, but doesn't replicate the previous failure.
The only error is an undefined `plt` in mice which strangely shows up only on one version..

This version is again very fast in the test runs, 11 to 15 minutes for the fastest.

**Comment by jseabold** [comment]
That's the version with no mpl, so I suspect we have an unprotected import?

**Comment by jseabold** [comment]
I'm more inclined to trust these results on the official ubuntu:14.04 image than whatever image based on very old ubuntu that Travis was using. I also can't replicate these on OS X, as I mentioned in #2672. If we really want to I can keep trying to replicate, but I think we should skip it unless users report problems.

**Comment by jseabold** [comment]
It could even be something that's fixed in newer gcc (it could be a lot of things). The one in the default travis environment is fairly old.

**Comment by josef-pkt** [comment]
I compared versions of several packages between hanging and not hanging travis versions and didn't see any difference, for example openblas is the same version.

Can we use this image here as a permanent solution, i.e. merge it into master?

If TravisCI doesn't fail anymore with this, then there is no immediate reason to skip the tests, and we should wait if someone has a machine that runs into the same errors, or if it's really just a case of using outdated infrastructure.

Debugging the nans might then be again bug hunting as usual instead of trying to replicate strange machines.

**Comment by jseabold** [comment]
I'm very much in favor of having a known, relatively new container in which we can run things locally and punting on the failures if they show back up. 14.04 LTS is probably conservative enough. We could even make debian ones to head those failures off.

**Comment by jseabold** [comment]
Merge and fix matplotlib import in another PR?

**Comment by jseabold** [comment]
FWIW, the reason we switched to Circle was because we couldn't replicate errors we saw on Travis. The only recourse before they switched to the container-based infra. was to e-mail them and maybe they send you a VM image.

**Comment by josef-pkt** [comment]
yes, go ahead and merge.  I'm especially glad we get the speed back.

**Pull request merged**
