### PR TITLE
CLN: fix and lint for W391 blank line at end of file

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@ChadFulton it’ll take about 30 seconds to scroll through the diff and confirm this is exactly what it says on the tin.

**Comment by jbrockmendel** [comment]
rebased

**Comment by ChadFulton** [comment]
LGTM, will merge tomorrow unless there are concerns.

**Comment by jbrockmendel** [comment]
Ping

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel !

**Pull request merged**
