### PR TITLE
TST: Add flake8 testing for new additions

### PR DESCRIPTION
**Pull request by bashtage**
Add flake8 testing for new additions
Only applies to main code for now, not test code

### CODE REVIEW

**Comment by josef-pkt** [comment]
I'm not sure I fully understand this.

AFAICS, this runs the flake check for every python version. Can we check it only once like coverage?

Is the output for the flake check supposed to be in the regular travis log? Currently I only see "exited with 0"

**Comment by bashtage** [comment]
Since it only runs on the diff lines it is very fast, even on a large commit.

**Comment by josef-pkt** [comment]
> Since it only runs on the diff lines it is very fast, even on a large commit.

AFAICS, you are still fetching the entire repo again, which is still quite a bit of workload.
Plus, if a failing flake check makes the travis result red, then I would rather check only one python version to see whether it is a real failure or error or just a flake check. 
If flake is run only on one version, we would still see that the other versions are green.

**Comment by bashtage** [comment]
Yes, no need to pull full repo.  Only fetches master now.

**Pull request closed without merging**
