### PR TITLE
Fix syntax-like error

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt actual real-life error being fixed here.

**Comment by jbrockmendel** [comment]
@josef-pkt pls take a look.  Slow-and-steady process is all it takes.  Teamwork Makes The Dream Work, buddy.

**Comment by josef-pkt** [comment]
fixing the syntax error is fine
but I don't like to delete `__main__` examples if they are not stored somewhere.

**Comment by jbrockmendel** [comment]
@josef-pkt [Recall](https://github.com/statsmodels/statsmodels/pull/4624#discussion_r189412522)
> A clear docstring fix is usually a fast merge,

If you're not able or willing to handle these, then please consider empowering other talented members of community to help.

**Comment by josef-pkt** [comment]
If you could rebase and squash, then I/we could just hid the merge button.

**Comment by jbrockmendel** [comment]
Neither "rebase and merge" nor "squash and merge" do it for ya?  After "git rebase upstream/master" and being reminded that "git squash" is not a thing, there's 188 commits to go through in "rebase -i".  It'd be easier just to make a new PR.

**Comment by jbrockmendel** [comment]
Closing in favor of #4720.

**Pull request closed without merging**
