### PR TITLE
TST: Update travis

### PR DESCRIPTION
**Pull request by bashtage**
Suggested new testing defaults for Travis using a rule to test things back at least 2 years. Dates below.

Update travis config to test releases at least 2 years old:

NumPy 1.8+ (Oct 2013)
SciPy: 0.15+ (May 3, 2014)
Pandas: 0.14+ (May 30, 2014)
Matplotlib: 1.3+ (July 31, 2013)

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt I have fixed the issue that makes Travis slow with MPL 1.5 in this PR.  There is a small version bump in some of the testing, but nothing dramatic (2+ yrs).

**Comment by josef-pkt** [comment]
@bashtage Thanks, looks good based on a brief look 
but it might be better to wait with merging until 0.8 is tagged or we decide what to do for 0.8.

(I will look more closely on Friday)

**Comment by bashtage** [comment]
Well, I'm mostly against backward compat :+1:

**Comment by bashtage** [comment]
I have made it a little more conservative, using a rule of current release plus previous 4 for NumPy, SciPy and Pandas.  MPL is slower and so only current and 2 previous.

Update Travis config to test releases at least 2 years old:

NumPy 1.7+ (Feb 2013)
SciPy: 0.13+ (Oct 2013)
Pandas: 0.14+ (May 30, 2014)
Matplotlib: 1.3+ (July 31, 2013)

Also changes the MPL backend to address performance with MPL 1.5.

**Comment by N-Wouda** [comment]
I went looking for this as `np.isclose()` was added only in version 1.7. I'd fully support upgrading the dependencies to an at least somewhat more modern version following the release of our 0.8.

**Comment by josef-pkt** [comment]
Travis changes look fine, AFAIU (I'm not up-to-date on matplotlib changes)

However, what's the problem with the DatetimeIndex? 
AFAICS, it didn't fail before with pandas 0.14 (on python 3.4).
Those changes shouldn't be in the same commit, so that we have a record of what's going on.

**Comment by bashtage** [comment]
I think this is an obscure config bug in pandas where it doesn't correctly interpret `end` to be exclusive, and so the last observation needs to be dropped for this version.

**Comment by ChadFulton** [comment]
> This is working now and would fix the strange bugs in @ChadFulton 's code on Python 2.6 (which should be dropped)

Sorry, I haven't been paying enough attention - is there something that I messed up that I should be fixing?

**Comment by bashtage** [comment]
I thought I saw it in reference to some KF tests, but it seems to be elsewhere:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/188103793/log.txt

**Comment by ChadFulton** [comment]
Okay - I'll just keep my eyes open then.

**Comment by bashtage** [comment]
@ChadFulton There are win-32 variable size issues though (long/int)

https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.1095/job/rvmcw8wqwnr7ctb4

**Comment by bashtage** [comment]
@ChadFulton I think pickling on Python 3.6 is broken.  Log is here:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/194489044/log.txt

Do you need an explicity `__reduce__` method and constructor to restore it?

Skipping these for now on 3.6.

There were the errors (in case log is deleted):

```
======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_save.test_sarimax
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/tsa/statespace/tests/test_save.py", line 22, in test_sarimax
    res.save('test_save_sarimax.p')
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/base/wrapper.py", line 72, in save
    save_pickle(self, fname)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/iolib/smpickle.py", line 15, in save_pickle
    cPickle.dump(obj, fout, protocol=-1)
TypeError: can't pickle statsmodels.tsa.statespace._representation.dStatespace objects

======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_save.test_structural
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/tsa/statespace/tests/test_save.py", line 35, in test_structural
    res.save('test_save_structural.p')
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/base/wrapper.py", line 72, in save
    save_pickle(self, fname)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/iolib/smpickle.py", line 15, in save_pickle
    cPickle.dump(obj, fout, protocol=-1)
TypeError: can't pickle statsmodels.tsa.statespace._representation.dStatespace objects

======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_save.test_dynamic_factor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/tsa/statespace/tests/test_save.py", line 50, in test_dynamic_factor
    res.save('test_save_dynamic_factor.p')
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/base/wrapper.py", line 72, in save
    save_pickle(self, fname)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/iolib/smpickle.py", line 15, in save_pickle
    cPickle.dump(obj, fout, protocol=-1)
TypeError: can't pickle statsmodels.tsa.statespace._representation.dStatespace objects

======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_save.test_varmax
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/tsa/statespace/tests/test_save.py", line 65, in test_varmax
    res.save('test_save_varmax.p')
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/base/wrapper.py", line 72, in save
    save_pickle(self, fname)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python3.6/site-packages/statsmodels-0.8.0-py3.6-linux-x86_64.egg/statsmodels/iolib/smpickle.py", line 15, in save_pickle
    cPickle.dump(obj, fout, protocol=-1)
TypeError: can't pickle statsmodels.tsa.statespace._representation.dStatespace objects

----------------------------------------------------------------------
```

**Comment by josef-pkt** [comment]
Is this ok for merging.

I would like to update Travis now that 0.8 testing in master is not required anymore.

**Comment by bashtage** [comment]
Yes. It is good and will test numpy 1.12 once Anaconda releases a build.

**Comment by josef-pkt** [comment]
thanks, we are in 0.9

**Pull request merged**
