### PR TITLE
bug fix in coint function

### PR DESCRIPTION
**Pull request by tsando**
adfuller lag selection specified in coint argument autolag not passed to adfuller but rather set as 'None' for all cases

### CODE REVIEW

**Comment by josef-pkt** [comment]
@tsando  Thanks for finding this and the fix.

Ignoring the user provided choice is a serious bug.

However, I guess I was thinking that the default aic lag search is too expensive for the standard usecase.
So the question is whether we should change the default which is currently ignored to `None`, i.e. no lag search.

**Comment by jbrockmendel** [comment]
Right now this function is incorrect, this PR fixes that.  If there is a design decision to be made, it should be made separately.  The immediate issue is not returning incorrect results.

**Comment by josef-pkt** [comment]
It's a bit of a mess that I had made this mistake.
The design decision needs to be made when fixing this, because we will not change it again and potentially breaking backwards compatibility twice in a row.

My initial intention was to have a fixed number of lags as default, but I'm slowly changing my mind to use the same defaults as adfuller, i.e. with lag search. In that case this PR has the required change.

**Comment by josef-pkt** [comment]
@tsando  can you rebase this on current master?
If not, then I can do it.

I think now: merge as is, and call it a bug-fix that returns backwards incompatible results.
(coint was new as public function in 0.8)

**Comment by tsando** [comment]
@josef-pkt but if i rebase to current master these comments would be lost, no? Can you tell me what to do to avoid conflicts? happy to do this myself, just be clear on how you want the change. thanks

**Comment by josef-pkt** [comment]
@tsando The comments will not disappear. The commits will get shifted to the end, so some comments are not anymore next to the corresponding commits. However, this is mainly a problem of large PRs that take a long time (e.g. GSOC PRs. In that case we push the rebased branch to a new PR.

If you used the webinterface (as indicated by branch name) to create the PR, then you would still need to create a local checkout and then rebase on master.
In that case it might be easier for me to do it, unless you want to go through the exercise.

**Comment by tsando** [comment]
@josef-pkt I tried to rebase my local branch to the master but then i got this error after trying to merge it to the master:

```
$ git push
Username for 'https://github.com':
Password for 'https://tsando@github.com':
remote: Permission to statsmodels/statsmodels.git denied to tsando.
fatal: unable to access 'https://github.com/statsmodels/statsmodels.git/': The requested URL returned error: 403
```

would appreciate your help as it is useful for me to go through the exercise for future contributions. Thanks! :)

**Comment by josef-pkt** [comment]
you need to push to your branch `https://github.com/tsando/statsmodels.git patch-1` and not to https://github.com/statsmodels 
Any pushes to your PR branch will automatically show up in the PR here

maybe
`git push -f https://github.com/tsando/statsmodels.git patch-1`
the https://github.com/tsando/statsmodels.git might need to be replaced by your alias or how you have defined your github remote for your statmodels fork

**Comment by josef-pkt** [comment]
I usually use `git gui` for pushing, which doesn't require remembering the command line command and options, and allows for a quick check what is in the changes.
It still requires that the remotes were set up first.

**Comment by tsando** [comment]
@josef-pkt i just followed what you said but not sure if this worked - does it all look ok to you?

**Comment by josef-pkt** [comment]
I'm not sure what happened here, autolag is still not transmitted
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/stattools.py#L1020

**Comment by josef-pkt** [comment]
fixed in #4492 to use autolag and 'aic' default

**Pull request closed without merging**
