### PR TITLE
REF: Statespace: Fix recent deprecation / future warning issues

### PR DESCRIPTION
**Pull request by ChadFulton**
Fixes issues described in #2769.

### CODE REVIEW

**Comment by ChadFulton** [comment]
This can be merged unless we want to replace more `TimeSeries` with `Series` across the rest of Statsmodels in this PR.

**Comment by ChadFulton** [comment]
Latest commit (507a4c7) replaces `TimeSeries` with `Series` across all of statsmodels. It appears to not cause any new errors, so if that sounds fine I'll merge this.

**Comment by ChadFulton** [comment]
Will merge tonight unless there are concerns.

**Comment by josef-pkt** [comment]
TravisCI is as green as it get, and looks good to me.

go ahead

**Comment by ChadFulton** [comment]
Fixes #2769

**Comment by ChadFulton** [comment]
I apparently closed this rather than merging it...

**Pull request merged**
