### PR TITLE
ENH/TST: add FactorResults get_loadings_frame, adjust tests

### PR DESCRIPTION
**Pull request by josef-pkt**
test changes:
changes matplotlib backend for plot test in test_factor, see #4166 
adjustment for trailing whitespace in summary test 
(will need rebase and merge conflict resolution with #4156) DONE

This adds one method `get_loadings_frame` to `FactorResults`
currently loadings are only ndarray, and not available as DataFrame

This now also adds factor_scoring with two verified and two inofficial methods

also this adds some options for output formatting and to sort to the loadings dataframe
examples in this notebook:
http://nbviewer.jupyter.org/gist/josef-pkt/5e4f652c732978ce0e18f85164a29a14

### CODE REVIEW

**Comment by josef-pkt** [comment]
test errors: there is an extra dependency for using Styler

```
E       ImportError: pandas.Styler requires jinja2. Please install with `conda install Jinja2`
E       or `pip install Jinja2`
```

I guess we need to skip tests if not available.

**Comment by josef-pkt** [comment]
compat problems with pandas 0.16:

`E           AttributeError: 'DataFrame' object has no attribute 'sort_values'`

**Comment by josef-pkt** [comment]
This pull request introduces 2 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-a0535c2be3972b3307b70b42f6d7e31d3056318d)

**new alerts:**

* 2 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
precision is setting significant numbers and not decimals.
I didn't interpret this correctly. i.e. small numbers show up with more decimals. It doesn't matter much if values smaller than 0.1 are whitened out.

I think it's better to use fixed floating point formatting instead of styler precision.

**Comment by josef-pkt** [comment]
This pull request introduces 2 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-1b868bb1043b4f170335bc3b060db4b62b3e2cee)

**new alerts:**

* 2 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-06426911b3d099daf4cdeea501f28b7d33246b1c)

**new alerts:**

* 2 for Module-level cyclic import
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
amending last commit: corr is modified inplace in fit_pa - make copy
current version verifies against Stata for factor_scoring method='reg' and 'bartlett',  
ols and gls produce similar factors but are not available in Stata. I keep those out of the docstring for now

need good dataset for unit tests against Stata

**Comment by josef-pkt** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-b21aff3e8baddcba23bd5b071e06d986c678722c)

**new alerts:**

* 2 for Module-level cyclic import
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
rebase conflicts, mistake in reshuffling discovered after push.

It's about time to give up here. 

for the record: my Stata do file for the factor scores

```
set type double

import delimited "path-to\factor_data.csv", clear
factor var1 var2 var3 var4 var5, factors(2)
rotate, varimax
predict f1 f2
predict f1b f2b, bartlett


rotate, oblique oblimin
predict f1o f2o
predict f1ob f2ob, bartlett

outsheet f1 f2 f1b f2b f1o f2o f1ob f2ob using "M:\josef_new\stata_work\factors_stata.csv", delimiter(",")
```

data was create by simulation (in one more notebook):

```
np.random.seed(987125)

nobs = 100
k_fact = 2
k_endog = 5
f = np.random.randn(nobs, k_fact)
L = np.array([[1,   0.5],
              [0.7, 0.1],
              [0.1, 0.5],
              [0.3, 0.6],
              [0.1, 1]])
y_true = f.dot(L.T)
y = y_true + np.random.randn(nobs, k_endog)
y = np.round(y, 4)
y_m = y.mean(0)
y_s = y.std(0, ddof=1)
ys = (y - y_m) / y_s


mod_w = Factor(y, 2)
res_w = mod_w.fit(maxiter=1)
res_w.rotate('varimax')
res_w.summary()

endog_df = pd.DataFrame(y, columns=['var%d' % d for d in range(1, k_endog+1)])
endog_df.to_csv('factor_data.csv', index=False)
```

**Comment by josef-pkt** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-1d0e2b787ae444ddd25312efc311215a507b50a1)

**new alerts:**

* 2 for Module-level cyclic import
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
The sorting option for the loadings dataframe requires pandas >= 0.17 and skips the tests if pandas is too old.

**Comment by josef-pkt** [comment]
There is a problem in `Factor.__init__` in master: endog super treatment comes too late, i.e. there is processing (nobs, ...) before asarray is called and missing are removed.
This will be a bug if `missing='drop'` reduces the size of endog (nobs will be wrong)

@kshedden you added a ValueError if both endog and corr are provided. I would like to switch this back to a warning. Usecase is that we want to provide some corr for the factor analysis, but we also want to provide endog for post-estimation results like factor scoring and what else will become available.
one possibility: provide pairwise missing deletion corr, but base endog on case/row deletion.

another possibility that I thought of first is using outlier robust corr and endog, but standardizing endog in postestimation would also need robust loc and scale which will not yet be possible with the current api, and will need more work.

**Comment by josef-pkt** [comment]
@kshedden @yl565 

I would like to stop here and merge, if you want to have a look at the changes.

I reshuffled the `Factor.__init__` to have super call early on, and changed some docstrings. I didn't change the "not both" ValueError for endog+corr. (that's not urgent)
Also this always attaches `corr` as attribute in `Factor.__init__` so it will always be available, and attaches the factor instance to the results instance as `model`.
No reshuffling/dropping of other attributes yet.

**Comment by josef-pkt** [comment]
about unit test coverage: 
It looks like the jinja2 and possibly the pandas version requirement makes the test skip the styler options. (which have only smoke tests anyway)

**Comment by kshedden** [comment]
I agree, warning is appropriate in this case.

**Comment by josef-pkt** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-36c1745a2793058a039821ab96775d6646f129f2)

**new alerts:**

* 2 for Module-level cyclic import
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
amended last commit: 
change ValueError to warnings, if both endog and corr are specified
a bit more work on docstrings

merge when green

**Comment by josef-pkt** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-cf12b90ca2cb97b48425c9244d0e15f80aa309db)

**new alerts:**

* 2 for Module-level cyclic import
* 1 for Illegal raise

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
LGTM found a silly editing mistake `raise warnings.warn(...`
needs another amend 

(cyclic imports are because of our api.py and are all false alarms, AFAICS)

**Comment by josef-pkt** [comment]
This pull request introduces 2 alerts - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-98203325931366dde5ec9db2b6335ee6126d20b9)

**new alerts:**

* 2 for Module-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
as green as it gets, merging

**Pull request merged**
