### PR TITLE
REF: Use ArmaProcess.generate_sample instead of ArmaFft

### PR DESCRIPTION
**Pull request by jbrockmendel**
Move armafft-specific test to an armafft-specific test file.  After this, non-sandbox does not import armafft

### CODE REVIEW

**Comment by josef-pkt** [comment]
What's the point of just moving a test function around?

There is no point to this.

**Comment by josef-pkt** [comment]
Did you start writing the release notes and the missing documentation?

**Comment by jbrockmendel** [comment]
The point is to isolate sandbox from non-sandbox.  This is entirely consistent with what I have said elsewhere.

**Comment by josef-pkt** [comment]
This is just shuffling things around, it doesn't change which functions are unit tested and which are not. The location of the file is secondary. (independently what you might say elsewhere)

If you want to separate this part, then review and write unit test for the FFT process and then we can move it out of the sandbox into statsmodels.tsa

**Comment by jbrockmendel** [comment]
> If you want to separate this part, then review and write unit test for the FFT process and then we can move it out of the sandbox into statsmodels.tsa

Is this anything resembling a policy?

**Comment by josef-pkt** [comment]
which one?

The policy that sandbox code needs to be reviewed and unit tested before moving out of the sandbox.

or 

Sandbox code should not be reshuffled and moved without substantive review and work on it because it might obscure the original intention for the code.

or

Don't remove examples if there is no equivalent one available. 
(the example for the use of the MonteCarlo class refers to a different PR.)

or

Don't waste the time of maintainers with cosmetic changes when they are supposed to figure out some statistics.

or 

...

**Comment by jbrockmendel** [comment]
The policy that once code has reasonable tests it can be moved out of sandbox.

Please try to maintain a contributor-friendly tone.

**Pull request closed without merging**
