### PR TITLE
MAINT: wrap lm_robust instead of re-implementing

### LINKED ISSUE #4905: base._parameter_inference should not copy code from _diagnostic_other
That's what "import" is for.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #4905

Updates docstring to accurately describe return values.

BTW the function that calls `_lm_score` appears to be inconsistent in what it returns, and in what it expects `_lm_score` to return.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Don't touch this.
this is less than a year old and work in progress

**Comment by josef-pkt** [comment]
meaning, I don't want to think now about why I made a copy of the function.

**Comment by jbrockmendel** [comment]
Buddy, leave it open and look at it in a year like everything else.

**Comment by jbrockmendel** [comment]
> meaning, I don't want to think now about why I made a copy of the function.

Oh, I can answer that because the discussion came up before: it was because you wanted to avoid a circular import.  But that's no longer an issue, AFAICT.

**Comment by josef-pkt** [comment]
What changed that circular import is not an issue anymore? if it was

(I thought the circular import argument was for another function.)

I closed it so that Kevin is not tempted to merge it.

**Comment by jbrockmendel** [comment]
> What changed that circular import is not an issue anymore? if it was

I'm not convinced it was ever an issue, but https://github.com/statsmodels/statsmodels/issues/4905#issuecomment-413055668 you said that was why you copy/pasted instead of importing.  I guess somehow you were concerned about it becoming a circular import at some point in the future (?).

But (and I'm not sure why I didn't point this out in that thread at the time) _diagnostic_other was imported right at the top of the file right from the start in #2096 until unused imports were removed.

Can you take a look at the two places where `_lm_robust` is used and double-check my speculation that signature-drift may be causing trouble?  The call on L225 is hit in the test suite, but the call on L238 is not.  If I'm reading it right, that will end up calling `stats.chi.sf((lm_stat, pval, k_constraints), k_constraints)` where you probably intended to use `stats.chi.sf(lm_stat, k_constraints)` (which is in fact already done in `_lm_robust`).  `stats.chi.sf` will then return a 3-entry array, which I don't think is what you want here.

(Me being wrong here is the desired outcome)

**Comment by jbrockmendel** [comment]
Besides the possible bug discussed in this thread, the thread itself makes the risk of Kevin merging it effectively zero, while the risk of it falling through the cracks is significant.  Please re-open.

**Comment by josef-pkt** [comment]
There is the open issue #4905 for it cross-linking to here, so I don't see a reason to keep the PR open.

**Comment by jbrockmendel** [comment]
That's actually pretty reasonable.  Let's see what other non-mergeable PRs can be closed by the same logic.  Many of them are long-abandoned.

**Comment by josef-pkt** [comment]
the difference is that old PRs that add new features contain useful information for implementing or reimplementing those features.

This PR just (re)moves code when it is not clear where the final location of the function will be and which version of the function and returns we want to keep in the end.
It's unlikely that we keep the diagnostic_other location or version.

also both modules are _private because the final design and location is unclear, independently where the official path will be

**Comment by jbrockmendel** [comment]
> This PR just (re)moves code when it is not clear where the final location of the function will be and 

This PR prevents further drift in copy/pasted code, which has already caused one possible-bug.  One possibly-bug that you've avoided discussing because you are reflexively hostile.  Consider putting a pin in this for a couple months.

**Comment by josef-pkt** [comment]
Drift in code is part of the development process and can be intentional.

This type of functions need to change when we add new use cases for it. We don't have a complete blueprint for how these functions should look at the end, and we need to figure it out along the way as the use cases change and the number increases.

**Comment by jbrockmendel** [comment]
I’m not getting into the “development process” discussion again.  It only leads to a gif of Inigo Montoya asking what you thin YAGNI means.

**Comment by josef-pkt** [comment]
> I’m not getting into the “development process” discussion again.

The why do you keep submitting these PRs?
The code comment and my reply mentioned that it is intended, the docstring says it's experimental, and another code comment mentions that a hidden option is not yet working.
Plus the code has been adjusted to match the new use case and so intentionally diverges from the original version..

If you don't want to waste your and my time arguing about the development process and repeating it each time again, then stick to it.
My impression is that you are not listening to anything I'm saying and just keep going on with the code prettification crusade.

Many of those are useful, but proposing or making soooooooo many cleanup changes is not.

Except for #5741, I haven't seen any interesting statistics or econometrics question/issue in a week.

**Pull request closed without merging**
