### PR TITLE
fixed the beta method in proportion_confint for 2 corner cases

### LINKED ISSUE #2742: BUG: proportion confint returns nan, negative and larger than 1
partially duplicate of #2609

see https://github.com/josef-pkt/misc/blob/proportion_one/notebooks/proportion_one_power.ipynb
(not yet committed and pushed)
example copied below

beta/exact confidence interval contains a NaN if the count is all of the same kind, 
normal and agresti_coull return proportions that are negative or larger than one.

This might also be the reason for the comment that binom_test inversion fails, it uses normal ci for the bounds of root search, which should fail if probability is negative or larger than 1.

TODO: trim/clip to [0,1], and explicitly set bounds to 0 or 1 for beta in corner case.

```
import numpy as np
import statsmodels.stats.proportion as smprop
import pandas as pd

confint_methods = ['beta', 'wilson', 'normal', 'agresti_coull', 'jeffrey']
nobs = 30
count_ = 0
confints0 = [smprop.proportion_confint(count_, nobs, alpha=0.05, method=method) for method in confint_methods]
count_ = 1
confints1 = [smprop.proportion_confint(count_, nobs, alpha=0.05, method=method) for method in confint_methods]
count_ = nobs - 1
confintsnm1 = [smprop.proportion_confint(count_, nobs, alpha=0.05, method=method) for method in confint_methods]
count_ = nobs
confintsn = [smprop.proportion_confint(count_, nobs, alpha=0.05, method=method) for method in confint_methods]
pd.DataFrame(np.column_stack((confints0, confints1, confintsnm1, confintsn)), index=confint_methods, 
             columns=['0 lower', '0 upper', '1 lower', '1 upper', 'n-1 lower', 'n-1 upper', 'n lower', 'n upper'])
```

### PR DESCRIPTION
**Pull request by ngaurav**
Compared count and nobs. Earlier the 2 cases were showing NaN. Fixes #2742 
Logic:
(i) if count = 0, ci_low = 0.
(ii) if count = nobs, ci_high = 1.

### CODE REVIEW

**Comment by josef-pkt** [comment]
see the test error on TravisCI.
This needs to be able to work vectorized.

**Comment by josef-pkt** [comment]
The problem is the equality condition which doesn't return a scalar bool.

**Comment by ngaurav** [comment]
I have used nan_to_num() which simply replaces each occurrence of NaN by 0. This is what we in ci_low. I have assumed that ci_upp never becomes 0 and therefore I replace NaN by 0 then 0 by 1. The other assumption is that in 'beta' method, NaN occurs in ci_low only when count is 0; and NaN occurs in ci_upp only when count == nobs.

**Comment by josef-pkt** [comment]
closing, fixed by #4410

**Pull request closed without merging**
