### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by josef-pkt**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
FWIW I implemented something similar [here](https://github.com/jbrockmendel/sm2/pull/96); the hardest part was getting azure to recognize a failing when tests failed.  I expect some of the config there can be made useful here.

**Comment by bashtage** [comment]
Hard to put much time in since there isn't much activity around here.

**Comment by bashtage** [comment]
@jbrockmendel Are you willing to give this a go?  If it gets working, I'll merge it.

**Comment by jbrockmendel** [comment]
> Are you willing to give this a go? If it gets working, I'll merge it.

Yes, but it'll take me a few days before I can devote attention to it.

Seeing the action here in the last couple days has been exciting.  If you see anywhere else I can be helpful, don't be shy.

**Comment by bashtage** [comment]
The CI situation is quite slow ATM.  11 Builds on Travis = 1.5 hours for a run, inclusion optionals.  Appveyor is also 1.25 hours or more. 

Ideally, the next release would occur soonish and then 2.7 and 3.4 can hopefully be dropped. That would shave at least 3 builds.

**Comment by jbrockmendel** [comment]
@bashtage closed by #5617?

**Pull request closed without merging**
