### PR TITLE
ENH: Warn for non-convergence in elastic net

### LINKED ISSUE #4607: BUG/ENH: fit_regularized elasticnet does not show non-convergence
I didn't get results with GLM fit_regularized with alpha=0 that match the unpenalized fit.

The problem is that maxiter was reached before convergence. There is no warning or `converged` attribute or mle_retvals to show the information about convergence status.

If I start with the unpenalized res.params as start_values, then fit_regularized returns immediately.

(I'm using Star98 dataset with GLM-Binomial with and without counts, using proportions and no n_trials)

### PR DESCRIPTION
**Pull request by kshedden**
Closes #4607

### CODE REVIEW

**Comment by kshedden** [comment]
@ChadFulton,  I'm getting linting errors that seem to arise in TSA, is this something that you can fix?

statsmodels/tsa/statespace/mlemodel.py:2594:80: E501 line too long (85 > 79 characters)
statsmodels/tsa/statespace/mlemodel.py:2607:80: E501 line too long (89 > 79 characters)
statsmodels/tsa/statespace/tests/test_exponential_smoothing.py:885:80: E501 line too long (84 > 79 characters)

**Comment by ChadFulton** [comment]
Yes! I merged a PR too fast, and didn't clean up my mess.

**Comment by ChadFulton** [comment]
Linting errors fixed in #6698, I think.

**Comment by kshedden** [comment]
Thanks @ChadFulton !

**Pull request merged**
