### PR TITLE
MAINT: remove sandbox.formula, supplanted by patsy

### LINKED ISSUE #5688: DEPR: Is sandbox.formula supplanted by patsy?
It doesn't import patsy, which makes me think (along other sandbox-related clues) that it was started before patsy was used, and is never going to be made usable.  @josef-pkt can you comment on this speculation?

If it can be removed, then sandbox.examples.ex_formula can be removed, along with a bunch of invalid-escapes in docstring'd-out code.

That would also put us on a path towards removing utils_old and contrast_old.

cc @bashtage

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #5688
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message). 

Removes example and test files, then contrast_old and utils_old that are currently used in sandbox.formula and nowhere else.

### CODE REVIEW

**Comment by josef-pkt** [comment]
is_nested looks like an interesting function
https://github.com/statsmodels/statsmodels/pull/5692/files#diff-6058ff01fa21c06e9fcbb94e7ef4b6c5L655

**Comment by jbrockmendel** [comment]
> is_nested looks like an interesting function

Any idea if it would work with patsy-based inputs?  i.e. could we keep that function and just lose the classes?

**Comment by josef-pkt** [comment]
The formula and term handling is obsolete and can be removed

But I'm always looking for linalg and other helper functions for things that I don't know or cannot write from memory.
#5722 new issue for is_nested, nested categoricals

**Comment by jbrockmendel** [comment]
Great.  With #5722 in place is there anything else to salvage from these files?

**Comment by jbrockmendel** [comment]
I tried to debug the failures in ex_formula, got one of em but the rest would take some major re-implementation of patsy, not worth it.  cc @bashtage

**Pull request merged**
