### PR TITLE
Make glm's predict function return numpy array even if exposure is a pandas series

### PR DESCRIPTION
**Pull request by kbrose**
- [ ] closes #xxxx
- [ ] tests added / passed. 
- [ ] code/documentation is well formatted.  
- [ ] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 
<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in master and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/master -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by bashtage** [comment]
Why? You can use as array in your own code to ensure numpy.

**Comment by bashtage** [comment]
Taking another look it seems pretty reasonable. Exog should determine type and index in most cases.  This said, if exposure has an index and exog does not, it seems that the index should be preserved.

**Comment by kbrose** [comment]
I passed in exposure as a pandas series with the name "exposure", and got out a pandas series with the name "exposure". That didn't seem correct to me and is why I submitted the PR. Thanks for taking a look at it!

**Comment by bashtage** [comment]
This makes sense and is likely safer.  Thanks.

**Pull request merged**
