### PR TITLE
REF: NegativeBinomial de-duplicate digamma calls

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request **introduces 1 alert** and **fixes 60** when merging 432529e4f3107e90e712fb5e43d40f6a3050b7f4 into ac87dec28cee1e554ae7f1efc514a1bc4c24fe81 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-44563e583bfc1e69aec7e8b9cb4329c2106e4fb0)

**new alerts:**

* 1 for Syntax error

**fixed alerts:**

* 53 for Module\-level cyclic import
* 3 for First argument to super\(\) is not enclosing class
* 2 for Mismatch between signature and use of an overridden method
* 1 for Unnecessary pass
* 1 for \_\_init\_\_ method calls overridden method

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
Free lunch.

**Comment by josef-pkt** [comment]
looks good and is green. I don't remember the details about behavior at or around alpha=0 from previous comments.

can you rebase and squash?
then ready to merge

**Comment by jbrockmendel** [comment]
@josef-pkt free lunch, with perf improvements.  This is a blocker for other cleanups.

**Comment by josef-pkt** [comment]
I will get back to merging several of your PRs later today. I will most likely rebase some of them and force push to your branch, if they are too far behind master. 
(I will be mostly offline for the next several hours.)

**Comment by jbrockmendel** [comment]
Ping

**Comment by jbrockmendel** [comment]
@ChadFulton this is a blocker for the a really nice payoff in the next round.

**Comment by josef-pkt** [comment]
don't merge without rebase and removing the master merges.

**Comment by jbrockmendel** [comment]
He's right, definitely hit the "squash" button.

**Comment by josef-pkt** [comment]
There ain't no squash button.
Otherwise this https://github.com/statsmodels/statsmodels/issues/3076#issuecomment-318904156 becomes useless

**Comment by jbrockmendel** [comment]
The "Merge" button has a dropdown menu, one of the options is "Squash and merge"

**Comment by josef-pkt** [comment]
I explained to you why we don't use that!

**Comment by jbrockmendel** [comment]
I got the impression that was why _you_ don't use it.  You've got a workflow that involves doing everything in a desktop client.  Am I remembering that wrong?

Or was this the thing about squashing losing potentially useful git history?  I very specifically make small PRs to be effectively single-commit (e.g. here 1 with actual changes, 3 typo fixups, 2 merges, so informative history is lost by squashing).

**Comment by josef-pkt** [comment]
**We** don't use fast forward merge because then git log and similar don't show merges.

Squashing itself is fine/good for smaller PRs, but not for larger PRs or PRs that have distinct (different types of) commits (e.g. we don't mix cleanup with bug-fixes).

**Comment by jbrockmendel** [comment]
OK, well after an hour of rebasing the same thing over and over (hey guys, I found a negative TFP shock!), we now get to wait for the CI to see if any new typos were introduced.

> Squashing itself is fine/good for smaller PRs, but not for larger PRs 

Right, which for the Nth time is why I try to make small PRs. (along with, in this case, the fact that I want to separate steps of algebra)

**Comment by jbrockmendel** [comment]
> What's the problem with rebasing? It should essentially just be one git command on the command line.

I'll take the blame for incompetence on this one.  `git rebase upstream master` and `git rebase -i [use git log to find the commit before the first commit of the PR]` each ask me to go through a whole bunch of commits de-conflicting the same thing over and over.

**Comment by jbrockmendel** [comment]
Message from a couple days ago apparently got lost.  IIRC:

>  It should essentially just be one git command on the command line.

I'll take credit for git-incompetence on this one, but I tried both `git rebase upstream master` and `git rebase -i [hash for last pre-PR commit]` and they both had me going through and de-conflicting the same code over and over for each commit.

Regardless: ping.

**Comment by jbrockmendel** [comment]
ping

**Comment by josef-pkt** [comment]
merged

@jbrockmendel Thanks for the improvement

**Pull request merged**
