### PR TITLE
MAINT: Remove old pandas compat code.

### PR DESCRIPTION
**Pull request by jseabold**
I think there may be more simplifications that are possible in the time series code. Opening this so I don't forget about it.

### CODE REVIEW

**Comment by jseabold** [comment]
Rebased and fixed up.

**Comment by josef-pkt** [comment]
pushing to 0.8, but should be merged very soon, in case we catch something 
(I'm not familiar with most of this)

**Comment by jseabold** [comment]
Should be fine to merge. I think we should get it in, then do a quick micro release if there are issues, which there shouldn't be given we have travis and it worked on pandas master 2 weeks ago. Releases get tested more than master in any case. I don't think the last issue with the scipy changes would have been avoided by waiting longer to merge or merging earlier in the release cycle would it have?

**Comment by josef-pkt** [comment]
If you think it's safe enough, it can go in.
I don't really like to have to do quick micro releases for last minute refactoring bugs.

If the scipy lapack refactoring had been in master longer, then someone else might have reported it also. I didn't realize what the impact will be on released versions when agriffing opened the PR to fix and update our code for it.

If we do another release in 3 or 4 months, then I don't think there is so much pressure to squeeze changes in just before a release, if the changes are not urgent.
Even a quick and easy micro release creates work for everyone.

**Comment by springcoil** [comment]
Has this been merged yet?

**Comment by josef-pkt** [comment]
Not merged yet. There have been "putting out fires" to keep up with pandas compatibility. 

Needs another rebase, and I guess a check how it affects related issues, for example for frequencies that are not supported in the current version.

**Pull request closed without merging**
