### PR TITLE
MAINT: strict linting for sm.stats files _close_ to already passing

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@josef-pkt also includes fix for typo in lint.sh

**Comment by jbrockmendel** [comment]
@josef-pkt like K said two weeks ago: tiny PR with simple cleanups

**Comment by josef-pkt** [comment]
@bashtage 
Better to rebase, merging master into a feature branch causes a mess in git commit history.

**Comment by bashtage** [comment]
Yes, I think that was a mistake. I was trying to rebase but forgot to
switch.

**Comment by josef-pkt** [comment]
also, according to git log, it looks like there are some fast forward ff merges in master
that is, `git log` or `git log --pretty=oneline` shows individual commits instead of only merge commits.

**Comment by josef-pkt** [comment]
actually, I'm not sure anymore what I'm supposed to see in git log

**Comment by josef-pkt** [comment]
direct commits to master do not show up as merged branches

for example PR #5249 is closed with a merged commit, but does not have an extra merge commit

this means `git log --merges` and github `is:merged` doesn't show them
https://github.com/statsmodels/statsmodels/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+sort%3Amerged+

For previous releases I used something like the following to go through the list of changes
`>git log --merges origin/master --pretty=oneline --abbrev-commit > git_log_merged_abbrev.txt`

**Comment by bashtage** [comment]
Hmm looks like rebase and merge doesn't create a merge commit, but instead places the commites in a PR at the tip.

**Pull request merged**
