### PR TITLE
DEPR: warn that VARResults.cov_params will become method

### PR DESCRIPTION
**Pull request by jbrockmendel**
Could easily be rolled in to #5220.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@ChadFulton thoughts?

**Comment by josef-pkt** [comment]
LGTM, but maybe far behind master

**Comment by jbrockmendel** [comment]
Will rebase.

**Comment by jbrockmendel** [comment]
rebased

**Comment by jbrockmendel** [comment]
green

**Comment by josef-pkt** [comment]
will most likely cause merge conflict with #5220 
Users will not access `cov_params` in standard usage, so this is fine to change withing one release, IMO.

**Pull request merged**
