### PR TITLE
import instead of copy/pasting

### PR DESCRIPTION
**Pull request by jbrockmendel**
Yes it still sucks, but it sucks _less_.

### CODE REVIEW

**Comment by josef-pkt** [comment]
This pull request **fixes 2 alerts** when merging fe89a483f4247f746223532ad6f94a86ca640f47 into 989bd4454f6fb0aad93c9706968f6d8cd228eed6 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-0ed7104ebb0bfad91550e067d9adf9a68d983044)

**fixed alerts:**

* 1 for Mismatch between signature and use of an overridden method
* 1 for \_\_init\_\_ method calls overridden method

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
@ChadFulton little help?

**Comment by jbrockmendel** [comment]
@josef-pkt something about trivial stuff having fast turnaround...

**Comment by ChadFulton** [comment]
In principle LGTM although I don't know if `sandbox` methods are tested, so is it possible that this breaks sandbox stuff (more than it already might be, anyway)?

**Comment by jbrockmendel** [comment]
> although I don't know if sandbox methods are tested, so is it possible that this breaks sandbox stuff (more than it already might be, anyway)

`OneTimeProperty` is identical to the imported version (though that should be removed too and along with cache_whatever should be replaced with simpler implementations, e.g #4468).

The version of LikelihoodModel currently in `garch` is out of date, in particular the `fit` method.  The unnoticed-drifting-apart is pretty much exactly why this copy/paste should be avoided in the first place (#4519, #4458, #4314, #4334, #4321, all of `base.covtype`...).  And no, the code in `garch` is not runnable at the moment (there was an Issue about that recently, dont have the number on hand (might have been on the mailing list?)).  Part of the idea of cleaning out unnecessary junk is to make it easier to triage whether there is anything worth saving (#4484).

**Comment by ChadFulton** [comment]
> Part of the idea of cleaning out unnecessary junk is to make it easier to triage whether there is anything worth saving (#4484).

I just looked at the garch file and IMO it would be easier for a new contributor to start from scratch than to try and interpret / salvage the code, but it might be easier for an existing contributor to remember what was being done in that file.

So maybe it's best to just ignore the issues in that file altogether? But I haven't looked at the file all that closely. Is it your opinion that with enough cleanup it could be made useful?

**Comment by jbrockmendel** [comment]
> it would be easier for a new contributor to start from scratch than to try and interpret / salvage the code

This is my opinion about _most_ of `sandbox`.  To the extent that there is anything worth salvaging, it will be much easier to find if surrounded by less detritus.  For a lot of it I would just throw out the entire file (sandbox.mle, sandbox.utils_old,...), but much less ambitious with this PR.

Because there isn't a clean separation of useful-code-in-non-sandbox/everything-else-in-sandbox (e.g. GMM, stats.diagnostic) users de facto _do_ see that this file exists and expect it to be useful (e.g. https://groups.google.com/forum/#!searchin/pystatsmodels/garch%7Csort:date/pystatsmodels/SkqrUl0Lvp8/dKYCf3LSCQAJ)

**Comment by jbrockmendel** [comment]
a) To the extent that there are fixed costs in getting up to speed in a given backwater module, you and I have already paid it for these.  These frankly trivial changes should happen now so the cost doesn't need to be paid next time around.

b) Drift in copy/pasted code is the kind of thing that gets worse over time.  This is a problem _all over_ the codebase and we should be developing Good Habits.

c) Either something useful is going to be salvaged from this code, in which case making that easier by clearing out detritus is helpful, or it isn't, in which case the whole thing should be tossed.

**Comment by josef-pkt** [comment]
That's a good reason for me to ignore maintenance for half a year so I can work on the backlog of my own "junk" and work on my 48 PRs and 10 to 20 PR equivalents in the sandbox and the 10 to 30 PRs that I haven't even started yet and maybe on the 10 to 20 PRs by others that should be high priority for review and finishing up.

(Nobody needs to get up to speed on some "backwater module" unless they what to get some ideas for reimplemting or finishing specific parts, e.g. Copulas, HetGLS equivalent using gaussian mle, ... E.g. Zero-Inflated GSOC took some design and major pieces from miscmodel and a gist by Skipper, but reimplemented them as full MLE models with an up-to-date interface and inheritance.)

**Comment by jbrockmendel** [comment]
Or, you know, you could delegate and _not_ allow tech debt to continue building up to the point where no one knows what the original author's intention was.  I get that maintenance isn't fun (seriously, you think I enjoy it?) but for crying out loud, We're On The Same Team Here.

**Pull request closed without merging**
