### PR TITLE
BLD: Add line displaying CPU info to CI

### PR DESCRIPTION
**Pull request by bashtage**
Show CPU type in CI to help understand random failures

### CODE REVIEW

**Comment by bashtage** [comment]
Coveralls is really bugged -- 0 changes to code and a decrease in coverage.

**Comment by jbrockmendel** [comment]
Travis log suggests running with sudo.

+1 on this.

**Comment by jbrockmendel** [comment]
Looking at the logs this works as advertised.  @josef-pkt should be merged

**Comment by jbrockmendel** [comment]
@josef-pkt we’ve got a fellow trying to improve the CI here.  Maybe let him?

**Comment by jbrockmendel** [comment]
@josef-pkt please empower someone to help with this kind of thing.

**Pull request merged**
