### PR TITLE
DEPR: Remove items deprecated in previous versions

### PR DESCRIPTION
**Pull request by jbrockmendel**
Ref #5092.

Also usages of `np_matrix_rank`, which is no longer necessary.

### CODE REVIEW

**Comment by bashtage** [comment]
Also seems completely coherent and straightforward.

**Comment by jbrockmendel** [comment]
@josef-pkt ping, CI fail is false positive

**Comment by jbrockmendel** [comment]
@josef-pkt these should be removed before 0.10.0

**Comment by jbrockmendel** [comment]
@josef-pkt appvryor queue is empty, good time to do some merging

**Comment by jbrockmendel** [comment]
@ChadFulton I know you were interested in remove deprecated functions at one point

**Comment by jbrockmendel** [comment]
@ChadFulton (last one for today) getting this up-to-date before 0.10.0 would be really nice, could use your help making it a reality (ok and also #5157)

**Comment by ChadFulton** [comment]
In principle LGTM, two questions:

- Can you remind me why `np_matrix_rank` is no longer necessary? Is it because our minimum numpy has moved up?

- This actually implements some of the warned deprecations (`get_logdet`, `het_breushpagan`, `acorr_breush_godfrey`, `lillifors`).  I am happy to do this, since they are all marked as being removed in v0.9, and so removal in v0.10 seems like no big deal, but @josef-pkt please let me know if we should not do this for some reason.

**Comment by jbrockmendel** [comment]
> Can you remind me why np_matrix_rank is no longer necessary? Is it because our minimum numpy has moved up?

Yes.

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel

**Pull request merged**
