### PR TITLE
ENH: 2-sample z-test unequal variances case

### LINKED ISSUE #8936: two-sample ztest may have bug
#### Describe the bug

The implementation of the two sample ztest does not appear to match documented algorithms

Specifically, the calculation of `var_pooled` below deviates slightly from how it is calculated elsewhere. 

https://github.com/statsmodels/statsmodels/blob/114d812133c0b8360c6d2e6059414e0706007977/statsmodels/stats/weightstats.py#L1543-L1561

For reference consult the following documentation:

https://en.wikipedia.org/wiki/Student%27s_t-test#Independent_two-sample_t-test

The code most closely resembles the "Equal or unequal sample sizes, similar variances" equation, but on line 1552 should subtract `ddof` from the nobs e.g. `var_pooled = (nobs1 - ddof) * x1_var + (nobs2 - ddof) * x2_var`

However we should not assume that the variances are similar, and should be using the more general "Equal or unequal sample sizes, unequal variances" equation.

### PR DESCRIPTION
**Pull request by melizwu**
Adds the case for unequal variances in the 2-sample z-test in `weightstats.py`.
Closes #8936 
@josef-pkt

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks, Looks good and correct.

can you add a unit test against R or other package?
a unit test for z-value in z-test equal to t-value in t-test would also work

**Comment by josef-pkt** [comment]
(prio-elevated so I don't forget about it when I return from vacation)

**Comment by melizwu** [comment]
I added unit tests against R BSDA. Let me know if there's anything I can revise. @josef-pkt

**Comment by josef-pkt** [comment]
looks good to me, thanks

this looks ready to merge AFAICS, (but I will be without much internet access for the next week)

**Comment by josef-pkt** [comment]
Thanks again
mergin

**Pull request merged**
