### PR TITLE
MAINT: remove file that just says to remove it

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@kshedden could not be simpler

**Comment by jbrockmendel** [comment]
@josef-pkt this file is 5 lines, including a docstring that says to get rid of it.  let's get rid of it.

**Comment by jbrockmendel** [comment]
@josef-pkt 5 line diff

**Comment by jbrockmendel** [comment]
@josef-pkt the entirety of the removed file:

```
"""
This should be merged into statsmodels/tests/model_results.py when things
move out of the sandbox.
"""
import numpy as np
```

**Comment by josef-pkt** [comment]
LGTM, but maybe far behind master

**Comment by jbrockmendel** [comment]
rebased

**Pull request merged**
