### PR TITLE
MAINT: fix invalid exception messages

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt Tiny PR with simple cleanups.  Should be merged.

**Comment by jbrockmendel** [comment]
@ChadFulton little help?  This has been OKed by bashtage.

**Comment by jbrockmendel** [comment]
@josef-pkt 9 line diff, OKed by bashtage, Green, and no merge conflicts

**Comment by jbrockmendel** [comment]
@josef-pkt green, no rebase needed

**Comment by jbrockmendel** [comment]
@josef-pkt green, no rebase needed

**Comment by jbrockmendel** [comment]
@josef-pkt buf-adjacent, 9 line diff

**Comment by jbrockmendel** [comment]
@josef-pkt I'm gonna try to spend some time away.  On my way out, here are the extant actual-bugfix PRs: #5003 (this), #5127, #4977 

Bug-adjacent: #5192 

Fixing warnings from the Night Of A Million Warnings a few weeks back: #5204

Removing files that are 100% unnecessary: #5070, #5240, #4941

Improving the tests in ways that are not Just Cleanup: #4978, #4980, #4983, #5136
I think #4988 and #4936 also fall into this category, but expect those would get more pushback.

Actually needs your attention (by my standards): #5132.

Things that don't fall into any of the above categories but I hope you'll take a look at after a few weeks of calm:
#5224, #5221, #5205, #5170, #5157, #5138, #4954

All the best.

**Comment by jbrockmendel** [comment]
@josef-pkt easy bugfixes have quick turnaround, yah?

**Comment by jbrockmendel** [comment]
@ChadFulton trivial bugfix

**Pull request merged**
