### PR TITLE
monotone_fn_inverter: fixed docstring

### PR DESCRIPTION
**Pull request by hlin117**
Addresses #2570

### CODE REVIEW

**Comment by hlin117** [comment]
Not sure why the build is failing. The branch is up to date with the master branch, and I only fixed a docstring...

Any guidance would be helpful.

**Comment by josef-pkt** [comment]
The TravisCI error is unrelated to this PR. Current master times out every once in a while on this machine. 

The change here looks good, and I will be back to merging in the next few days.

Thanks @hlin117

**Comment by josef-pkt** [comment]
I just realized that this is the module in the sandbox. I don't know why it's still there.
The function is now in `statsmodels.distributions.empirical_distribution`  (with the same typo)

**Comment by hlin117** [comment]
I fixed the docstring in the non-sandbox version.

**Comment by josef-pkt** [comment]
Thanks, merging

FYI: If it's just a change in the documentation, then we don't need to run the unit tests.
Travis skips the test run if `[ci skip]` is in the commit message
http://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Pull request merged**
