### PR TITLE
ENH: State space: Exact diffuse initialization

### PR DESCRIPTION
**Pull request by ChadFulton**
This adds exact diffuse initialization for filtering and smoothing for state space models.

This PR follows on top of #4042 (I don't know if it will be possible to merge #4042 first, but hopefully we can).

I haven't actually set `SARIMAX` or `UnobservedComponents` to use the exact diffuse method yet, but that would be pretty trivial given #4042, although I guess we might want to have the approximate diffuse method deprecated for a release cycle. The main work will be going through the tests, since some of them will likely fail with the exact method.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Well whoops messed up the last merge commit there, but I will fix it.

**Comment by josef-pkt** [comment]
This pull request **introduces 3 alerts** and **fixes 2** when merging 21127084df01cd8f1432dfb63559dee98350d6bc into 5a01211ab0c73b8b9182396e6d551efe220c2ee9 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-1dd3cc24b39b8ea3cc14b4792fa967b630a8d8b5)

**new alerts:**

* 3 for Potentially uninitialized local variable

**fixed alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
Just for general information, my current plan for this (and my other outstanding) PRs:

- Merge this (or #4042 first if possible) basically right after 0.9 is branched.
- New PR to remove the old state space framework ("compatibility mode")
- Revisit #3480 to make it work with the diffuse filter and any other changes since I first wrote it.
- Make a decision about how to implement #3513.

I think that this will put us in a good place for moving ahead on a number of fronts, including especially figuring out what to do with #3884. I think that with the new features from the above PRs, we will be able to move forward on a middle ground between full deprecation of ARIMA and the current situation where those models aren't maintained.

Of course we'll see how things go.

**Comment by ChadFulton** [comment]
Rebased after merging the updated frequency-domain seasonals in `structural.py`

**Comment by josef-pkt** [comment]
This pull request **fixes 2 alerts** when merging 7887bf794b54efe6fb6873dd06b360726d3dfc85 into 7cbaa2e9c8b996696bdcba08fc12fcf1b5253c49 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-8cc59f2e67508e19f9237ef83df91fe0353b407a)

**fixed alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by Noobivsho** [comment]
@ChadFulton do you want/need any help with your plan?  I am interested in this feature and can pitch in if useful.  Maybe starting in on 

> I haven't actually set SARIMAX or UnobservedComponents to use the exact diffuse method yet, but that would be pretty trivial given #4042, although I guess we might want to have the approximate diffuse method deprecated for a release cycle. The main work will be going through the tests, since some of them will likely fail with the exact method.

?

**Comment by josef-pkt** [comment]
This pull request **fixes 2 alerts** when merging ef29cf99aa4f0c415fcc937fcb4a6e96b9369326 into 7cbaa2e9c8b996696bdcba08fc12fcf1b5253c49 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-79acb51513c8bcb4ae8932d5e1e40410a83fa285)

**fixed alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
My current plan is to merge this (i.e. not #4042 first since there's really no reason to do that) as soon as possible, since it is green on all scipy >= 0.18.

However, I guess before we do that we should drop the CI lines for scipy < 0.18 so that master isn't permanently broken.

**Comment by ChadFulton** [comment]
Rebased. Assuming this comes back green, I will merge it (unless there are concerns). Although this PR adds the functionality, its scope is still pretty limited since no model actually uses the exact diffuse method yet.

A couple of notes:

- In 9d6995e I have an expected failure test where I show numerical problems that can arise if exact diffuse initialization is to an "irrelevant" state in a model (see #4619). These numerical problems also arise in e.g. the R package KFAS. This comment is just a note that these exist and a potential future test case, but this is not really a problem since we just shouldn't be specifying a state space model with an irrelevant diffuse state.

- After this is merged, my next PR will be to strip out all of the conditional compilation stuff and remove the old state space code. I'm looking forward to this :)

- I think the next step after that is to start using exact diffuse initialization in the `RecursiveLS` model, and I anticipate that in constructing that PR I will find additional improvements / refactors / fixes to the exact diffuse initialization code introduced in this PR.

**Comment by josef-pkt** [comment]
This pull request **fixes 2 alerts** when merging 37267cc2f7c01c98e64b7ff6b848d67ef310a1a1 into d465ebc54533afe2d003ca72287ca866498eb399 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-d7a9fc0b1a8b3a26bef67d77e70ba4b5e031db38)

**fixed alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
sounds good to me

I would like to plan for a release in (close to) half a year. Changes that will be merged soon, then still get some time in master to figure out and fix some problems that show up after the merges.

I will open an issue about conditional compilation for a possible 0.9.1

Question for 0.10 after removing compilation conditional on scipy: 
Do we need scipy for compilation, e.g. some header files or is scipy currently needed only for the version check?

**Comment by josef-pkt** [comment]
travis failure is unrelated doc build issue
`CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://conda.anaconda.org/r/linux-64/r-r6-2.2.2-mro343_0.tar.bz2>`

appveyor errors look serious, each exits in a different test

`statsmodels\tsa\statespace\tests\test_structural.py ...........Command exited with code -1073741819`

```
statsmodels\tsa\statespace\tests\test_sarimax.py ....................... [ 72%]
........................................................................ [ 73%]
.................................................Command exited with code -1073741819
```

```
statsmodels\tsa\statespace\tests\test_dynamic_factor.py ................ [ 64%]
...................................s..Command exited with code -1073741819
```

**Comment by ChadFulton** [comment]
Uh oh

**Comment by josef-pkt** [comment]
I restarted the doc build which is now green, but it looks like pandas_datareader.fred is incompatible with pandas which causes errors in the notebook builds

```
~/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/pandas_datareader/data.py in <module>()
     12     ImmediateDeprecationError
     13 from pandas_datareader.famafrench import FamaFrenchReader
---> 14 from pandas_datareader.fred import FredReader
     15 from pandas_datareader.google.daily import GoogleDailyReader
     16 from pandas_datareader.google.options import Options as GoogleOptions
~/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/pandas_datareader/fred.py in <module>()
----> 1 from pandas.core.common import is_list_like
...
ImportError: cannot import name 'is_list_like'

```

**Comment by ChadFulton** [comment]
> I restarted the doc build which is now green, but it looks like pandas_datareader.fred is incompatible with pandas which causes errors in the notebook builds

This is a bummer. I see that the prescient @bashtage already fixed this in pandas-datareader master (pydata/pandas-datareader/pull/520).

What is the best option for handling this? @bashtage are you planning to release a 0.6.1 for this error, or just release a 0.7.0? And is there a timeline?

**Comment by josef-pkt** [comment]
We don't need to use the latest pandas for the doc build, we can just stick with a previous version of pandas that works

**Comment by ChadFulton** [comment]
> We don't need to use the latest pandas for the doc build, we can just stick with a previous version of pandas that works

Oh, good point. I'll make a PR now to change the docbuild pandas to 0.22

**Comment by josef-pkt** [comment]
This pull request **fixes 2 alerts** when merging 00e6891f49d610c637025dc18d85829febd51447 into d465ebc54533afe2d003ca72287ca866498eb399 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-54ee05f968ab21356a14bc26dcc9ba134b0469ce)

**fixed alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
> Uh oh

But the good news is I can replicate it on Windows, so will be able to track it down and fix it.

**Comment by ChadFulton** [comment]
> Question for 0.10 after removing compilation conditional on scipy:
Do we need scipy for compilation, e.g. some header files or is scipy currently needed only for the version check?

Yes, I think so, since we have in the Cython files e.g.

```python
cimport scipy.linalg.cython_blas as blas
cimport scipy.linalg.cython_lapack as lapack
```

**Comment by josef-pkt** [comment]
If scipy is a build requirement, then it still needs to be added to the setup.py. If the analogy to numpy is correct, then we need to add
`setup_requires.append('scipy')`

**Comment by josef-pkt** [comment]
This pull request **fixes 2 alerts** when merging 7a42e22c1f596d2d583c8b452e2ad0b032e09473 into 6611e878fb625e20b587a34c208f69e1b9d2495b - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-1a182e13df594cd1629b9533c8b41d8acaa840d1)

**fixed alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
Pretty sure that fixed the Appveyor problems. I've also added scipy to `setup_requires`.

If green, will merge...

**Comment by josef-pkt** [comment]
This pull request **fixes 2 alerts** when merging ca0b9737b8d8bddd90b2625f1dbd80f503d7be39 into 6611e878fb625e20b587a34c208f69e1b9d2495b - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-b28880fdf26630f2a108806c6c3a1f222fce53d3)

**fixed alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ChadFulton** [comment]
Is green, am merging.

**Pull request merged**
