### PR TITLE
expose nsides to the seasonal_decompose so users can choose their favorite filter method for the resulting trend and residual.

### PR DESCRIPTION
**Pull request by brianlan**
Added nside=2 to the arg list of seasonal_decompose in tsa/seasonal.py, so users can choose the way to do filter on the trend in STL decomposition.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Needs docstring and unit tests.

Because nside can only take on two values, I think a boolean argument like `two-sided=True` might be better.

**Comment by brianlan** [comment]
Thanks, @josef-pkt. Will add docstring and unit test.

**Comment by brianlan** [comment]
Hi @josef-pkt , the PR has been updated with docstring and unit test.

**Comment by josef-pkt** [comment]
Where do the test comparison numbers come from?
Can you add a short `#` comment with the source/origin. And if it's R or another package, then the command to call it would also be useful for future reference (especially if there are options).

I don't see any problems with the changes ( based on brief look). I'll go over them again tomorrow and merge.

Thanks.

**Comment by josef-pkt** [comment]
@brianlan  do you still have the source for the unit test reference numbers?
I'd like to merge this on Monday, because it looks good.

**Comment by brianlan** [comment]
@josef-pkt The source is not from R. I just imitated the logic that used in statsmodels itself.

**Comment by josef-pkt** [comment]
@brianlan  Thank you, merged

**Pull request merged**
