### PR TITLE
EX: Update ex_arch_canada, ensure reproducible

### PR DESCRIPTION
**Pull request by jbrockmendel**
Updated the reference results in ex_arch_canada, then cleaned it up so its ready to become a notebook.  Is there a preferred way of showing R comparison results in notebooks (I think I read somewhere that jupyter can mix/match python/R)?

Small cleanups in diagnostic.py found while working through the example.

Removed ex_pairwise, as it is redundant with try_tukey_hsd, which is more modern.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@josef-pkt moving conversation about this PR to the appropriate thread.

> or what is "wrong" with the current version.

The R results don't replicate _quite_ right.  Also it's not easy to tell what calls were used to create each block of python results.

**Comment by josef-pkt** [comment]
If your new numbers are taken from R, then they fixed some (precision) bugs since I wrote this, and now the results of R are closer to mine, AFAICS

There are also changes and bugfixes in other packages in R or in Stata, so I expect some of our comparison number for unit tests results won't replicate exactly with current versions.
But this is only important if it is not just some irrelevant decimals.

**Comment by jbrockmendel** [comment]
> But this is only important if it is not just some irrelevant decimals.

Of the 3 R results present, only one would fail an assert_allclose check, conditional on the previous step (in the next sentence) being done correctly.

If you get the data into R by taking the raw data here and pasting it into a text file and then loading it with `Canada <- read.csv("canada.txt", sep="\t")` then the columns will be off by one from what the reproduction code suggests, i.e. line 115 reads
`#R:FinTS: ArchTest(as.vector(Canada[,3]), lag=5)` but it should be `Canada[,2]` and similar for the other entries (which are themselves much less clear in how they were produced)

(In fairness, the reproduction steps in the module docstring in this PR _also_ do not make clear how to get the data into R.  That will be addressed)

The python-produced results in the status quo are also unclear on what calls were used to produce them.

If I had trouble figuring out what was going on here, other readers likely would too.  If you want to skip the intermediate step of having a updated .py script and go straight to a notebook I'm on board, that just gets back to the OP question of whether/how we put R code into the notebooks.

**Comment by josef-pkt** [comment]
I prefer if R code is copied as text, with possible an R magic ipython cell that is/can be disabled.
The python and ipython version that I use most of the time does not have R installed and connected to ipython/notebooks.

**Comment by bashtage** [comment]
In terms of CI/doc generation, you can include R cells since R is available, although I think it is better the R is in a markdown cell with code delimiters ``` ``` .

**Comment by josef-pkt** [comment]
It requires a bit of searching to find the dataset in R.
I usually don't import datasets csv into R but use the ones provided by packages.

It looks like `Canada` is taken from this example
https://www.rdocumentation.org/packages/vars/versions/1.5-3/topics/arch.test

but it seems like I didn't like their arch test and used FinTS instead in the example

**Comment by jbrockmendel** [comment]
Updated to make this into a notebook, remove the py file

**Comment by jbrockmendel** [comment]
Gentle ping, got a notebook to show off

**Comment by bashtage** [comment]
The notebook needs to look like a notebook that someone would want to read.  It isn't that helpful to dump the contents wholesale.  A little bit of explanation and some section headers is all that is needed. Oh, and there are also trailing empty cells .

**Pull request closed without merging**
