### PR TITLE
WIP: ENH: Johansen's Cointegration test and VECM

### PR DESCRIPTION
**Pull request by josef-pkt**
see issue: #448, some additional notes about matlab versions in #1763

mailing list message about possible issues with critical values https://groups.google.com/d/msg/pystatsmodels/YHZoX-vIsLo/eLaHy-2DtKoJ
with reference to this article that compares critical values across statistics packages
Turner, P. (2009), Testing for cointegration using the Johansen approach: are we using the correct critical values?. J. Appl. Econ., 24: 825–831. doi: 10.1002/jae.1073
http://onlinelibrary.wiley.com/doi/10.1002/jae.1073/abstract

currently mainly translation of LeSage's spatial econometrics toolbox function, the cointegration test only

the intermediate results used in this can be extended to get a VECM representation for VAR's, and to get the estimator for it.

Not yet done or tried: 
residual from cointegrating vectors should be stationary, try unitroot test in example
what are we doing with VECM if there are some variables in the VAR that are I(0) and not I(1)?

### CODE REVIEW

**Comment by josef-pkt** [comment]
one test failure

also switch to assert_allclose

```
======================================================================
FAIL: statsmodels.tsa.tests.test_coint.TestCointJoh12.test_evec
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/tsa/tests/test_coint.py", line 50, in test_evec
    assert_almost_equal(self.res.evec, self.evec_m)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 517, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 912, in assert_array_almost_equal
    precision=decimal)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals
(mismatch 62.5%)
 x: array([[  1.1025171e-02,   7.5178889e-03,   2.8460741e-02,  -7.1412913e-02,
          6.8171301e-02,  -3.3270701e-02,  -8.7823132e-02,   1.8689955e-03],
       [ -2.1854816e-01,  -2.0146294e-01,   2.0213855e-02,   1.4067027e-02,...
 y: array([[  1.1025171e-02,   7.5178889e-03,   2.8460741e-02,   7.1412913e-02,
         -6.8171301e-02,   3.3270701e-02,   8.7823132e-02,  -1.8689955e-03],
       [ -2.1854816e-01,  -2.0146294e-01,   2.0213855e-02,  -1.4067027e-02,...
```

**Comment by skebanga** [comment]
What is the status of the please?

**Comment by josef-pkt** [comment]
I might be able to tell more in a few days. But it should be in master by Fall, at least johansen test and hopefully also VECM.

**Comment by paberline** [comment]
+1 for merge into master or statsmodels.sandbox, would be great.

**Comment by esvhd** [comment]
Hi guys - would this be included in the upcoming release? together with VECM? 
thanks.

**Comment by josef-pkt** [comment]
The plan is to get this into 0.9, and into master maybe in January. 
(I needed a break from code, reviewing and maintenance after the summer, but the break lasted longer than expected. We don't have enough reviewers and merging developers.)

**Comment by esvhd** [comment]
Thanks @josef-pkt . Total understand. Frankly I'd love to help more, but simply could not squeeze out more time at the moment... So really appreciate the effort.

**Comment by travis945** [comment]
+1 for merge, would love to have it, thanks for all the hard work!

**Comment by josef-pkt** [comment]
Johansen's cointegration test has been merged as part of the VECM PR #3246 and is already in master.
(Still partially experimental)

**Comment by josef-pkt** [comment]
closing this.
This cointegration test has been included in the VECM PR and been merged

**Pull request closed without merging**
