### PR TITLE
ENH: Data Interface to simplify numpy type conversion

### LINKED ISSUE #1148: catch/handle pandas.Categoricals
Right now the only way we specially handle Categorical variables is through a formula. As of 0.14, pandas will allow Categorical types in the BlockManager for DataFrames, so we'll also be able to detect them and do some default Categorical handling for those who use y, X API where they contain a Categorical.

https://github.com/pydata/pandas/issues/5313

### LINKED ISSUE #2133: Handle category dtype from pandas
Pandas now handles categorical and ordinal variables within the blocks of a DataFrame. Will need to write some code to handle these appropriately. Right now we do get a fairly informative error message though. As an example (Python 3, pandas 0.15.2)

```
[~/]
[55]: from io import BytesIO

[~/]
[56]: from urllib.request import urlopen

[~/]
[57]: dta = pd.read_stata(BytesIO(urlopen("http://www.stata-press.com/data/r13/fullauto.dta").read()))
```

rep77 is ordinal and foreign is categorical

### LINKED ISSUE #3027: Design/ENH: check no asarray, or usage of asanyarray
#2240 drops asarray from detrend so it works with numpy ndarrays and with pandas.

This is potentially dangerous, alt least lists will not work anymore, other array subtypes (matrices, ...) might have problems, although unlikely in this case.

Also some other recent PRs use asanyarray.

One possibility is to replace asarray usage with a whitelist or allowed types and convert everything else. (xarray, dask, ... ?)

### PR DESCRIPTION
**Pull request by bfcondon**
As a follow-up to the discussion in #3027, many functions have code that converts user provided data objects into the internal data representation used by that part of the library. This is an initial implementation of a DataInterface class to give developers control over that process.

Closes #3027

### CODE REVIEW

**Comment by bfcondon** [comment]
@josef-pkt It looks like Travis crashed.  Can you restart it?

**Comment by josef-pkt** [comment]
I restarted 3 of the travis jobs, and will restart the others after the first is finished

**Comment by josef-pkt** [comment]
The old 2.7 already stopped again with
```
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/pro/linux-64/mkl-rt-11.1-p0.tar.bz2: https://repo.continuum.io/pkgs/pro/linux-64/mkl-rt-11.1-p0.tar.bz2
```

**Comment by josef-pkt** [comment]
It looks like there is something wrong either with travis or with conda. The builds stopped again. I restarted the job with py 3.5 again.

**Comment by bfcondon** [comment]
@josef-pkt Thanks.  There are some new patsy errors, but all other tests are passing.  Any thoughts on what I have so far?

**Comment by bfcondon** [comment]
@josef-pkt I have fixed the failing tests related to this PR.  The remaining ones seem to relate to the ongoing errors you have mentioned.  Do you have any thoughts on this PR?  It now includes both a numpy data interface and an updated to_categorical function as well as various helper functions.

**Comment by bfcondon** [comment]
@josef-pkt I am sure that you have been busy, but I would like to get feedback on this.  If you don't think it is worthwhile, just let me know and I will close it.

**Comment by bfcondon** [comment]
@ChadFulton I saw your new code on improving date handling for time series models and I thought you might have thoughts on this PR regarding data handling for arrays.  I would appreciate any suggestions or comments you may have.

**Comment by ChadFulton** [comment]
Your PR looks interesting! Here are some of my thoughts; I should say at the outset that all of the formula / Categorical stuff is something I've pretty much always ignored, since it's less relevant for `tsa`. Also I have not looked at xarray or dask, and I have never been really too clear on how `np.asarray` vs `np.asanyarray` work in all cases.

I guess that the underlying issue here, and in my PR, and in #3027 and others is that Statsmodels is getting to the point where we need to have a formalized "data" policy? I guess it used to be just use `np.asarray` at the top of the function call (at least that's what I did, maybe also some `_is_using_pandas` nonsense).

It looks like you've done a lot of implementation work already. My view is that it would be good to have some kind of document with our "policy" on data inputs and outputs. This is one of the major reasons I implemented new date handling - because it wasn't clear what we supported or even what we intended to support.

That's a tall order, I know, because there's a bunch of different use cases and types of models and it's tough to figure out one set of policies that works for everything. As I said, I'm not comfortable with formulas / Categorical and so I would have a pretty hard time writing such a thing up.

I also think we should do "as little as possible" in Statsmodels. Partly because it's better to hand off data handling to a project designed for it, but mostly because we just don't seem to have the number of contributors required to maintain support for handling a lot of custom code unrelated to the core statistical work. I think that was another issue with date support - there was a lot of custom code to do a lot of very useful tricks, but then it was unsupported (and e.g. a lot of the code that existed was designed to support Pandas < 0.8!).

I think this is an important question, so thanks for your work and I'll be happy to participate in the process.

**Comment by bfcondon** [comment]
Chad, thanks for your comments.  I think a "data policy" would hopefully give users a more consistent experience with the library.  While I am not familiar with many parts of statsmodels, I put together a few notes that are consistent with this "data interface" and what I have seen so far.

# Overview
The policy has three key goals:
1. Supporting core data types well.
2. Giving the model designers the freedom to choose which of these data types works best for their requirements.
3. When possible, returning data to the user in the same format it was supplied.

# Core Types
* numpy arrays
* pandas Series
* pandas Dataframe
* list

> Should we still support recarray?  It is annoying and outdated.

> Should we accept data as a dictionary?  We would probably just convert it into a Dataframe.

If a developer wants to add a new core type such as dask arrays or xarray, this should be discussed in the PR.

> pandas Panel's should be deprecated in favor of xarray if a multidimentional data structure is still needed.

# Cross Sectional Data

The preferred datatype is the numpy array.

# Time Series Data

The preferred datatype is the pandas Series.

**Comment by bfcondon** [comment]
@josef-pkt  For the data interface to consistently convert user inputs into numpy arrays and back to the user's type, all tests are now passing (one unrelated test fails).  I have also added an initial description / write-up of a "data policy" that might be useful.  @ChadFulton provided some initial comments on the data policy which I have tried to incorporate.  Please @josef-pkt or @ChadFulton, let me know what you think the next steps might be or if you have comments on the code.

**Comment by bashtage** [comment]
While I support this concept, there seems to be no consensus or momentum, so I am going to close.

**Pull request closed without merging**
