### PR TITLE
ENH GeneralizedPoisson followup

### PR DESCRIPTION
**Pull request by josef-pkt**
add numerical score_obs

after this change, cov_type='HC0' works

no unit tests

### CODE REVIEW

**Comment by josef-pkt** [comment]
@evgenyzhurko   The only extra that is needed to get fit cov_type argument to work is score_obs.
Here I just copied the numerical method from NegativeBinomial.

(Note: complex step derivative does not work with Probit if cdf is used, because the current scipy.stats.norm.cdf special function does not support complex numbers)

**Comment by evgenyzhurko** [comment]
@josef-pkt I think this implementation will work
```
    def score_obs(self, params):
        if self.transparams:
            alpha = np.exp(params[-1])
        else:
            alpha = params[-1]

        params = params[:-1]
        p = self.parameterization
        exog = self.exog
        y = self.endog[:,None]
        mu = self.predict(params)[:,None]
        mu_p = np.power(mu, p)
        a1 = 1 + alpha * mu_p
        a2 = mu + alpha * mu_p * y
        a3 = alpha * p * mu ** (p - 1)
        a4 = a3 * y
        dmudb = mu * exog

        dalpha = (mu_p * (y * ((y - 1) / a2 - 2 / a1) + a2 / a1**2))
        dparams = dmudb * (-a4 / a1 + a3 * a2 / (a1 ** 2) + (1 + a4) *
                  ((y - 1) / a2 - 1 / a1) + 1 / mu)

        return np.concatenate((dparams, np.atleast_2d(dalpha).T),
                              axis=1)

    def score(self, params):
        score = np.sum(self.score_obs(params), axis=0)
        if self._transparams:
            score[-1] == score[-1] ** 2
            return score
        else:
            return score
```

**Comment by evgenyzhurko** [comment]
Previous implementation doesn't work.
I refactored  previous implementation and tested new one.
So, working implementation.
```
    def score_obs(self, params):
        if self._transparams:
            alpha = np.exp(params[-1])
        else:
            alpha = params[-1]

        params = params[:-1]
        p = self.parameterization
        exog = self.exog
        y = self.endog[:,None]
        mu = self.predict(params)[:,None]
        mu_p = np.power(mu, p)
        a1 = 1 + alpha * mu_p
        a2 = mu + alpha * mu_p * y
        a3 = alpha * p * mu ** (p - 1)
        a4 = a3 * y
        dmudb = mu * exog

        dalpha = (mu_p * (y * ((y - 1) / a2 - 2 / a1) + a2 / a1**2))
        dparams = dmudb * (-a4 / a1 + a3 * a2 / (a1 ** 2) + (1 + a4) *
                  ((y - 1) / a2 - 1 / a1) + 1 / mu)

        return np.concatenate((dparams, np.atleast_2d(dalpha)),
                              axis=1)

    def score(self, params):
        score = np.sum(self.score_obs(params), axis=0)
        if self._transparams:
            score[-1] == score[-1] ** 2
            return score
        else:
            return score
```

**Comment by josef-pkt** [comment]
GPP was refactored during GSOC and score_obs added 6da65e3edd109083d6dad78f4b14ef8829397571 
merged in #3908

**Pull request closed without merging**
