### PR TITLE
[TST/CLN] Turn decorators __main__ section into tests

### PR DESCRIPTION
**Pull request by jbrockmendel**
Add both the decorators module and the test module to the lint-fully list.

### CODE REVIEW

**Comment by josef-pkt** [comment]
LGTM, merge if/when green

**Comment by jbrockmendel** [comment]
> LGTM, merge if/when green

green

**Comment by josef-pkt** [comment]
no has a merge conflict after the latest merge, I guess in `lint.sh`

**Comment by josef-pkt** [comment]
OK github never does what we want!

I tried the resolve conflict in the github interface to see whether it works. After resolving the merge conflict, it merged master into this PR instead of editing this PR so we can merge it into master.

This needs now a rebase that removes the merge commit, and still needs resolving of merge conflict.
The merge conflict itself is trivial, just keep both changes.

**Comment by jbrockmendel** [comment]
> This needs now a rebase that removes the merge commit

I'll take care of this and let you know when it gets to green.  As long as you're in a merging mood, I have incentives to take things off your plate.

**Comment by josef-pkt** [comment]
@jbrockmendel thank you

**Pull request merged**
