### PR TITLE
Implement smoke-tests for IRF errbands

### PR DESCRIPTION
**Pull request by jbrockmendel**
Implemented smoke tests to call each of the `irf.err_band_XXX` methods, four of them break:

```
======================================================================
ERROR: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_errband_mc
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "irf_smoketests/statsmodels/tsa/vector_ar/tests/test_var.py", line 361, in test_errband_mc
    errband_mc = irf.errband_mc()
  File "irf_smoketests/statsmodels/tsa/vector_ar/irf.py", line 282, in errband_mc
    burn=burn, cum=False)
  File "irf_smoketests/statsmodels/tsa/vector_ar/var_model.py", line 1114, in irf_errband_mc
    lower = ma_sort[index[0],:, :, :]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_sz1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "irf_smoketests/statsmodels/tsa/vector_ar/tests/test_var.py", line 366, in test_sz1
    err_band_sz1 = irf.err_band_sz1()
  File "irf_smoketests/statsmodels/tsa/vector_ar/irf.py", line 340, in err_band_sz1
    lower[1:,i,j] = irfs[1:,i,j] + W[i,j,:,k[i,j]]*q*np.sqrt(eigva[i,j,k[i,j]])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_sz2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "irf_smoketests/statsmodels/tsa/vector_ar/tests/test_var.py", line 371, in test_sz2
    err_band_sz2 = irf.err_band_sz2()
  File "irf_smoketests/statsmodels/tsa/vector_ar/irf.py", line 379, in err_band_sz2
    elif svar:
NameError: global name 'svar' is not defined

======================================================================
ERROR: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_sz3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "irf_smoketests/statsmodels/tsa/vector_ar/tests/test_var.py", line 376, in test_sz3
    err_band_sz3 = irf.err_band_sz3()
  File "irf_smoketests/statsmodels/tsa/vector_ar/irf.py", line 447, in err_band_sz3
    elif svar:
NameError: global name 'svar' is not defined
```

I'll make some more commits shortly with fixes for these, but first wanted to make sure they were documented here.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Added the same smoke-tests for analogous methods in SVAR.  `sirf_errband_mc` raises an IndexError under the status-quo.

**Comment by jbrockmendel** [comment]
From the Appveyor log on py3:

```
[00:10:49] ======================================================================
[00:10:49] ERROR: statsmodels.tsa.vector_ar.tests.test_svar.TestSVAR.test_sirf_errband_mc
[00:10:49] ----------------------------------------------------------------------
[00:10:49] Traceback (most recent call last):
[00:10:49]   File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
[00:10:49]     self.test(*self.arg)
[00:10:49]   File "C:\projects\statsmodels\statsmodels\tsa\vector_ar\tests\test_svar.py", line 72, in test_sirf_errband_mc
[00:10:49]     _ = self.res1.sirf_errband_mc()
[00:10:49]   File "C:\projects\statsmodels\statsmodels\tsa\vector_ar\svar_model.py", line 721, in sirf_errband_mc
[00:10:49]     B=B_pass).fit(maxlags=k_ar)
[00:10:49]   File "C:\projects\statsmodels\statsmodels\tsa\vector_ar\svar_model.py", line 95, in __init__
[00:10:49]     Anum[~A_mask] = A[~A_mask]
[00:10:49] IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index
```

What is the desired behavior here?

**Comment by josef-pkt** [comment]
can you use the debugger to check what values those have Anum[~A_mask] = A[~A_mask]

nosetests --pdb path_to_testfile

**Comment by jbrockmendel** [comment]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/svar_model.py#L82

`A_mask` is coming back as just `False` instead of a 3x3 bool array.  It looks like this is a bytes/unicode issue.

```
>>> A
array([[b'1', b'0', b'0'],
       [b'E', b'1', b'0'],
       [b'E', b'E', b'1']], 
      dtype='|S1')
>>> A_mask = np.logical_or(A == 'E', A == 'e')
>>> A_mask
False
>>> A_mask2 = np.logical_or(A==b'E', A==b'e')
>>> A_mask2
array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]], dtype=bool)
```

New commits will be pushed shortly.

**Comment by josef-pkt** [comment]
just as background information for last commit "Explicitly case A and B to bytes":  
(AFAICS from browsing the code for this  )

The conversion to bytes is local and just used for creating the mask. The attributes that are attached are the numerical representation (with "E" replace by np.nan), e.g. `self.A = Anum`
So we only need consistency in the type but it doesn't matter whether we use unicode or bytes. AFAICS, the user can provide either, and dtype object as used for pandas strings should also work.

**Comment by jbrockmendel** [comment]
I'm having second thoughts about this. Adding smoketests here gives an illusion of test coverage which might be better avoided.

The bug-fixes are clearly necessary, but I'm leaning towards shelving the tests in this PR until they can be replaced with real tests.

**Pull request closed without merging**
