### PR TITLE
DOC: Fix doc errors

### PR DESCRIPTION
**Pull request by bashtage**
Fix error in MANOVA and MultivariateOLSResults
Fix incorrect numpy code in contengency tables
Add mixed glm to index
Fix typo in Parametes
Fix missig pandas OLS in DynamicVAR

### CODE REVIEW

**Comment by josef-pkt** [comment]
great, thanks @bashtage 
I have one more commit, mixed GLM needs the classes in the rst, second commit here https://github.com/statsmodels/statsmodels/pull/4523/commits

With "Fix missig pandas OLS in DynamicVAR" this is also MAINT and not just Docs

**Comment by josef-pkt** [comment]
This pull request **introduces 1 alert** when merging 0174fad1a0af5bd52e9ab4a6fcb38e2ff19f670f into 989bd4454f6fb0aad93c9706968f6d8cd228eed6 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-14a7b7e9a07f96b67e23cdd8830c8644e1560e1f)

**new alerts:**

* 1 for Module\-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request **introduces 3 alerts** when merging 543f9fb9588fe505d6faca8f4462c29d2c5e04dc into 989bd4454f6fb0aad93c9706968f6d8cd228eed6 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-59af1e0593c092433e6c03c20c974cf347adeb74)

**new alerts:**

* 3 for Module\-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by bashtage** [comment]
@josef-pkt This is now finished.  I incorporated anything I had missed in your branch into this one. 

I added tests that run against pandas <= 0.19.2 for the workaround in DynamicVAR

closes #4527

**Comment by bashtage** [comment]
There are only a handful of warnings left, all in contingency due to the interaction of cache_readonly and sphinx.

**Comment by josef-pkt** [comment]
Thanks, 
I will merge when Travis is finished, I cancelled the latest planned appveyor run because it doesn't check any doc build.

**Comment by josef-pkt** [comment]
This pull request **introduces 3 alerts** when merging 4d76116c9c3f47c629503837b3db91bec4d22a5a into 989bd4454f6fb0aad93c9706968f6d8cd228eed6 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-704f3e5ae8ebcdbd043b2484b54a084b179958c5)

**new alerts:**

* 3 for Module\-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
This pull request **introduces 3 alerts** when merging 51b505447d3027bf632add1dd2864fa46d3f4c1b into 989bd4454f6fb0aad93c9706968f6d8cd228eed6 - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-588a2f97de6be54df6192c6796e8cdeff792c452)

**new alerts:**

* 3 for Module\-level cyclic import

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by josef-pkt** [comment]
looks good, merging

besides the contingency table warnings, there is a pandas Warning that is most likely in one of the example code (ipython directive ?), but it doesn't specify where.
I think we ignore this until we see where something looks wrong in an example

```
<string>:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
<string>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
<string>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```

**Pull request merged**
