### PR TITLE
TST: NumPy 1.12 test for 0.8.x branch

### PR DESCRIPTION
**Pull request by bashtage**
DO NOT MERGE

@josef-pkt

### CODE REVIEW

**Comment by ChadFulton** [comment]
Looks good in the state space area. Some warnings, but nothing representing an actual problem.

**Comment by josef-pkt** [comment]
There is one pandas deprecation warning
statsmodels.tsa.statespace.tests.test_mlemodel.test_pandas_endog ... /home/travis/miniconda2/envs/statsmodels-test/lib/python3.5/site-packages/statsmodels-0.8.0rc1-py3.5-linux-x86_64.egg/statsmodels/tsa/base/tsa_model.py:44: DeprecationWarning: pandas.core.common.is_numeric_dtype is deprecated. import from the public API: pandas.api.types.is_numeric_dtype instead

and the recarray warnings from numpy that I thought were fixed.

**Comment by ChadFulton** [comment]
> There is one pandas deprecation warning
statsmodels.tsa.statespace.tests.test_mlemodel.test_pandas_endog ... /home/travis/miniconda2/envs/statsmodels-test/lib/python3.5/site-packages/statsmodels-0.8.0rc1-py3.5-linux-x86_64.egg/statsmodels/tsa/base/tsa_model.py:44: DeprecationWarning: pandas.core.common.is_numeric_dtype is deprecated. import from the public API: pandas.api.types.is_numeric_dtype instead

This is fixed in master from when I did date refactoring, but I'll make a backport PR for just that part so that we don't have to worry about it later.

**Comment by ChadFulton** [comment]
Well I have a PR that should fix the problem by importing the correct dtype, but I can't even replicate the deprecation error. e.g. when I do: `ipython` and then `from pandas.core.common import is_numeric_dtype` I feel like I should get a deprecation warning, but I don't.

**Comment by ChadFulton** [comment]
And I do have pandas 0.19.2:

```
In [7]: pd.__version__
Out[7]: u'0.19.2'
```

**Comment by bashtage** [comment]
Not sure if this is expected, but 0.8.x branch is still failing:

https://travis-ci.org/bashtage/statsmodels/jobs/198789365

**Comment by josef-pkt** [comment]
@bashtage  Can you rebase this so we get another numpy 1.12 check for 0.8?

The maintenance branch should now be the release version if we didn't miss anything.

**Comment by bashtage** [comment]
Closing since this works as expected.

**Pull request closed without merging**
