### PR TITLE
MAINT: many but not all trailing whitespace

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
ready to merge, not too invasive

qu: Do we have one of the CI pep-8/flake checks to prevent getting trailing whitespace in?

**Comment by jbrockmendel** [comment]
> Do we have one of the CI pep-8/flake checks to prevent getting trailing whitespace in?

We have that for _new_ files.  For existing files, we can't implement that until it would actually pass, which it won't at the moment.

**Comment by jbrockmendel** [comment]
@josef-pkt “ready to merge” yah?  Green.

**Comment by josef-pkt** [comment]
merging
@jbrockmendel Thank you

**Pull request merged**
