### PR TITLE
CLN: document-or-Delete commented-out code in base (excluding tests)

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by josef-pkt** [comment]
you can leave the modules and code alone that I just merged this summer. It needs another round of work before more cleanup.
I left comments (commented out code) in there on purpose to remind me of implementation choices or limitations where not all models are supported yet.

(And don't tell me that I'm not working on it for another five years.)

**Comment by jbrockmendel** [comment]
> you can leave the modules and code alone that I just merged this summer. It needs another round of work before more cleanup.

Fair enough, will update.

> I left comments (commented out code) in there on purpose to remind me of implementation choices or limitations where not all models are supported yet.

OK.  I'd take it as a kindness if in the next pass you'd clearly mark any commented-out code fitting this description.  If nothing else it'll keep me from bugging you about it.

**Comment by jbrockmendel** [comment]
@josef-pkt removed edits to recently-created files, as requested.

**Comment by josef-pkt** [comment]
closing to avoid having to think about this

**Comment by jbrockmendel** [comment]
That’s why you need to deputize someone to catch things you can’t be bothered with.

**Comment by josef-pkt** [comment]
To repeat myself one more time:
I do NOT want the code/test comment cleanup without substantive review.
And because I'm currently the only one that knows the old code, I am not delegating the review.

**Comment by jbrockmendel** [comment]
Yep, that's why you trust your teammates to judge what subsets of changes actually need your attention and triage.

**Pull request closed without merging**
