### PR TITLE
Weibull survival modeling with absorbing state

### PR DESCRIPTION
**Pull request by JbFoncin**
This model is a Weibull survival distribution with something special : survival can become infinite. It is useful for some analysis like unemployment duration where some people will never find a job : they come in "absorbing state".
The model allows truncated values to be used and is estimated by the maximum likelihood with reparameterization.
Coefficient's VAR matrix is estimated by the delta method. Optimizer used is Powell because it is the only one able to converge, the likelihood is pretty strange.
Parameters are like wikipedia's Weibull formula for k and lambda ; AS prop is the proportion on population in absorbing state.

It is my first contribution : any comments are welcome.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Sorry, I forgot to reply here. I went briefly over it a few days ago and read you pdf file in your other repo on using cython.

One of the question is how much we actually gain from using cython in this case. Do you have a rough timing of cython versus plain numpython?
So far we only put things in cython when we need an explicit loop over all observations and it cannot be vectorized. We are losing performance by having to create more intermediaries and use more memory, but I don't think we loose too much. However, eventually it might be good to have more basic things like likelihood calculation in cython, but I have not seen any timings for it when also a vectorized solution exists, and even within the current code we still have some slack. 

I think the main class needs to go out of cython, mainly for maintenance and flexibility reasons but I doubt there is anything to gain by keeping it in cython, e.g. plot and similar results methods. Then we can also use our standard framework to inherit additional methods, like data handling, choice of optimizers and inference.
In my experience `powell` is not a very good optimization methods, and I think we can do better, and converge faster, but I haven't looked at the details yet.

One detail: In the code, your recompute parts that could be assigned to a temporary variable to safe on repeated calculations, e.g. `exp(lam)` and `exp(k)`.

I think we should also add the regression case as you have it for your piecewise model.

**Comment by JbFoncin** [comment]
Thank you very much for your answer.

Your advice about the computation of exp(k) and exp(lam) each time is totally right and I will correct it before Friday.

About the timing between vectorized operation and Cython, I think the biggest gain in on parallelism. We could have a good speed by using a Cython function just for individual likelihood and use it by apply_along_axis method. Actually, prange makes the model 3 times faster on my 4-cores computer.

About the optimization, using Powell is not an option : the proportion of sample in absorbing state is STRONGLY over-estimated.

I agree with the idea to put the main class out of Cython, I think it's the kind of thing I do because I am not used with open source contribution.

If you like the model, I would be very happy to add regression!

**Comment by josef-pkt** [comment]
I would like to see this type of models in statsmodels. I had added the idea for parametric survival and similar models on the GSOC ideas list.

I never tried cython with parallelization and we don't have any code yet that uses it. Two possible problems
- cross platform compatibility: does this bring in additional requirements for cython? Does it work on all our usually supported platforms, e.g. Windows and Mac, besides the Linux variants.
- usage: 
   - Setup cost: specifically on Windows, I found out years ago that there is something like a 10 second minimum workload to be worth it with standard python (joblib) parallel computation
   - competition and level for the parallelization: In some cases, especially if individual tasks are fast, then it is more advantageous to do the parallel processing in a higher level, e.g. for bootstrap or cross-validation search. On the lower level also the linear algebra libraries like MKL work in parallel but it can be turned of if it's the wrong level of parallel execution.

I would consider the internal cython part as an experiment to see whether we can gain from it. Your piecewise function will be even more an example to see what how cython versus optimized numpy might perform.

The model itself, and regression and other extensions look fine, but will need some adjustments to match our pattern and take advantage of the inheritance structure.

(I will be mostly offline until New Year.)

And in general: It would be great to have more developers that are familiar with cython. While I'm not sure there is much to gain in this case, we still have other problems with expensive python loops for which it would be very useful to have a simple pattern to move them into cython.

**Comment by josef-pkt** [comment]
another design issue I just remembered:
We should keep in mind that we will want to extend this to other distributions besides Weibull. So we might eventually need some common base class(es) or mixins for this, possibly one for AFT and one for the proportional hazard types, and work with inheritance and/or with outsourcing to separate functions and delegation to share common code.

**Comment by JbFoncin** [comment]
Cython parallelism is really wonderful with big samples (and when individual computation are fast as you said). I will check for cross-platform problems but I am sure OpenMP features exist on Windows, Mac and Linux. Timings will be very close because this parallelism is at lower level than Python joblib/multiprocessing. I am very used with parallel tools, and this one is a good compromise between developing time and efficiency. The only way I know to really increase speed is to use Intel's TBB library, but code is more complex (and you need to code C++).  

OpenMP behaves exactly like MKL : it removes parallelism if not available and does computation on one core. Because the loop is statically typed, timing is still very good.

I will add regression and other features, and other models when this one will be done ! The next step could be to clean PCH code because this model is really wonderful for complex survival analysis. But actually, code is messy because it's the first complex tool I built.

**Comment by josef-pkt** [comment]
superseded by #3358 ?

**Comment by jbrockmendel** [comment]
@JbFoncin this doesn’t show any changes as having been made.  Did the changes get merged via another PR?

**Pull request closed without merging**
