### PR TITLE
MAINT: stop duplicating stuff from scipy

### PR DESCRIPTION
**Pull request by jbrockmendel**
Part of the effort to salvage usable (and used!) code from sandbox.stats.multicomp

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@rgommers this and #5027 are going to require some peer pressure to get across the finish line.  Any thoughts?

**Comment by josef-pkt** [comment]
there ain't no peer pressure that works.

Those were copied for local adjustments and comparison. If I think I want to use them in the next round, then we keep them.
Multiple comparison based on rank data is WIP, even though it has been ignored for years.

**Comment by jbrockmendel** [comment]
>  If I think I want to use them in the next round

Then the time to write them is at that time.  As is, all they are doing is 1) falling behind actually-maintained scipy versions, 1a) confusing future readers into thinking resulting differences are intentional, 2) adding to the wall of code between a reader and _actually_ useful code, and 3) making coverage stats less meaningful.

**Comment by josef-pkt** [comment]
Those two functions say "equivalent" to scipy
the scipy version of rankdata is in cython, AFAIR. my/statsmodels tiecorrect uses a different implementation with bincount instead of sort

But, in any case this is a question for working on rank based multiple comparisons functionality and not of CLN, cleaning without context.

**Comment by jbrockmendel** [comment]
> cleaning without context

The context is that this file is imported from outside sandbox, but is predominantly unused and possibly unusable.  Separating out the supposedly well-tested well-supported parts so readers/users/contributors can verify this testing is made easier by triaging.

**Comment by rgommers** [comment]
``scipy.stats.rankdata`` was rewritten in pure Python recently, in a way that was faster than the Cython version and IIRC fixed a bug.

I have some thoughts on the wider discussion here, but no time to share them today probably.

**Comment by josef-pkt** [comment]
I think this is just a wast of time. I'm spending now time looking at different implementation of rankdata and tiecorrect, which is completely irrelevant to what I should be doing.

As I said before: No cleanup without refactoring. The context is developing multiple comparison features. Users can use the advertised functions. 

The point is that scipy has standalone functions with, in many cases, repeated computation when several functions are called separately. The redundant repeat computation can be eliminated if we refactor it and combine it into a class. an example is weightstats which is more cumbersome than a scipy t-test for a single test, but combines confidence intervals and other features without having to recompute everything from scratch each time.
statsmodels.sandbox.stats.multicomp.MultiComparison is intended to be a similar class as statsmodels.stats.weightstats.DescrStatsW and CompareMeans
contingency table is another example
 2-sample proportion #4829 is similar but I don't have enough of the individual pieces yet to make it into a consistent (Multi)Comparison class. In 4829 I was struggling all the time with how much of the computation to repeat in functions. Currently calling the test function and the confidence interval functions separately needs to make repeated intermediate computations because those are not stored anywhere.
My guess is that tiecorrect can be an auxiliary function of rankdata and intermediate results can be attached to an instance of some Rankdata-MultipleComparison class.

However, that requires that we actually look into the rankdata MultipleComparison implementation, and not just: (Ok this function has the same name as another function so let's delete it.)

**Comment by jbrockmendel** [comment]
> not just: (Ok this function has the same name as another function so let's delete it.)

You seem to be under the impression that I am going about this mindlessly.  Please consider alternatives.

> My guess is that tiecorrect can be an auxiliary function of rankdata and intermediate results can [...]

Until that becomes a reality, most of this code is just making it harder for readers -- many of whom I'll stress are not you -- to focus on the actually-relevant code.

**Comment by rgommers** [comment]
>  If it turns out that there is more support for redundant code than I expected, I may just accept this as one of the facts of life that I don't understand 

There's not, at least not from me. It's not black-and-white in every case, but on average the code base would benefit from cleanups.

My $2c follows:

This discussion is not the only one going on over the past weeks. Rather than just resolving this one, it seems important to discuss and write down how decisions on all these PRs and policies get made. That way it's clear to everyone, and individual things can move forward (or they can be decided against).

As for the actual governance model, right now the de facto status seems to be that Josef acts as the BDFL, and other maintainers have ownership only of the things they're the expert on. Formalizing that Josef is the BDFL is one way to go - he's certainly earned it through more than a decade of working on statsmodels and scipy.stats. I'd then advise him to write down clear decisions on things like code cleanups, and at the same time listen to and work with other maintainers to give them more clear ownership.

**Comment by josef-pkt** [comment]
It's not so much that I am the de-facto BDFL, but that I'm the default maintainer and developer.

The main point I was trying to make is that I am the default maintainer for more than half of statsmodels, and large parts of unfinished or needs work code is my own. Anything that makes my maintainer and developer role more difficult needs to have a large enough benefit to be merged, and I don't count most of the pep-8 and similar cleanups as having large enough benefit.

Additionally, many clean-up PRs are not as "innocent" as they sound like, so I still have to review all of them, which can be time consuming if there are more than 100 of them, plus I need to jump all over the statsmodels code base and topics instead of being able to concentrate on a few parts.
(example code comments in unit tests: I don't want to have to triage which comments are useful and which are not. Skipper spent a lot of time in the first two years of scikits.statsmodels to write unit tests and compare to R and Stata. I don't want to delete his comments, or somebody else's similar comments, when the only way to figure out what the problem was or is, is to actually understand the underlying issues, code and what other packages are doing.

I'm also in favor of cleaner code "in the abstract", but not if it takes me several times longer to quickly respond to a problem report, or to figure out how some code could be refactored.
Cleanup is much easier when a piece of code is already getting a substantive review.

Example: Kevin is taking over more of tsa functions. I don't have a problem with associated cleanup because it becomes less likely now that I have to go bug hunting or refactoring in those parts.

**Comment by jbrockmendel** [comment]
@rgommers thanks for weighing in; everything you said makes sense to me.

@josef-pkt I think on many of these issues we are coming at them from different directions.

Valid Viewpoint A: The maintainer's attention is a binding constraint, so let's avoid low-priority changes (e.g. readability).
Valid Viewpoint B: The maintainer's attention is a binding constraint, so let's make code readable enough that delegation is viable.

Valid Viewpoint A: git history is important to keep uncluttered because that is what the maintainer uses to understand the intention of the code.
Valid Viewpoint B: with sufficient readability/documentation improvements, it would not be necessary to look at the git history to figure out the intention.

----
I think we're on the same page about your attention being the scarce resource here.  My preferred solution is

a) let Kevin merge some agreed-upon types of PRs.  This involves trusting his judgement, and will end up differing from exactly what you would do, but it would get a lot of stuff off your plate and let you focus on stuff that genuinely does need your attention.

b) Less-trusted contributors (yo!) can help by identifying code that does not need your attention, e.g. code copy/pasted from scipy, or copy/pasted in multiple places around statsmodels.  This can help you focus on the things that genuinely do need your attention.

c) Allowing/encouraging small improvements encourages eyeballs, which are the best debugging tool available.

**Comment by josef-pkt** [comment]
just an example from #5102
I don't know how the reference numbers for RLM were created many years ago.
Having the ancient `RModel` command in code comments provides the hints and following the blame finds the history
https://github.com/statsmodels/statsmodels/blame/master/statsmodels/robust/tests/test_rlm.py#L147
Skipper is not available anymore for asking about this history.
If I also get hit by the proverbial bus, then the only information left is in the git history.
`RModel` cannot be found by github search because it is not in the source anymore, and there is no starting point to to find it with blame. 
This is for the case that some developer or maintainer wants or needs to know how the reference numbers were created. It might be easy for a R robust expert, but not for a general maintainer.

This ancient history is less relevant for GLM, for example, because there were many contributors/developers/maintainers that worked on GLM. But RLM and many parts in the sandbox are still mostly based on ancient code, and information accessible through source or git history can be important.

I am not spending time writing additional developer documentation for work in progess, those is spread out throughout the git history and in many github issues and PRs.

(Disappearing developers and getting hit by buses: Maybe my strong preference for an informative repo history comes from my time in scipy.stats where almost the only hints I had were based on the repo history, and most topics I had never heard about.)

**Comment by jbrockmendel** [comment]
5102 is a great example, since it showcases both the "the answers are in the git history" view and my "and they shouldnt be" view.

Getting back to the delegation point, I think 5132 is a worthwhile example.  It contains some warning-supression that is trivial and could be handed off to bashtage, and some unexpected behavior that needs your attention.  bashtage should be trusted to tell the difference, at which point the pieces could be separated into one that he takes care of and one that you get pinged on.  Instead as it is, you end up getting pinged on everything which is way too much.

**Pull request closed without merging**
