### PR TITLE
DOC: change doc link and remove easy_install

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @josef-pkt 

Also removed the suggestion to use the `--upgrade` flag, since that can cause all sorts of trouble by updating not just statsmodels.

looks like
screen shot 2016-06-21 at 11 05 47 am

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Oops, one sec, going to make that css change too.

**Comment by josef-pkt** [comment]
dropping the upgrade flag didn't work for me because I had a previous installed version
we need to specifically add `--no-deps`

statsmodels should not specify dependencies, but I didn't want to risk it and use always --no-deps with pipupgrade

**Comment by TomAugspurger** [comment]
So you're saying `pip install --upgrade --no-deps statsmodels` won't upgrade any deps? I haven't used both those flags together; typically I'll uninstall and then install.

**Comment by TomAugspurger** [comment]
@josef-pkt CSS fixed, should be good now.

**Comment by josef-pkt** [comment]
@TomAugspurger  Yes, I'm usually using this, especially with pandas and patsy

```
>pip install --upgrade  --no-deps M:\josef_new\eclipse_ws\statsmodels\release\statsmodels_08\statsmodels\dist\statsmodels-0.8.0rc1-cp34-none-win_amd64.whl"
```

**Comment by josef-pkt** [comment]
@TomAugspurger  Thanks, merging

Note: needs to be added to master

**Pull request merged**
