### PR TITLE
TST: Ensure random numbers are reproducible

### PR DESCRIPTION
**Pull request by bashtage**
Add more random state resets to improve predictability

### CODE REVIEW

**Comment by bashtage** [comment]
Another random failure here:

https://ci.appveyor.com/project/bashtage/statsmodels/build/1.0.1022/job/kyg6klcyia378fhs

**Comment by bashtage** [comment]
xref #5197

**Comment by josef-pkt** [comment]
all green, merging

@bashtage Thank you

**Comment by josef-pkt** [comment]
(Seems like I had forgotten to push the merge button)

**Pull request merged**
