### PR TITLE
whitespace cleanup in glm_results

### PR DESCRIPTION
**Pull request by jbrockmendel**
Still an unholy mess, but less so.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
BS, sir, BS.  There is evidence of manual editing _all over_ these files.

**Comment by josef-pkt** [comment]
BS = BackSpace, Beijing Subway, BellSouth, ... ?

Even in cases where I edited the files in a few spots, it doesn't change anything.
No pep-8 cleanup on those files.

Also, I find it much easier to read the long lists of numbers with spaces around `=`, independent of whatever pep-8 claims or wants.
Stata produces a similar list, although centered on `=`, which makes it easy to skim and compare results.

**Comment by josef-pkt** [comment]
clarification: 
results_glm is constructed from mix of edits and automatic prints (mainly Skipper and thequackdaddy, IIRC)
results_glm_poisson_weights is (almost?) only autogenerated Stata output

**Comment by jbrockmendel** [comment]
> BS = BackSpace, Beijing Subway, BellSouth, ... ?

2 points, I got a chuckle out of that.  I keep forgetting that it takes a few decades for vernacular to make it to the Deep North.

Aside from whitespace issues, which can be worked around, these files include a significant amount of commented-out code that needs the traditional "document or delete" treatment.  linting is the start of the fixing-stuff process, not the end of it.

**Comment by jbrockmendel** [comment]
@josef-pkt re Sentimental Value from the other thread.

Beijing Subway above provides precedent for gentle sarcasm being acceptable.  If you want to apply a double standard that's your prerogative, but I have no reason to believe that you are inclined to be petty.

You've previously acknowledged (no luck so far finding the Issue/PR) that a bunch of commented-out code exists because you have an "irrational aversion to the delete button".  While I may not like the result of such a process, I can appreciate the honesty*.  SV is a pretty good shorthand for that kind of decision making criterion.

As for language, I make a point of not cussing around here, also of avoiding "dumb", "stupid", etc.  A complaint about language is either disingenuous or very poorly communicated.

\* Can't seem to find a youtube clip.  Please share a mental image with me of the scene in Firefly when Malcolm admits that he's robbing the guy and he says "Well, I appreciate your honesty.  Not, you know, a lot."

**Pull request closed without merging**
