### PR TITLE
ENH/TST: Possibility of not printing r-squared in summary_col

### PR DESCRIPTION
**Pull request by lanzariel**
- [x] closes #xxxx
- [x] tests added / passed. 
- [x] code/documentation is well formatted.  
- [x] properly formatted commit message. See 
      [NumPy's guide](https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message). 

<details>

**Notes**:

* It is essential that you add a test when making code changes. Tests are not 
  needed for doc changes.
* When adding a new function, test values should usually be verified in another package (e.g., R/SAS/Stata).
* When fixing a bug, you must add a test that would produce the bug in main and
  then show that it is fixed with the new code.
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, you can
  verify you changes are well formatted by running 
  ```
  git diff upstream/main -u -- "*.py" | flake8 --diff --isolated
  ```
  assuming `flake8` is installed. This command is also available on Windows 
  using the Windows System for Linux once `flake8` is installed in the 
  local Linux environment. While passing this test is not required, it is good practice and it help 
  improve code quality in `statsmodels`.
* Docstring additions must render correctly, including escapes and LaTeX.

</details>

### CODE REVIEW

**Comment by josef-pkt** [comment]
@lanzariel 

Thanks for the PR.
Looks very good. I will try it out today and merge.

Can you amend the commit with style fixes?  pep-8

from the azure style check:

```
statsmodels/iolib/summary2.py:422:1: W293 blank line contains whitespace
statsmodels/iolib/tests/test_summary2.py:203:16: E713 test for membership should be 'not in'
statsmodels/iolib/tests/test_summary2.py:204:16: E713 test for membership should be 'not in'
statsmodels/iolib/tests/test_summary2.py:204:50: W292 no newline at end of file
```

**Comment by lanzariel** [comment]
@josef-pkt 

Thank you for the heads-up. I have amended the commit.

**Comment by josef-pkt** [comment]
Looks good, I tried the example from
https://stackoverflow.com/questions/75366372/why-is-summary-col-ignoring-the-info-dict-parameter

merging

Thanks for the PR

**Comment by josef-pkt** [comment]
I just saw a bug comparing the stackoverflow answer with my results table in a notebook:
The html rendition in the notebook does NOT include the explanation text below the table. `print(out_table)` includes it.

**Pull request merged**
