### PR TITLE
MAINT: silenced as_pandas warnings in documentation

### PR DESCRIPTION
**Pull request by thequackdaddy**
There are a few warnings in the docs. First, the Guerry dataset needs a `master` in the http string. Next, we added a warning to say that we are going to generally change `dataset.load()` to return a DataFrame, so I silenced as many as I could.

### CODE REVIEW

**Comment by thequackdaddy** [comment]
xref #4853

**Comment by josef-pkt** [comment]
LGTM AFAIU

**Comment by josef-pkt** [comment]
This has now merge conflicts created by merging #4912

**Comment by thequackdaddy** [comment]
@josef-pkt rebased

**Comment by josef-pkt** [comment]
I'll wait for appveyor run, then merge

Thanks

**Comment by thequackdaddy** [comment]
@josef-pkt There is one failure on appveyor... 

`test_arima111_predict_exog_2127`

When I ran on my appveyor, it was good...
https://ci.appveyor.com/project/thequackdaddy/statsmodels/build/1.0.329

I recall that one has been problematic before. I don't think this caused it. Should I investigate or merge as-is?

**Comment by josef-pkt** [comment]
Given that the test failure is unrelated to this PR, I will merge this as is.

There is most likely still some fragility when running under 32-bit.

**Pull request merged**
