### PR TITLE
Use default implementations for methods

### PR DESCRIPTION
**Pull request by jbrockmendel**
Less code --> less maintenance burden.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Let's see how this turns out in the unit tests. Right now there is a syntax error that makes all tests error.

The main problem moving this to the top model level is that it is not necessarily defined for subclasses.
There are a few inconsistencies still across models, either intentionally or by not using a consistent definition when a model was created.

One problem is that resid = endog - fittedvalues = endog - predict only holds for additive models.
E.g. In GMM, resid is intentionally not implemented in the general version. because we don't have any information or assumption about a additive prediction.

GLM currently does not use `resid` but that should change again. GLM has several resid_xxx that are more commonly used and more useful tham resid_response.

The test results could be informative to see how far we currently get in making this consistent or where we would have to override the general pattern.

**Comment by josef-pkt** [comment]
This pull request **introduces 5 alerts** and **fixes 106** when merging 3bc265edca52278ff5b99840a4c5172e216d7dd2 into 935ceaab237fd5f25a415a7e8861fa22f07a3d9d - [view on lgtm.com](https://lgtm.com/projects/g/statsmodels/statsmodels/rev/pr-7e7b17c7e114cfa97204e5bbc209bb0470df0fc2)

**new alerts:**

* 2 for Potentially uninitialized local variable
* 1 for Wrong name for an argument in a call
* 1 for Syntax error
* 1 for Mismatch between signature and use of an overridden method

**fixed alerts:**

* 93 for Module\-level cyclic import
* 7 for Mismatch between signature and use of an overridden method
* 2 for Missing call to \_\_init\_\_ during object initialization
* 2 for \_\_init\_\_ method calls overridden method
* 1 for Superclass attribute shadows subclass method
* 1 for First argument to super\(\) is not enclosing class

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by jbrockmendel** [comment]
> There are a few inconsistencies still across models, either intentionally or by not using a consistent definition when a model was created.

Fixing these inconsistencies is the thing I'm most interested in addressing.

> One problem is that resid = endog - fittedvalues = endog - predict only holds for additive models.

I'm comfortable putting this in the base class, but putting this into a LinearResultsMixin or something would also be a reasonable option.  

> E.g. In GMM, resid is intentionally not implemented in the general version.

Until its out of the sandbox, I'm considering GMM a non-entity.  Even so, it should have the method and raise NotImplementedError instead of AttributeError.

**Comment by josef-pkt** [comment]
> I'm comfortable putting this in the base class, ..

I'm not, I need to be convinced something belongs there, and I'm not sure yet in this case.
adding `fittedvalues` might be fine, given that we already have predict, but additive resid requires stronger assumptions.

That is, this is firstly a theoretical design issue, and not an implementation issue about using inheritance, given that it has consequences for all Model classes.

> Until its out of the sandbox, I'm considering GMM a non-entity. Even so, it should have the method and raise NotImplementedError instead of AttributeError.

It looks like you don't care about future enhancements to statsmodels. 
But I do, and the design is partially made with respect to what we will add in future. 
(E.g. if I had known when we started with statsmodel what I did 5 years ago, then we would have a top level MEstimatorModel instead of LikelihoodModel (which still wouldn't properly describe GMM but would provide more informative names for non-MLE models.)

Also, gmm is in use, so it's not a non-entity.
AttributeError is more appropriate IMO, general GMM does not have this attribute/property because of theoretical reasons and not because it is NotImplemented.

**Comment by josef-pkt** [comment]
A large number of test failures are in discrete, which *should* still override what is inherited.
However, something is wrong and I currently don't see a reason for this.

(discrete uses currently a different definition for fittedvalues)

**Comment by jbrockmendel** [comment]
> It looks like you don't care about future enhancements to statsmodels.

I "don't care" about future enhancements the same way you "don't care" about maintenance/code quality/QA.  Different priorities.  I'm of the opinion that fixing internal inconsistencies will make future features easier to implement.

If GMM is an entity, then get it out of the darned sandbox.  Otherwise how am I supposed to tell it apart from, say, garch?

**Comment by josef-pkt** [comment]
> the same way you "don't care" about maintenance/code quality/QA

Given that I spend a large amount of time tracking down bug candidates and fixing bugs, I might stop reading this type of comments.

However, I don't care much about maintenance/code quality/QA in terms of cosmetics and pep-8, if I think it might interfere with other maintencance work, and compared to, for example, https://github.com/statsmodels/statsmodels/issues?q=is%3Aopen+is%3Aissue+label%3Atype-bug

I think the main difference is that you want to clean up status-quo, while I want code (and messy parts) that help us get through the next five years in a better way.

GMM has unit tests, answers on stackoverflow and is in the documentation, while search in the online docs for 'garch' finds one mention of the word in the description of the sandbox.
http://www.statsmodels.org/devel/search.html?q=gmm

**Comment by jbrockmendel** [comment]
> Given that I spend a large amount of time tracking down bug candidates and fixing bugs,

The quotation marks in my previous comment were meant to convey that while these might be our perceptions of one another, they are caricatures at best.  Poor communication on my part.  I disagree with the rest of your comment, but don't see any upside to fleshing that out.

>  [...] I might stop reading this type of comments.

These interactions have become more frustrating and less productive (I think we're on the same page on this one), so it seems like a good time to take a few weeks away.  I'll close less pressing/obvious Issues/PRs on my way out.

**Pull request closed without merging**
