### PR TITLE
DOC update release notes for 0.8

### PR DESCRIPTION
**Pull request by josef-pkt**
I moved one section and added some items that have been backported since 0.8rc1

### CODE REVIEW

**Comment by TomAugspurger** [comment]
lgtm (you're doing the git log just before release?)

**Comment by josef-pkt** [comment]
I didn't find my bash shell yet for the git log.  :)
There shouldn't be any new names coming in compared to current git log.

I will be offline for large parts of the afternoon (family), but will be back late afternoon in case anything remains. I'll merge whatever is ready before going offline, or Chad can finish.

**Comment by josef-pkt** [comment]
I found only two extra names compared to 0.8rc1
`git log dfd2b4ec8f2cffa65c44675ab25bba67de801058..HEAD --format='* %aN' | sed 's/<>//' | sort -u`
copied from https://github.com/statsmodels/statsmodels/issues/2176#issuecomment-227048066

**Comment by josef-pkt** [comment]
merged, should be ready for backporting

**Pull request merged**
