### PR TITLE
Cleanup non-standard imports

### PR DESCRIPTION
**Pull request by jbrockmendel**
In particular, got rid of `import scipy.linalg as L` and `import numpy.linalg as npl`.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Looks good to me, merge when green

**Comment by josef-pkt** [comment]
travis fails with
`AttributeError: module 'numpy.linalg' has no attribute 'chol'`

**Comment by jbrockmendel** [comment]
Just pushed a fix.

**Comment by jbrockmendel** [comment]
AFAICT the coveralls "failure" is because coverage % dropped.  That should be ignored-- this PR just deleted 5 lines of imports, did not change make any real change in coverage.

**Comment by jbrockmendel** [comment]
ping

**Comment by jbrockmendel** [comment]
I think this will be subsumed by #3815.

**Comment by bashtage** [comment]
Closeable?

**Comment by jbrockmendel** [comment]
Looks like a yes.

The CI isn't reporting a merge conflict though.  Is that not a standard feature?

**Comment by josef-pkt** [comment]
Maybe it's not a merge conflict, it could be a "no-op" commits that are already in master.

(I haven't tried comparing git branches on the command line in years.)

**Comment by bashtage** [comment]
I think there wouldn't be a conflict since there is 0 diff and so "mergeable"

**Pull request closed without merging**
