### PR TITLE
ENH: Markov switching models: cython Kim smoother and Hamilton filter improvements

### PR DESCRIPTION
**Pull request by ChadFulton**
- Separates the Cython-based Hamilton filter into (1) a wrapper for performing filtering across all `nobs` and (2) a function for a single iteration; (2) can be re-used eventually in the state space switching models.
- Adds a Cython-based Kim smoother in the same pattern as the Hamilton filter, so that it can be re-used eventually in the state space switching models.

### CODE REVIEW

**Comment by ChadFulton** [comment]
Test failures are unrelated (just the new Scipy failures)

**Comment by josef-pkt** [comment]
(don't forget labels)
this is for 0.9 I assume

**Comment by ChadFulton** [comment]
Hoping this commit fixes the missing coverage. If so, it's okay to merge 0.9 items now, right?

**Comment by ChadFulton** [comment]
I will merge this tomorrow unless there are concerns.

**Comment by ChadFulton** [comment]
I guess some 0.9 milesone PRs have been merged, so I will merge this.

**Pull request merged**
