### PR TITLE
FIX: Fix broken Pandas/Python 2.6 usage

### PR DESCRIPTION
**Pull request by bashtage**
Fix incorrect pandas assignment for older pandas
Remove unnecessary unicode

### CODE REVIEW

**Comment by bashtage** [comment]
@josef-pkt This fixed the broken 2.6 tests so that master can now pass.

**Comment by TomAugspurger** [comment]
FYI, pandas doesn't support python 2.6 anymore. AFAIK, we haven't had any complaints. Might be worth discussing on the mailing list whether statsmodels should drop 2.6 support.

**Comment by bashtage** [comment]
I don't think there is any doubt 2.6 should be dropped.  There is a PR that updates the testing to 2.7+.  This build uses and ancient pandas (0.12).

**Comment by josef-pkt** [comment]
python 2.6 doesn't matter for this, but replacing the fancy, unicode quote/apostrophe by a simple ascii quotation mark is necessary to avoid (julia style :) confusion about which weird character to type.

(we don't want to get into argument like this where usability also might be language and keyboard specific https://tedclancy.wordpress.com/2015/06/03/which-unicode-character-should-represent-the-english-apostrophe-and-why-the-unicode-committee-is-very-wrong/ )

**Comment by bashtage** [comment]
closes #3376

**Comment by josef-pkt** [comment]
merged @bashtage  Thank you
this should make master green again

**Pull request merged**
